### ISSUE TITLE
[NR5] [DIST/Dev] Add a header file to export utility functions for sub-plugin developers

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#1037]
This issue is a sub-issue of #956.  and a backlog of EPIC #846

https://github.com/nnsuite/nnstreamer-ros requires tensor_common.h which is not included in the dev package anymore. Since at least utility functions in tensor_common.h are still useful for the sub-plugin developers who work in the other repository, we need to provide a header file to export utility functions for those developers.

**Comment by myungjoo** [comment]
You will need to think about how the implementations of tensor_common are exposed to users. Currently, they are in nnstreamer plugin so, which is located in gst plugin path, which may be not in LD path.

**Comment by wooksong** [comment]
@myungjoo How about creating a directory named nnstreamer in the "DEFAULT" library dir (e.g., such as /usr/lib/x86_64-linux-gnu/nnstreamer, /usr/lib, and /usr/lib64) and using a custom ld.conf file (i.e., in the case of x64 Ubuntu, /etc/ld.so.conf.d/nnstreamer.conf) to indicate our .so for exposing nnstreamer functions.
