### ISSUE TITLE
Latency support in tensor mux/merge

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#1144]
With basepad synchronization, the mux/merge needs to sync with clock for an element which has not yet arrived.

In the example given in the wiki (https://github.com/nnsuite/nnstreamer/wiki/Synchronization-Policies-at-Mux-and-Merge), the second frame will reach the sink at 50000000, but with buffer time_stamp of 33333333 as it is synced with basepad0. This will result in frame drop in live sink.

This needs to be handled with latency compensation in the case when basepad synchronization has `duration` more than 0. Handling `GST_QUERY_LATENCY` with minimum latency set as the `duration` and maximum latency set as the buffer size will resolve the situation.

**Comment by myungjoo** [comment]
This needs discussions with @jijoongmoon and @jaeyun-jung

**Comment by kparichay** [comment]
Baseline video which displays 1 frame every 5 sec with no frame drops:
`gst-launch-1.0 souphttpsrc location=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm is-live=TRUE ! matroskademux name=d2 ! vp8dec ! videoconvert ! tensor_converter ! tensor_decoder mode=direct_video ! videoscale ! videoconvert ! videorate ! video/x-raw,framerate=1/5 ! autovideosink sync=TRUE max-lateness=100`

Baseline video at default fps with no frame drops:
`gst-launch-1.0 souphttpsrc location=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm is-live=TRUE ! matroskademux name=d2 ! vp8dec ! videoconvert ! tensor_converter ! tensor_decoder mode=direct_video ! videoscale ! videoconvert ! autovideosink sync=TRUE max-lateness=100`

However, using mux to merge these 2 streams and demuxing to pick the first stream and playing it results in lot of frame drops (notified by the video sink), duration is set to 5.1 sec:
`DURATION=5100000000`
`gst-launch-1.0 tensor_mux name=mux silent=false sync_mode=basepad sync_option=0:$DURATION ! tensor_demux name=demux tensorpick=0 ! tensor_decoder mode=direct_video ! videoscale ! videoconvert ! autovideosink sync=TRUE max-lateness=1000 souphttpsrc location=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm is-live=TRUE ! matroskademux name=d2 ! vp8dec ! videoconvert ! videorate ! video/x-raw,framerate=20/1 ! tensor_converter ! mux.sink_0 souphttpsrc location=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm is-live=TRUE ! matroskademux name=d ! vp8dec ! videoconvert ! videorate ! video/x-raw,framerate=1/1 ! tensor_converter ! mux.sink_1`

Setting duration to 0 should result in video with no frame drops, however there are still many frame drops.

**Comment by myungjoo** [comment]
@kparichay Please confirm if this is still a valid issue.

**Comment by kparichay** [comment]
This is resolved with latest nnstreamer version.
