### ISSUE TITLE
[Tizen/API] Element name aliasing needs more parsing rules

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1622]
#1592 is good for the basis. However, the problem is that it does simple string replace, which may incur unintended side effects.

Let's merge #1592 first and fix it later anyway..

The following pipelines:
```
... ! tee name=tizencamvideosrc ...
```
,
```
... ! tensor_filter framework="tensorflow-lite" model="tizencamvideosrc.tflite" ...
```
get string replacements, which breaks the pipelines.

Possible solutions:

1. If there is parsing-only gstreamer API, we can use that and scan for element names.
2. With GLIB REGEX, filter out ${alias} inside quotes, "=\w*${alias}, \W+${alias}, ${alias}\W+, and so on.

---- Note by MJ (2021-01-25)
There is no "parsing-only" gstreamer API. Gst-parser does processing at the same time.
We will need approach 2 (could be incomplete) that prevents a few well-known/expected side-effects.

Expeted worksize: < 1 mw

**Comment by gichan-jang** [comment]
`... ! tee name=tizencamvideosrc ! tensor_filter framework="tensorflow-lite" model="tizencamvideosrc.tflite" ...`
These cases are already handled well. I added a test case to check it.

https://github.com/nnstreamer/api/blob/243c5df420c9914b42412a3d4923b5f4ccdbd70c/tests/capi/unittest_capi_inference.cc#L3480-L3496

**Comment by myungjoo** [comment]
If you sure that this is already addressed, you may close it.

**Comment by gichan-jang** [comment]
Close this issue.
