### ISSUE TITLE
ORC-ARM64

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1666]
This is not directly related with nnstreamer; however, in order to have proper performance in Android and Tizen devices, we definitely need this.

We probably need to take https://gitlab.freedesktop.org/gstreamer/orc/issues/2 and drive it.

If anyone dares to tackle assemblers and low-level codes, this is it!!

**Comment by dongju-chae** [comment]
I'll try this because the work overhead in NPU SW stack stuff is getting stable.

**Comment by dongju-chae** [comment]
Related PRs will be uploaded to this branch: https://github.com/nnsuite/orc/tree/aarch64_support,

**Comment by myungjoo** [comment]
Reopen this when we resume this task
