### ISSUE TITLE
[New Element] Handle if statement nicely.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1703]
Without adding yet another custom filters wrapping others, if would be much better if we can add an "if" statement based on tensor values as a filter.

V1. E.g., (version 1 supports .so only)
```
... ! tensor_if skipif="user_code_with_tensor_if_API_bool.so" ! ...
... ! tensor_if outputselect="user_code_with_tensor_if_API_int.so" name=output  output.0 ! ... output.1 ! ...
```

V2. E.g., (version 2 supports python code)
```
... ! tensor_if skipif="${python code with given API}" ! ...
... ! tensor_if skipif="user_code_with_tensor_if_API_bool.py" ! ...
```
or (version 2 supports some scripts)
```
... ! tensor_if skipif="scripting with what we've defined..." ! ...
```

Idea 20191001: the whole "if-then-else" clauses might need to be enclosed in a "bin"... maybe... maybe not...

If we are using multi tensor with conditional variable, then it could be as below.
![image](https://user-images.githubusercontent.com/23226860/66291974-13ae6e00-e91e-11e9-8457-b9a37c98e8ff.png)

**Comment by jijoongmoon** [comment]
I think we might need the end-if element. if there is separate pipeline, then it is ok without end-if element, but these separate pipeline should be merged into one stream, then we might need end-if element. We could use merge or mux but these are going to wait to the other stream is arrived and it will be stall. Or we could add options in the merge or mux which allow push down stream if one of stream data arrived. 
 
![image](https://user-images.githubusercontent.com/23226860/66355534-9ed14780-e9a2-11e9-8ad4-b334b5ad6c55.png)

**Comment by myungjoo** [comment]
CC: @leemgs  (refer to the code at /gst/nnstreamer/tensor-if )

**Comment by gichan-jang** [comment]
todo list
 1. custom callback function for user-defined condition
 2. determine the srcpads at the negotiation phase
 3. Find a way to connect with the other element. (e.g, input-selector)
  - Or one src pad allow a true / false action? So it can operate as input-selector.
    -> in this case, Allow dynamic configuration? or just allow the same configuration only.
 4. tensor_if control with meta info 
 5. property update during pipeline is on running or paused state. (Only options that do not affect cap, like supported value? )

**Comment by myungjoo** [comment]
This is going in a good direction! Great!

**Comment by myungjoo** [comment]
@gichan-jang I think you've completed this. Please close it.

**Comment by gichan-jang** [comment]
The Tensor_if element example can be found here:
https://github.com/nnstreamer/nnstreamer-example/tree/master/bash_script/example_tensorif
Close this issue.
