### ISSUE TITLE
Tensorflow-Lite operator version check

### ISSUE THREAD

**Issue by abcinje** [nnstreamer/nnstreamer#1759]
There are many examples in https://www.tensorflow.org/lite/examples we can get.
However, some of them is not compatible with tf1.13, which nnstreamer currently supports.
(If some of operators in a model are of tf1.14 or later, the model is not loaded.)

Moreover, until constructing the pipeline to use it, we cannot even know if a specific model can work with tensor_filter_tflite.

In my opinion, how about providing a tool which can inform about the model is supported or not with the current version(s) of tensor_fliter_tflite. If it is, we can simply know without constructing pipeline. In addition, by using this tool, you can also show which models in official tflite page are curretly supported by tensor_filter or not in your md files.

Thanks in advance for any opinions.

**Comment by myungjoo** [comment]
1. If we can easily determine the supported tf-lite version of a .tflite file, this can be done by tensorflow-lite subplugin without any external tool.
2. If there is (already) a tf-lite tool that determines the required tf-lite version, we may let tensorflow-lite subplugin to execute the tool (if its availability is confirmed at runtime.)

@abcinje Do you have related information to determine the "if conditions" in the above statements?

**Comment by abcinje** [comment]
@myungjoo Sorry for being late.

In my opinion, it is enough to check whether a model can be loaded on current NNStreamer.
At first, my intended goal was making a tool that determines the supported tf-lite version of a model, but it may involve some overheads such as looking for the versions of operators contained in a model.

Using functions defined in `ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc`, I wrote a program to check whether a specific model is loadable or not.

[Demo]
- model is loadable
![ok](https://user-images.githubusercontent.com/33629617/67080894-1be59380-f1d1-11e9-9cfd-d8a09918db3a.png)

- model is not loadable
![failed](https://user-images.githubusercontent.com/33629617/67080910-26079200-f1d1-11e9-93af-33bb74d01953.png)

How about adding this tool to `tools` directory? As I mentioned before, developers can simply know the loadability of their models without writing a pipeline script.

Thank you!

**Comment by kparichay** [comment]
@abcinje You can use the single-shot api given in `api/capi/include/nnstreamer-single.h` to do what you are doing more easily compared to directly interfacing with `ext/nnstreamer/tensor_filter/tensor_filter_tensorflow_lite_core.cc`.

**Comment by myungjoo** [comment]
Yes, as long as you can do it with public APIs, you are not supposed to use internal functions. They are not portable.

**Comment by myungjoo** [comment]
Closing it as there seem to be no more issues to be discussed.
