### ISSUE TITLE
Release Minimized Android Package

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1783]
1. Minimized Android nnstreamer+gst package for audio processing
2. Minimized Android nnstreamer+gst package for video processing

(Target: < 15MB, single arch)

**Comment by jaeyun-jung** [comment]
PR #1804 to add build option for min gst plugins.

**Comment by jaeyun-jung** [comment]
package name

1. default (includes all plugins in gstreamer-android) for armeabi-v7a and arm64-v8a
org.nnsuite:nnstreamer:<version>

2. lite (includes core plugins in gstreamer-android) for armeabi-v7a (or arm64-v8a)
org.nnsuite:nnstreamer-lite-armv7:<version>
org.nnsuite:nnstreamer-lite-armv8:<version>

**Comment by myungjoo** [comment]
In case we need to diet further,
2. lite-all (include core plugins of audio-video and nnstreamer standard build)
3. lite-video-only (include core plugins w/o audio and nnstreamer no-audio build)
4. lite-audio-only ...
For this version, 3 and 4 may be reserved for later development.

**Comment by jaeyun-jung** [comment]
TODO (After M2 release)
1. replace single capi (clear old pipeline-based code)
2. define plugins for lite version
  current core plugins : coreelements coretracers adder app audioconvert audiomixer audiorate audioresample audiotestsrc compositor gio overlaycomposition pango rawparse typefindfunctions videoconvert videorate videoscale videotestsrc volume autodetect videofilter
3. finally upload lite version of android library to jcenter (lite-all includes both armv7/v8)

**Comment by myungjoo** [comment]
Now, we have official request from clients.

Binaries to be released:
1. Full (single API + pipeline API + full gst plugins)
2. Light (single API + pipeline API + + tensor-filter subplugins (SN, TF-Lite, TBD(nnfw?)) chosen gst plugins) (<10MB?)
3. Ultra-light / Single-only (single API + tensor-filter subplugins (SN, TF-Lite, TBD(nnfw?) ) + NO GST at all)

- Can we package other subpligins (edge-tpu, vivante, openVINO, ncsdk, ...) as "extension"? (for both Full and Light and UltraLigt)

**Comment by myungjoo** [comment]
Done. Waiting for clients for further info.
