### ISSUE TITLE
Request for unit test case

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1813]
We need either SSAT or GTEST test cases for
- tensordec-imagesegment.c (2.7%)
- tensordec-pose.c (58.9%)
- nnstreamer-capi-util.c (71.1%)

**Comment by gichan-jang** [comment]
@myungjoo 
Since the coverage of the specified unit test has increased a lot, this issue may be closed.

tensordec-imagesegment.c (2.7%) -> increased to 85.6%
tensordec-pose.c (58.9%) -> increased to 93.3%
nnstreamer-capi-util.c (71.1%) -> increased to 85.8%

**Comment by myungjoo** [comment]
Great! Thanks!
