### ISSUE TITLE
[API changes] android c#

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/nnstreamer#1852]
Issues from Mr.Ham, data container for Tensor

We implemented two classes for tensor-data and tensor-info.
Need to set metadata in data class.

1. Add metadata in TensorsData class
2. Define Tensor class and contain both metadata and buffer.

We have to consider the tizen c# SingleShot APIs can be updated for next release.

For Android APIs, see attached javadoc.

1. 2019-11-13 defined Tensor class and integrate all methods
[nnstreamer-api-javadoc_2019-11-13.zip](https://github.com/nnsuite/nnstreamer/files/3839418/nnstreamer-api-javadoc_2019-11-13.zip)

2. 2019-11-22 add method to get metadata in TensorsData
[nnstreamer-api-javadoc_2019-11-22.zip](https://github.com/nnsuite/nnstreamer/files/3884960/nnstreamer-api-javadoc_2019-11-22.zip)

3. add clear() method and handle error case to update metadata in TensorsData
[nnstreamer-api-javadoc_2019-11-27.zip](https://github.com/nnsuite/nnstreamer/files/3895387/nnstreamer-api-javadoc_2019-11-27.zip)

4. constructor in TensorsData, CustomFilter and NNStreamer class
[nnstreamer-api-javadoc_2019-11-28.zip](https://github.com/nnsuite/nnstreamer/files/3900941/nnstreamer-api-javadoc_2019-11-28.zip)

5. create TensorsData with TensorsInfo meta (non-null)
[nnstreamer-api-javadoc_2019-12-04.zip](https://github.com/nnsuite/nnstreamer/files/3925132/nnstreamer-api-javadoc_2019-12-04.zip)

6. register multiple sink callback
[nnstreamer-api-javadoc_2019-12-16.zip](https://github.com/nnsuite/nnstreamer/files/3967714/nnstreamer-api-javadoc_2019-12-16.zip)

7. add SNAP, enumeration for data type and nnfw
[nnstreamer-api-javadoc_2019-12-31.zip](https://github.com/nnsuite/nnstreamer/files/4012076/nnstreamer-api-javadoc_2019-12-31.zip)

8. add clone() method in TensorsInfo class to prevent the meta-info change after allocaing the byte-buffer.
[nnstreamer-api-javadoc_2020-01-02.zip](https://github.com/nnsuite/nnstreamer/files/4018347/nnstreamer-api-javadoc_2020-01-02.zip)

9. link pipeline state
[nnstreamer-api-javadoc_2020-01-10.zip](https://github.com/nnsuite/nnstreamer/files/4052469/nnstreamer-api-javadoc_2020-01-10.zip)

**Comment by myungjoo** [comment]
For backward compatibility, it may have "has a" relation to conventional TensorData and TensorInfo.
Or, extent TensorData to have "has a" relation to TensorInfo.

**Comment by myungjoo** [comment]
Assuming that the conventional data structure is "class TensorData",
we can extend TensorData itself; I understand that SE textbooks prohibit such behaviors and tell us to "inheir" TensorData; however, for the backward compatibility and full reuse of previous API sets, we can do directly extend TensorData:

For example if TensorData of previous version is:
```
class TensorData {
  element A;
  element B;
};
```

Then, the new version will become:
```
class TensorData {
   element A;
   element B;
   TensorInfo meta;
};
```

**Comment by again4you** [comment]
### AS-IS
* 2 `TensorsInfo` for each Tensor information
* 2 `TensorsData` for each Tensor Buffer
* `SingleShot` class

### class diagram
![00](https://user-images.githubusercontent.com/433435/69049371-0dde9900-0a43-11ea-86f7-d0b73a1b446e.JPG)

### code
```C#
byte[] in_buffer = new byte[3 * 224 * 224 * 1];
byte[] out_buffer;
string model_path = ResourcePath + "models/mobilenet_v1_1.0_224_quant.tflite";

TensorsInfo in_info;
TensorsInfo out_info;
TensorsData in_data;
TensorsData out_data;

/* Set input & output TensorsInfo */
in_info = new TensorsInfo();
in_info.AddTensorInfo(TensorType.UInt8, new int[4] { 3, 224, 224, 1 });

out_info = new TensorsInfo();
out_info.AddTensorInfo(TensorType.UInt8, new int[4] { 1001, 1, 1, 1 });

/* Create single inference engine */
SingleShot single = new SingleShot(model_path, in_info, out_info);

/* Set input data */
in_data = in_info.GetTensorsData();
in_data.SetTensorData(0, in_buffer);

/* Single shot invoke */
out_data = single.Invoke(in_data);

/* Get output data from TensorsData */
out_buffer = out_data.GetTensorData(0);

/* Release Single inference instance */
single.Dispose();

/* clean up */
in_data.Dispose();
out_data.Dispose();
in_info.Dispose();
out_info.Dispose();
```

## To-Be (First draft)
* Newly add `Tensors` Class
* Keep `TensorsInfo` and `TensorsData` classes and its related method for backword compatibility
* Pros
  * Shorter than before and easy to maintain
  * Support previous APIs
* Cons
  * New `Tensors` class ?!
  * SingleShot.Invoke() returns different classes.

### Class diagram
![01](https://user-images.githubusercontent.com/433435/69049461-3feffb00-0a43-11ea-9b25-c47ab50e8ddb.JPG)



### code
```c#
var in_buffer = new byte[3 * 224 * 224 * 1];
string model_path = ResourcePath + "models/mobilenet_v1_1.0_224_quant.tflite";

/* Set Input Tensors */
Tensors inTensors = new Tensors();
inTensors.AddTensor(TensorType.UInt8, new int[4] { 3, 224, 224, 1 });

/* Set Output Tensors */
Tensors outTensors = new Tensors();
outTensors.AddTensor(TensorType.UInt8, new int[4] { 1001, 1, 1, 1 });

/* Create single inference engine */
SingleShot single = new SingleShot(_modelPath, inTensors, outTensors);

/* Set input data */
inTensors.SetData(0, in_buffer);

/* Single shot invoke */
outTensors = single.Invoke(inTensors);

/* Release Single Inference instance */
single.Dispose();

/* clean up */
inTensors.Dispose();
outTensors.Dispose();
```

## To-Be (Second draft)
* `TensorsData` class has a `TensorsInfo` class
* Pros
  * No class are newly added.
* Cons
  * `TensorsData` has lots of method for `TensorsInfo`
  * `SingleShot` class should check the `TensorsInfo` validataion of `TensorsData` class

### Class Diagram
![02](https://user-images.githubusercontent.com/433435/69049232-bd673b80-0a42-11ea-9b1f-15fb7ee8f967.JPG)


### code
```C#
var in_buffer = new byte[3 * 224 * 224 * 1];
string model_path = ResourcePath + "models/mobilenet_v1_1.0_224_quant.tflite";

/* Set input TensorsData info & data */
/* With TensorsInfo class */
in_info = new TensorsInfo();
in_info.AddTensorInfo(TensorType.UInt8, new int[4] { 3, 224, 224, 1 });

TensorsData in_data = new TensorsData (in_info)
in_data.SetData(0, in_buffer);

/* Set output TensorsData info */
out_info = new TensorsInfo();

/* Without TensorsInfo class */
TensorsData out_data = TensorsInfo();
out_data.AddTensorInfo(TensorType.UInt8, new int[4] { 1001, 1, 1, 1 });

/* Create single inference engine */
SingleShot single = new SingleShot(_modelPath, in_data, out_data);

/* Single shot invoke */
out_data = single.Invoke(in_data);

/* Release Single Inference instance */
single.Dispose();

/* clean up */
in_data.Dispose();
out_data.Dispose();
in_info.Dispose();
```

**Comment by myungjoo** [comment]
Ok. Let's discuss this in person and explain me the benefit and objectives you propose. Anytime you want this week should be fine (preferably tomorrow? :) ).

**Comment by again4you** [comment]
I made a PR for [first draft](https://github.com/Samsung/TizenFX/pull/1154). for this work. Detailed items are as below.
* SingleShot class
  - Support various Neural Network framework such as TensorFlow,
    TensorFlowLite, Custom Filter or NNFW (default: Any)
  - Support various HW resources such as CPU, GPU or NPU (default: Any)
  - Load neural network model without Input / Output TensorsInfo
    (Dynamic mode or model file has input/output information)
  - Newly adds GetInputInfo() and GetOutputInfo() to fetch tensors information
  - Newly adds SetTimeout() to set the maximum amount of time to wait for an output
  - Newly adds SetInputInfo() to set the tensors information

* TensorsData class
  - Newly adds SetTensorsInfo() to set the tensors information
  - Newly adds GetTensorsInfo() to fetch tensors information
  - Newly adds AddTensorData() to add a new tensor data
  - Newly adds ClearData() to clean all tensors data
  - Newly adds static Allocate() for TensorsData Instance

* TensorsInfo class
  - Newly adds GetTensorSize() to get the byte size of tensor data

**Comment by again4you** [comment]
### Progress
* C# API ACR: https://code.sec.samsung.net/jira/browse/TCSACR-295

**Comment by jaeyun-jung** [comment]
C# API implemented and Java API also changed. Now TensorsData class includes metadata (TensorsInfo).
