### ISSUE TITLE
Tizen API: Tizen Feature Keys

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1918]
http://tizen.org/feature/machine_learning.inference.nnfw
http://tizen.org/feature/machine_learning.elements.flatbuffers
http://tizen.org/feature/machine_learning.training
http://tizen.org/feature/machine_learning.training.${to be named by @jijoongmoon }
...

**Comment by myungjoo** [comment]
Please check with appropriate Tizen maintainers and add Machine Learning Feature Keys.
(When you define keys, please consult with @jaeyun-jung (current APIs) @jijoongmoon (training APIs) @myungjoo (overall relations) )

**Comment by myungjoo** [comment]
@again4you : PTAL. It's time to prepare this for Tizen 6.0 M2 releases.

**Comment by again4you** [comment]
@kparichay  starts to ACR as below and he requests to newly make the feature key for training API.
* https://code.sec.samsung.net/jira/browse/ACR-1579

**Comment by myungjoo** [comment]
I think we need to register these keys somewhere...: https://www.tizen.org/feature

MachineLearning is still not shown there...

**Comment by myungjoo** [comment]
Done. They are shown!
