### ISSUE TITLE
Refactoring: Generalize tf-lite filter subplugin for hardware acceleration.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1944]
Background: recent edge-tpu runtime library exists as a backend of tensorflow-lite as we had once wished. Thus, we can enable nnstreamer-edge-tpu by simply adding a few line of "edge-tpu delegation" in tensor_filter_tensorflow_lite_core.cc.

Before we enable it, we need to redo the whole hardware acceleration / NNAPI mechanisms of tflite subplugin, which is already convoluted.

This may require re-refactoring of ACCLERATION property of tensor_filter.

**Comment by myungjoo** [comment]
@jaeyun-jung I think we've refactored this a few months ago. Please assess if we need further refactoring.

**Comment by jaeyun-jung** [comment]
Now we can set the accelerator with the property 'accelerator', also can select tf-lite delegate using custom option string.
