### ISSUE TITLE
Test Request: nnstreamer-edgetpu @ Tizen board.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1966]
Already tested:
- nnstreamer-edgetpu / Ubuntu 18.04 x64 PC + Real USB Edge-TPU
- nnstreamer-edgetpu / Tizen GBS on x64 PC + dummy Edge-TPU runtime-library (no TPU H/W)

To be tested:
- nnstreamer-edgetpu / Tizen RPI3/RPI4/Odroid/or-what-so-ever + Tizen 6.0 + Real USB Edge-TPU
- Please post the test results.

**Comment by myungjoo** [comment]
Now, we have a client who wants to use this with Tizen 6.0 M2.

**Comment by myungjoo** [comment]
@wooksong A few days ago, you've mentioned that you found a bug in this feature and are working on it. Please share related info here if you want.

**Comment by wooksong** [comment]
@myungjoo I will create another issue that contains the current status and action items to resolve this issue. How about that?

**Comment by myungjoo** [comment]
> @myungjoo I will create another issue that contains the current status and action items to resolve this issue. How about that?

It's ok to proceed. Close this and create another, then.

**Comment by wooksong** [comment]
> > @myungjoo I will create another issue that contains the current status and action items to resolve this issue. How about that?
> 
> It's ok to proceed. Close this and create another, then.

Before addressing this as another issue, I've tested several basic pipelines on Tizen-aarch64 board.

#### Environment
- Target: RPI3
- Kernel: 4.19.49-arm64-rpi3-v8 (**tizen-unified_20200528.2_iot-boot-arm64-rpi3.tar.gz**)
- Platform: rootfs and system-data are extracted from t(**izen-6.0-da-unified_20200528.142056_DA-M64-HEADLESS-WW-AD-DEBUG.tar.gz**)
- edgeTPU runtime:
  - [libedgetpu-dev-12.1-1.1.aarch64.rpm](http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/aarch64/libedgetpu-dev-12.1-1.1.aarch64.rpm) for Tizen-aarch64
  - For compiler for x66_64, 12.1-1 ([14237f65ba07b7b1d8287e9f60dd20c88562871a](https://github.com/google-coral/edgetpu/commit/14237f65ba07b7b1d8287e9f60dd20c88562871a))

#### 1. Plain MobiNet V1 (mobilenet_v1_1.0_224_quant.tflite)
```bash
gst-launch-1.0 filesrc location=/orange.png ! pngdec ! videoscale ! \
imagefreeze ! videoconvert ! video/x-raw,format=RGB,framerate=0/1 ! \
tensor_converter ! \
tensor_filter framework=edgetpu model=mobilenet_v1_1.0_224_quant.tflite ! \ 
filesink location=tensorfilter_edgetpu.out.log
```
- This pipeline worked fine with the edgeTPU. (without the device, it is failed to launch this pipeline.)

#### 2. Compiled MobiNet V1 (mobilenet_v1_1.0_224_quant_edgetpu.tflite)
- Failed to compile **mobilenet_v1_1.0_224_quant.tflite** on x86_64
```bash
$ ./edgetpu_compiler mobilenet_v1_1.0_224_quant.tflite 
Edge TPU Compiler version 2.0.267685300

Internal compiler error. Aborting! 
```

#### 3. Plain MobiNet V2 (mobilenet_v2_1.0_224_quant.tflite)
```bash
gst-launch-1.0 filesrc location=/orange.png ! pngdec ! videoscale ! \
imagefreeze ! videoconvert ! video/x-raw,format=RGB,framerate=0/1 ! \
tensor_converter ! \
tensor_filter framework=edgetpu model=mobilenet_v2_1.0_224_quant.tflite ! \ 
filesink location=tensorfilter_edgetpu.out.log
```
- This pipeline also worked fine with the edgeTPU. (without the device, it is failed to launch this pipeline.)

#### 4. Compiled MobiNet V2 (mobilenet_v2_1.0_224_quant_edgetpu.tflite)
- Failed to launch the pipeline
```bash
# ./runTest_edgetpu_mobinetV2_compiled.sh 
Null custom op data.
Node number 0 (edgetpu-custom-op) failed to prepare.

Failed to allocate tensors.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Invoke called on model that is not ready.
Failed to invoke tensorflow-lite + edge-tpu.
ERROR: from element /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0: Internal data stream error.
Additional debug info:
gstimagefreeze.c(924): gst_image_freeze_src_loop (): /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0:
streaming stopped, reason error (-5)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...

(gst-launch-1.0:1700): GStreamer-CRITICAL **: 11:04:59.338: gst_mini_object_unref: assertion '(g_atomic_int_get (&mini_object->lockstate) & LOCK_MASK) < 4' failed
Freeing pipeline ...
```

WiP...

**Comment by myungjoo** [comment]
Nicely done. As you've mentioned earlier today, we will need a edgetpu-compiled-binary-compatible filter; the current version uses delegation.

However, the priority depends on whether the client really need it right now or not.

**Comment by wooksong** [comment]
@myungjoo Here is the update on the compiled model with nnstreamer-edgeTPU (Note that mobilenet_v2_1.0_224_quant_edgetpu.tflite is used for this verification).
- The pipeline used for testing is as follows:
```
gst-launch-1.0 filesrc location=/orange.png ! pngdec ! videoscale ! \
imagefreeze ! videoconvert ! video/x-raw,format=RGB,framerate=0/1 ! \
tensor_converter ! \
tensor_filter framework=edgetpu model=mobilenet_v2_1.0_224_quant_edgetpu.tflite ! \ 
filesink location=tensorfilter_edgetpu.out.log
```
### Tizen-aarch64
  - With TFLite 1.15.2,
     - Worked fine.
  - With TFLite 1.13.1,
     - Failed to allocate tensors and invoke the framework
     - IMO, in this case, TFLite 1.13.1 does not support the model.
     - Possible solution: Release nnstreamer-edgetpu linked with tflite 1.15.2 via 
http://10.113.136.201/project/show/devel:Tizen:6.0:AI
```bash
      # ./run.sh                                      
      Null custom op data.
      Node number 0 (edgetpu-custom-op) failed to prepare.

      Failed to allocate tensors.
      Setting pipeline to PAUSED ...
      Pipeline is PREROLLING ...
      Invoke called on model that is not ready.
      Failed to invoke tensorflow-lite + edge-tpu.
      ERROR: from element /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0: Internal data stream error.
      Additional debug info:
      gstimagefreeze.c(924): gst_image_freeze_src_loop (): /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0:
      streaming stopped, reason error (-5)
      ERROR: pipeline doesn't want to preroll.
      Setting pipeline to NULL ...

      (gst-launch-1.0:3022): GStreamer-CRITICAL **: 09:59:40.526: gst_mini_object_unref: assertion '(g_atomic_int_get (&mini_object->lockstate) & LOCK_MASK) < 4' failed
      Freeing pipeline ...
```

### Ubuntu-x86_64
  - With TFLite 1.15.2,
    -  Case 1-F: ```ninja -C build install``` (since we do not release nnstreamer-edgetpu for ubuntu yet)
```bash
      INFO: Initialized TensorFlow Lite runtime.
      Setting pipeline to PAUSED ...
      Pipeline is PREROLLING ...
      ERROR: Node number 0 (edgetpu-custom-op) failed to invoke.

      Failed to invoke tensorflow-lite + edge-tpu.

       ** (gst-launch-1.0:26980): CRITICAL **: 17:50:27.295: Tensor-filter invoke failed (error code = -22).

      ERROR: from element /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0: Internal data stream error.
      Additional debug info:
      gstimagefreeze.c(851): gst_image_freeze_src_loop (): /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0:
      streaming stopped, reason error (-5)
      ERROR: pipeline doesn't want to preroll.
      Setting pipeline to NULL ...
      Freeing pipeline ...
```
    -  Case 1: After remove rpath of /usr/lib/nnstreamer/filters/
       libnnstreamer_filter_edgetpu.so, worked fine.

```bash
      $ sudo chrpath /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so 
      /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so: RUNPATH=$ORIGIN/../../../gst/nnstreamer:/home/wook/Work/NNS/nnstreamer/build/tests/nnstreamer_filter_edgetpu
      $ sudo chrpath /usr/lib/nnstreamer/filters/libnnstreamer_filter_edgetpu.so -d
```
  - With TFLite 1.13.1,
    -  Regardless of the rpath, failed to run the pipeline.
```bash
     Null custom op data.
     Node number 0 (edgetpu-custom-op) failed to prepare.
     ...omission...
     Invoke called on model that is not ready.
     Failed to invoke tensorflow-lite + edge-tpu.
     ...omission...
```

**Comment by myungjoo** [comment]
Would it be possible to let users know that they need to upgrade tf-lite in case it's failed due to 1.13 vs 1.15+ issue?

If it is entirely impossible, with unknown errors at the invocation of tf-lite, (or edge-tpu delegation), we need to emit additional info that the user may need to retry with different tf-lite versions.
