### ISSUE TITLE
[Protobuf] the different version of protobuf is required.

### ISSUE THREAD

**Issue by helloahn** [nnstreamer/nnstreamer#1970]
## Description
This issue is about the version of [protobuf](https://github.com/protocolbuffers/protobuf).

## Details
Currently, we've mainly been concentrating on the protobuf v3.6.1 because of the Tensorflow 1.9 recommends protobuf 3.6.1.
Unfortunately, however, the [mediapipe](https://github.com/google/mediapipe) requires protobuf v3.8.0 and it's not compatible with v3.6.1.

I'll report at this thread that the tensorflow 1.9 works properly with the protobuf 3.8.0 first.
If it is not compatible, we need to make a decision.

I need your opinion about this situation.

**Comment by myungjoo** [comment]
You don't need to check with tf 1.9. test with tf 1.13.
Another point to check is that tf might be building with its own protobuf.

**Comment by myungjoo** [comment]
Looks like related fixes are mostly merged?
