### ISSUE TITLE
Version Update of TensorFlow & Protobuf

### ISSUE THREAD

**Issue by helloahn** [nnstreamer/nnstreamer#2074]
Related to #1970 

Currently, we provide `ubuntuport-tensorflow` and `protobuf` through Launchpad.

However, because of below reasons, we need to update the version of the packages.
* there are many updates after those versions.
* the version of TF(1.13.1) and Protobuf(3.6.1) are not compatible with Mediapipe.

IMO, to make Mediapipe run without `bazel` or 'to include it at `NNStreamer` as an element, we have to update our packages and related resources.

The targeting new version is
* Tensorflow 1.15.x
* Protobuf 3.8.0

@wooksong will make the package of protobuf 3.8.0 & Tensorflow-Lite 1.15.x
@helloahn will handle Tensorflow 1.15.x

#### Action items
- [x] Copy the bazel (0.25.2) package to https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa from  https://launchpad.net/~neural-network-support/+archive/ubuntu/ppa @wooksong 
   - 19.04 https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+sourcepub/10976081/+listing-archive-extra
   - 18.04 https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+sourcepub/10976080/+listing-archive-extra
   - 16.04 https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+sourcepub/10976079/+listing-archive-extra
- [x] [ProtoBuf/Tizen] @wooksong 
  - Repository: [sandbox/wooksong/3.8.0](https://review.tizen.org/gerrit/gitweb?p=platform%2Fupstream%2Fprotobuf.git;a=shortlog;h=refs%2Fheads%2Fsandbox%2Fwooksong%2F3.8.0)
  - OBS Build Test (SPIN): [Tizen:5.0:TAOS:BuildTest](http://10.113.136.201/package/show/Tizen:5.0:TAOS:BuildTest/protobuf)
  - OBS Build Test (Public): [devel:AIC:Tizen:5.0:nnsuite](https://build.tizen.org/package/show/devel:AIC:Tizen:5.0:nnsuite/protobuf)
- [x] [ProtoBuf/Debian] @wooksong 
  - Repository: https://github.com/wooksong/tizenport-protobuf/tree/v3.8.0/debian
  - LaunchPad Build Test: [ppa-build-test](https://code.launchpad.net/~nnstreamer/+archive/ubuntu/ppa-build-test) 16.04/18.04/19.04/19.10/20.04
- [x] [FlatBuffers/Debian] (Required by tf-lite 1.15.2) @wooksong  
  - Repository: [sandbox/wooksong/v1.11.0](https://review.tizen.org/gerrit/gitweb?p=platform%2Fupstream%2Fflatbuffers.git;a=shortlog;h=refs%2Fheads%2Fsandbox%2Fwooksong%2Fv1.11.0-debian)
  - LaunchPad Build Test: [ppa-build-test](https://code.launchpad.net/~wooksong/+recipe/flatbuffers-test) 16.04/18.04/19.04/19.10/20.04
- [ ] [Tensorflow&TFLite/Debian] @helloahn @wooksong 
  - Build test was done about tensorflow 1.15 with `bazel-dist`(v0.25.2, @wooksong copied) at ubuntu `xenial/bionic`
  - Debian packaging for Bionic is done and merged at the [ubuntuport-tensorflow](https://github.com/nnsuite/ubuntuport-tensorflow/tree/debian/c_api/1.15.2)
  - LaunchPad Build Test: [ppa-build-test](https://code.launchpad.net/~wooksong/+recipe/tensorflow) 16.04/18.04/19.04
  - [WIP] Test for Xenial and unittests
- [x] [TFLite/Tizen] @wooksong 
  - Repository: [sandbox/wooksong/1.15.2](https://review.tizen.org/gerrit/gitweb?p=platform%2Fupstream%2Ftensorflow.git;a=shortlog;h=refs%2Fheads%2Fsandbox%2Fwooksong%2F1.15.2) (**Updated on Mar, 12**)
   - OBS Build Test (Public): [ devel:AIC:Tizen:5.0:nnsuite]
(https://build.tizen.org/package/show/devel:AIC:Tizen:5.0:nnsuite/tensorflow-lite)  (**Updated on Mar, 12**)

**Comment by myungjoo** [comment]
Please update Tizen as well.

If you are worried about compatibility with other packages, start with sandbox branchs + https://build.tizen.org/project/show/devel:AIC:Tizen:5.0:nnsuite

**Comment by helloahn** [comment]
> Please update Tizen as well.
> 
> If you are worried about compatibility with other packages, start with sandbox branches + https://build.tizen.org/project/show/devel:AIC:Tizen:5.0:nnsuite

Acked.

**Comment by wooksong** [comment]
@helloahn Please test TF and TF Lite with our tensor filters.

**Comment by siekanskiP** [comment]
Hi, when do you plan to release updated nnstreamer version with tf 1.15.x and protobuf 3.8?

**Comment by myungjoo** [comment]
@siekanskiP You can use tf 1.15.x with the current version of nnstreamer, you just need to install tf 1.15.x in your build machine and rebuild nnstreamer on it.

We are releasing binary packages of 1.15.x as there are clients who want to keep 1.13 :(

**Comment by myungjoo** [comment]
NOTE: This project is halted as 1.13.x is required by clients.

However, 1.15.x is tested with nnstreamer and users may build nnstreamer w/ tf 1.15.x. We just release official binaries with 1.13.x, not 1.15.x

**Comment by myungjoo** [comment]
In the long run, we may need to release multiple binary packages for multiple versions of TF (subplugin subpackages only)

**Comment by myungjoo** [comment]
Halt. As 1.15 is not desirable for the deployment. We will hold 1.13 and make it coexist with 2.x
