### ISSUE TITLE
Single-API only binary release

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2098]
- [x] Add a build option that build Single-API with necessary codes without dependencies on GStreamer. (for devices without Gstreamer) It will probably require tensor-filter subplugins and its secondary tensor-filter plugin only.
- [x] Add an Android build option to use such binary w/ Single-API only.
- [x] Release Single-API support only binaries along with conventional (as a seperated pacakge)
- [x] Add test cases for it to avoid regressions.

Note: do the first task and wait for others. We just need to be ready for this; some non-Tizen products/clients want this "mode".

**Comment by jaeyun-jung** [comment]
PR #2102 

How to build
1. Setup Android API build (https://github.com/nnsuite/nnstreamer/blob/master/api/android/README.md)

2. Download filter sub-plugin for SNAP
3. Download SNAP SDK interface from Samsung developer site
4. Copy SNAP SDK header and library to snap sub-plugin directory
    - copy header into `snap/include`
    - copy interface library to `snap/lib/arm64-v8a`
```
/SNAP_DIRECTORY <snap sub-plugin path>
     /snap
          /include
          /lib
              /arm64-v8a
     /Android-snap.mk
```
3. Set env-var
    - SNAP_DIRECTORY : dir path to snap sub-plugin
    - ANDROID_HOME : dir path to Android SDK
    - GSTREAMER_ROOT_ANDROID : dir path to GStreamer prebuilt libraries for Android
    - NNSTREAMER_ROOT : dir path to NNStreamer

4. Run build script with option (snap and single-shot only)
```
$ ./api/android/build-android-lib.sh --api_option=internal
```

You can find the library in `NNSTREAMER_ROOT/android_lib` directory.

**Comment by jaeyun-jung** [comment]
SNAP is available on arm64 only, so I am considering to upload nnstreamer / nnstreamer-lite only for arm64-v8a.

**Comment by myungjoo** [comment]
Because Android Play Store enforces to use aarch64, that's fine.
