### ISSUE TITLE
Support flat buffer

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#2124]
- [x] Tensor decoder subplugin - support tensor

- [x] Tensor decoder subplugin - support tensors

- [x] Tensor converter subplugin - support tensor

- [x] Tensor converter supports tensors

- [x] Tensor converter subplugin - support tensors

Flatbuffer is required for efficient data transfer between UDP communications or elements within the pipeline.
As the first step, I define a flatbuffer data structure of tensor and tensors.
An tensors is the basic type and a tensor has been replaced by the tensors.

*The following structures have been tested for normal operation

```
namespace NNStreamer;

enum tensor_type : int { 
  NNS_INT32 = 0,
  NNS_UINT32,
  NNS_INT16,
  NNS_UINT16,
  NNS_INT8,
  NNS_UINT8,
  NNS_FLOAT64,
  NNS_FLOAT32,
  NNS_INT64,
  NNS_UINT64 = 10,

  NNS_END = 99
  }

enum media_type : int { 
  NNS_MEDIA_INVALID = -1,
  NNS_VIDEO = 0,
  NNS_AUDIO = 1,
  NNS_TEXT = 2,
  NNS_OCTET = 3,

  NNS_MEDIA_PLUGINS = 99
}

struct frame_rate {
  rate_n : int;
  rate_p : int;
}

table Tensor {
  name  : string;
  t_type : tensor_type = NNS_END;
  m_type : media_type = NNS_MEDIA_INVALID;
  dim : string;
  fr : frame_rate;
  data : [ubyte];
}

table Tensors {
  num_tensor : int;
  tensor : [Tensor];
}

root_type Tensors;
```

Related issue : #1919

**Comment by jijoongmoon** [comment]
I think media_type is not need for flatbuffer <--> tensor, tensors.

**Comment by gichan-jang** [comment]
@myungjoo @anyj0527 
I would like to discuss before starting writing tensor insert subplugin.
What would be a good pipeline description for the flatbuf?
 1) appsrc _**! application/flatbuf ! tensor_converter !**_ tensor_sink
 2) appsrc _**! tensor_converter mode=flatbuf !**_ tensor sink
Or please recommend other description.

**Comment by myungjoo** [comment]
I'd suggest to start with 2 unless you have additional properties for ```application/flatbuf``` type.

**Comment by gichan-jang** [comment]
Since the converter and decoder of the flatbuffers are merged, close this issue.
