### ISSUE TITLE
[GLib] NULL checkings after  g_new(), ... , g_malloc(), ... , g_realloc() are unnecessary

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#2179]
From https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html,

> If any call to allocate memory using functions g_new(), g_new0(), g_renew(), g_malloc(), g_malloc0(), g_malloc0_n(), g_realloc(), and g_realloc_n() fails, the application is terminated. This also means that there is no need to check if the call succeeded. On the other hand, g_try_...() family of functions returns NULL on failure that can be used as a check for unsuccessful memory allocation. The application is not terminated in this case.

Possible solutions:
1. Don't care
2. Change all the g_new() or g_malloc()-like functions to g_try_...
3. Remove all NULL checkings after the g_new() or g_malloc()-like functions

IMHO. (2) is the best choice for us.

**Comment by myungjoo** [comment]
Crunch time is coming (multiple clients!). Thus, my choice would be 1.
But I won't NACK any activities related with 3.

But... 2 is NACK.

**Comment by wooksong** [comment]
> Crunch time is coming (multiple clients!). Thus, my choice would be 1.
> But I won't NACK any activities related with 3 and we need to share this "knowledge" with all core contributors :)
> 
> But... 2 is NACK.

@myungjoo ACKED. But I have a question. Is it Ok with immediate termination of the application without any clean-up procedure after failing g_malloc()?

**Comment by myungjoo** [comment]
> > Crunch time is coming (multiple clients!). Thus, my choice would be 1.
> > But I won't NACK any activities related with 3 and we need to share this "knowledge" with all core contributors :)
> > But... 2 is NACK.
> 
> @myungjoo ACKED. But I have a question. Is it Ok with immediate termination of the application without any clean-up procedure after failing g_malloc()?

If it is a unit test case code (its built binary won't be deployed to products) and if it really terminates the whole process, not cleaning up malloc-ed memory is OK.

If it is a core code (its built binary will be shipped to the products), it isn't ok. In such a case, it is NOT ok for us (a library) to terminate the application, either, in general. Thus, we need to remove asserts gradually if the assert may happen without critical internal bugs.

**Comment by myungjoo** [comment]
I think we'd fixed this already.
