### ISSUE TITLE
Android Engineering Sample Release for AI Developers

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2255]
1. .AAR for Android Studio developers;
- NNRuntime ( latest? android-binary ready? - check w/ CS-Lee)
- Single Only
- Both C and Java APIs
- ARM64/Android

Provide it for the "AI DEVEL" client.
Sample apps might be required.

2. Visit the client, do 1:1 pair programming for their package (adopting to nnstreamer API)

CC: @yunakim @lemmaa @chunseoklee

**Comment by jaeyun-jung** [comment]
PR #2260 (includes simple test with NNFW sub-plugin), I tested NNFW (CPU only) in my local.
I will update .mk file to build ML API  with prebuilt NNFW libs.

**Comment by jaeyun-jung** [comment]
#2260 add nnfw (nnstreamer android lib)
https://github.com/nnstreamer/nnstreamer-android-resource/pull/3 for native developer
