### ISSUE TITLE
DEB Packaging & Deployment of nnstreamer-example.git

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2271]
For "Get Started" page of nnstreamer.ai, it would be great if we have nnstreamer-example.deb for Ubuntu/PPA users!

**Comment by gichan-jang** [comment]
If no one handles it yet, I will do it.

**Comment by gichan-jang** [comment]
nnstreamer-example ppa is added.
ppa launchpad : https://launchpad.net/~nnstreamer-example
```
$ sudo add-apt-repository ppa:nnstreamer-example/ppa
$ sudo apt-get update
$ sudo apt-get install nnstreamer-example
$ cd /usr/lib/nnstreamer/bin
```

**Comment by myungjoo** [comment]
👍
