### ISSUE TITLE
meson: use feature option instead of boolean

### ISSUE THREAD

**Issue by gdesmott** [nnstreamer/nnstreamer#2281]
You may want to use [meson feature options](https://mesonbuild.com/Build-options.html#features) instead of booleans as we do in GStreamer. This is the proper way to enable/disable features and also allow to automatically enable features based on detected deps.

**Comment by myungjoo** [comment]
@zhoonit Would you please take a look on this? This might ve a good chance to become familiarize with meson for you.

**Comment by zhoonit** [comment]
No worries. I will take care of this :)
