### ISSUE TITLE
Do not make important calls inside g_assert()

### ISSUE THREAD

**Issue by ndufresne** [nnstreamer/nnstreamer#2282]
Hi there, this is a quick recommendation to improve your code quality. First thing that struck me when I inspected this is code is this type of usage:

```
g_assert (gst_buffer_map (srcbuf, &src_info, GST_MAP_READ));
```

It is common on embedded devices to compile out run-time checks. It's actually a GLib feature. If you construct your code the way you do, the call to gst_buffer_map() will be removed, and your code will crash badly. It is also usually recommended to cleanly handle map failure.

**Comment by myungjoo** [comment]
Thank you for pointing it out!
And I agree that map-errors should be handled property without assert.
