### ISSUE TITLE
[Potential Bug] ml_single_set_gst_info handles TFLITE & CUSTOM only

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2326]
ml_single_set_gst_info() of nnstreamer-capi-single.c supports
ML_NNFW_TYPE_{TENSORFLOW_LITE, CUSTOM_FILTER} only.

What about other frameworks and hardware accelerators?

**Comment by kparichay** [comment]
@myungjoo Yes, `ml_single_set_gst_info` should treat all the frameworks supported by the single-api same. `g_tensor_filter_set_input_info` in `tensor_filter_single.c` should be able to handle if this the set info is supported or not and return more detailed errors than just `gboolean`.
