### ISSUE TITLE
Experiment Request for Paper

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2345]
Since the last technical paper, nnstreamer has evolved significantly.

I'm updating the technical paper (2020-2nd-half) and I request for additional experiments:

1. NPU Usage (DA/V)
    - Tested H/W AMLOGIC + NPU
    - Tested S/W A: nnstreamer / B: no-nnstreamer
    - Tested Pipeline 1-1 - 1-2(or 3): different single NPU network / 2-1 - 2-2(or 3): two NPU networks / 3: two NPU networks + 1 CPU network
    - Metric: model latency (1-x only) / output framerate / memory usage / CPU workload / LoC

2. Compare w/ MediaPipe
    - Tested H/W TBD
    - Tested S/W A: nnstreamer (w/ tf or tf-lite direct inference) / B: mediapipe (pure) / C: nnstreamer + mediapipe (nnstreamer pipeline with mediapipe as element)
    - Tested Pipeline: TBD
    - Metric: model latency / output framerate / memory usage / CPU workload / pipeline LoC

CC: @helloahn / @again4you (@helloahn has experienced all the required setup. @again4you: please review experiment processes and oversee executions)

Don't hesitate to contact me for more information.

**Comment by helloahn** [comment]
The 3 commands will be used for profiling.
The `.pbtxt` files for the Mediapipe cases are in progress.

nnstreamer(tf-lite)
```bash
gst-launch-1.0 \
filesrc location=input_640x480.mp4 ! decodebin name=decode ! videoconvert ! \
videoscale ! video/x-raw,width=320,height=320,format=RGB ! tensor_converter ! \
tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
tensor_filter framework=tensorflow-lite model=mediapipe/models/ssdlite_object_detection.tflite ! \
fakesink
```

nnstreamer(mediapipe)
```bash
gst-launch-1.0 \
filesrc location=input_640x480.mp4 ! decodebin name=decode ! videoconvert ! \
videoscale ! video/x-raw,width=640,height=480,format=RGB ! tensor_converter ! \
queue max-size-buffers=4 ! \
tensor_filter framework=mediapipe model=nnstreamer_mediapipe_profiling_graph.pbtxt \
inputname=input_video input=3:640:480:1 inputtype=uint8 \
outputname=output_video output=3:640:480:1 outputtype=uint8 ! \
fakesink
```

mediapipe
```bash
bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tflite \
--calculator_graph_config_file=mediapipe/graphs/object_detection/object_detection_desktop_tflite_graph.pbtxt \
--input_side_packets=input_video_path=input_640x480.mp4,output_video_path=output_640x480.mp4
```

**Comment by myungjoo** [comment]
Great! Thanks!

**Comment by helloahn** [comment]
<table>
    <thead>
        <tr>
            <th rowspan=2 colspan=2>Input Video 1920*1080</th>
            <th colspan=3>TFLite 2.1.0</th>
            <th>TFLite 1.15.2</th>
            <th colspan=2>Preprocessing</th>
        </tr>
        <tr>
            <th>NNStreamer:<br>TFLite</th>
            <th>Mediapipe</th>
            <th>NNStreamer:<br>Mediapipe</th>
            <th>NNStreamer:<br>TFLite</th>
            <th>NNStreamer</th>
            <th>Mediapipe</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th rowspan=3>CPU</th>
            <td>real</td>
            <td>24.5611s</td>
            <td>25.4309s</td>
            <td>24.7302s</td>
            <td>8.2981s</td>
            <td>1.7524s</td>
            <td>2.3214s</td>
        </tr>
        <tr>
            <td>user</td>
            <td>37.7761s</td>
            <td>39.7359s</td>
            <td>40.697s</td>
            <td>22.2997s</td>
            <td>5.3238s</td>
            <td>6.1843s</td>
        </tr>
        <tr>
            <td>sys</td>
            <td>0.3692s</td>
            <td>1.9641s</td>
            <td>0.8415s</td>
            <td>0.3664s</td>
            <td>0.0793s</td>
            <td>1.3059s</td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY</th>
            <td>mmap sum</td>
            <td>126,540,822 </td>
            <td>1,312,817,824 </td>
            <td>776,418,434 </td>
            <td>129,471,106 </td>
            <td>87,089,061 </td>
            <td>1,275,804,576 </td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>204,005 </td>
            <td>187,716 </td>
            <td>301,913 </td>
            <td>204,354 </td>
            <td>172,188 </td>
            <td>148,238 </td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY (without Preprocessing)</th>
            <td>mmap sum</td>
            <td>39,451,761 </td>
            <td>37,013,248 </td>
            <td>689,329,373 </td>
            <td>42,382,045 </td>
            <td>- </td>
            <td>- </td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>31,817 </td>
            <td>39,478 </td>
            <td>129,725 </td>
            <td>32,166 </td>
            <td>- </td>
            <td>- </td>
        </tr>
        <tr>
            <th rowspan=3>FRAMERATE</th>
            <td>total output</td>
            <td>314</td>
            <td>314</td>
            <td>314</td>
            <td>314</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>running time</td>
            <td>24.5611</td>
            <td>25.4309</td>
            <td>24.7302</td>
            <td>8.2981</td>
            <td>1.7524</td>
            <td>2.3214</td>
        </tr>
        <tr>
            <td>fps</td>
            <td>12.78444369</td>
            <td>12.34718394</td>
            <td>12.69702631</td>
            <td>37.83998747</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <th>LATENCY (AVG of 200 dummies)</th>
            <td>microseconds</td>
            <td> 72,764 </td>
            <td> 74,683 </td>
            <td> 76,389 </td>
            <td> 22,288 </td>
            <td> - </td>
            <td> - </td>
        </tr>
    </tbody>
</table>

**Comment by helloahn** [comment]
<table>
    <thead>
        <tr>
            <th rowspan=2 colspan=2>Input Video 640*480</th>
            <th colspan=3>TFLite 2.1.0</th>
            <th>TFLite 1.15.2</th>
            <th colspan=2>Preprocessing</th>
        </tr>
        <tr>
            <th>NNStreamer:<br>TFLite</th>
            <th>Mediapipe</th>
            <th>NNStreamer:<br>Mediapipe</th>
            <th>NNStreamer:<br>TFLite</th>
            <th>NNStreamer</th>
            <th>Mediapipe</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th rowspan=3>CPU</th>
            <td>real</td>
            <td>15.2682s</td>
            <td>15.4335s</td>
            <td>16.0423s</td>
            <td>4.5025s</td>
            <td>0.3074s</td>
            <td>0.3026s</td>
        </tr>
        <tr>
            <td>user</td>
            <td>21.9833s</td>
            <td>22.5952s</td>
            <td>23.4281s</td>
            <td>11.5364s</td>
            <td>0.6034s</td>
            <td>0.7656s</td>
        </tr>
        <tr>
            <td>sys</td>
            <td>0.209s</td>
            <td>0.5203s</td>
            <td>0.5296s</td>
            <td>0.1891s</td>
            <td>0.0305s</td>
            <td>0.1059s</td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY</th>
            <td>mmap sum</td>
            <td>126,540,822</td>
            <td>1,308,668,576</td>
            <td>776,418,434</td>
            <td>129,471,106</td>
            <td>87,085,814</td>
            <td>1,269,552,000</td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>104,188</td>
            <td>123,209</td>
            <td>196,265</td>
            <td>103,561</td>
            <td>69,902</td>
            <td>91,173</td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY (without Preprocessing)</th>
            <td>mmap sum</td>
            <td>39,455,008</td>
            <td>39,116,576</td>
            <td>689,332,620</td>
            <td>42,385,292</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>34,286</td>
            <td>32,036</td>
            <td>126,363</td>
            <td>33,659</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <th rowspan=3>FRAMERATE</th>
            <td>total output</td>
            <td>205</td>
            <td>205</td>
            <td>205</td>
            <td>205</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>running time</td>
            <td>15.2682</td>
            <td>15.4335</td>
            <td>16.0423</td>
            <td>4.5025</td>
            <td>0.3074</td>
            <td>0.3026</td>
        </tr>
        <tr>
            <td>fps</td>
            <td>13.42659908</td>
            <td>13.28279392</td>
            <td>12.77871627</td>
            <td>45.53026097</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <th>LATENCY (AVG of 200 dummies)</th>
            <td>microseconds</td>
            <td>72,105</td>
            <td>73,407</td>
            <td>76,177</td>
            <td>21,732</td>
            <td>-</td>
            <td>-</td>
        </tr>
    </tbody>
</table>

**Comment by helloahn** [comment]
<table>
    <thead>
        <tr>
            <th rowspan=2 colspan=2>Input Video 1920*1080<br>60sec</th>
            <th colspan=3>TFLite 2.1.0</th>
            <th>TFLite 1.15.2</th>
            <th colspan=2>Preprocessing</th>
        </tr>
        <tr>
            <th>NNStreamer:<br>TFLite</th>
            <th>Mediapipe</th>
            <th>NNStreamer:<br>Mediapipe</th>
            <th>NNStreamer:<br>TFLite</th>
            <th>NNStreamer</th>
            <th>Mediapipe</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th rowspan=3>CPU</th>
            <td>real</td>
            <td>132.0337s</td>
            <td>137.0743s</td>
            <td>141.8717s</td>
            <td>38.803s</td>
            <td>9.6892s</td>
            <td>12.4186s</td>
        </tr>
        <tr>
            <td>user</td>
            <td>220.8596s</td>
            <td>219.5778s</td>
            <td>233.9112s</td>
            <td>135.2977s</td>
            <td>29.5123s</td>
            <td>34.0543s</td>
        </tr>
        <tr>
            <td>sys</td>
            <td>1.8361s</td>
            <td>11.0321s</td>
            <td>4.4418s</td>
            <td>1.5931s</td>
            <td>0.16s</td>
            <td>7.378s</td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY</th>
            <td>mmap sum</td>
            <td>143,325,889</td>
            <td>1,275,822,976</td>
            <td>776,413,997</td>
            <td>146,256,173</td>
            <td>87,089,061</td>
            <td>1,275,822,976</td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>199,527</td>
            <td>189,524</td>
            <td>307,600</td>
            <td>204,238</td>
            <td>171,364</td>
            <td>147,087</td>
        </tr>
        <tr>
            <th rowspan=2>MEMORY (without Preprocessing)</th>
            <td>mmap sum</td>
            <td>56,236,828</td>
            <td>-</td>
            <td>689,324,936</td>
            <td>59,167,112</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>usage (VmRSS, kB)</td>
            <td>28,1</td>
            <td>42,4</td>
            <td>136,</td>
            <td>32,8</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <th rowspan=3>FRAMERATE</th>
            <td>total output</td>
            <td>1818</td>
            <td>1818</td>
            <td>1818</td>
            <td>1818</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <td>running time</td>
            <td>132.0337</td>
            <td>137.074</td>
            <td>141.8717</td>
            <td>38.803</td>
            <td>9.6892</td>
            <td>12.4186</td>
        </tr>
        <tr>
            <td>fps</td>
            <td>13.76921195</td>
            <td>13.26290909</td>
            <td>12.81439498</td>
            <td>46.85204752</td>
            <td>-</td>
            <td>-</td>
        </tr>
        <tr>
            <th>FULL LATENCY (AVG of 200 dummies)</th>
            <td>microseconds</td>
            <td>72,764</td>
            <td>74,683</td>
            <td>76,389</td>
            <td>22,288</td>
            <td>-</td>
            <td>-</td>
        </tr>
    </tbody>
</table>

**Comment by myungjoo** [comment]
Great. I've applied the new results as well. Thanks!
