### ISSUE TITLE
[Google Store] nnstreamer multi-model is removed.

### ISSUE THREAD

**Issue by leemgs** [nnstreamer/nnstreamer#2349]
* nnstreamer android apps at Google Store:
  * nnstreamer multi-model app
  * nnstreamer ssd app

Recently, the **nnstreamer multi-model** app is removed by Google policy because the app requirements of Google Store is changed. 

![image](https://user-images.githubusercontent.com/82404/81242023-fd4cca00-9046-11ea-9e7e-8ac0233cd2a4.png)

**Comment by leemgs** [comment]
When we try to upload the existing **nnstreamer multi-model** app, we could meet the unexpected issue below. :(

##  Android App Bundles and APKs to add

* These app bundles and APKs will be served in the Google Play Store after the rollout of this releas

* Upload failed
  * The AndroidManifest.xml of the uploaded APK must not contain a meta-data entry with the name com.android.vending.derived.apk.id.

**Comment by again4you** [comment]
I will take at least 7 days for application review.

![appstore](https://user-images.githubusercontent.com/433435/83473466-a19a2300-a4c4-11ea-8db3-5c12fa04f2de.jpg)

**Comment by again4you** [comment]
Done!
* https://play.google.com/store/apps/details?id=org.freedesktop.gstreamer.nnstreamer.multi
