### ISSUE TITLE
Verify nnstreamer-example codes/guides. Add CI-tests in nnstreamer.git

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2353]
- [x] Test ALL nnstreamer-example applications with latest nnstreamer
- [x] Fix nnstreamer-example if it is no more compatible
- [x] Fix guides if it is not up to date
- [x] Add CI test of nnstreamer.git that builds all relevant nnstreamer-example.git apps for a PR in nnstreamer.git (Tizen, Android, Ubuntu)

**Comment by again4you** [comment]
All tasks are done so I close this issue.
