### ISSUE TITLE
Tracing GstBuffer in pipeline

### ISSUE THREAD

**Issue by Spiraline** [nnstreamer/nnstreamer#2365]
I'm trying to make Buffer Timeline Visualizer for NNStreamer.
Buffer Timeline Visualizer will visualize the time each buffer enters and exits the pad.
I think it can help profiling by mapping system profile information and buffer timeline information.
(We implemented [LiveProfiler](https://github.com/cts-2019f-nnstreamer/gst-shark) to see system profile information using gst-shark) 

Since the address of the buffer changes after passing through the filter, I tried to add metadata for each buffer. I found functions which add/get metadata for GstBuffer in gst library and implement custom metadata referring to [gst/nnstreamer/tensor_repo/tensor_repo.c / tensor_repo.h](https://github.com/nnstreamer/nnstreamer/blob/master/gst/nnstreamer/tensor_repo/tensor_repo.c).

```
typedef struct
{
  GstMeta meta;
  GstCaps *caps;
} GstMetaRepo;

GType gst_meta_repo_api_get_type (void);
#define GST_META_REPO_API_TYPE (gst_meta_repo_api_get_type())

const GstMetaInfo *gst_meta_repo_get_info (void);
#define GST_META_REPO_INFO ((GstMetaInfo*) gst_meta_repo_get_info())

#define gst_buffer_get_meta_repo(b) \
  ((GstMetaRepo*) gst_buffer_get_meta((b), GST_META_REPO_API_TYPE))

GstMetaRepo *gst_buffer_add_meta_repo (GstBuffer * buffer);

#define GST_META_REPO_GET(buf) ((GstMetaRepo*) gst_buffer_get_meta_repo(buf))
#define GST_META_REPO_ADD(buf) ((GstMetaRepo*) gst_buffer_add_meta_repo(buf))
```

In detail, I implemented above function by changing only the contents of metadata.

But when I tried to add custom metadata, it raised below warning and failed to add.
```
gst_buffer_add_meta: assertion 'gst_buffer_is_writable (buffer)' failed
```
I also found that there is function `gst_buffer_make_writable` which makes buffer writable. But after I used `gst_buffer_make_writable` and tried to add metadata, it raised below warning and halted.
```
gst_mini_object_unref: assertion 'GST MINI_OBJECT REFCOUNT VALUE (mini_object) > 0' failed
```

I think it is also address changing problem.
1) Can we add metadata to GstBuffer in such case?

2) If not, is it possible to trace Gstbuffer in pipeline? Specifically, I want to identify each buffer when it pushed to pad so I can make timeline for each buffer.

**Comment by myungjoo** [comment]
Assigned: @jijoongmoon and @jaeyun-jung , the main contributors of tensor_repo*

**Comment by myungjoo** [comment]
Closing this as there is no progress for long time.
