### ISSUE TITLE
Unit test fail when add custom mime type

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#2393]
I'm trying to add `other/flatbuf-tensor` to the converter.
When I added just below code, nnstreamer unit test for merge, mux and demux sometimes fail.
The TC number that fails is not consistent.
```
~~~
#define GST_FLATBUF_TENSOR_CAP_DEFAULT \
    "other/flatbuf-tensor, " \
    "framerate = " GST_TENSOR_RATE_RANGE

#define append_flatbuf_caps_template(caps) \
    gst_caps_append (caps, gst_caps_from_string (GST_FLATBUF_TENSOR_CAP_DEFAULT))
~~~
  append_flatbuf_caps_template (pad_caps);
```
When I debug the cap, it is appended well.
```
DEBUG       tensor_converter tensor_converter.c:1461:gst_tensor_converter_query_caps:
<tensorconverter0> caps = other/flatbuf-tensor, framerate=(fraction)[ 0/1, 2147483647/1 ];
```
I can't find the reason for failure. I ask for your help.

**Comment by myungjoo** [comment]
Mux and Demux support ```other/tensor(s)``` only.
```other/flatbuf-tensor``` should be translated by tensor-converter to ```other/tensor``` before fed to Mux/Demux.

**Comment by gichan-jang** [comment]
> Mux and Demux support `other/tensor(s)` only.
> `other/flatbuf-tensor` should be translated by tensor-converter to `other/tensor` before fed to Mux/Demux.

Thank you.
Cap of source pad is determined tensor or tensors depending on the peer cap of the following element. 
All test pass in all architecture now, I will close this issue after all flatbuf related PR are merged.
