### ISSUE TITLE
Need Privacy policy (개인정보 처리방침) for Android Store

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2408]
## Issue ##
Our sample applications use the `CAMERA` device. To register NNStreamer application in Android Store, we need to write Privacy policy (개인정보 처리방침) and publish it on the web. If not, below error occurs when publishing an application.

```
앱 APK에 포함된 버전 코드(1)가 특정 권한(android.permission.CAMERA)을 필요로 합니다.
APK에서 이 권한을 사용하는 앱에는 개인정보처리방침 세트가 필요합니다.
```
This is the governer's policy so we have to comply with that regulation.

Required items for Privacy policy are as below.
* 회사명 / 사이트명 / URL
* 개인정보 처리 방침 상세
* 개인정보 보호책임자 (성명/직책/직급/연락처)
* 개인정보보호 담당부서 (부서명/담당자/연락처)

## Possible Solutions ##
* Use Sansung's Privacy policy. ([Link](https://www.samsung.com/sec/info/privacy_new/))

* Write our own Privacy policy and publish it as wiki page.

**Comment by again4you** [comment]
I made a wiki page for Privacy policy of NNStreamer application.

* Privacy policy for NNStreaemr application: [Link](https://github.com/nnstreamer/nnstreamer-example/wiki/NNStreamer-Application%EC%9D%98-%EA%B0%9C%EC%9D%B8-%EC%A0%95%EB%B3%B4-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EC%B9%A8)

**Comment by myungjoo** [comment]
Let LF be the representative.

**Comment by myungjoo** [comment]
State that we do not receive or deal personal info.

```
개인정보처리 방침: NNStreamer Example App은 개인 정보를 보관하거나 가져오지 않습니다.
```
