### ISSUE TITLE
Packaging conflict between tensorflow-lite-dev and libflatbuffers-dev

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2435]
## Issue Description

Both `tensorflow-lite-dev` and `libflatbuffers-dev` have the same header files of flatbuffers. Moreover, its version is different.
* tensorflow-lite-dev: flatbuffer __v1.9.0__
* libflatbuffers-dev: flatbuffer __v1.11.0__

Because of this reason, installration failure ouccurs when installing both of them.
IMHO, there will be a compile time error or runtime error when executing flatbuffer subplugin.

-------------------
* `tensorflow-lite-dev` package
```bash
$ dpkg-query -L tensorflow-lite-dev | grep flatbuffer
/usr/include/flatbuffers
/usr/include/flatbuffers/code_generators.h
/usr/include/flatbuffers/minireflect.h
/usr/include/flatbuffers/flatc.h
/usr/include/flatbuffers/grpc.h
/usr/include/flatbuffers/flexbuffers.h
/usr/include/flatbuffers/idl.h
/usr/include/flatbuffers/stl_emulation.h
/usr/include/flatbuffers/hash.h
/usr/include/flatbuffers/registry.h
/usr/include/flatbuffers/flatbuffers.h
/usr/include/flatbuffers/base.h
/usr/include/flatbuffers/reflection_generated.h
/usr/include/flatbuffers/reflection.h
/usr/include/flatbuffers/util.h
/usr/include/tensorflow/lite/core/api/flatbuffer_conversions.h
```

* `libflatbuffers-dev` package
```bash
$ dpkg -c libflatbuffers-dev_1.11.0-0~202003310618~ubuntu16.04.1_amd64.deb 
drwxr-xr-x root/root         0 2020-04-01 13:36 ./
drwxr-xr-x root/root         0 2020-04-01 13:36 ./usr/
drwxr-xr-x root/root         0 2020-04-01 13:36 ./usr/include/
drwxr-xr-x root/root         0 2020-04-01 13:36 ./usr/include/flatbuffers/
-rw-r--r-- root/root      9336 2020-04-01 12:44 ./usr/include/flatbuffers/stl_emulation.h
-rw-r--r-- root/root     36606 2020-04-01 12:44 ./usr/include/flatbuffers/idl.h
-rw-r--r-- root/root     52807 2020-04-01 12:44 ./usr/include/flatbuffers/flexbuffers.h
-rw-r--r-- root/root     23753 2020-04-01 12:44 ./usr/include/flatbuffers/util.h
-rw-r--r-- root/root      3631 2020-04-01 12:44 ./usr/include/flatbuffers/hash.h
-rw-r--r-- root/root     12601 2020-04-01 12:44 ./usr/include/flatbuffers/base.h
-rw-r--r-- root/root     95674 2020-04-01 12:44 ./usr/include/flatbuffers/flatbuffers.h
-rw-r--r-- root/root      2992 2020-04-01 12:44 ./usr/include/flatbuffers/flatc.h
-rw-r--r-- root/root     20577 2020-04-01 12:44 ./usr/include/flatbuffers/reflection.h
-rw-r--r-- root/root      6858 2020-04-01 12:44 ./usr/include/flatbuffers/code_generators.h
-rw-r--r-- root/root     42713 2020-04-01 12:44 ./usr/include/flatbuffers/reflection_generated.h
-rw-r--r-- root/root      4489 2020-04-01 12:44 ./usr/include/flatbuffers/registry.h
-rw-r--r-- root/root     11755 2020-04-01 12:44 ./usr/include/flatbuffers/grpc.h
-rw-r--r-- root/root     13177 2020-04-01 12:44 ./usr/include/flatbuffers/minireflect.h

**Comment by gichan-jang** [comment]
I'm trying packaging tf-lite-dev excluding flatbuf headers.
( https://code.launchpad.net/~gichan-jang/nnstreamer-packaging-test/+git/trunk )
If there is a runtime problem, I think we should lower the version of the flatbuf.

**Comment by myungjoo** [comment]
Then, you need to make sure that applications built with tf-lite run with the platform's flatbuf.

If we update tf-lite to be built with platform's flatbuf (removing flatbuf tar.gz from tensorflow git), it'd be a perfect solution, though.

**Comment by gichan-jang** [comment]
> Then, you need to make sure that applications built with tf-lite run with the platform's flatbuf.
> 
> If we update tf-lite to be built with platform's flatbuf (removing flatbuf tar.gz from tensorflow git), it'd be a perfect solution, though.

I fixed tf-lite-dev pkg to build protobuf and flatbuf as a minor workaround. 
(to solve build fail : https://github.com/nnstreamer/nnstreamer/pull/2426 )
I'will remove flatbuf.tar.gz and link dependency to the flatbuf.
