### ISSUE TITLE
Add various Android AAR libraries to Internal Artifactory

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2446]
@jaeyun-jung Please add various Android AAR libraries (doing it manually is ok for initial releases) to the internal Artifactory repos, preferably this week (or Mon/Tue of next week).

**Comment by jaeyun-jung** [comment]
uploaded to generic
```
nnstreamer/libs/<date>
    /nnstreamer-2020-06-11.aar
    /nnstreamer-lite-2020-06-11.aar
    /nnstreamer-single-2020-06-11.aar
```

**Comment by myungjoo** [comment]
Consider using maven instead of generic

**Comment by jaeyun-jung** [comment]
generic : includes .aar and native.zip
maven: uploaded (initial ver 0.0.1 LGPL-2.1)

**Comment by myungjoo** [comment]
Done! Please maintain it properly.
