### ISSUE TITLE
Tizen/API Request (element-wise properties)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2466]
1. Get nnstreamer element instance (e.g., tensor_filter, tensor_converter, ...) based on name
2. Get/Set a few (predetermined / allowed by platform developers) properties
    e.g., update sync-policy of tensor_mux
3. Put the nnstreamer element instance

Usage example, update sync policy in custom-easy function, 

4. Make sure that custom-easy is working properly with Tizen APIs

ps. @jaeyun-jung Please look at this together (would Android counterpart be required as well??)

**Comment by again4you** [comment]
### Psudo code for Request 1, 2 and 3
```cpp
const char *pipeline = "videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! videorate max-rate=1 ! " \
"tensor_converter ! tensor_mux name=mux! tensor_demux ! tensor_sink sync=true";

status = ml_pipeline_construct (pipeline, NULL, NULL, &handle);

// New API
// - Currently private API
status = ml_pipeline_get_element (handle, "mux", &ele_handle);

// New API, Which one is better?
status = ml_pipeline_set_property (ele_handle, "sync_mode", "nosync");
status = ml_pipeline_set_property (ele_handle, "sync_mode=nosync", NULL);

// New API
status = ml_pipeline_get_property (ele_handle, "sync_mode, &mode);
g_free (mode);

status = ml_pipeline_start (handle);
...

// New API
status = ml_pipeline_release_element (ele_handle);

status = ml_pipeline_destroy (handle);
...
```

**Comment by myungjoo** [comment]
The draft looks good.
```
status = ml_pipeline_set_property (ele_handle, "sync_mode", "nosync");
```
would be my choice, and we need to support setting multiple properties for an element:
```
status = ml_pipeline_set_property (ele_handle, "sync_mode", "base", "basepad", "src0");
```
Refer: GStreamer / GLIB APIs.
