### ISSUE TITLE
[edgetpu]How can I upgrade tensorflow-lite?

### ISSUE THREAD

**Issue by junmin-kim** [nnstreamer/nnstreamer#2489]
I converted a frozen model to a tflite model, and converted the tflite model to a edge-tpu model.
Then, I tried to run with nnstreamer-edgetpu(installed version: `1.5.3.0-0~202006220018~ubuntu18.04.1`).
But I encountered below log.
```
Null custom op data.
Node number 0 (edgetpu-custom-op) failed to prepare.


** (gst-launch-1.0:24860): CRITICAL **: 13:18:43.154: Failed to allocate tensors.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Invoke called on model that is not ready.

** (gst-launch-1.0:24860): CRITICAL **: 13:18:43.157: A compiled model by edgetpu-compiler has been given, but this extension might be statically linked with TensorFlow Lite v1.13.1 which does not support the model.

** (gst-launch-1.0:24860): CRITICAL **: 13:18:43.157: To use this model, we recommend to upgrade the tensorflow-lite package to version 1.15.2 and rebuild the subplugin with the upgraded tensorflow-lite.
Failed to invoke tensorflow-lite + edge-tpu.

** (gst-launch-1.0:24860): CRITICAL **: 13:18:43.157: Tensor-filter invoke failed (error code = -22).

ERROR: from element /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0: Internal data stream error.
Additional debug info:
gstimagefreeze.c(851): gst_image_freeze_src_loop (): /GstPipeline:pipeline0/GstImageFreeze:imagefreeze0:
streaming stopped, reason error (-5)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

It seems that I have to upgrade the tensorflow-lite package, but I'm using the nnstreamer-edgetpu package from ppa.
Is it possible to upgrade tflite with ppa nnstreamer-egdetpu?
How can I solve this problem?

**Comment by myungjoo** [comment]
If you want to use newer versions of tensorflow-lite, you need to uninstall PPA packages and rebuild nnstreamer with newer versions of tensorflow-lite and install your own built binaries.

**Comment by wooksong** [comment]
@junmin-kim FYI, please refer this PPA: https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa-build-test

**Comment by junmin-kim** [comment]
@wooksong I added ppa-build-test repo. and updated the tensorflow-lite-dev(`1.15.2-0~202004010609~ubuntu18.04.1`).
And I reinstalled nnstreamer-edgetpu, but the same log occurs.

So, I tried to remove tensorflow-lite-dev, and reinstall&run nnstreamer-edgetpu **without** tensorflow-lite-dev.
I expected `no tensorflow lite package`, but I got `but this extension might be statically linked with TensorFlow Lite v1.13.1`.

I think I should check where nnstreamer-egdetpu links tensorflow-lite.
Would you let me know?

**Comment by myungjoo** [comment]
Please check if you have uninstall ALL nnstreamer-* packages before reinstalling packages from test ppa.

**Comment by junmin-kim** [comment]
I tried below, but it doesn't work.
```
$ conda remove tensorflow
$ sudo apt purge nnstreamer*
$ sudo apt purge tensorflow*
$ sudo apt install tensorflow*
$ sudo apt install nnstreamer nnstreamer-edgetpu 
```

**Comment by myungjoo** [comment]
Without specifics (do not erase info when you quote terminal outputs), nobody can know what's wrong.
What's the version/commit-id of each subpackage you've installed? (don't let us ask specifics again and again, please include all related info from the first place)

**Comment by junmin-kim** [comment]
Now, I tried to build NNStreamer from the GitHub repository.

I tried below.
1. Modify `meson_options.txt`
```
...
option('enable-edgetpu', type: 'boolean', value: true)
...
```
2. meson build && ninja -C build install
    2-1.  I asked, "Is edgetpu run-time dependency not found is okay?". And this is the right log.
    ```
    Run-time dependency edgetpu found: NO (tried pkgconfig and make)
    Has header "edgetpu.h" : YES 
    Library edgetpu found: YES
    ```
3. gst-inspect-1.0 tensor_filter
    3-1. I encountered the below log.
    ```
    No such element or plugin 'tensor_filter'
    ```

    3-2. Add the path to my `.bashrc`
    ```
    export NN_ROOT_PATH=/home/mycomputer/github/nnstreamer/
    export GST_PLUGIN_PATH=${NN_ROOT_PATH}/build/gst/nnstreamer
    export NNSTREAMER_CONF=${NN_ROOT_PATH}/nnstreamer/nnstreamer.ini
    export NNSTREAMER_FILTERS=${NN_ROOT_PATH}/build/ext/nnstreamer/tensor_filter
    export NNSTREAMER_DECODERS=${NN_ROOT_PATH}/build/ext/nnstreamer/tensor_decoder
    ```
4. Run GStreamer
    ```
    gst-launch-1.0 \
            filesrc location=orange.jpg ! jpegdec ! videoscale ! imagefreeze ! videoconvert ! video/x-raw,format=RGB,framerate=0/1 ! \
            tensor_converter ! tensor_filter framework=edgetpu model=mobilenet_v1_1.0_224_quant_edgetpu.tflite ! \
            tensor_decoder mode=image_labeling option1=labels.txt ! \
            fdsink fd=1
    ```

    4-1. I encountered the below log.

    ```
    WARNING: erroneous pipeline: no element "tensor_converter"
    ```

**Comment by junmin-kim** [comment]
According to 3-2, where can I find the documentation about that?
I referred [getting-started](https://github.com/nnstreamer/nnstreamer/blob/master/Documentation/getting-started.md), but I can't find about setting the path.

**Comment by myungjoo** [comment]
> 1. Modify meson_options.txt
...
option('enable-edgetpu', type: 'boolean', value: true)
...

No, don't modify meson_options.txt

Add option at build-timd.
E.g.,
```
$ meson build -Denable-edgetpu=true
```

> 2-1. I asked, "Is edgetpu run-time dependency not found is okay?". And this is the right log.

That's fine. It only means edgetpu is not found with pkgconfig, but it is found with headers.


> 4.

```$ gst-inspect-1.0 tensor_converter``` ?


Where did you install with ```meson build install``` ?
You need to make sure that the gstreamer is loading the newly built nnstreamer, not the preloaded and old nnstreamer binaries; you may need to uninstall old nnstreamer binaries to make sure.

**Comment by junmin-kim** [comment]
I removed `/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so` and reinstall, but no difference.
I think it is something like a permission problem...
When I tried `gst-inspect-1.0` without `sudo`,  I can find `tensor_converter`.
But with `sudo`, I can't find `tensor_converter`


```
$ sudo gst-inspect-1.0 tensor_converter
No such element or plugin 'tensor_converter'
$ sudo gst-launch-1.0 videotestsrc ! tensor_converter ! tensor_sink
WARNING: erroneous pipeline: no element "tensor_converter"
```

```
$ gst-inspect-1.0 tensor_converter
Factory Details:
  Rank                     none (0)
  Long-name                TensorConverter
  Klass                    Converter/Tensor
  Description              Converts audio or video stream to tensor stream of C-Array for neural network framework filters
  Author                   MyungJoo Ham <myungjoo.ham@samsung.com>

Plugin Details:
  Name                     nnstreamer
  Description              nnstreamer plugin library
  Filename                 /home/tinyara/github/nnstreamer/build/gst/nnstreamer/libnnstreamer.so
...

$ gst-launch-1.0 videotestsrc ! tensor_converter ! tensor_sink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:01.091688204
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by myungjoo** [comment]
env-vars in root will be different. you need to setup env for root if you want to use it under sudo; install all nnstreamer files to the regular locations (/usr/lib, not /usr/local/lib or /home/....). 

In fact, you are not supposed to use sudo for non-administrative tasks in general Linux. If you need sudo here, you are doing it wrong.

**Comment by junmin-kim** [comment]
Summary:
If you want to run NNStreamer with the model which is compiled by the **edgetpu-compiler**, you should uninstall PPA packages and rebuild NNStreamer with the upgraded TensorFlow Lite.
