### ISSUE TITLE
Dynamic tensor(s) config update event

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#2492]
Currently, the nnstreamer does not have the function to update tensor(s) config when the tensor(s) config is changed after playing.
For example, since the tensor config information of the flatbuf is not known before converting it to tensor. 
So, dimension of tensor config is defined as 1: 1: 1: 1.
After conversion from the flatbuf to the tensor, the decoder still considers the dimension 1: 1: 1: 1.

example pipeline : 
gst-launch-1.0 v4l2src ! videoconvert ! videoscale ! video/x-raw, width=640, height=480, framerate=5/1,format=RGB ! \
tensor_converter ! tensor_decoder mode=flatbuf ! other/flatbuf-tensor ! tensor_converter ! \
tensor_decoder mode=direct_video ! videoconvert !  videoscale ! video/x-raw,width=640,height=480 ! xvimagesink

When I forcibly updated tensors config, the pipeline worked normally.

Therefore, I ask for feedback on the direction of the modification.
1. Generates a downstream event when the tensor (s) config is changed.
2. The element that receives the event updates tensor(s) config and cap.
3. The element that receives the event drops all buffers being processed or in possession.
4. Remove self->configured and check validation whenever necessary

**Comment by myungjoo** [comment]
Could you please survey how other GStreamer elements react to GSTCAP update events, first?

**Comment by myungjoo** [comment]
As we have discussed recently with @jaeyun-jung , we'd better use the conventional caps-update events and do close-re-open converter subplugin with updated caps (don't do it if the new cap is the same as the old cap)
