### ISSUE TITLE
Tizen ACR for 6.0 M2 release

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2499]
### Add ###
* https://github.com/nnstreamer/nnstreamer/pull/2355
  * Added `ML_NNFW_TYPE_SNPE` enum value into ml_nnfw_type_e

* https://github.com/nnstreamer/nnstreamer/pull/2377
  * Added `ML_NNFW_HW_CPU_SIMD` enum value into ml_nnfw_hw_e

* https://github.com/nnstreamer/nnstreamer/pull/2455
  * Add new API for custom filter
  * Review stage

* https://github.com/nnstreamer/nnstreamer/pull/2476
  * Add element-wise control functions
  * Review stage

### Modify ###
* https://github.com/nnstreamer/nnstreamer/pull/2341
  * No signature changed / Comment updated

* https://github.com/nnstreamer/nnstreamer/pull/2472
  * Remove unnecessary error code 

### Native API ###
* [Add] Add new API and enum for neural network framework
  * https://code.sec.samsung.net/jira/browse/ACR-1571
  * Status: `ACR APPROVE`
  * Notice: [Link](http://mosaic.sec.samsung.net/kms/comty.do?comtyId=2305148&menuId=2305189&postId=835576166&page=view&type=LIST&access=ADDRESS)

* [Modify] Remove unnecessary error code and update comments
  * https://code.sec.samsung.net/jira/browse/ACR-1572
  * Status: `ACR APPROVE`
  * Notice: [Link](http://mosaic.sec.samsung.net/kms/comty.do?comtyId=2305148&menuId=2305189&postId=810167279&page=view&type=LIST&access=ADDRESS)

### C# API ###
* [Add] Add CustomFilter class and getter/setter methods to NodeInfo class
  * https://code.sec.samsung.net/jira/browse/TCSACR-365
  * Status: `TCS PREPARE`
  * Notice: [Link](http://mosaic.sec.samsung.net/kms/comty.do?comtyId=2772060&menuId=2772069&postId=866858792&page=view&type=LIST&access=ADDRESS)
 * Snapshot : tizen-unified_20200827.2

**Comment by myungjoo** [comment]
Let's start ACR process in July.

**Comment by myungjoo** [comment]
Only TCACR is remaining and it is already at DOC PREPARE. So let's close this. We do not have any actual things left to do for this.
