### ISSUE TITLE
Sample Apps for .webp (.gif) animations

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2518]
More sample apps with more visualization effects (tensor-decoder subplugins) for .webp animations

1. Need appropriate sample apps. Write apps and upload to nnstreamer-example.git with proper build scripts
2. Capture appropriate .webp files of it
3. Publish the .webp files! (along with README.md for the sample apps)
4. Update README.md with the new .webp demo-animations. We will update nnstreamer.ai pages accordingly, then.

**Comment by kbumsik** [comment]
FYI, I've looked into this issue, however, GStreamer doesn't seem to support animated webp/gif.

[webpdec from gst-plugins-bad](https://gstreamer.freedesktop.org/documentation/webp/webpdec.html?gi-language=c#webpdec-page) does support decoding WebP pictures but does not support WebP animations. It can be confirmed by looking at [the source code](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/tree/master/ext/webp) that does not use [libwebp Demux API](https://developers.google.com/speed/webp/docs/container-api#demux_api) which is necessary to obtain multiple frames.

We might consider using [libav (from FFPMEG) GStreamer plugin](https://gstreamer.freedesktop.org/documentation/libav/avdec_webp.html?gi-language=c#avdec_webp) but [it doesn't support decoding animated WebP images neither](https://trac.ffmpeg.org/ticket/4907).

Similarly, GStreamer [can decode only a single from from animated .gif files](http://gstreamer-devel.966125.n4.nabble.com/Animated-gif-files-are-not-supported-td4666690.html).

That's what I have found so far, but things can get better later.
