### ISSUE TITLE
To SOS-Master, Contributon, SOS-Mine/SAFFY Participants (Korean)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2519]
**SOS-master, 오픈소스 컨트리뷰톤, SOS-Mine 행사 참가자 여러분들을 위한 공지입니다.**
This announcement is for SOS-master, Open-source-contributon, SOS-MINE participants, who are expected to be able to read Korean.

## 소통 채널

- 개인 메일이나 메신져 보다는 모든 분들이 함께 보실 수 있는 곳에서 소통 하시는 것이 보다 오픈소스 개발 모델에 적합합니다.
    - nnstreamer **공용 채팅방**: https://gitter.im/nnstreamer/Lobby
    - nnstreamer **메일링 리스트**: https://lists.lfai.foundation/g/nnstreamer-technical-discuss/topics
        - 일반적인 질문은 mailing list가 가장 적합하겠습니다.
    - nnstreamer **GitHub Issue**: https://github.com/nnstreamer/nnstreamer/issues
    - https://nnstreamer.slack.com
    - GitHub Issue에는 Bug Report, 구현하시려는 기능 제안의 목적에 보통 적합하며, Bug Report때에는 쉽고 빠르게 재현 가능하도록 관련한 모든정보가 포함되면서도 간결해야 합니다. 재현하기 위한 사용환경과 재현하기 위한 코드 (필요없는 부분을 모두 제거한 최소한의 코드)와 실제 에러 로그가 포함되어야 합니다.

&nbsp;

- 구현해 보시려는 기능이 있을 경우, GitHub Issue에 먼저 기능에 대해 소개를 해주시고 실제 구현에 들어가시는 것을 권장합니다.
    - 특정 오픈소스 행사 참가의 일환이신 경우 글 본문에 언급해 주셔도 됩니다.
    - GitHub issue에서 충분히 이야기 되지 않고 덜컥 Pull-request부터 하시면 시간과 노력만 많이 소모하고 받아들일 수 없는 경우가 쉽게 발생합니다.

&nbsp;

- 언어: 개발자와 사용자/LF-관계자 분들은 타 언어권 분들도 많이 계셔서 가능하면 영어 사용 권장드립니다.

&nbsp;

## Pull-Request (PR)

- Pull-Request를 올리고 실제로 적용될때까지 오랜 시간이 걸릴 수 있습니다. 특히 익숙하지 않으신 분들이라면. 다음 사항에 대해서도 생각해 주세요.
    - Coding Style, 읽기 쉬운 코드, 충분한 테스트, 기존 기능과의 간섭 가능성 고려
    - PR에 대한 CI의 Test는 당연히 모두 통과되어야 함. (PR submit 전 미리 빌드 / 테스트 해보시기 바랍니다.)
    - Architecture적인 문제도 고려 필요. (plugin만 수정되어야 하는 상황에서 core, framework를 수정하시려는 경우가 가장 흔합니다: OCP 원칙)
    - 하나의 PR에는 하나의 주제로 빠르고 쉽게 **타인이** 읽을 수 있는 분량만. (그래야 제때 리뷰 받습니다.)
    - 각각의 PR은 독립적으로 Build & Test 성공해야 함.
    - **리뷰어들의 지적과 비판은 코드에 대한 것이지, 작성자 개인에 대한 것이 아닙니다.** PR하신 코드에 대해 비판이 이어지고 그에 대한 대응으로 개선된 코드가 다시 올라온 뒤 (PR수정), 다시 그에 대해 비판이 이어지는 "Cycle"은 매우 흔합니다. 이미 수백개의 PR을 Merge시킨 Committer들도 자꾸만 겪는 일이니, 리뷰어들의 지적과 비판에 실망하지 마세요.

&nbsp;

- 한번 올린 Pull-Request를 수정하실 때에는 지우고 다시 올리시면 안됩니다. 기존 기록을 모두 보존할 수 있도록 기존 Pull-Request에 대해 덮어 쓰시거나 Commit을 추가해 주세요. (Commit 추가로 하신 경우 나중에 Commit Squash를 요청드리게 됩니다.)

&nbsp;

- 다른 PR에 대한 Review에도 참여 함께 해 주세요.

&nbsp;

## Issue / 개발 Item 고르기

- "sos-masters" tag에 지나치게 신경 쓰실 필요 없습니다. 새 주제를 발굴하시고 Issue를 생성하시고 진행하셔도 되며, 기존 Issue 에 참여하셔도 괜찮습니다. 단, 릴리즈 스케쥴와 관련이 될 경우에는 Committer가 "낚아채어" 완료해 버릴 가능성은 있습니다. (특히 "Release Critical" tag가 붙거나 단기간의 Milestone이 할당되는 경우)
- 오픈소스 활동에 익숙하지 않은 경우 처음에는 문서를 개선해 주시거나, 코드내 주석을 개선해 주시는 것으로 시작하시는 것을 권장합니다. 그 후 [Sample/Example Application 개발](https://github.com/nnstreamer/nnstreamer-example) 이나 [Code Coverage](http://nnsuite.mooo.com/nnstreamer/ci/gcov_html/index.html) 보시고 빠져있는 [Test Case](https://github.com/nnstreamer/nnstreamer/tree/master/tests) 추가를 하시면서 워밍업 하셔도 좋습니다.

## Workshops (offline / online) w/ reviewers

- 개별 PR이나 Issue에 대한 기술적 토론은 Github내에서 충분할 것이지만, 다수의 참가자 분들이 미리 어느정도 주제를 모으실 수 있으면 평일 저녁시간 중 개최 가능할 것 같습니다.

&nbsp;

**Comment by kbumsik** [comment]
안녕하세요, 이번 오픈소스 컨트리뷰톤 참가자입니다.
SOS-Master 에 행사는 잘 몰라서 질문드리는건데요, 그럼 이슈에 붙은 `sos-master` 라벨은 "Good First Issue" 와 비슷한 것이라고 봐도 될까요?

**Comment by myungjoo** [comment]
> 안녕하세요, 이번 오픈소스 컨트리뷰톤 참가자입니다.
> SOS-Master 에 행사는 잘 몰라서 질문드리는건데요, 그럼 Issue에 붙은 `sos-master` 라벨은 "good first issue" 라벨과 비슷한 것이라고 봐도 될까요?

네, 그렇게 보셔도 됩니다.

**Comment by myungjoo** [comment]
Closing (temporarily) as there are no on-going events.
