### ISSUE TITLE
tflite interpreter fine control using nnstreamer tflite filter

### ISSUE THREAD

**Issue by junmin-kim** [nnstreamer/nnstreamer#2527]
Hello, all.

**Is your feature request related to a problem? Please describe.**
I'm trying to control the TensorFlow lite interpreter using nnstreamer tflite filter.
I want to set inputs, outputs, and execution plan, so below are functions I want to use.

- tflite::Interpreter::SetInputs
- tflite::Interpreter::SetOutputs
- tflite::Interpreter::SetExecutionPlan

It seems that there is no code about these functions in `tensor_filter_tensorflow_lite.cc`.

**Describe the solution you'd like**
I can set these properties when I construct the pipeline if you support these features.

**Describe alternatives you've considered**
Or if you are not going to support, maybe I can make the custom filter.

**Additional Context**
I'm not sure what should I do when I need features that are not supported in tensor_filter.
Requests features? or makes our own filter?
Would you give your policy about it?

Thanks,
Junmin

**Comment by junmin-kim** [comment]
I'll consider it more and reopen this.

**Comment by myungjoo** [comment]
Closing this as there is no progress. Reopen when you are ready to continue.
