### ISSUE TITLE
Gtest tc name shouldn't include underscore

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nnstreamer#2541]
Gtest recommends [not to use underscore](https://github.com/google/googletest/blob/master/googletest/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore) in test names.

I think it could be applied to nnstreamer as well.

Please review this issue and label as SOS-MASTERS if it'd be fine 🐹  

Expected Workload: ~ 1 md (man-day)

**Comment by myungjoo** [comment]
Any sos-masters or contributon participants may take and resolve this issue.

**Comment by JuYeong0413** [comment]
I would like to work on this issue. 🙂 
(By the way, the reference documentation has moved to https://github.com/google/googletest/blob/master/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore)

**Comment by gichan-jang** [comment]
As one of the test rules of the nnstreamer, the negative case must always end with `_n`.
Please revise it with this rule.
