### ISSUE TITLE
Tizen/C-API/NNFW Performance (Latency) Issue

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2546]
Please optimize run-time performance of nnfw subplugin to the ultimate level.
- No I/O buffer memcpy at all
- No conversions
- Search for better nnfw internal APIs
- You may disable timeout feature for nnfw (as the default behavior) if that's helpful.
    - Or.. as we've discussed a few minutes ago, default timeout = INFINITE & when timeout is INFINITE, make it bypass all related timeout-routines.
    - In this case, you can release first and do SR later.
- And any mechanisms you can imagine :)

@lemmaa @chunseoklee : please let us know the case where the performance lag happens.

@jaeyun-jung  Let's try to finish this up around 7/21

**Comment by myungjoo** [comment]
Added single-api related optimizations and benchmarks (in NNStreamer-Wiki)
Please let me know if there are further issues.

**Comment by kparichay** [comment]
![Screenshot from 2020-09-03 12-54-06](https://user-images.githubusercontent.com/6565775/92069664-e21b7c80-ede4-11ea-8ed2-ecba735bd63d.png)
Screenshot for latency tflite and nnfw on RPI4
