### ISSUE TITLE
Tizen/TV/Minimal-Build Dist File

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2547]
With a given RPM macro value defined at build-time,
build nnstreamer Tizen packages with minimal dependencies
and reduced features as requested by Semun Lee.

Then, notify them so that we can include nnstreamer and CAPI to their releases.

**Comment by myungjoo** [comment]
Reference: https://review.tizen.org/gerrit/#/c/platform/upstream/nnstreamer/+/238740/

**Comment by myungjoo** [comment]
@chunseoklee This is the issue I've told you an hour ago: we do not have nnfw in TV release; thus, nnstreamer/ML-API for TV release will omit nnfw support. When you have included nnfw for TV release, please tell us so that we add nnfw ML-API support (a subpackage of nnstreamer). CC: @lemmaa

**Comment by lemmaa** [comment]
@myungjoo , As we discussed off-line this afternoon, let's go through the repository sync process so that `nnstreamer` and `nnfw` are included in the TV release image together. :)

**Comment by myungjoo** [comment]
Yes. @again4you Please add nnstreamer-nnfw with the initial release to VD product.

As flatbuffer is going to be required by nnfw, we can add nnstreamer-flatbuf as well.

**Comment by again4you** [comment]
Done!
