### ISSUE TITLE
Multi-modal Pipeline Example App (Tizen and/or Android?)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2553]
Possible inputs: various sensors (mobile), mic, camera stream.

Find some model that uses two or more input streams

Provide a demo app.

**Comment by noon-otter** [comment]
Was this completed? Where can I find the example?

**Comment by myungjoo** [comment]
You may find examples at https://github.com/nnstreamer/nnstreamer-example
There are already Android and Tizen sample applications there.

This specific example is for external contributors in "Contributhon" or "sos-masters" program.
