### ISSUE TITLE
No such element factory "tcpserversrc"

### ISSUE THREAD

**Issue by chanijjani** [nnstreamer/nnstreamer#2562]
Hello again, maintainers.

Recently I'm doing some tests based on Android nnstreamer-ssd example.

But in logcat, following logs are found when I apply some gst commands such as "tcpserversrc" and "gdpdepay".

D/NNStreamer: Pipeline: tcpserversrc port=3000 ! gdpdepay ! tensor_filter framework=tensorflow-lite model=/sdcard/nnstreamer/tflite_model/ssd_mobilenet_v2_coco.tflite ! gdppay ! tcpserversink port=3001
W/GStreamer+GST_ELEMENT_FACTORY: 0:00:00.239011923 0x7dd6b98c40 ../gst/gstelementfactory.c:462:gst_element_factory_make no such element factory "tcpserversrc"!
E/GStreamer+GST_PIPELINE: 0:00:00.239128039 0x7dd6b98c40 ../gst/parse/grammar.y:816:priv_gst_parse_yyparse no element "tcpserversrc"
W/GStreamer+GST_ELEMENT_FACTORY: 0:00:00.239256731 0x7dd6b98c40 ../gst/gstelementfactory.c:462:gst_element_factory_make no such element factory "gdpdepay"!
E/GStreamer+GST_PIPELINE: 0:00:00.239367077 0x7dd6b98c40 ../gst/parse/grammar.y:816:priv_gst_parse_yyparse no element "gdpdepay"
    0:00:00.239482962 0x7dd6b98c40 ../gst/parse/grammar.y:901:priv_gst_parse_yyparse link has no source [sink=@0x0]
D/nnstreamer: Framework = tensorflow-lite

Could you let me know what I have to do for using the commands "tcpserversrc" and "gdpdepay" in Android..?

Thank you in advance for sparing your time.

**Comment by myungjoo** [comment]
Make sure that you have gdpdepay and tcpserversrc installed in your target machine.
You need to build them (they are in gst-plugins-bad) and install them into .apk

Because in Android, gst plugins are packaged into .apk, we try to minimize the number of plugins to reduce .apk size.

**Comment by chanijjani** [comment]
This issue is resolved by using another library, thanks!
