### ISSUE TITLE
Replacing the invalid tensor type in nns_tensor_type 

### ISSUE THREAD

**Issue by dongju-chae** [nnstreamer/nnstreamer#2563]
Although we have init-functions to initialize `GstTensorInfo`-related structures such as `GstTensorInfo`, `GstTensorsInfo`, `GstTensorConfig` and `GstTensorsConfig`, but sometimes, we are missing to call those functions due to performance issue or just mistakes.

In this case, it's safe to assume that initializing them to zeros is exactly same to call such init-functions. However, currently, the init-functions are setting `GstTensorInfo`'s type to `_NNS_END` (i.e., invalid tensor type), which is not zero.

So, my proposal is revisiting `_nns_tensor_type` like below, to expect that calling init-functions and explicitly setting zeros cause the same effect.
```
typedef enum _nns_tensor_type
{
  _NNS_NONE = 0  
                          
  _NNS_INT32,            
  _NNS_UINT32,               
  _NNS_INT16,                
  _NNS_UINT16,               
  _NNS_INT8,                 
  _NNS_UINT8,                
  _NNS_FLOAT64,              
  _NNS_FLOAT32,              
  _NNS_INT64,                
  _NNS_UINT64,
} tensor_type;
```
rather than
```
typedef enum _nns_tensor_type
{                            
  _NNS_INT32 = 0,            
  _NNS_UINT32,               
  _NNS_INT16,                
  _NNS_UINT16,               
  _NNS_INT8,                 
  _NNS_UINT8,                
  _NNS_FLOAT64,              
  _NNS_FLOAT32,              
  _NNS_INT64,                
  _NNS_UINT64,               
                             
  _NNS_END,                  
} tensor_type;               
```

Related issue: https://github.com/nnstreamer/nnstreamer/pull/2542

**Comment by myungjoo** [comment]
```
typedef enum _nns_tensor_type
{
  _NNS_NONE = 0  
                          
  _NNS_INT32,            
  _NNS_UINT32,               
  _NNS_INT16,                
  _NNS_UINT16,               
  _NNS_INT8,                 
  _NNS_UINT8,                
  _NNS_FLOAT64,              
  _NNS_FLOAT32,              
  _NNS_INT64,                
  _NNS_UINT64,

  _NNS_MAX,
} tensor_type;

??

**Comment by dongju-chae** [comment]
@myungjoo Looks good! I will discuss with @jaeyun-jung, to check that there're potential side-effects in tizen/android APIs.

**Comment by myungjoo** [comment]
@jaeyun-jung After 7.0 M2 release and nnstreamer-edge RTOS build, please take a look at this issue and close it if it's become irrelevant.
