### ISSUE TITLE
Unable to reset single API invoke timeout

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#2568]
Setting single API invoke timeout using `ml_single_set_timeout` considers the input argument of `timeout` of `0` as invalid. 
However, this does not allow resetting the `timeout` to `0` once set to a non-zero value.
As `timeout == 0` has a meaning, how about allow setting `timeout` to 0.

**Comment by myungjoo** [comment]
Yes. that is a bug. Please fix it.
