### ISSUE TITLE
How can I set the GstAppSrcCallbacks using capi?

### ISSUE THREAD

**Issue by junmin-kim** [nnstreamer/nnstreamer#2581]
Hello, all.

Now I'm trying to enhance the performance of my pipeline.
Currently, I'm using an atomic boolean variable which is set after input data and is unset at the sink time.
I found that `ml_pipeline_src_input_data` uses `app_src`, and `app_src` can set [GStAppSrcCallbacks](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gst-plugins-base-libs-0.10/gst-plugins-base-libs-appsrc.html#gstappsrccallbacks).

I think if I set `need_data` and `enough_data` callback, my pipeline will be faster.
Is it possible to set these callbacks using nnstreamer-capi? How can I use it if it is possible?

I will be grateful for any help you can provide.

**Comment by myungjoo** [comment]
Tizen CAPI does not allow GstAppSrcCallbacks in Tizen 5.5 and 6.0.

In case you want to prepare input data frames before the previous input data is processed, you may add a ```queue``` after ```appsrc``` with the appropriate size and queue policies.

We may add an API (for 6.5 M1?) if its benefit is clear, please show us the usage case and its benefit.

**Comment by myungjoo** [comment]
@again4you @jaeyun-jung @gichan-jang @anyj0527 Please consider this as a new C-API/C#-API/Java-API/Web-API for Tizen 6.5 ML-API. (callback-based appsrc)

**Comment by myungjoo** [comment]
@again4you This might require ACR. Please take a look.

**Comment by myungjoo** [comment]
I'll assign a developer who's going to be freed from the current EPIC around 4/1.

**Comment by myungjoo** [comment]
@junmin-kim With nnstreamer/api#37, we can support such callbacks. However, you still won't be able to directly access GstAppSrc objects. Is it still ok?

**Comment by myungjoo** [comment]
The resolving PR was merged and SR'ed a while ago.
