### ISSUE TITLE
Add coherence of structs in API and used internally

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#2587]
The data structures and enums used in API and internally should be checked at compile that they are coherent.
This allows direct translation between the two, reducing the overhead of creating more wrappers and copying between them.

**Comment by kparichay** [comment]
Also add checks to ensure that the size of structs are same at compile-time or with static asserts.

**Comment by myungjoo** [comment]
@kparichay Do you think we need more build-time checks? or are you done?

**Comment by kparichay** [comment]
@myungjoo The build-time checks have not been added yet as of now. I will try and add it soon.
