### ISSUE TITLE
Tensor filter memory destroy bug

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#2593]
Memory allocated by the tensor filters inside them (which support allocate_in_invoke)
is not freed appropriately. When using the single API, this memory is wrapped with ml_tensors_data
and freed wtih ml_tensors_data_destroy. However, these memories allocated by the tensor filter itself 
must be destroyed with destroyer of the tensor filter extension.

**Comment by kparichay** [comment]
This issue also exists in the pipeline C-API as well.

**Comment by myungjoo** [comment]
Isn't this resolved?

**Comment by kparichay** [comment]
The memory allocated by custom filters internally is NOT YET tracked by single/pipeline API to be able to call the filter handle later (if open) as of now.
