### ISSUE TITLE
Tizen privelege check missing

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#2627]
NNStreamer checks for camera and recorder privelege for video and audio sources in Tizen.
However, does MediaStorage/ExternalStorage privilege needs to be checked in case filesink/multifilesink or elements which store files to disk are used in the pipeline. Further, reading data files from the disk with filesrc might also require similar privileges.

**Comment by again4you** [comment]
When constructing the NNStreamer pipeline, the APIs check the Camera, Recorder, and Storage privilege.
It is mentioned in API document as below. 
* https://docs.tizen.org/application/native/api/mobile/5.5/group__CAPI__ML__NNSTREAMER__PIPELINE__MODULE.html#ga16d808d0e331219e430388aa5d53b82c

```
Remarks:
    If the function succeeds, pipe handle must be released using ml_pipeline_destroy(). 
    http://tizen.org/privilege/mediastorage is needed if pipeline_description is relevant to media storage. 
    http://tizen.org/privilege/externalstorage is needed if pipeline_description is relevant to external storage. 
    http://tizen.org/privilege/camera is needed if pipeline_description accesses the camera device. 
    http://tizen.org/privilege/recorder is needed if pipeline_description accesses the recorder device. 
```

You mean that those are not enough for privilege checking. right?

**Comment by kparichay** [comment]
> You mean that those are not enough for privilege checking. right?

Those are enough. 
However, as we discussed offline, these checks for `mediastorage` and `externalstorage` are not performed in the nnstreamer API.

**Comment by myungjoo** [comment]
Maintaining examples as Remarks properly should be enough.
We may need to add remarks for network usages in the future. (tcp/udp/...)
