### ISSUE TITLE
TCM result does not meed the release criteria.

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2633]
### Summary
* No Assertion Test Cases: 12
* Total Test Cases: 412
* Negative Test Cases: 162

### Results
* [result.zip](https://github.com/nnstreamer/nnstreamer/files/5062427/result.zip)

### Todo items
* Fix `No Assertion Test Cases`: @gichan-jang 
* Add 44 or more __Negative__ test cases: TBD

**Comment by gichan-jang** [comment]
Checked!

**Comment by gichan-jang** [comment]
Add 44 or more Negative test cases: TBD -> Add 88 or more Negative test cases: TBD

**Comment by gichan-jang** [comment]
1. No assertion test are fixed except false-negative case
2. Negative TCs are added
    - Total TCs: 503
    - Positive TCs: 250
    - Negative TCs: 253

![캡처](https://user-images.githubusercontent.com/56856496/90709630-98586f80-e2d7-11ea-85e4-019669eda23e.PNG)
