### ISSUE TITLE
Choosing backends for nnfw

### ISSUE THREAD

**Issue by semun-lee** [nnstreamer/nnstreamer#2645]
# Issue Description
acl_cl backend doesn't loaded even when I set ML_NNFW_HW_GPU as a hardware type.

```
ml_single_open(&single_h, "...", NULL, NULL, ML_NNFW_TYPE_NNFW, ML_NNFW_HW_GPU);
```
Expected Result
============
nnfw loads acl_cl backend when I set GPU as a hardware.

How to Reproduce
===============
1. call ml_single_open() with ML_NNFW_TYPE_NNFW and ML_NNFW_HW_GPU.

Further Information
===============

Tizen TM4 with OpenCL support. (armv7l binary)

It looks like "acceleartor" property of a filter object is not passed properly to the nnfw.

```
Thread 1 "ml_single_api" hit Breakpoint 3, nnfw_get_accelerator (pdata=0x429200, accelerators=0x0) at /usr/src/debug/nnstreamer-1.5.3/ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c:235
235     in /usr/src/debug/nnstreamer-1.5.3/ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
(gdb) finish
Run till exit from #0  nnfw_get_accelerator (pdata=0x429200, accelerators=0x0) at /usr/src/debug/nnstreamer-1.5.3/ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c:235
nnfw_open (private_data=0x428120, prop=0x428124) at /usr/src/debug/nnstreamer-1.5.3/ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c:236
236     in /usr/src/debug/nnstreamer-1.5.3/ext/nnstreamer/tensor_filter/tensor_filter_nnfw.c
(gdb) p accelerator
$3 = 0xf4afa9a8 "cpu"
```

**Comment by kparichay** [comment]
@semun-lee Thanks for reporting the issue.
I have added patch #2649 to fix this.
Can you please check if this issue is resolved with this patch?

**Comment by kparichay** [comment]
@semun-lee Please check the comments https://github.com/nnstreamer/nnstreamer/pull/2649#issuecomment-674078486 and https://github.com/nnstreamer/nnstreamer/pull/2649#issuecomment-674076325 on the PR #2649.

**Comment by myungjoo** [comment]
I think the workaround has fixed the issue?

**Comment by semun-lee** [comment]
> I think the workaround has fixed the issue?

Sorry for late reply. I've already confirmed that #2649 fixed the issue I reported.
