### ISSUE TITLE
NNStreamer docker support

### ISSUE THREAD

**Issue by JeonChangMin** [nnstreamer/nnstreamer#2657]
My NNStreamer study mates and I are having trouble building and rebuilding the NNStreamer when some serious errors occur.
Reinstalling the dependancies is a time-consuming and repetitive task.

Under these circumstances, using the docker can be a great solution.
If we have an NNStreamer Docker image, we can use it when we want to start over at the scratch.

Writing an installation script without using a docker can be a possible way to solve the problem.

If there is already existing docker images, they might be very usefull to begginers and even commiter.

How about providing an image of NNStreamer Docker?
Can my teammates and I create the docker image?

**Comment by myungjoo** [comment]
Yes, you may create them.

In my case, I have never reinstalled any dependencies for building nnstreamer, thus, I just don't have the need. (still don't understand, but you do not need to ask and continue creating and deploying them) Usually, developing software packages with standard C/C++ libraries do not have the need for dockerizing, but if you are too familiar with dockerized developing environment, why not?

**Comment by JeonChangMin** [comment]
Oh, I thought that a docker image based on a popular OS could also help make easy setup and create the same development environment. Could you tell me more about it?
Thank you for your reply.

**Comment by myungjoo** [comment]
> Oh, I thought that a docker image based on a popular OS could also help make easy setup and create the same development environment. Could you tell me more about it?

In general, for configuring build environment, ```mk-build-deps``` should be enough for Ubuntu machines.
If what you suffer is install/configuring built binaries, nnstreamer-chk ( #2640 ) should be helpful.

**Comment by myungjoo** [comment]
Anyway, don't get discouraged. If you wan to share the standard developing environment as a dockerfile, you may share one. It is just I that do not depend on dockers for developing native codes. If recent developers tend to use docker for native code developments, why not?

**Comment by myungjoo** [comment]
#2716 addresses this. It will be merged if the directory paths are updated.
