### ISSUE TITLE
Memory leak with 15db62b589cb3a3676

### ISSUE THREAD

**Issue by chunseoklee** [nnstreamer/nnstreamer#2683]
# Issue Description

Memory leak occur after https://github.com/nnstreamer/nnstreamer/commit/15db62b589cb3a36765b2d2b38f70882c72da7c0

Our internal app shows huge memory leak( before commit : 350MB vs after commit : 1.5GB) 

Expected Result
============

around 350 MB RSS memory footprint

How to Reproduce
===============

Please refer to https://github.sec.samsung.net/STAR/nnfw/issues/11696(sorry for internal url due to confidentiality)

Further Information
===============
* A link to an output result showing the issue
* Exact OS version

**Comment by chunseoklee** [comment]
@jaeyun-jung PTAL

**Comment by jaeyun-jung** [comment]
#2682 reverts old PRs to convert output tensors.

**Comment by jaeyun-jung** [comment]
https://stackoverflow.com/questions/35363486/jni-direct-buffers-who-is-responsible-for-native-buffer-freeing

Direct buffer from native cannot set the deallocator, this causes mem leak in native heap.
To fix this issue, call method to set direct buffer in Java.

**Comment by jaeyun-jung** [comment]
PR #2682 can fix this issue.
