### ISSUE TITLE
[~2020/11] TF2-Lite Requirements: GPU Delegation via Single/Pipeline APIs, Coexistence.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2700]
I guess this is mainly "verification" task because it appears that most required codes are already there.

1. Coexistence
    - The ability to coexist with tensorflow-lite 1.x filters
    - The ability to choose corresponding tf-lite filter with given model file (aliasing)
        - Suggestion: rename tensorflow-lite --> tensorflow1-lite. then, tensorflow-lite will choose tensorflow2-lite and tensorflow1-lite dynamically.
    - A system may have only tf1-lite or tf2-lite or both.

2. Delegation
    - With the given Single API option, users should be able to use GPU delegation
    - In Pipeline API, it should be intuitive as well.
    - The ability to check if GPU Delegation is in effect or not easily.

3. Client Release Deadline: 2021/2. (code release: 2021/1. tested & verfied release: 2021/2)

4. Release Android-NNStreamer Library with delegation-enabled tensorflow-lite included.
    - Need GPU delegation control (get/set property) definition. (need reference / documentation as well)
    - We can control this with hw-accel property.
    - This may be released before others (@semun-lee wants this)

**Comment by again4you** [comment]
### Required Task ###
#### TFLite should support GPU
* TFLite GPU for Android C/C++ uses the Bazel build system: [Link](https://www.tensorflow.org/lite/performance/gpu_advanced#android_cc)

**Comment by myungjoo** [comment]
Yes, it may be simply because the Makefile script does not have something required; you will need to find that out, update Makefile, release for our target platforms, and upstream to tensorflow.

This is not expected to be related with the SW platform itself, but is expected to be related with the "completeness"of the tensorflow-lite's build scripts.

**Comment by myungjoo** [comment]
@again4you I think this is completed. Please close it.

**Comment by again4you** [comment]
### Usage
* SingleShot
  ```cpp
  ml_single_open (&single, test_model, NULL, NULL, ML_NNFW_TYPE_TENSORFLOW_LITE, ML_NNFW_HW_GPU);
  ```
* Pipeline
  ```
  tensor_filter framework=tensorflow2-lite accelerator=true:gpu model=./mobilenet_v1_1.0_224_quant.tflite
  ```

### Execution Result
* Test env.
  * TM4 Device (since it supports OpenCL)
* Result
  ```
  sh-3.2# gst-launch-1.0  filesrc location=/root/orange.png ! \                           
  > pngdec ! videoscale ! imagefreeze ! videoconvert ! \
  > video/x-raw,format=RGB,framerate=0/1 ! tensor_converter ! queue ! \
  > tensor_filter framework=tensorflow2-lite accelerator=true:gpu model=/root/mobilenet_v1_1.0_224_quant.tflite ! \
  > filesink location=/root/tflite2.out.log
  ** Message: 20:53:57.472: accl = gpu
  INFO: Created TensorFlow Lite delegate for GPU.
  ERROR: Following operations are not supported by GPU delegate:
  SQUEEZE: Operation is not supported.
  29 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
  INFO: Initialized OpenCL-based API.
  INFO: Created 1 GPU delegate kernels.
  Setting pipeline to PAUSED ...
  Pipeline is PREROLLING ...
  Pipeline is PREROLLED ...
  Setting pipeline to PLAYING ...
  New clock: GstSystemClock
  Got EOS from element "pipeline0".
  Execution ended after 0:00:00.000943885
  Setting pipeline to PAUSED ...
  Setting pipeline to READY ...
  Setting pipeline to NULL ...
  Freeing pipeline ...
  ```

### Limitation
* NNStreamer filter for TFLite2 GPU delegate only supports **OpenCL** backend since GLES v3.1 backend has a constraint that
Invoke() must be called from the same EGLContext. However, GStreamer pipeline execution does not guarantee this condition.

### Inference Priority
* MIN_LATENCY > MIN_MEMORY_USAGE > MAX_PRECISION

### Known Issue
* Current `ml_check_nnfw_availability(ML_NNFW_TYPE_TENSORFLOW_LITE, ML_NNFW_HW_GPU)` does not check the HW availability and required libraries such as `OpenCL`.
