### ISSUE TITLE
"AUTO MODE" for tensor-filter in GST-Pipeline / Pipeline-API

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2702]
Let's allow:

```
... ! tensor-filter model="abc.tflite ! ...
```

And let tensor-fitler decides which to use dynamically (decided at install-time or boot-time or run(open)-time)

**Comment by gichan-jang** [comment]
Currently, when `framework` is set to `auto`, the tensor filter determines the framework.
Is it necessary to decide only by the model without a framework option?

**Comment by myungjoo** [comment]
1. tensor-filter determines frameworks with the same routine of CAPI-SINGLE
2. the nnstreamer.ini entries are applied
3. test cases of using this "auto" mode (no frameworks specified) exist.

If ```1 && 2 && 3``` is satisfied, then, this is satisfied (close it)

**Comment by gichan-jang** [comment]
> 1. tensor-filter determines frameworks with the same routine of CAPI-SINGLE
> 2. the nnstreamer.ini entries are applied
> 3. test cases of using this "auto" mode (no frameworks specified) exist.
> 
> If `1 && 2 && 3` is satisfied, then, this is satisfied (close it)

All requirements are satisfied.
Close this issue.
