### ISSUE TITLE
ninja -C build problem in raspberry pi 3B+

### ISSUE THREAD

**Issue by suehdn** [nnstreamer/nnstreamer#2711]
I use raspberry pi 3B+ (armv7l) and ubuntu 18.04.5

I tried nnstreamer build using meson/ninja and installed tensorflow-lite 
```
$ sudo apt-get install tensorflow-lite-dev
```
The error kept happening when I tried ninja -C build.

```
ninja: Entering directory `build'
[96/188] Compiling C++ object 'ext/nns...r_flatbuf@sha/tensordec-flatbuf.cc.o'.
FAILED: ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/tensordec-flatbuf.cc.o 
c++ -Iext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha -Iext/nnstreamer/tensor_decoder -I../ext/nnstreamer/tensor_decoder -Igst/nnstreamer -I../gst/nnstreamer -Igst/nnstreamer/./include/ -I../gst/nnstreamer/./include/ -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++14 -g '-DVERSION="1.5.3"' '-DVERSION_MAJOR="1"' '-DVERSION_MINOR="5"' '-DVERSION_MICRO="3"' -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -DENABLE_TENSORFLOW_LITE=1 -DHAVE_ORC=1 -DENABLE_FLATBUF=1 -Wredundant-decls -fPIC -pthread -MD -MQ 'ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/tensordec-flatbuf.cc.o' -MF 'ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/tensordec-flatbuf.cc.o.d' -o 'ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/tensordec-flatbuf.cc.o' -c /home/ubuntu/nnstreamer/ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc
In file included from /home/ubuntu/nnstreamer/ext/nnstreamer/tensor_decoder/tensordec-flatbuf.cc:25:0:
ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/nnstreamer_generated.h: In function ‘const char* nnstreamer::flatbuf::EnumNameTensor_type(nnstreamer::flatbuf::Tensor_type)’:
ext/nnstreamer/tensor_decoder/7bf3534@@nnstreamer_decoder_flatbuf@sha/nnstreamer_generated.h:72:20: error: ‘IsOutRange’ is not a member of ‘flatbuffers’
   if (flatbuffers::IsOutRange(e, Tensor_type_NNS_INT32, Tensor_type_NNS_END)) return "";
                    ^~~~~~~~~~
[97/188] Linking target ext/nnstreamer/tensor_filter/nnstreamer_python3.so.
FAILED: ext/nnstreamer/tensor_filter/nnstreamer_python3.so 
c++  -o ext/nnstreamer/tensor_filter/nnstreamer_python3.so 'ext/nnstreamer/tensor_filter/584bea7@@nnstreamer_python3@sha/tensor_filter_python_api.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,nnstreamer_python3.so gst/nnstreamer/libnnstreamer.so /usr/local/lib/libpython3.7m.a -ldl /usr/lib/arm-linux-gnueabihf/libglib-2.0.so /usr/lib/arm-linux-gnueabihf/libgstreamer-1.0.so /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so -Wl,--export-dynamic /usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so -pthread /usr/lib/arm-linux-gnueabihf/libgstbase-1.0.so /usr/lib/arm-linux-gnueabihf/libgstcontroller-1.0.so /usr/lib/arm-linux-gnueabihf/libgstvideo-1.0.so /usr/lib/arm-linux-gnueabihf/libgstaudio-1.0.so -lm /usr/lib/arm-linux-gnueabihf/liborc-0.4.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/../../../gst/nnstreamer' -Wl,-rpath-link,/home/ubuntu/nnstreamer/build/gst/nnstreamer 
/usr/local/lib/libpython3.7m.a(posixmodule.o): In function `os_openpty_impl':
/home/ubuntu/Python-3.7.4/./Modules/posixmodule.c:5951: undefined reference to `openpty'
/usr/local/lib/libpython3.7m.a(posixmodule.o): In function `os_forkpty_impl':
/home/ubuntu/Python-3.7.4/./Modules/posixmodule.c:6045: undefined reference to `forkpty'
collect2: error: ld returned 1 exit status
[101/188] Compiling C++ object 'ext/nn...a/tensor_filter_tensorflow_lite.cc.o'.
ninja: build stopped: subcommand failed.
```

![스크린샷, 2020-09-10 12-54-52](https://user-images.githubusercontent.com/67812466/92680020-e4418600-f364-11ea-8725-2ed6dab4fd66.png)

I think there's no problem on 'tensorflow-lite', but why do I keep getting errors?

**Comment by myungjoo** [comment]
Please show us your
1. meson options
2. meson's stdout
3. meson log (.../log/meson-logs/meson-log.txt)

**Comment by suehdn** [comment]
this is my meson options
![1](https://user-images.githubusercontent.com/67812466/92711407-7a8ca080-f393-11ea-9bfd-e7cbf3ea1009.PNG)
![2](https://user-images.githubusercontent.com/67812466/92711417-7c566400-f393-11ea-8f7c-14eaf63e0245.PNG)
![3](https://user-images.githubusercontent.com/67812466/92711416-7bbdcd80-f393-11ea-92ab-afc42497ffdd.PNG)


## menson log
![log1](https://user-images.githubusercontent.com/67812466/92711478-89735300-f393-11ea-8e91-6b4d0f1a7f53.PNG)
![log2](https://user-images.githubusercontent.com/67812466/92711485-8aa48000-f393-11ea-861d-a5dd0a1696e5.PNG)

**Comment by myungjoo** [comment]
The, one possible issue is that the version of Flatbuf is not compatible.
Please show us the flatbuf version you have installed.

If you want to keep using flatbuf with nnstreamer: If the flatbuf (and its devel package) is not from nnstreamer-ppa, please replace it with nnstreamer-ppa's flatbuf.
If you do not care: force-disable flatbuf (add ```-Dflatbuf-support=disabled``` to meson)

**Comment by wooksong** [comment]
I guess the version of your ```flatc ``` (/snap/bin/flatc) is different from the library used for building nnstreamer.

**Comment by wooksong** [comment]
@myungjoo This version issue occurs quite often. I will submit a PR for checking flatc/flatbuffers versions and enforcing to use same ones.

**Comment by myungjoo** [comment]
@wooksong Please reconfigure meson so that it will "disable building flatbuf subplugins and emit NOT-IGNORABLY-VISIBLE warning messages" if flatbuf/flatc is not compatible.

In long-term, it'd be better if our code can support wider ranges of versions, but that will incur testing hell.

**Comment by suehdn** [comment]
When I check dpkg --get-selections
flatbuf and flatc are not exist.

I don't remember exactly what was installed. 
But when I installed it with a command that was completed by pressing the tab key in [sudo apt-get install ~], it changed no to yes.(meson build)

example,
```
$ sudo apt-get install flatbuffers-compiler 
```

I can't find how to know flatc&flatbuf version I installed. 😓

**Comment by myungjoo** [comment]
> When I check dpkg --get-selections
> flatbuf and flatc are not exist.
> 
> I don't remember exactly what was installed.
> But when I installed it with a command that was completed by pressing the tab key in [sudo apt-get install ~], it changed no to yes.(meson build)
> 
> example,
> 
> ```
> $ sudo apt-get install flatbuffers-compiler 
> ```
> 
> I can't find how to know flatc&flatbuf version I installed. 😓

```
$ dpkg -s flatbuffers-compiler
```

**Comment by suehdn** [comment]
@myungjoo 
The result is 
```
~/nnstreamer$  dpkg -s flatbuffers-compiler
Package: flatbuffers-compiler
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 1489
Maintainer: Wook Song <wook16.song@samsung.com>
Architecture: armhf
Multi-Arch: same
Source: flatbuffers
Version: 1.12.0-0~202008030927~ubuntu18.04.1
Description: Memory Efficient Serialization Library (compiler)
 FlatBuffers is a cross platform serialization library architected for maximum
 memory efficiency. It allows you to directly access serialized data without
 parsing/unpacking it first, while still having great forwards/backwards
 compatibility.
 .
 This package contains the development header and static library files.
Homepage: https://github.com/google/flatbuffers
```

**Comment by myungjoo** [comment]
That flatbuf should be compatible.

While @wooksong checks out this issue as mentioned above, you can keep building and using nnstreamer with:
```
$ meson build -Dflatbuf-supported=disabled
```

If you do not convert flatbuf-stream to tensor-stream or tensor-stream to flatbuf-stream, you do not need it.

**Comment by suehdn** [comment]
Even if I type that sentence, ninja -C build does not work..
So, I'll wait.

**Comment by wooksong** [comment]
@suehdn Could you share the result of ```dpkg -S /snap/bin/flatc```.

**Comment by wooksong** [comment]
> That flatbuf should be compatible.
> 
> While @wooksong checks out this issue as mentioned above, you can keep building and using nnstreamer with:
> 
> ```
> $ meson build -Dflatbuf-supported=disabled
> ```
> 
> If you do not convert flatbuf-stream to tensor-stream or tensor-stream to flatbuf-stream, you do not need it.

```
$ meson build -Dflatbuf-support=disabled
```
@suehdn 
s/supported/support

This might work. I am working on revising the flatbuffers packages.

Alternatively, ```meson build``` after running ```sudo snap remove flatbuffers```.
