### ISSUE TITLE
How can I clone https://git.tizen.org/cgit/platform/upstream/tensorflow?

### ISSUE THREAD

**Issue by suehdn** [nnstreamer/nnstreamer#2717]
Hello, I tried building a meson/ninja by referring to [nnstreamer/Documentation/getting-started-meson-build.md](https://github.com/nnstreamer/nnstreamer/blob/master/Documentation/getting-started-meson-build.md).

```
$ git clone https://git.tizen.org/cgit/platform/upstream/tensorflow
```
I tried clone with three computer (ubuntu 18.04), but It didn't succeed -just stoped. 
How can I solve this problem?

**Comment by dongju-chae** [comment]
How about `git://git.tizen.org/platform/upstream/tensorflow`?

**Comment by wooksong** [comment]
@suehdn It does work. What does 'just stopped' mean?
```
$  git clone https://git.tizen.org/cgit/platform/upstream/tensorflow
Cloning into 'tensorflow'...
Checking connectivity: 472478, done.

$ cd tensorflow
$ git log
commit f5639eaa17a3d48b9d6ba69f36e3f0011a8a3960 (HEAD -> master, origin/sandbox/helloahn/tf-mediapipe, origin/master, origin/HEAD)
Author: Tizen Infrastructure <tizen.infra@samsung.com>
Date:   Sun Feb 11 23:21:24 2018 +0000

    Initial empty repository
```

**Comment by suehdn** [comment]
In my computer It works like this
![스크린샷, 2020-09-11 10-19-11](https://user-images.githubusercontent.com/67812466/92845129-99d20f00-f421-11ea-9502-25629eec7ac9.png)
and nothing comes up afterwards.
Do I have to wait?

**Comment by suehdn** [comment]
@dongju-chae @wooksong 
I tried clone git://git.tizen.org/platform/upstream/tensorflow.
```
~$ cd tensorflow
~/tensorflow$ git log
commit f5639eaa17a3d48b9d6ba69f36e3f0011a8a3960 (HEAD -> master, origin/sandbox/helloahn/tf-mediapipe, origin/master, origin/HEAD)
Author: Tizen Infrastructure <tizen.infra@samsung.com>
Date:   Sun Feb 11 23:21:24 2018 +0000

    Initial empty repository
```

**Comment by kparichay** [comment]
you are at `master` branch which is empty. 
Switch to `tizen` branch.

**Comment by wooksong** [comment]
> @wooksong
> In my computer It works like this
> ![스크린샷, 2020-09-11 10-19-11](https://user-images.githubusercontent.com/67812466/92845129-99d20f00-f421-11ea-9502-25629eec7ac9.png)
> and nothing comes up afterwards.
> Do I have to wait?

You might do.

**Comment by wooksong** [comment]
> @dongju-chae @wooksong
> I tried clone git://git.tizen.org/platform/upstream/tensorflow.
> 
> ```
> ~$ cd tensorflow
> ~/tensorflow$ git log
> commit f5639eaa17a3d48b9d6ba69f36e3f0011a8a3960 (HEAD -> master, origin/sandbox/helloahn/tf-mediapipe, origin/master, origin/HEAD)
> Author: Tizen Infrastructure <tizen.infra@samsung.com>
> Date:   Sun Feb 11 23:21:24 2018 +0000
> 
>     Initial empty repository
> ```

```
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/accepted/tizen_5.0_unified
  remotes/origin/accepted/tizen_5.5_unified
  remotes/origin/accepted/tizen_unified
  remotes/origin/master
  remotes/origin/sandbox/akazmin/tizen_6.0_build
  remotes/origin/sandbox/chunseoklee/fix_rss
  remotes/origin/sandbox/dkson95/lto
  remotes/origin/sandbox/dkson95/lto-test
  remotes/origin/sandbox/gichan/1.13.1_rm_flatbuf_header
  remotes/origin/sandbox/helloahn/tf-capi-1.13.1
  remotes/origin/sandbox/helloahn/tf-mediapipe
  remotes/origin/sandbox/helloahn/tizen_6.0
  remotes/origin/sandbox/jijoong/tensorflow_deb
  remotes/origin/sandbox/mzx/1.13.1
  remotes/origin/sandbox/mzx/bazelbuild
  remotes/origin/sandbox/mzx/tflite-only-1.13
  remotes/origin/sandbox/nmerinov/llvm
  remotes/origin/sandbox/sangjung/launchpad_bugfix
  remotes/origin/sandbox/semun/neon_sigmoid_2.2
  remotes/origin/sandbox/semun/tensorflow-lite_1.12
  remotes/origin/sandbox/wooksong/1.15.2
```

There are many branches. Just do ```git checkout``` 
For example, 
```
$ git checkout tizen
$ git log
```

**Comment by wooksong** [comment]
@suehdn Does it work?

**Comment by suehdn** [comment]
It works.
```
~/tensorflow$ ls
ACKNOWLEDGMENTS     CONTRIBUTING.md    WORKSPACE           packaging
ADOPTERS.md         ISSUE_TEMPLATE.md  arm_compiler.BUILD  tensorflow
AUTHORS             LICENSE            configure           third_party
BUILD               README.md          configure.py        tools
CODEOWNERS          RELEASE.md         debian
CODE_OF_CONDUCT.md  SECURITY.md        models.BUILD
```

Umm.. another problem has occurred.
An error occurred when I tried meson build. 
```
tests/tizen_capi/meson.build:7:0: ERROR: Unknown variable "unittest_util_dep".
```
I've build nnstreamer a few times, but I've never found an error like this.

**Comment by wooksong** [comment]
> @wooksong
> It works.
> 
> ```
> ~/tensorflow$ ls
> ACKNOWLEDGMENTS     CONTRIBUTING.md    WORKSPACE           packaging
> ADOPTERS.md         ISSUE_TEMPLATE.md  arm_compiler.BUILD  tensorflow
> AUTHORS             LICENSE            configure           third_party
> BUILD               README.md          configure.py        tools
> CODEOWNERS          RELEASE.md         debian
> CODE_OF_CONDUCT.md  SECURITY.md        models.BUILD
> ```
> 
> Umm.. another problem has occurred.
> An error occurred when I tried meson build.
> 
> ```
> tests/tizen_capi/meson.build:7:0: ERROR: Unknown variable "unittest_util_dep".
> ```
> 
> I've build nnstreamer a few times, but I've never found an error like this.

That's weird. Anyway, your first issue seems to be resolved.
If you do not have any more problems related to ```git clone``` for tensorflow, is it OK with closing this issue?

For the meson/ninja build/ please post another issue with detailed commands and logs.

**Comment by suehdn** [comment]
Ok, thanks for your help!
