### ISSUE TITLE
question about gdppay and tcp plugin usage

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [nnstreamer/nnstreamer#2724]
Hello, I'm writing simple code using nnstreamer, and have a question.
**I used gdppay** and **camera streaming is really slow**, so I'm curious that **is it natural or did I do something wrong?**
 
I've read some Tizen apps using gdppay and tcp plugin, so I referenced it.
My pipeline is...

**sender** (rpi4b, ubuntu18.04 arm64): 
```
str_pipeline =
      g_strdup_printf
      ("v4l2src name=cam_src ! videoconvert ! videoscale ! "
      "video/x-raw,width=%d,height=%d,format=RGB ! gdppay ! tcpserversink host=%s port=%d async=false", width, height, host, port);
```

**receiver** (PC, ubuntu18.04):
```
  str_pipeline =
      g_strdup_printf
      (
      "tcpclientsrc host=%s port=%d ! gdpdepay ! tee name=t_raw "
      "t_raw. ! queue ! videoconvert ! ximagesink sync=false",
      host, port);
```

When I used jpegenc/jpegdec, streaming quality was really good(seamless).
But I don't think jpegenc is proper for tensorflow project, is it?

I used tcpserversink for sender and tcpclientsrc for receiver, is it correct?

sorry for long question.

**Comment by myungjoo** [comment]
That is why engineers have invented data compression.

Find out the data throughput required by your gdppay video stream and the data throughput supported by your connection.

**Comment by myungjoo** [comment]
If you want some concrete values, try to measure throughput (not bandwidth) of your network connection and calculate the throughput required by your gdppay traffic.

**Comment by tony-jinwoo-ahn** [comment]
thank you for detailed explanation! :+1:
