### ISSUE TITLE
[~2020/10] TensorRT custom filter examples and templates for developes (whitebox access)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2731]
### Timeline
2020/10: Release with simple test cases, let the clients use them
2020/11: Release with full CI, automated tests.

### Target Platforms
Yocto and Ubuntu

### Examples
- custom-easy (C/C++ function calls in a C function)
- custom / C call
- custom / C++ class call

**Comment by dongju-chae** [comment]
I will take a look if nobody starts this issue.

**Comment by myungjoo** [comment]
@dongju-chae I think it's done. Please check and close it. If there are remaining tasks, please just identify them in the github issue article (so that someone else or you can continue later)
