### ISSUE TITLE
[Yocto] Enable nnstreamer and its sub-plugins for the recent Poky releases 

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#2740]
This is a sub-item of #2732.

Codename | Yocto Project Version | Release Date | Current Version | Support Level | Poky Version | BitBake branch
-- | -- | -- | -- | -- | -- | --
Gatesgarth | 3.2 | Oct 2020 |   | Dev | 24.0 | 1.48
Dunfell | 3.1 | April 2020 | 3.1.2 | Long Term Support | 23.0 | 1.46
Zeus | 3.0 | October 2019 | 3.0.4 | Community | 22.0.3 | 1.44
Warrior | 2.7 | April 2019 | 2.7.4 | EOL | 21.0 | 1.42

https://wiki.yoctoproject.org/wiki/Releases

We need to enable nnstreamer and its sub-plugins in the recent Poky releases (>= 3.0).

## Zeus (3.0)
 - [x] NNStreamer
 - [x] NNStreamer-TFLite: 
 - [x] NNStreamer-Python3
 - [x] NNStreamer-cpp
 - [x] NNStreamer-customs
 - [ ] ...

## Dunfell (3.1)
 - [ ] NNStreamer
 - [ ] NNStreamer-TFLite
 - [ ] ...

**Comment by myungjoo** [comment]
Update the status, please.

**Comment by wooksong** [comment]
> Update the status, please.

Sorry for the late update.
- On Zeus, NNStreamer (the most recent version) with basic features such as python3, custom filters, and cpp are working now.
- The extension for TFLite 1.15.2 also works.
- To enable the CI system, I had been trying to resolve the python version issues but there was no more progress since I've started working on ROS/ROS2.

**Comment by myungjoo** [comment]
I guess this is almost done except for CI support. Close when you are done.
