### ISSUE TITLE
[Rough Idea Suggestion] Pipeline Pause and Resume (resource saver)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2749]
With nnstraemer API, to save memory while the pipeline won't be active for a while:

```
ml_pipeline_designate_resourcesave_filters (pipeline, filtername);

ml_pipeline_pause_resourcesave (pipeline);
```

Then, pipeline pauses and pre-defined tensor-filters closes big models to save memory.

After then,

```
ml_pipeline_resume (pipeline);
```
when, before pipeline-resume, it will re-open such big models.

&nbsp;

&nbsp;

&nbsp;

CAUTION: This requires modifications in tensor_filter's core.

**Comment by dongju-chae** [comment]
@myungjoo It seems that each sub-plugin may handle its own resource saving (of course, using the tensor_filter common interface). Also, I think we have to add extra `event_op` like `reload_model` to support this feature. I wonder this approach meets your intention.

**Comment by myungjoo** [comment]
There could be two different approaches for tensor_filter. (I consider tensor_filter as the only target for now)

1. Do close(pause)/open centrally from tensor-fitler. No need to touch subplugins
2. As you've mentioned, do it locally with event hanlders at each subplugin
3. Hybrid (if event handler is not present, use 1)

Concern: is every invoke state-less? (if not, we cannot use 1.)
