### ISSUE TITLE
[Meson] Several test cases require nnstreamer_example when running them after installation.

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#2761]
In Yocto, there is no way to run the unit tests at build time. Unless all the test cases are re-written, Image tests are required after installing all the components to test. For this purpose, we already have a meson option, ```install-test```.

However, some test cases require custom-filters (e.g., unittest_sink requires custom_example_passthrough and the other custom filters). Therefore, without setting ```install-example``` to true, this test does not work well. 

Fortunately, ```unittest_sink``` supports an optional argument to indicate the location of custom filters so that we might need to revise the meson build script to fix this issue. IMHO, possible solutions could be as follows:

1. Install such test cases only if the install-example option is true
2. Make install-test automatically set install-example
3. Modify such test cases not to run if those custom filters do not exist
4. ...

How do you think about it?

**Comment by myungjoo** [comment]
It is ok to install such test cases into "nnstreamer-unittests" subpackage.

**Comment by wooksong** [comment]
> It is ok to install such test cases and custom filters into "nnstreamer-unittests" subpackage.

That sounds good.
