### ISSUE TITLE
Handle License Issues reported by LF/AI

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2765]
This is to be included in both ```main``` and ```lts/1.6.y``` branches. (1.6.1 material)

---

Dear NNStreamer technical-discuss list,

I am providing the results of a license scan of the NNStreamer codebase, based on a snapshot of the repos as of Sept. 1. The findings and license summary are available at:

https://lfscanning.org/reports/lfai/nnstreamer-2020-09-01-3d17e6bd-9a6c-4f43-8823-4ca171eb976f.html

That page lists any key findings/recommendations and the corresponding files in the repo, as well as a summary of all detected licenses. The more detailed catalogue of all files for each license can be obtained at:

https://lfscanning.org/reports/lfai/nnstreamer-2020-09-01-3d17e6bd-9a6c-4f43-8823-4ca171eb976f.xlsx

Finally, SPDX documents are also available for the license scan results. These can be seen and obtained at https://github.com/lfscanning/spdx-lfai. The SPDX documents contain human-readable and machine-readable details about the license notices and copyright notices for each file that was scanned. Although the project does not need to do anything with these SPDX files, I am providing them in the hopes that they may be helpful for the FOSS license compliance processes for your companies and the broader community.

Please feel free to reach out to me directly with any questions. If so, please cc me (swinslow@linuxfoundation.org) on any responses, as I might not receive messages sent to the list address.

Best regards,
Steve

**Comment by jaeyun-jung** [comment]
1 6
nnstreamer-example/android/IoT-ARM64/02-gst-android-with-cerbero

2 Done
nnstreamer-android-resource/external/tensorflow-lite-2.3.0.tar.xz
> https://github.com/nnstreamer/nnstreamer-android-resource/pull/11

3 4 5 8
nnshark

7
TAOS-CI/README.md
homebrew-neural-network/LICENSE
homebrew-neural-network/README.md
meta-neural-network/LICENSE
nnshark/eclipse/GstSharkFeature/plugins/org.eclipse.pde.build_3.9.100.v20150521-1524.jar/about_files/LICENSE-2.0.txt
nnshark/eclipse/GstSharkSite/plugins/org.eclipse.pde.build_3.9.100.v20150521-1524.jar/about_files/LICENSE-2.0.txt
nnstreamer-edge/README.md
nntrainer/README.md
reference-models/LICENSE

9
nnstreamer-ros/common/package.xml

10
nntrainer

11
nnstreamer-example/Tizen.native/SingleSample/inc/nnstreamer-sample-single.h
nnstreamer-example/Tizen.native/SingleSample/src/nnstreamer-sample-single.c
nnstreamer-ros/common/include/nns_ros_publisher.h
nnstreamer-ros/common/include/nns_ros_subscriber.h
nnstreamer-ros/common/node/nns_ros_publisher.cc
nnstreamer-ros/common/node/nns_ros_subscriber.cc
nnstreamer-ros/gst/tensor_ros_sink/tensor_ros_sink.c
nnstreamer-ros/gst/tensor_ros_sink/tensor_ros_sink.h
nnstreamer-ros/gst/tensor_ros_src/tensor_ros_listener.hpp
nnstreamer-ros/gst/tensor_ros_src/tensor_ros_src.cc
nnstreamer-ros/gst/tensor_ros_src/tensor_ros_src.h
nntrainer/nntrainer/include/nntrainer_error.h

12
meson project license
- https://github.com/nnstreamer/nnstreamer/pull/2767

**Comment by zhoonit** [comment]
**NNTrainer related**

`#7` confirmed that NNTrainer is Apache-2.0
`#10` Done
`#11` nntrainer/nntrainer/include/nntrainer_error.h Done

detail has been logged to https://github.com/nnstreamer/nntrainer/issues/598

**Comment by wooksong** [comment]
> 3 4 5 8
> nnshark
> 
> 9
> nnstreamer-ros/common/package.xml
> 
> nnstreamer-ros/common/include/nns_ros_publisher.h
> nnstreamer-ros/common/include/nns_ros_subscriber.h
> nnstreamer-ros/common/node/nns_ros_publisher.cc
> nnstreamer-ros/common/node/nns_ros_subscriber.cc
> nnstreamer-ros/gst/tensor_ros_sink/tensor_ros_sink.c
> nnstreamer-ros/gst/tensor_ros_sink/tensor_ros_sink.h
> nnstreamer-ros/gst/tensor_ros_src/tensor_ros_listener.hpp
> nnstreamer-ros/gst/tensor_ros_src/tensor_ros_src.cc
> nnstreamer-ros/gst/tensor_ros_src/tensor_ros_src.h

+ homebrew-neural-network

Could we use other licenses (which are not LGPL2.1) for the repositories under nnstreamer org?

**Comment by myungjoo** [comment]
> Could we use other licenses (which are not LGPL2.1) for the repositories under nnstreamer org?

Yes, you may. (I'd recommend LGPL-2.1 if it's supposed to be shared library and uses LGPL components; otherwise, Apache-2.0 is a good replacement. I don't want the strictness of GPL in general.)
