### ISSUE TITLE
tensor_sink callback error with gdp

### ISSUE THREAD

**Issue by junmin-kim** [nnstreamer/nnstreamer#2770]
# Issue Description

If 4 tensors passes `gdppay` and `gdpdepay`, the number of gst buffer becomes 1.
It causes the mismatch of the number of tensors.(`api/capi/src/nnstreamer-capi-pipeline.c:189`)

Expected Result
============
`cb_sink_event` works without error.
I think we should check the total size of tensors.

How to Reproduce
===============
Let's test with `native/example_pose_estimation_tflite/nnstreamer_example_pose_estimation_tflite.cc`
1. Modify line 571
    from
    ```c++
    "tensor_sink name=tensor_sink",
    ```

    to

    ```c++
    "gdppay ! gdpdepay ! tensor_sink name=tensor_sink",
    ```

2. run

3. assert at line 356
    ```c++
    g_assert (gst_buffer_n_memory (buffer) == 4);
    ```

**Comment by junmin-kim** [comment]
I found that I can solve with `tensor_decoder mode=protobuf ! gdppay` and `gdpdepay ! other/protobuf-tensor,framerate=0/1 ! tensor_converter`.
Is this method recommended?

**Comment by myungjoo** [comment]
1. @jaeyun-jung : Please investigate this issue
> If 4 tensors passes gdppay and gdpdepay, the number of gst buffer becomes 1.
It causes the mismatch of the number of tensors.(api/capi/src/nnstreamer-capi-pipeline.c:189)

It appears that we do not allow a ```other/tensors``` with ```num_tensors > 1``` to have a single GSTBUF per Frame.
In this case, we will require flatbuf/protobuf for multi-tensor-stream gdppay/depay.

2. @junmin-kim : Yes. Using protobuf or flatbuf (flatbuf is supposed to be faster) for gdppay/gdpdepay is the safest (portable) procedure for inter-node tensor transmission.

**Comment by junmin-kim** [comment]
@myungjoo In android api, `tensor_decoder mode=flatbuf` is not supported.

```
2020-09-06 10:12:39.605 22589-22589/com.beyond.sprintc E/GStreamer+tensor_decoder: 0:00:09.200645455 0x729b8514d0 /home/nnstreamer/gst/nnstreamer/tensor_decoder/tensordec.c:496:gst_tensordec_set_property:<tensordec0> The given mode for tensor_decoder, flatbuf, is unrecognized.
--



```

There is no `init_fb()` and `init_pb()`.
```c++
    // api/andriod/src/main/jni/nnstreamer-native-api.c:712
    /* tensor-decoder sub-plugins */
    init_dv ();
    init_bb ();
    init_il ();
    init_pose ();
    init_is ();
```

**Comment by myungjoo** [comment]
Then, flatbuf and flatbuf subplugin need to be included in Android build script.

**Comment by junmin-kim** [comment]
Thanks for the kind reply
