### ISSUE TITLE
[Feature] Custom property description of filter/decoder/conv subplugins for users (at runtime or doc)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2782]
We need a mechanism to show custom property descriptions of each sub-plugin for users.

- [x] Add a common interface for sub-plugins to register the description text
- [x] Add a mechanism to show sub-plugin info with "nnstreamer-check" utility (/tools/development/confchk)
- [x] Package/publish/release the utility, "nnstreamer-check" for uesrs.

**Comment by dongju-chae** [comment]
I think it's almost resolved but we sill have to add descriptions for each sub-plugin.
