### ISSUE TITLE
[Tensor-Filter/New Feature] Combined Tensor Picking

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2803]
Example
- model X has 3 input tensors and 2 output tensors
```
... other/tensors (5 tensors: 0...4) ! tensor_filter model=X inputCombination=1,3,4, outputCombination=p0,p1,p2,o0,o1 ! other/tensors (5 tensors)
```

Then, model X gets inputTensor[1], inputTensor[3], inputTensor[4] as input.
With output[0], output[1] from model X, the resulting stream becomes
output stream (5 tensors) : inputTensor[0], inputTensor[1], inputTensor[2], output[0], output[1]

Requirement
1. Do not require changes in sub-plugins
2. if there is no properties expressed, the behavior should be backward compatible.
3. A good documentation is required.

Future Work
1. tensor-decoder requires similar features

Motivation
1. We can simplify pipelines in many cases, with less concerns of synchronization issues.

**Comment by gichan-jang** [comment]
I will handle this issue.

**Comment by gichan-jang** [comment]
Code and documentation have been merged, close this issue.
