### ISSUE TITLE
Tizen WEB API: Single & Pipeline APIs

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2806]
In Tizen 6.5, ML-API in WEB is required for single/pipeline.
We already have official requests from client.

Target: Tizen 6.5 M1
need ACR as well.

Reference: https://review.tizen.org/gerrit/gitweb?p=platform/core/api/webapi-plugins.git;a=tree;h=refs/heads/tizen;hb=refs/heads/tizen

@again4you @jaeyun-jung

**Comment by again4you** [comment]
### Tizen Web API ACR
* SingleShot: https://code.sec.samsung.net/jira/browse/TWDAPI-273
  - [ ] Privilege Review
  - [ ] Feature Review
  - [ ] Implementation

* Pipeline: https://code.sec.samsung.net/jira/browse/TWDAPI-274
  - [ ] Privilege Review
  - [ ] Feature Review
  - [ ] Implementation
