### ISSUE TITLE
[Documentation] Example table: app list, features, quality,

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2811]
Add a table of example applications in nnstreamer-example.git

Columns should include, app name, path to its src, features of nnstreamer or NN concepts used, quality, ...

**Comment by anyj0527** [comment]
I added some tables with https://github.com/nnstreamer/nnstreamer-example/pull/239

**Comment by myungjoo** [comment]
Great! Thansk!
