### ISSUE TITLE
ACR items for Tizen 6.5

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#2813]
#### ml_single_invoke_fast ()
* Without allocating the output tensors data, this function uses the allocated memory space by the caller.
* The name is not defined yet.

#### ml_single_open_custom ()
* Some sub-filter requires the specific options.
  * e.g. # of threads in TFLite filter
* The name is not defined yet.

**Comment by myungjoo** [comment]
```ml_single_open_custom ()``` --> ```ml_single_open2 ()``` or ```ml_single_open_ ()``` or ```ml_single_open_full ()```

**Comment by jaeyun-jung** [comment]
2020-10-23 add new PR
https://github.com/nnstreamer/nnstreamer/pull/2818

**Comment by jaeyun-jung** [comment]
New function to check GStreamer element available on the pipeline.
https://github.com/nnstreamer/nnstreamer/pull/2873

**Comment by gichan-jang** [comment]
**ml_tensor_if_custom_register ()**
 - Registers a tensor_if custom callback.
 - The name is not defined yet.

**ml_tensor_if_custom_unregister()**
 - Unregisters the tensor_if custom callback.
 - The name is not defined yet.

**Comment by jaeyun-jung** [comment]
#2988 add new nnfw type pytorch

**Comment by gichan-jang** [comment]
- List of ACR items 

     * Added Functions
       + int ml_single_invoke_fast (ml_single_h single, const ml_tensors_data_h input, ml_tensors_data_h output);
       + int ml_single_open_full (ml_single_h * single, const char *model, const ml_tensors_info_h input_info, const ml_tensors_info_h output_info, ml_nnfw_type_e nnfw, ml_nnfw_hw_e hw, const char *custom_option);
       + int ml_check_element_availability (const char *element_name, bool *available);
       + int ml_pipeline_tensor_if_custom_unregister (ml_pipeline_if_h if_custom);
       + int ml_pipeline_tensor_if_custom_register (const char *name, ml_pipeline_if_custom_cb cb, void *user_data, ml_pipeline_if_h *if_custom);

     * Enum
        + Added ML_NNFW_TYPE_PYTORCH enum value into ml_nnfw_type_e

**Comment by gichan-jang** [comment]
https://code.sec.samsung.net/jira/browse/ACR-1612
API review has begun.

**Comment by gichan-jang** [comment]
Added ML_NNFW_TYPE_NNTR_INF  enum value into ml_nnfw_type_e.
https://github.com/nnstreamer/nnstreamer/pull/3029

**Comment by myungjoo** [comment]
@again4you Do you have more items to be implemented for 6.5 M1 ACR?

**Comment by myungjoo** [comment]
@gichan-jang : Please update the status

**Comment by again4you** [comment]
@myungjoo 

Tizen 6.5 M1 is already released. 
So what about creating a new issue for Tizen 6.5 M2 instead of using this?

**Comment by myungjoo** [comment]
@again4you Yes, please create one, assign, and add timeline.
