### ISSUE TITLE
Ninja Build Undefined Symbols Error in macOS

### ISSUE THREAD

**Issue by lsj1213m** [nnstreamer/nnstreamer#2821]
I tried to build nnstreamer with tensorflow support in macOS, but it shows an undefined symbols error.
Here is my environments and error messages. How can I build properly to use with tensorflow?

Thanks :)

<br/>

**Environments**

- NNStreamer source v1.6.0 (with git checkout)
- Python 3.7.9, Tensorflow 1.15.4, Protobuf 3.13.0, Flatbuffers(1.11.0 but not found in pkgconfig) within Anaconda env
- Ninja 1.10.1, Meson 0.55.3, Clang 12.0.0
- macOS Catalina 10.15.7
<br/>

**meson_options.txt**
```
option('video-support', type: 'feature', value: 'enabled')
option('audio-support', type: 'feature', value: 'enabled')
option('tf-support', type: 'feature', value: 'enabled')
option('tflite-support', type: 'feature', value: 'auto')
option('pytorch-support', type: 'feature', value: 'auto')
option('caffe2-support', type: 'feature', value: 'auto')
option('python2-support', type: 'feature', value: 'auto')
option('python3-support', type: 'feature', value: 'auto')
option('mvncsdk2-support', type: 'feature', value: 'disabled')
# nnfw-runtime ( details in https://review.tizen.org/gerrit/p/platform/core/ml/nnfw )
# For tf-lite/nnapi, enable-nnfw allows to use nnfw::tflite::nnapi as a backend.
option('nnfw-runtime-support', type: 'feature', value: 'disabled')
option('tflite-nnapi-delegation', type: 'feature', value: 'disabled')
option('armnn-support', type: 'feature', value: 'disabled')
option('orcc-support', type: 'feature', value: 'disabled')
option('snpe-support', type: 'feature', value: 'disabled')
option('protobuf-support', type: 'feature', value: 'auto')
option('flatbuf-support', type: 'feature', value: 'auto')
```

<br/>

**Build**
```
$ ninja -C build
ninja: Entering directory `build'
[98/167] Linking target ext/nnstreamer/tensor_filter/nnstreamer_python3.dylib
FAILED: ext/nnstreamer/tensor_filter/nnstreamer_python3.dylib 
c++  -o ext/nnstreamer/tensor_filter/nnstreamer_python3.dylib ext/nnstreamer/tensor_filter/nnstreamer_python3.dylib.p/tensor_filter_python_api.c.o -L/usr/local/opt/libtensorflow@1/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -shared -install_name @rpath/nnstreamer_python3.dylib gst/nnstreamer/libnnstreamer.dylib -ldl /Users/sjlee/opt/anaconda3/lib/libglib-2.0.dylib /Users/sjlee/opt/anaconda3/lib/libintl.dylib /usr/local/Cellar/gstreamer/1.18.0/lib/libgstreamer-1.0.dylib /Users/sjlee/opt/anaconda3/lib/libgobject-2.0.dylib /Users/sjlee/opt/anaconda3/lib/libgmodule-2.0.dylib /usr/local/Cellar/gstreamer/1.18.0/lib/libgstbase-1.0.dylib /usr/local/Cellar/gstreamer/1.18.0/lib/libgstcontroller-1.0.dylib /usr/local/Cellar/gst-plugins-base/1.18.0/lib/libgstvideo-1.0.dylib /usr/local/Cellar/gst-plugins-base/1.18.0/lib/libgstaudio-1.0.dylib /usr/local/Cellar/gst-plugins-base/1.18.0/lib/libgsttag-1.0.dylib -lm -Wl,-rpath,@loader_path/../../../gst/nnstreamer
Undefined symbols for architecture x86_64:
  "_PyArg_ParseTuple", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
  "_PyArg_ParseTupleAndKeywords", referenced from:
      _TensorShape_init in tensor_filter_python_api.c.o
  "_PyCapsule_GetPointer", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyCapsule_Type", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyErr_Format", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyErr_Print", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
  "_PyErr_SetString", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
      __import_array in tensor_filter_python_api.c.o
  "_PyExc_AttributeError", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyExc_ImportError", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
  "_PyExc_RuntimeError", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyImport_ImportModule", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyList_Append", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
  "_PyList_GetSlice", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
  "_PyList_New", referenced from:
      _TensorShape_new in tensor_filter_python_api.c.o
  "_PyList_Size", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
  "_PyLong_FromLong", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
  "_PyModule_AddObject", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
  "_PyModule_Create2", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
  "_PyObject_CallMethod", referenced from:
      _TensorShape_init in tensor_filter_python_api.c.o
  "_PyObject_GetAttrString", referenced from:
      __import_array in tensor_filter_python_api.c.o
  "_PyType_Ready", referenced from:
      _PyInit_nnstreamer_python in tensor_filter_python_api.c.o
  "_Py_BuildValue", referenced from:
      _TensorShape_getDims in tensor_filter_python_api.c.o
      _TensorShape_getType in tensor_filter_python_api.c.o
  "__Py_Dealloc", referenced from:
      __Py_DECREF in tensor_filter_python_api.c.o
  "__Py_NoneStruct", referenced from:
      _TensorShape_setDims in tensor_filter_python_api.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[115/167] Compiling C++ object tests/cpp_methods/unittest_cppfilter.p/_Users_sjlee_nnstreamer_tests_cpp_methods_unittest_cpp_methods.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by myungjoo** [comment]
It appears that a package of python3 (numpy or any python package that supports the missing symbol) is missing.
You may skip python3 support with meson option. E.g., add ```-Dpython3-support=disabled``` to meson.

**Comment by myungjoo** [comment]
#2692 might help, too.

**Comment by myungjoo** [comment]
@wooksong Is this related with your solution to #2692 ?

**Comment by lsj1213m** [comment]
Thanks for your help!
Now I can build and install it by skipping python3 support, and I'll check later what packages did I miss.

But there is an another problem, which was occurred both in macOS and Ubuntu when I build from source code.
Even if I've checked tensorflow and its library built from nnstreamer sources was successfully installed in my device,
gstreamer says **it couldn't identify the tensorflow framework**.

These error messages are from macOS, after following your guideline.
```
** (<unknown>:6415): WARNING **: 13:05:26.117: Failed to load the configuration, no config file found.
** (<unknown>:6415): WARNING **: 13:05:26.117: Cannot identify the given neural network framework, tensorflow

(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_unref: assertion 'mini_object != NULL' failed
... omitted ...

Traceback (most recent call last):
  File "object_detection_yolov3_tiny.py", line 386, in <module>
    od_instance.run()
  File "object_detection_yolov3_tiny.py", line 121, in run
    self.pipeline = Gst.parse_launch(
gi.repository.GLib.Error: gst_parse_error: could not link tensortransform0 to tensorfilter0 (3)
```

I found a similar issue #1853, but it didn't help to me.
The error can be occur since I skipped python3 support?

**Comment by lsj1213m** [comment]
Thanks for your help!
Now I can build and install it by skipping python3 support, and I'll check later what packages did I miss.

But there is an another problem, which was occurred both in macOS and Ubuntu when I build from source code.
Even if I've checked tensorflow and its library built from nnstreamer sources was successfully installed in my device,
gstreamer says **it couldn't identify the tensorflow framework**.

<br/>

These error messages are from macOS, after following your guideline.
```
** (<unknown>:6415): WARNING **: 13:05:26.117: Failed to load the configuration, no config file found.
** (<unknown>:6415): WARNING **: 13:05:26.117: Cannot identify the given neural network framework, tensorflow

(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed
(<unknown>:6415): GStreamer-CRITICAL **: 13:05:26.134: gst_mini_object_unref: assertion 'mini_object != NULL' failed
... omitted ...

Traceback (most recent call last):
  File "object_detection_yolov3_tiny.py", line 386, in <module>
    od_instance.run()
  File "object_detection_yolov3_tiny.py", line 121, in run
    self.pipeline = Gst.parse_launch(
gi.repository.GLib.Error: gst_parse_error: could not link tensortransform0 to tensorfilter0 (3)
```

<br/>

I found a similar issue #1853, but it didn't help to me.
```
$ ls /usr/local/lib/nnstreamer/filters/libnnstreamer_filter_tensorflow.dylib
/usr/local/lib/nnstreamer/filters/libnnstreamer_filter_tensorflow.dylib

$ gst-inspect-1.0 tensor_filter
Factory Details:
  Rank                     none (0)
  Long-name                Tensor_Filter
  Klass                    Converter/Filter/Tensor
  Description              Handles NN Frameworks (e.g., tensorflow) as Media Filters with other/tensor type stream
  Author                   MyungJoo Ham <myungjoo.ham@samsung.com>

Plugin Details:
  Name                     nnstreamer
  Description              nnstreamer plugin library
  Filename                 /usr/local/lib/gstreamer-1.0/libnnstreamer.dylib
  Version                  1.6.0
  License                  LGPL
  Source module            nnstreamer
  Binary package           nnstreamer
  Origin URL               https://github.com/nnstreamer/nnstreamer
```

The error can be occur since I skipped python3 support?

**Comment by wooksong** [comment]
@lsj1213m Can I see your meson log?

**Comment by lsj1213m** [comment]
@wooksong My [meson log](https://github.com/nnstreamer/nnstreamer/files/5445102/meson-log.txt) is here.
It's a little messy since I've tried to add some paths to resolve any issues somehow..

**Comment by lsj1213m** [comment]
@myungjoo After following your guidelines, nnstreamer is finally installed without python3 support once.
But now I have an another problem. If I run my python script which uses gstreamer and nnstreamer plugins, it says:
```
$ python3
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
>>> import tensorflow as tf
>>> tf.__version__
'2.3.1'

$ python3 object_detection_yolov3_tiny.py
2020-10-27 21:22:10.592008: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1]    24075 illegal hardware instruction  python3 object_detection_yolov3_tiny.py
```

<br/>

The same file can run on Ubuntu 18.04/20.04 without any problems, if ppa version of nnstreamer is installed on it.
I wanted to look closer on the error with gdb, but I couldn't work with it since it says no debugging symbols found in python3.

Do you have any suggestions with this issue?
Thank you :)

**Comment by myungjoo** [comment]
> @myungjoo After following your guidelines, nnstreamer is finally installed without python3 support once.
> But now I have an another problem. If I run my python script which uses gstreamer and nnstreamer plugins, it says:
> 
> ```
> $ python3
> Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
> [Clang 12.0.0 (clang-1200.0.32.2)] on darwin
> >>> import tensorflow as tf
> >>> tf.__version__
> '2.3.1'
> 
> $ python3 object_detection_yolov3_tiny.py
> 2020-10-27 21:22:10.592008: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> [1]    24075 illegal hardware instruction  python3 object_detection_yolov3_tiny.py
> ```
> 
> 
> The same file can be executed on Ubuntu 18.04/20.04 without any problems, if ppa version of nnstreamer is installed on it.
> I wanted to look closer on the error with gdb, but I couldn't work with it since it says no debugging symbols found in python3.
> 
> Do you have any suggestions with this issue?
> Thank you :)

What the heck is ```object_detection_yolov3_tiny.py```? You need to ask someone who wrote it.

**Comment by lsj1213m** [comment]
@myungjoo I wrote it referencing nnstreamer object detection c++ example codes.
And I think I've used CPUs which have equivalent architectures (i7-9700K and i9-9880H).
I'll check more about this issue, then I'll update comment here if it is solved.

Thanks for your lots of help.
If I have to close the issue now?

**Comment by myungjoo** [comment]
If you don't need further discussion, please close it.

**Comment by wooksong** [comment]
> @myungjoo After following your guidelines, nnstreamer is finally installed without python3 support once.
> But now I have an another problem. If I run my python script which uses gstreamer and nnstreamer plugins, it says:
> 
> ```
> $ python3
> Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
> [Clang 12.0.0 (clang-1200.0.32.2)] on darwin
> >>> import tensorflow as tf
> >>> tf.__version__
> '2.3.1'
> 
> $ python3 object_detection_yolov3_tiny.py
> 2020-10-27 21:22:10.592008: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> [1]    24075 illegal hardware instruction  python3 object_detection_yolov3_tiny.py
> ```
> 
> 
> The same file can be executed on Ubuntu 18.04/20.04 without any problems, if ppa version of nnstreamer is installed on it.
> I wanted to look closer on the error with gdb, but I couldn't work with it since it says no debugging symbols found in python3.
> 
> Do you have any suggestions with this issue?
> Thank you :)


>> 2020-10-27 21:22:10.592008: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

@lsj1213m 

How did you install TensorFlow on your machine? In general, TensorFlow you did not build for your own machine does not support SIMD instructions but it is only related to the performance. You can ignore it. 
If it fails,
1) Check the tf version. According to [the release note](https://github.com/tensorflow/tensorflow/releases?after=v1.6.0), AVX is enabled by default from tf1.6. 
2) If you have multiple libraries related to CUDNN/CUDNN, match one that used in compiling with the one used in the runtime.

I think Solution 1 would resolve your problem:)

**Comment by lsj1213m** [comment]
@wooksong Thanks for your advice!
Though the real problem I focused on was illegal hardware instruction error, I'll try your solution later :)

**Comment by lsj1213m** [comment]
Now I can run nnstreamer with tensorflow installed with anaconda, thank you :)

To sum up,
  - Undefined symbols error can be avoided by adding ```-Dpython3-support=disabled``` option for ```meson build```.
  - Illegal hardware instruction error didn't occur if ```autovideosink``` is used in the pipeline code instead of ```osxvideosink```.
