### ISSUE TITLE
[Suggestion/C-Api] data handle to wrap user-allocated mem

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/nnstreamer#2827]
@kparichay suggested new function to wrap user-allocated memory while reviewing invoke-no-alloc feature.

However, as nnstreamer tensor_data c-api does not allow to create a wrapper of tensor_data around already allocated memory, I think the usage of this API might be limited.
You might consider introducing an additional API like int ml_tensors_data_create (const ml_tensors_info_h info, ml_tensors_data_h *handle, void *data) where void *data is the pre-allocated memory allocated by the user. This function would just wrap the user allocated memory with tensor_data so that it can be used inside nnstreamer. (I know this is currently limited to just 1 tensor but can be extended)

IMO, we dont need tensor-info for this function, this requires the array of mem and size.

- case 1: open struct ml_tensor_data_s and new function wrap()
```
typedef struct {
  void *tensor; /**< The instance of tensor data. */
  size_t size; /**< The size of tensor. */
} ml_tensor_data_s;

int ml_tensors_data_wrap (ml_tensor_data_s *data_list, unsigned int list_size, ml_tensors_data_h *data)
```
- case 2: define replace() function
After creating data handle using ml_tensors_data_create(), replace memory buffer and free old.

```
int ml_tensors_data_replace (ml_tensors_data_h data, unsigned int index, void *raw_data, size_t data_size)
```

We also need to consider the destroy_notify when pushing this data to appsrc.

**Comment by myungjoo** [comment]
@jaeyun-jung  Is this issue still valid?

**Comment by jaeyun-jung** [comment]
we determined to use the allocated buffer internally, close this issue.
