### ISSUE TITLE
Custom Build - Tensorflow Git not responding

### ISSUE THREAD

**Issue by JohnnyOpcode** [nnstreamer/nnstreamer#2829]
https://git.tizen.org/cgit/platform/upstream/tensorflow

Is not responding to a 'git clone' for a custom build. Please advise.

Johnny

**Comment by myungjoo** [comment]
You may create a Tizen account at "Register" (top right) of https://tizen.org and use the account to access review.tizen.org, which is more reliable than git.tizen.org.

git.tizen.org is not officially supported by tizen team; thus I suspect that that won't care much.

Unless you are developing Tizen packages, https://github.com/nnsuite/ubuntuport-tensorflow may be a working mirror, too.

**Comment by myungjoo** [comment]
Anyway, I've created a JIRA issue for infrastructure maintainers: https://bugs.tizen.org/browse/TINF-1585

**Comment by myungjoo** [comment]
I've tried git clone to git.tizen.org today and it's working. It appears that git.tizen.org was not responding temporarily.
That server has been always very slow. If you want faster access, get a tizen.org account and use review.tizen.org instead.
