### ISSUE TITLE
Unable to locate package nnstreamer-tensorflow

### ISSUE THREAD

**Issue by RockeyLuo** [nnstreamer/nnstreamer#2851]
Hi,
When I install nnstreamer and nnstreamer-example using PPA， the following error exist:

**sudo apt-get install nnstreamer-example
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nnstreamer-example : Depends: nnstreamer-tensorflow but it is not installable
E: Unable to correct problems, you have held broken packages.**
 
What is wrong with the nnstreamer-tensorflow source ?

**Comment by myungjoo** [comment]
@wooksong Please Take a Look at this (maybe Ubuntu PPA deployment issue?)

@RockeyLuo : Please let us know more about your situation so that we can reproduce your issue. I.e., what's your distro version?

**Comment by wooksong** [comment]
@gichan-jang Since https://launchpad.net/~nnstreamer-example/+archive/ubuntu/ppa depends on https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa, ```sudo apt install nnstreamer-example``` will complain about the packages that nnstreamer-example depends on. It better to move the nnstreamer-example package from the nnstreamer-example ppa to the nnstreamer ppa. 

@RockeyLuo Anyway, have you added https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa as one of your APT repository/source lists?

**Comment by gichan-jang** [comment]
@wooksong I agreed with your opinion. Separated ppa just cause confusion for user.
I will move the `nnstreamer-example` to nnstreamer ppa.

**Comment by gichan-jang** [comment]
@RockeyLuo 
As @wooksong mentioned, you wouldn't add nnstreamer ppa (https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa).
Now `nnstreamer-example` package is supported by nnstreamer ppa.

Please try this
```
sudo add-apt-repository --remove ppa:nnstreamer-example/ppa
sudo add-apt-repository ppa:nnstreamer/ppa
sudo apt-get update
sudo apt-get install nnstreamer-example
```

**Comment by wooksong** [comment]
@RockeyLuo Is it resolved?

**Comment by RockeyLuo** [comment]
> @RockeyLuo Is it resolved?
Hi everyone，
Thank you for your immediate reply.
I just install the binary pkg of nnstreamer from PPA on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-70-generic aarch64).
Nothing is done before the PPA install, is there any dependency need install? 
Is the OS/Hardware not compatible?
After the new CMD, the nnstreamer-tensorflow is still not installed. 
Here are the logs:
"
$ sudo apt-get install nnstreamer-example
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nnstreamer-example : Depends: nnstreamer-tensorflow but it is not installable
E: Unable to correct problems, you have held broken packages.
"

**Comment by myungjoo** [comment]
It appears that we do not publish tensorflow for aarch64 while there is dependency on tensorflow even in aarch64 build.
@wooksong will fix (cut the dependency) it for aarch64-Ubuntu.

**Comment by myungjoo** [comment]
Fix submitted: https://github.com/nnstreamer/nnstreamer-example/pull/236
PPA will soon deploy fixed versions. (within a few hours)
