### ISSUE TITLE
Survey: PyTorch-Mobile

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2858]
Need one of the reviewers to do
1. Survey PyTorch mobile, its status and advantages
2. Find out how "nnstreamer-pytorch-mobile" can be implemented.

**Comment by anyj0527** [comment]
I'm taking this, and I'll start with Android first.

**Comment by anyj0527** [comment]
## For Android

- [ ] Build Pytorch mobile for android with https://github.com/pytorch/pytorch/blob/master/scripts/build_pytorch_android.sh
- [ ] Get static libraries:
libc10.a  libclog.a  libcpuinfo.a  libeigen_blas.a  libnnpack.a  libpthreadpool.a  libpytorch_qnnpack.a  libtorch.a  libtorch_cpu.a  libXNNPACK.a
- [ ] Implement as a NNS subplugin

**Comment by myungjoo** [comment]
Before you move on to implementation, complete the survey and show it to us.
Support pytorch-mobile with nnstreamer is not highly prioritized.

Question:
- Would it be possible to use pytorch-mobile in general Linux (including Tizen)?
- How does it (expected to) perform? Does it support GPU acceleration? does it consume lower memory? ...
- How is it maintained? In the same code with different build option? In a different branch? In a different repo or directory?
- ...

**Comment by anyj0527** [comment]
@myungjoo @jaeyun-jung 

Q. How is it maintained? In the same code with different build option? In a different branch? In a different repo or directory?
A. It's in the same code with different build option.

Q. Would it be possible to use pytorch-mobile in general Linux (including Tizen)?
A. Yes, I think it's possible.

Q. How does it (expected to) perform? Does it support GPU acceleration? does it consume lower memory? ...
A. Currently it has benefit only for nnapi. With [provided tutorial](https://pytorch.org/tutorials/prototype/nnapi_mobilenetv2.html), I checked that it has similar latency with tflite.
(For mobilenet_v2 model in both cpu-backend and nnapi-backend)

I'll check about the memory usage.

**Comment by myungjoo** [comment]
We do not need to implement pytorch-mobile subplugin right now. You may close this when you have checked with memory consumption (compared with tf-lite).
