### ISSUE TITLE
ML-API/Single for TF-Lite 2.x

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2865]
Related: #2830 

1. (first part, higher priority) By default, Single-API use use the latest version (TF-lite 2.3 if it's available and the latest in the system)
2. (second part, lower priority) We still need to support both versions.

We may need to update semantics of ```ml_nnfw_type_e``` as well.
E.g., Mask 0xFFFF for file formats, 0xFFFF0000 for additional options for its runtime. (0 for auto, 1 for something, ...)

**Comment by myungjoo** [comment]
@jaeyun-jung PTAL. We need to supplrt tf-lite 2.x with ML-API.

**Comment by jaeyun-jung** [comment]
If sub-plugin name is tensorflow-lite, then 
1. parse ini and get priority for tflite model file
2. If found, check subplugin registration
3. If cannot get the prio from ini file, try to find tf-lite2 and tf-lite1

I will add new PR about this.

**Comment by jaeyun-jung** [comment]
PR #2905 
find sub-plugin with name "tensorflow2-lite" first if failed to get the subplugin "tensorflow2-lite"

**Comment by myungjoo** [comment]
> If sub-plugin name is tensorflow-lite, then
> 
> 1. parse ini and get priority for tflite model file
> 2. If found, check subplugin registration
> 3. If cannot get the prio from ini file, try to find tf-lite2 and tf-lite1
> 
> I will add new PR about this.

Refactoring (1 and 2) can be tracked by #2930
