### ISSUE TITLE
[Tizen] Latest snapshot does not contain libcapi-nnstreamer.so

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nnstreamer#2874]
Latest tizen snapshot(`tizen-unified_20201117.1_wearable-wayland-armv7l-tw3.tar.gz`) did not contain `libcapi-nnstreamer.so`
but only has `libcapi-nnstreamser.so.[1|0|1.7.0]`

Also installing capi-nnstreamer-1.7.0-62.2.armv7l.rpm does not install `libcapi-nnstreamer.so` but installing capi-nnstreamer-devel has the unversioned so

tested on TW3.

Need confirmation about the issue.

**Comment by zhoonit** [comment]
I think the problem is that my rootstrap is not updated to the latest. But could not verify

How to replicate

1. install the latest image to tw3
http://download.tizen.org/snapshots/tizen/unified/latest/images/standard/wearable-wayland-armv7l-tw3/

2. prepare a sample application
Currently, https://github.com/nnstreamer/nntrainer/tree/main/Applications/Tizen_native/CustomShortcut is used.

3. prepare tizen studio (with srib, tizen_studio_4.0 distribution)

4. install the sample app with tizen studio and try to run

5. error log can be observed at `dlogutil | grep dlopen` in sdb shell

E/LAUNCHPAD(17725): launchpad_loader.c: __loader_terminate_cb(352) > dlopen(/opt/usr/globalapps/org.example.nntrainer-custom-shortcut/bin/nntrainer-custom-shortcut) is failed. error(libcapi-nnstreamer.so: cannot open shared object file: No such file or directory)

6. ldd has `libcapi-nnstreamer.so` not found
$ldd (app binary) | grep nnstreamer
``
        libcapi-nnstreamer.so => not found
        libcapi-nnstreamer.so.1 => /lib/libcapi-nnstreamer.so.1 (0xf4934000)
        libnnstreamer.so => /lib/libnnstreamer.so (0xf4480000)
``

**Comment by again4you** [comment]
After adding `capi-nnstreamer-devel' to the platform image as a workaround, this issue is fixed. If Tizen 6.5 rootstrap is created, it will be removed.
