### ISSUE TITLE
NNStreamer for Ubuntu 20.04 is supposed to be published via PPA but it is not.

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#2881]
As following the configuration of the nnstreamer-daily in the PPA, NNStreamer is supposed to be published for Xenial, Bionic, Focal, and Groovy.  However, it seems to fail to build NNStreamer for Focal and Groovy. [ref](https://code.launchpad.net/~nnstreamer/+recipe/nnstreamer-daily)

IMO, at least, we need to fix it for Focal.

- [x] tensorflow-dev https://github.com/nnsuite/ubuntuport-tensorflow/pull/13
- [x] tensorflow-lite-dev https://github.com/nnsuite/ubuntuport-tensorflow/pull/13
- [x] pytorch
- [x] openvino and openvino-dev https://review.tizen.org/gerrit/#/c/platform/upstream/dldt/+/250932/
- [x] ~~protobuf-compiler17~~ protobuf-compiler23

---- 
#### Updated on Jan 12, 2021
Done.
https://launchpadlibrarian.net/516580081/nnstreamer_1.7.1.0-0~202101110529~ubuntu20.04.1_source.changes

#### Updated on Dec 18, 2020
Build dependencies on tensorflow and tensorflow-lite 1.13.1 have been resolved.

```bash
The following packages have unmet dependencies:
 builddeps:nnstreamer : Depends: pytorch but it is not installable
                        Depends: openvino-dev but it is not installable
                        Depends: openvino-cpu-mkldnn but it is not installable
                        Depends: protobuf-compiler17 but it is not going to be installed
```

#### Updated on Dec 02, 2020
```bash
The following packages have unmet dependencies:
 builddeps:nnstreamer : Depends: tensorflow-lite-dev but it is not installable
                        Depends: pytorch but it is not installable
                        Depends: openvino-dev but it is not installable
                        Depends: openvino-cpu-mkldnn but it is not installable
                        Depends: protobuf-compiler17 but it is not going to be installed
                        Depends: tensorflow-dev but it is not installable
```

**Comment by again4you** [comment]
@wooksong 

From now, our official PPA publishes the nnstreamer package for Ubuntu 20.04. So what about closing the issue?

**Comment by wooksong** [comment]
@again4you Let's close it.
