### ISSUE TITLE
[BeyonD/Android] android build option for tflite version

### ISSUE THREAD

**Issue by joan-juyeon** [nnstreamer/nnstreamer#2904]
i have changed its version manually by writing api/android/build-android-lib.sh,
```
63 # Set tensorflow-lite version (available: 1.9.0 / 1.13.1 / 1.15.2 / 2.3.0) 
64 tf_lite_ver="1.13.1" 
```
but maybe like by running api/android/build-android-lib.sh `--tflite_ver=2.3`, could we have build option for tflite version? 
the reason i'm asking it because gpu delegation works in tflite 2.3 ver. since https://github.com/nnstreamer/nnstreamer/pull/2855 [merged].

**Comment by myungjoo** [comment]
Yes. 

Please write a commit that updates ```build-android-lib.sh``` so that users may override ```tf_lite_ver``` value with arguments
Then, create a concise pull request with proper commit messages in it, with a reference to this issue.

**Comment by wooksong** [comment]
I've changed this issue's title. 

@joan-juyeon Do you have any plan (i.e., PR) to resolve this issue? If you need any help, please let me know.
