### ISSUE TITLE
Early-Exit related potential timing issue

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2911]
With early exit pipelines, we have a potential timing issue.

In an EE pipeline of:
```
... --> filter 1 --> branch (may go to JOIN directly) --> filter 2 --> JOIN --> P --> ...
```
With data-0 (first input), if branch passes to filter 2 and it passes to JOIN directly with data-1 (second input),
P may process data-1 before data-0.

How can we prevent this while allowing higher degree of pipeline parallelism?
Should we disable accepting data-i+1 until data-i is processed by JOIN?
or can we do re-sort or wait-for-next at JOIN or P?

CC: @jijoongmoon

**Comment by gichan-jang** [comment]
Agree about the problem situation.
Re-sorting buffers seem impossible.
I think it would be better to add options (`accept-latest` or `drop-delayed`) to `join`.
If the option is TRUE, join element memorize the timestamp of the last arrived buffer.
When a buffer arrives in join, compare the timestamp to decide whether to drop it or not.
So, if data-0 arrives after data-1 arrives, drop it.

**Comment by myungjoo** [comment]
Dropping a data frame is often not acceptable.

We will need a mechanism to disallow having multiple data frames in EE sub-pipeline (filter-A to JOIN) simultaneously as well.
(OR a manual/guide item that shows how to construct a sub-pipeline with such a requirement)

**Comment by myungjoo** [comment]
What about a new "queue-like" element that reacts to some signal:

===queue-signal
- dequeue condition = queue-signal's srcpad becomes available && ```pending_signal > 0```
- accepts a signal. accepting signal = ```pending_signal++;```
- ```pending_signal--;``` is a dequeue happens.
- Signal interface: TBD

===join (update)
- with queue-signal=${name}, it sends signal to ${name} queue-signal for next frame.
