### ISSUE TITLE
Architecture Discrepancy: Python API as Tensor Filter??

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2934]
```/ext/nnstreamer/tensor_filter/tensor_filter_python_api.c``` is NOT a tensor filter.
It may be migrated to https://github.com/nnstreamer/api and initiate the "api" project.

**Comment by dongju-chae** [comment]
That's right and it's not gstreamer element.

**Comment by dongju-chae** [comment]
As discussed in offline, we decided to rename/relocate the file.
