### ISSUE TITLE
New Stream Type Suggestion: "other/compressed-tensors"

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2936]
For better transmission performance, we may need to compress tensor streams.

This might be required by nnstreamer-edge as well. In such a case, core modules for other/compressed-tensor should exist separately with highly portable architecture.

Note that compression/decompression should incur low overhead.

**Comment by dongju-chae** [comment]
Is it different with serialized tensors? (e.g., `other/protobuf-tensor`)
Or, inclusive relationship?

**Comment by myungjoo** [comment]
Is other/flatbuf-tensor or other/protobuf-tensor compressed?

**Comment by dongju-chae** [comment]
No, it's a kind of encoding. Understood.

**Comment by myungjoo** [comment]
> No, it's a kind of encoding. Understood.

Anyway, we may need to consider the case of "compressed flatbuf tensors" or "flatbuf of compressed tensors"

The designer and implementer of this issue should decide such as well.

**Comment by anyj0527** [comment]
## TBU

Make two elements which (de/)compress other/tensor and other/tensors:
- tensor_compress
- tensor_decompress
- support type `other/compressed-tensor`

Survey topcis:
- usecases of "compressed" flatbuf/protobuf
- good compression algorithm for tensor

Check and measure:
- feasibility of "compressed tensor"
- performance gain

**Comment by myungjoo** [comment]
Before starting implementation, please draw class diagram and get it reviewed.

**Comment by myungjoo** [comment]
Or... gst_compress / gst_decompress, potentially taking "ANY". (and search for same functions)
For "ANY", we should be able to simply apply zlib, gzip, or such.

Later, we may consider (with some property values) applying different compressions for "sparse tensors".

**Comment by myungjoo** [comment]
Oh yes.. you may refer to https://github.com/Snec/gst-gz

If that's efficient enough, we may simply "fork it into here" and start "sparse tensors support" or add a tensor-efficient mechanism.

**Comment by anyj0527** [comment]
To compress / decompress "ANY":
User's pipeline can use the gstreamer plugin "gst-gz" (https://github.com/Snec/gst-gz) which supports two component `gzenc` and `gzdec` for zlib based encode / decode.

Usage:
```
$ gst-launch-1.0 filesrc location=file.txt ! gzenc ! filesink location=file.txt.gz

$ gst-launch-1.0 filesrc location=file.txt.gz ! gzdec ! filesink location=file_dec.txt
```

Unfortunately, it does not contained in `gst-plugins-(good | bad | ugly)`.
I think I can package it.

**Comment by anyj0527** [comment]
For "sparse tensor"

TensorFlow and PyTorch have been support sparse tensor:
https://www.tensorflow.org/guide/sparse_tensor
https://pytorch.org/docs/stable/sparse.html

Both framework use COO format (Two links above explain it well).

I may write converter / decoder subplugin which convert `other/tensor(s)` ("dense tensor") to `other/sparse-tensor(s)` ("COO formatted tensor") and vice versa.

**Comment by anyj0527** [comment]
Added Ubuntu package for `gst-gz` in https://launchpad.net/~anyj0527/+archive/ubuntu/ppa

**Comment by myungjoo** [comment]
@semun-lee Do you want to use gst-gz in your application? (If so, we will add it to Tizen.org, too)

**Comment by semun-lee** [comment]
> @semun-lee Do you want to use gst-gz in your application? (If so, we will add it to Tizen.org, too)

We don't have a plan to use gst-gz yet. We use image encoder like jpegenc for image inputs. For output tensors, I am more interested in the programmable tensor-filter.

**Comment by myungjoo** [comment]
Ok. @anyj0527 Please make gst-gz ready in Tizen:Unified and move on. (hold sparse-tensor compression)

**Comment by myungjoo** [comment]
We have gst-gz. Don't need this.
