### ISSUE TITLE
Use input/output combination of tensor_filter in demonstration apps.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2975]
In wiki of https://github.com/nnstreamer/nnstreamer/wiki/gst-launch-script-examples
and other example apps,

A. One of them (Not All!!!!, but the top one) need to use input/output-Combination options instead of Tee.

```
... --> tensor_filter (comb) --> tensor_demux -+-> tensor_decoder -+-> compositor --> video-out-sink
                                               +-> video_convert  -+
```

B. Then, another copy of the same app is to be reimplemented with Tee (keep as original of today) to provide an example of showing original raw images with high frequencies (60Hz) while inference results are shown at lower frequencies (e.g., 5Hz).

```
... --> tee -+-> queue -> tensor_filter (comb) ---> tensor_decoder -+-> compositor --> video-out-sink
             +-> queue -> video_convert  ---------------------------+
```

**Comment by gichan-jang** [comment]
An example apps are uploaded using `outputCombination`: https://github.com/nnstreamer/nnstreamer-example/pull/244

**Comment by gichan-jang** [comment]
Comparing using `tee` and `output-combination` was added in the object-detection example.
https://github.com/nnstreamer/nnstreamer/wiki/gst-launch-script-examples#script-of-nnstreamer_example_filter-using-tensorflow-model-eg-mobilenet

**Comment by myungjoo** [comment]
We need a small "independent" article (.md page) with pipeline diagrams showing the differences.

**Comment by gichan-jang** [comment]
> We need a small "independent" article (.md page) with pipeline diagrams showing the differences.

Okay. I will make documentation for it.

**Comment by gichan-jang** [comment]
Updated document comparing using tee and output-combination option.
https://nnstreamer.github.io/gst/nnstreamer/tensor_filter/README.html#comparison-of-tee-and-combination-option

**Comment by gichan-jang** [comment]
Examples and docs are done.
Close this issue.
