### ISSUE TITLE
[Edge-AI Future Feature] Heartbeats

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2999]
With Edge-AI support with tensor-filter::query, some users (clients) may make an edge-pipeline and send queries very infrequently.
For such usages, with or without some additional properties:

1. Maintain the connection. (E.g., keep the connection alive, reconnect if disconnected. Disconnect when not used for long time and reconnect when user notifies or a next query comes or the pipeline becomes alive, ...)
2. Send "heartbeats" to check the connection, status of servers, or so on.
3. Return "heartbeats" back to clients without incurring actual inferences in server pipelines (let server-src send a notification/event directly to server-sink node?)

This is to be considered when tensor-filter:query is somewhat completed. (2021-later feature)

CC: @wooksong  (I'm not assigning right now as this may be assigned to someone else; consider this as "subtask" of "edge-AI")

**Comment by wooksong** [comment]
@myungjoo Acked!
