### ISSUE TITLE
[C-API] Fool-Proof against #2968

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3001]
https://github.com/nnstreamer/nnstreamer/pull/2968

Can we create some fool-proof mechanism for seg-faults mentioned in #2968?

**Comment by dongju-chae** [comment]
That's a good idea. It's not easy for the CI server to detect such bugs. Actually, I got this bug related to #2968 after repeatedly running the same testcase 1000+ times :(

**Comment by myungjoo** [comment]
Looks like more than having ```data->handle = NULL;``` at ```__destroy_notify``` is not viable. Closing this.
