### ISSUE TITLE
Logging subsystem to help debugging  for deployment

### ISSUE THREAD

**Issue by leemgs** [nnstreamer/nnstreamer#3042]
In order that application developers can launch NNStreamer-based applications successfully, the logging systems are very crucial to them. 

## Summary
- [ ] 1. Tizen: Dlog system - Appropriate
- [ ] 2. Debugging Pipeline applications - Poor
- [ ] 3. Debugging facility to fix GStreamer elements - Poor
- [ ] 4. Debugging facility to fix NNStreamer elements - Poor

**Comment by leemgs** [comment]
## Report on a poor debugging facility of NNStreamer on the Tizen/RPI4 board.
* GST_DEBUG="4" GST_TRACER_PLUGINS="cpuusage;proctime;framerate" gst-launch-1.0 videotestsrc ! videorate max-rate=15 ! fakesink  
*  on the Ubuntu 18.04 board
![image](https://user-images.githubusercontent.com/82404/106564207-4a2ae600-6570-11eb-8f4a-20c27498c991.png)



*  on the Tizen/armv7l board 
![image](https://user-images.githubusercontent.com/82404/106564164-37181600-6570-11eb-98f2-1814157494d8.png)

**Comment by leemgs** [comment]
>  2. Debugging Pipeline applications - Poor

Let's describe an example. First, we assume that there is an original application (Not pipelined with NNStreamer). Then,  we added pipelined application. Then, we meet an run-time error with the pipelined application, we could not get appropriate hints from the output messages of the console. In this case, we could fix the issue by running the original application because it displays lots of message and more useful hint messages.

**Comment by leemgs** [comment]
@jaeyun-jung  PTAL.

**Comment by leemgs** [comment]
@helloahn , Could you append here on your experience that you have got the difficulty to debug errors while running pipeline applications?  Let's append the debugging issues to improve the deployment of applications with NNStreamer in this issue # 3042.

**Comment by jaeyun-jung** [comment]
Let's try to set env var in app,
```
g_setenv ("GST_DEBUG", "xxxx", TRUE);
.....
g_unsetenv ("GST_DEBUG");
```

**Comment by jaeyun-jung** [comment]
Or we should handle log function like below,
```
  gst_debug_set_active (TRUE); <-- enable log
  gst_debug_set_default_threshold (GST_LEVEL_WARNING); <-- set log level
  gst_debug_remove_log_function (gst_debug_log_default); <-- remove default log function
  gst_debug_add_log_function ((GstLogFunction) app_log_function, NULL, NULL);
```
