### ISSUE TITLE
Resolve issues from gRPC v1.35.0 upgrade

### ISSUE THREAD

**Issue by dongju-chae** [nnstreamer/nnstreamer#3045]
We're using gRPC 1.20.1 but Tizen upstream now starts to upgrade gRPC version to 1.35.0.

- [x] grpc/flatbuffer patch: https://review.tizen.org/gerrit/#/c/platform/upstream/flatbuffers/+/252922
- [x] NNStreamer Fix: https://github.com/nnstreamer/nnstreamer/pull/3054
- [x] Ubuntu PPA update: Done (need `libre2` and `abseil-cpp`)

**Comment by myungjoo** [comment]
As I've commented at #3046, you should not add indirect dependencies. Such dependencies should've resolved at grpc's package descriptions.

**Comment by dongju-chae** [comment]
I also don't want to do so. I will talk to the Tizen gRPC maintainer tomorrow.

**Comment by myungjoo** [comment]
There is no remaining issues.
