### ISSUE TITLE
Custom-easy-like subplugins for converter & decoder in C/C++

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3086]
If you are interested in this topic, please start discussions (identify use cases and requirements)

**Comment by gichan-jang** [comment]
How can we make the tensor converter aware of the custom?
How about giving the mode?

For example, in callback type,
`... ! media caps ! tensor_converter name=tconv mode=custom-c ! tensor(s) stream ... `

python script type
`... ! media caps ! tensor_converter mode=custom-script script=custom.py ! tensor(s) stream ... `

**Comment by jaeyun-jung** [comment]
My suggestion:
mode=custom-code:<registerd callback name>
mode=custom-script:<script name>

**Comment by myungjoo** [comment]
> My suggestion:
> 
> ```
> mode=custom-code:<registerd callback name>
> mode=custom-script:<script full path>
> ```

LGTM!
