### ISSUE TITLE
Enable pytorch, caffe2, armnn in Tizen build

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3090]
For Tizen:Unified public build, enable pytorch, caffe2, armnn.
If there are other disabled features that can be enabled trivially in Tizen, do it.

This shouldn't require too much time.

**Comment by dongju-chae** [comment]
It seems that Tizen has not published such packages. Do you know the reason?

**Comment by myungjoo** [comment]
> It seems that Tizen has not published such packages. Do you know the reason?

Because I (and other nnstreamer contributors) didn't bother. You may publish them. (only requires a few "paper works")

**Comment by dongju-chae** [comment]
I understood. I will try to revive such packages with minimum effort.

**Comment by myungjoo** [comment]
ARMNN: re-eabled: https://github.com/nnstreamer/nnstreamer/pull/3385

**Comment by myungjoo** [comment]
pytorch, caffe2: https://bugs.tizen.org/browse/TRE-2759

**Comment by myungjoo** [comment]
Done: https://build.tizen.org/package/show/Tizen:Unified/pytorch
