### ISSUE TITLE
Sharing Model Representation with CAPI

### ISSUE THREAD

**Issue by helloahn** [nnstreamer/nnstreamer#3114]
We can access a specific TFLite model through an `interpreter` object,
which can be built with the model path.

With TFLite API, when we want to use multi-threads to make processes faster,
because the `interpreter` is a sharable resource,
we can share the one `interpreter` without creating the new one for each thread.

However, in Single & Pipeline CAPI, there is no way to share the model representations currently.
I had a short discussion with @jaeyun-jung, and we made a few suggestions below.

1. Create a sharing table consists of Key(model path) & Value (`interpreter`) at each filter.
2. If there is any NEW request related to the added key(model path) the saved value(`interpreter`) will be used.
3. If there is no more usage of the shared Value(`interpreter`), it will be disappeared.

Though we still have some side-effects from the above solution, like the policy of dimension-change function, 
to reduce memory consumption, IMHO sharing the duplicated resource is quite important.

Please leave your opinions.

**Comment by helloahn** [comment]
> I wonder if a single interpreter can support different inputs where a thread can set tflite inputs for itself without affecting the other threads?

No, it cannot support it, as I know. To using one interpreter with multi-threads we have to adjust the order one by one.

> Note that this is only required when different threads will try to use the shared interpreter concurrently. If only one interpreter is going to use it at once, then it's fine.

You're right. The main purpose of this issue is to save memory consumption by sharing one interpreter.
If efficiency is the most important point, we can create as much as we need for the threads.
However, as you know, because interpreters require memory,
if memory consumption is important, we need to consider reducing it by sharing.

> Also, you can consider the batch for the inputs, where different threads can set the data in their corresponding location in the batch, and all the threads data can run at once in a single batch.

IMO, It can be another solution for the issue.
We can solve it without additional code fix by giving guide users to change batch size rather than using multi-thread. Good point.
However, is it available for all models (changing batch size)?

**Comment by kparichay** [comment]
> With the CPU-only environment, however, because the parallel calculation is not efficient, multi-thread could be better.

I wonder the difference in performance with the multi-threading done at pipeline level and multi-threading done with `interpreter.SetNumThreads()`.

**Comment by myungjoo** [comment]
For API format, try to keep backward-compatibility. (I believe you can do it.)

**Comment by helloahn** [comment]
> For API format, try to keep backward-compatibility. (I believe you can do it.)

Sure, it is one of the most important points.

**Comment by kparichay** [comment]
> but in a multicore CPU-only or NPU environment, there was no improvement :(

Then let's use multi-threading in our pipeline and parallelize over tf-lite interpreter.

**Comment by myungjoo** [comment]
@helloahn How's it going? (adjust milestone accordingly as well)
