### ISSUE TITLE
[Packaging] Separate nnstreamer conf as a package

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nnstreamer#3124]
# AS-IS
Testing nnstreamer sub-plugins are virtually impossible out of nnstreamer package in tizen. (reason of nnstreamer/nntrainer#997 build fail)

consider below.

```spec
Version: 0.0.1
Name: foo
Summary: nnstreamer tensor-filter subplugin.

BuildRequires: nnstreamer-devel
Requires: nnstreamer

%build
./some_build_script

export NNSTREAMER_CONF=${NNSTREAMER_BUILD_ROOT_PATH}/nnstreamer-test.ini # this does not works because, `/etc/nnstreamer.ini` overloads it.

./test_foo_subplugin.sh #this will fail
```

`./test_foo_subplugin.sh` will fail because, in tizen, `/etc/nnstreamer.ini` has higher priority than `NNSTREMAER_CONF` env vars.

referring to below code.
https://github.com/nnstreamer/nnstreamer/blob/0d9313f96886feb3733b32bb9d03b24cb8fef76a/gst/nnstreamer/nnstreamer_conf.c#L347-L374

# TO BE
When building nnstreamer sub-plugin, tester should let `nnstreamer` to recognize their built filter without installing it.

# Suggestion
1. Make a intermediate package (say, `nnstreamer-configuration`, `nnstreamer-core`) 
2. Make `nnstreamer` as a meta package requiring (`nnstreamer-configuration`, `nnstreamer-core`)
3. `nnstreamer-devel` requires only `nnstreamer-core`

[**workable example**](https://github.com/nnstreamer/nnstreamer/compare/main...zhoonit:@undef/draft/packaging?expand=1) if it sounds okay, i'd like to make a PR of it.

**Comment by zhoonit** [comment]
Consulted @myungjoo and decided to have `nnstreamer-test-devel` package to provide test environment. Soon there will be a patch

**Comment by myungjoo** [comment]
Anyway, your original suggestion to make nnstreamer.rpm as a meta-package requiring nnstreamer-core and nnstreamer-conf looks still good. I'm simply not doing it just because I'm too lazy.

We can manage default subpackages easily with such meta packages.

**Comment by zhoonit** [comment]
Cool, I will make a pr of it.
