### ISSUE TITLE
Tensor-Transform Multi-Tensor Support

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3141]
Allow processing tensors with tensor-transform

It may require to specify tensor numbers to be processed with property values.

"Project F" can be further optimized with this.

**Comment by gichan-jang** [comment]
I will take this issue.
1. Support tensors. Apply the same mode to all tensors
  `.. (tensors stream) ! tensor_transform mode=MODE option=OPTION ! (tensors stream) ...`
2. Apply the same mode to selected tensors only
  `.. (tensors stream) ! tensor_transform mode=MODE option=OPTION applied=SELECTED_TENSOR ! (tensors stream) ...`

**Comment by myungjoo** [comment]
```apply=SELECTED_TENSOR```
Please allow specifying multiple tensors; e.g., ```apply=0,1,2``` 
Having default as ```apply=all``` is good.

**Comment by gichan-jang** [comment]
> `apply=SELECTED_TENSOR`
> Please allow specifying multiple tensors; e.g., `apply=0,1,2`
> Having default as `apply=all` is good.

Right.

**Comment by jaeyun-jung** [comment]
Now tensor-transform supports multi tensors.
