### ISSUE TITLE
Stream Type: Sparse Tensors

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3145]
This is forked from #2936 (compressed tensor)

Requested by "client", transmitting sparse tensors for Edge-AI projects are required.

V1: sparse-tensor (compressed) stream type definition with converter & decoder standard subplugins
V2: sparse-tensor (compressed) stream direct inferences with a few tensor-filter subplugins
V1: TBD 2021
V2: TBD 2021 4Q or 2022.

CC: @jaeyun-jung @anyj0527

**Comment by kparichay** [comment]
I wonder about sparse tensor src/sink if they will also be needed?

**Comment by myungjoo** [comment]
Sparse Tensor is just another stream data type (e.g., other/sparsetensors).

For src, appsrc should be fine. (no need for yet another src element)

Tensorsink... let's see what happens without it. My guess is that we won't need it because users will generally use tensor-converter to get other/tensors. We can easily expand tensor-sink if that's really required. Actually, tensor-sink is not that useful when app-sink is available.

**Comment by kparichay** [comment]
> We can easily expand tensor-sink if that's really required. Actually, tensor-sink is not that useful when app-sink is available.

Agreed.

**Comment by myungjoo** [comment]
I guess this is already
