### ISSUE TITLE
Getting tensor shape of the model from tensor-filter element.

### ISSUE THREAD

**Issue by nicesj** [nnstreamer/nnstreamer#3148]
**Is your feature request related to a problem? Please describe.**
I'm using GStreamer C API with nnstreamer pipeline elements for the inference operation.
Unfortunately, I couldn't find ways to set or get tensor shapes for the model given to the tensor-filter element.
Is it possible to get such information without opening the model by myself or using a different API set (such as tflite C++ API...)

**Describe the solution you'd like**
If possible, please give me the properties of the tensor-filter element to get and to set input and output tensor shapes for the model.

**Describe alternatives you've considered**
Anything will be fine. I just want to know the tensor shape (input/output) of the model.

**Additional context**
Nope.

**Comment by again4you** [comment]
In the case of Single APIs, you can access tensor information such as dimension, type, and name. However, Pipeline APIs do not support them since the developers have to know this information of the model that they want to use.

What if you are going to use the pre-built model from the Web and do not know the input/output information, [netron](https://github.com/lutzroeder/netron) tool is useful to get this info.

![nettron_example](https://user-images.githubusercontent.com/433435/112243264-a49f1380-8c90-11eb-95f1-8e6702c0b942.JPG)

**Comment by nicesj** [comment]
> In the case of Single APIs, you can access tensor information such as dimension, type, and name. However, Pipeline APIs do not support them since the developers have to know this information of the model that they want to use.
> 
> What if you are going to use the pre-built model from the Web and do not know the input/output information, [netron](https://github.com/lutzroeder/netron) tool is useful to get this info.
> 
> ![nettron_example](https://user-images.githubusercontent.com/433435/112243264-a49f1380-8c90-11eb-95f1-8e6702c0b942.JPG)

Thank you for the comment.
Could you improve the tensor-filter element to get and set the tensor shape using the element's property feature?
The GST element provides the property feature.

**Comment by myungjoo** [comment]
In general, it might be not possible to get dimensions with given models.
There are cases where input/output dimensions are determined dynamically. (e.g., output dimension is determined by input dimensions given by users)

Anyway, have you tried to read via the following properties?
```
  input               : Input tensor dimension from inner array, up to 4 dimensions ?
                        flags: readable, writable
                        String. Default: ""
  inputtype           : Type of each element of the input tensor ?
                        flags: readable, writable
                        String. Default: ""
  inputname           : The Name of Input Tensor
                        flags: readable, writable
                        String. Default: ""
  inputlayout         : Set channel first (NCHW) or channel last layout (NHWC) or None for input data. Layout of the data can be any or NHWC or NCHW or none for now. 
                        flags: readable, writable
                        String. Default: ""
  inputranks          : The Rank of the Input Tensor, which is separated with ',' in case of multiple Tensors
                        flags: readable
                        String. Default: ""
  output              : Output tensor dimension from inner array, up to 4 dimensions ?
                        flags: readable, writable
                        String. Default: ""
  outputtype          : Type of each element of the output tensor ?
                        flags: readable, writable
                        String. Default: ""
  outputname          : The Name of Output Tensor
                        flags: readable, writable
                        String. Default: ""
  outputlayout        : Set channel first (NCHW) or channel last layout (NHWC) or None for output data. Layout of the data can be any or NHWC or NCHW or none for now. 
                        flags: readable, writable
                        String. Default: ""
  outputranks         : The Rank of the Out Tensor, which is separated with ',' in case of multiple Tensors
                        flags: readable
                        String. Default: ""
```

@again4you : he is using GST APIs, not ML APIs :)

**Comment by anon-wiz** [comment]
@myungjoo Thank you. I'll update this issue after checking properties.

**Comment by anon-wiz** [comment]
Thank you. it works very well.
```
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] input: 3:224:224:1
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] inputtype: uint8
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] inputname:
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] inputlayout: ANY
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] inputranks: 3
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] output: 1001:1:1:1
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] outputtype: uint8
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] outputname:
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] outputlayout: ANY
[peer_gst_server.cc:CommandHandlerPrepare:214] [2531] outputranks: 1
```
