### ISSUE TITLE
Project Mgt: Test Case Maturity Check-Up

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3150]
We have been refactoring a lot of test cases. We need to check up with TCM system to see if their weird metrics give weird outputs.

**Comment by gichan-jang** [comment]
The TCM system is not aware of the template tests using `unittest_tizen_template.cc.in`.
TCM doesn't count almost 84 TCs (35 PTCs, 49 NTCs).

**Comment by myungjoo** [comment]
> The TCM system is not aware of the template tests using `unittest_tizen_template.cc.in`.
> TCM doesn't count almost 84 TCs (35 PTCs, 49 NTCs).

Have you reported to the correspondents? (SE)

**Comment by myungjoo** [comment]
It appears that we have passed TCM; otherwise, SE would have reported before the release :)
