### ISSUE TITLE
The path of nnstreamer.ini should be fixed

### ISSUE THREAD

**Issue by helloahn** [nnstreamer/nnstreamer#3161]
## Envorinment
- Meson 0.53.2
- Ubuntu 20.04 (aarch64)

## Description
The install path of `nnstreamer.ini` should be fixed to something(like `/etc/nnstreamer.ini`)
If we install it through `meson build` and `ninja install` without any options like `--sysconfdir`,
`nnstreamer.ini` is installed at `/usr/local/etc/nnstreamer.ini`, and it is not searchable and generates the below error.

```bash
(run the example nnstreamer_example_object_detection_tflite)

** (nnstreamer_example_object_detection_tflite:40709): WARNING **: 17:09:07.325: Failed to load the configuration, no config file found.
...
```

**Comment by myungjoo** [comment]
Approach 1: set /usr/lib/... and /etc as the default location if unspecified. (need to check if it complies with "Linux customs")
Appraoch 2: add /usr/local/etc/nnstreamer.ini as "secondary default in location".

**Comment by myungjoo** [comment]
#3367 : Approach 3: let meson script handle sysconfdir properly with relative paths or empty paths.
