### ISSUE TITLE
nnstreamer with tensorflow-lite & delegate

### ISSUE THREAD

**Issue by peter197321** [nnstreamer/nnstreamer#3164]
I'm just looking into doc https://github.com/nnstreamer/nnstreamer/wiki/usage-examples-screenshots#usage-examples where I'm trying to locate TensorFlow-Lite usage with a specific delegate (e.g. XNNPACK).

How should I use nnstreamer with TensorFlow-Lite with its delegate?

Thank you.

**Comment by anyj0527** [comment]
Currently NNStreamer does not support TFLite XNNPACK delegate. GPU (Android, Tizen) and NNAPI (Android) are supported.

To use them, you can add property for delegates to `tensor_filter` in pipeline.
e.g.)
```
... ! \
tensor_filter framework=tensorflow-lite model=SOME_MODEL.tflite custom=Delegate:NNAPI ! \
...
```
```
... ! \
tensor_filter framework=tensorflow-lite model=SOME_MODEL.tflite custom=Delegate:GPU ! \
...
```

XNNPACK will be supported in near furture.

**Comment by myungjoo** [comment]
@peter197321 For which applications do you need XNNPACK delegation? Or are you good with GPU/NNAPI delegation?

**Comment by myungjoo** [comment]
NNStreamer APIs for TF-Lite Delegation have been expanded (and will include XNNPACK soon).
@anyj0527 Please report XNNPACK-delegation progress.

**Comment by anyj0527** [comment]
@myungjoo Still working on it. I'll update the result soon.

**Comment by myungjoo** [comment]
XNNPACK Delegation is fixed. Android/XNNPACK delegation is deployed.
