### ISSUE TITLE
AI Acceleration with "subplugins"

### ISSUE THREAD

**Issue by peter197321** [nnstreamer/nnstreamer#3165]
It seems the nnstreamer mentioned it provides various hardware acceleration "subplugins". Is there any example to use those "subplugins" e.g.  ARM-NN, Edge-TPU, or Verisilicon ...

Thank you.

**Comment by anyj0527** [comment]
You may check https://github.com/nnstreamer/nnstreamer-example.
There are some `gst-launch-1.0` based examples:

edge tpu
- https://github.com/nnstreamer/nnstreamer-example/tree/main/bash_script/example_image_segmentation_tensorflow_lite

openvino
- https://github.com/nnstreamer/nnstreamer-example/tree/main/bash_script/example_person_detection_openvino
- https://github.com/nnstreamer/nnstreamer-example/tree/main/bash_script/example_face_detection_openvino

**Comment by myungjoo** [comment]
Browse at https://github.com/nnstreamer/nnstreamer/tree/main/ext/nnstreamer/tensor_filter

In that directory, for hardware accelerators, you will find:
- Vivante
- ARMNN
- EdgeTPU
- Movidius NCSDK2
- OpenVINO
- SNAP
- SNPE
- TensorRT
-

**Comment by myungjoo** [comment]
As there is no follow-up questions or answers, I'm closing this,
