### ISSUE TITLE
`GstTensorFilterFrameworkStatistics` should be managed per instance, not filter framework

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3186]
`GstTensorFilterFrameworkStatistics` should be managed per instance, not per filter framework

**Comment by myungjoo** [comment]
Maybe you just need to add yet another metric that is counted per instance without modifying the semantics of GstTernsorFilterFrameworkStatistics.

**Comment by myungjoo** [comment]
Is this still pending? @anyj0527

**Comment by anyj0527** [comment]
@myungjoo It's been pending. I'm about to start this one!

**Comment by anyj0527** [comment]
Simply logging the latency and throughput values would be enough: #3376
