### ISSUE TITLE
Set tensor converter properties

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#3191]
The serialized buffers(Protobuf, flatbuf and flexbuf) don't know the output capability at the negotiation stage.
So initially set to default cap and update out cap when first buffer comes in.
However, this is a problem when used with some elements such as tensor_decoder::bounding_boxes.
The bounding box tensor decoder call assert failure if input cap does not match at the negotiation phase.
Example of a failed pipeline
```
gst-launch-1.0 \
    v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
    t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=300,height=300,format=RGB ! tensor_converter ! \
        tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
        tensor_filter framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! \
        tensor_decoder mode=flexbuf ! other/flexbuf ! tensor_converter ! \
        tensor_decoder mode=bounding_boxes option1=tflite-ssd option2=tflite_model/coco_labels_list.txt option3=tflite_model/box_priors.txt option4=640:480 option5=300:300 ! \
        compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink \
    t. ! queue leaky=2 max-size-buffers=10 ! mix.
```
To solve this particular case, properties can be set to the converter manually such as `application/octect-stream`.
If there are properties, use the properties to set the output cap; if not, set the default cap.
For example,
```
... ! other/flexbuf ! tensor_converter num-tensors=2 input-dim=1:2:3:4.2:3:4:5 input-type=uint8.float32 ! ... (tensor(s) stream)
```

@helloahn Please share your opinion.

**Comment by helloahn** [comment]
input-dim & input-type -> output-dim&output-type
I think it's your intention, right?

Anyway, we need to consider which way is more proper between
1. adding some properties at tensor_converter
2. require the right capabilities to the next element

I agree with @gichan-jang 's suggestion to solve the issue simply.
However, I am not sure whether it is consistent with GStreamer's directionality.

**Comment by gichan-jang** [comment]
@helloahn 
 > input-dim & input-type -> output-dim&output-type
I think it's your intention, right?

Right!

**Comment by myungjoo** [comment]
It'd be better if you simply do this:
```
! tensor_converter ! other/tensors,num_tensors=2,.... !
```

You don't need to add properties. Reuse caps-filter.

**Comment by myungjoo** [comment]
If you can generate a message recommending to use caps-filter (as above) in the given cases, it'd be the best.

**Comment by gichan-jang** [comment]
> It'd be better if you simply do this:
> 
> ```
> ! tensor_converter ! other/tensors,num_tensors=2,.... !
> ```
> 
> You don't need to add properties. Reuse caps-filter.

Got it! Thanks for the suggestion.

**Comment by gichan-jang** [comment]
Close this issue via #3198
