### ISSUE TITLE
[Audio] Can nnstreamer support audio to text?

### ISSUE THREAD

**Issue by kevinbingsong** [nnstreamer/nnstreamer#3206]
I found audio process in tensor_convert. can nnstreamer support audio to text? or any other audio use cases?

**Comment by jaeyun-jung** [comment]
below is an example using speech command model (tensorflow-lite)
https://github.com/nnstreamer/nnstreamer-example/blob/main/native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c

**Comment by kevinbingsong** [comment]
Ok. Thanks.
