### ISSUE TITLE
[Tizen/API] Revise element restrictions in pipeline API

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3244]
To be ready for edge AI supports, increase the coverage.

  Add all connection related elements, data wrapper/unwrappers.

CC: @wooksong (Edge AI connection maintainer) , @again4you (Tizen ML maintainer)

**Comment by anyj0527** [comment]
Need to add `audiocheblimit`
REF: https://gstreamer.freedesktop.org/documentation/audiofx/audiocheblimit.html?gi-language=c

**Comment by helloahn** [comment]
RTSP:
```
rtpdec rtspsrc rtspclientsink
```

ZeroMQ
```
zmqsrc zmqsink
```

mqtt
```
mqttsrc mqttsink
```

UDP
```
udpsrc udpsink multiudpsink
```

Query
```
queryclient queryserversrc queryserversink
```
