### ISSUE TITLE
[API.git] Spec file clean up required (unrequired dependencies)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3248]
nnstreamer/api.git should NEVER depend on indivisual frameworks (tensorflow, armnn, ...).
The conditions and dependencies on such should be removed from api.git

However, this can be started after Tizen 6.5 M1 releases.

**Comment by jaeyun-jung** [comment]
Actually nn framework dependency in api repo is not used in code, just for the feature definition in testcases.
