### ISSUE TITLE
PPA support for tensorflow2-lite

### ISSUE THREAD

**Issue by shortcipher3** [nnstreamer/nnstreamer#3282]
**Is your feature request related to a problem? Please describe.**

It would be nice if there was a `nnstreamer-tensorflow2-lite` repository in the PPA.  I would like to be able to call:
```
apt install nnstreamer-tensorflow2-lite
```

Some models require operations only available in tensorflow2, so the `tensorflow-lite` package can't run them.

**Comment by myungjoo** [comment]
TODO:
- [ ] https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/258437/
- [ ] PPA register: https://code.launchpad.net/~nnstreamer/+recipe/tensorflow2-daily
- [ ] Update nnstreamer debian packaging

**Comment by myungjoo** [comment]
Status
- tf2-lite for Ubuntu build: done (last commit is under review)
- tf2-lite subplugin for Ubuntu build: WIP (Ubuntu build script has some issues)

**Comment by myungjoo** [comment]
Fixes Tested. This issue will be closed if the following commits are merged:
- https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/258566/
- https://review.tizen.org/gerrit/#/c/platform/upstream/tensorflow2/+/258797/
- https://github.com/nnstreamer/nnstreamer/pull/3288

**Comment by myungjoo** [comment]
Merged all related commits.
Launchpad PPA should be releasing new packages within 24 hours and you can get the packages with pdebuild right now.
