### ISSUE TITLE
dependency('capi-nnstreamer') is not enough to link against libnnstreamer.so

### ISSUE THREAD

**Issue by smohantty** [nnstreamer/nnstreamer#3316]
# Issue Description
For nnstreamer dependency, using dependency('capi-nnstreamer') in meson results into linker error "error while loading shared libraries: libnnstreamer.so: cannot open shared object file"

Expected Result
============
should work as expected

How to Reproduce
===============
1. create a sample test app in meson and add dependency('capi-nnstreamer')  as dependency and try to invoke any ml_pipeline() results in runtime error.

Further Information
===============
- In nnstreamer.pc the library location mentioned  in /usr/local/lib/x86_64-linux-gnu . but the actual install directory when building nnstreamer from source is /usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/ hence the error.

**Comment by gichan-jang** [comment]
Thanks for posting the issue.
/usr/local/lib/x86_64-linux-gnu/libnnstreamer.so is symbolc link to /usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so.
Did you install the nnstreamer?
```
$ sudo add-apt-repository ppa:nnstreamer/ppa
$ sudo apt-get update
$ sudo apt-get install nnstreamer 
```

**Comment by smohantty** [comment]
@gichan-jang ,
I build the nnstreamer from source (branch lts/1.6.y)

step :
meson -Denable-test=false build
ninja -C build install

**Comment by gichan-jang** [comment]
Ah, You build from source.
Sorry for the insufficient description. 
Please use 
```
dependency('capi-ml-inference')
```
