### ISSUE TITLE
Documentation update for meson/ninja build

### ISSUE THREAD

**Issue by shortcipher3** [nnstreamer/nnstreamer#3320]
The documentation for the meson/ninja build is out-of-date, found here: Documentation/getting-started-meson-build.md

I would be great if this could be updated so people could build when they can't download and use a PPA build.

Ideally the instructions would be clear enough to build nnstreamer and some of the plugins such as tensorflow.

**Comment by myungjoo** [comment]
I'd update this document. However, it seems that writing proper build instructions of Tensorflow is way too complicated; Tensorflow is not C/C++ friendly and their build mechanism is convoluted and keeps changing. So, I'll skip build instructions of Tensorflow and assume that the user has installed Tensorflow and provide a sample pkg-config file for Tensorflow / Tensorflow-lite.

**Comment by shortcipher3** [comment]
That sounds great. It looks like for tensorflow-lite they are working to make the C API easier to use.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c

**Comment by myungjoo** [comment]
Doc Updated.
