### ISSUE TITLE
[NNS 2.0] Stream Data Type Consolidation

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3351]
1. Deprecate ```other/tensor```. Use ```other/tensors,format=static,num_tensors=1``` instead. Create warning messages for ```other/tensor``` users.
2. Introduce ```format={static,...}``` to ```other/tensors```. If unspecified, ```format=static```, which has mandatory key-values of conventional ```other/tensors```.
3. Consolidate ```other/tensors-flexible``` to ```other/tensors,format=flexible```. Remove ```other/tensors-flexible```
4. Introduce sparse tensors ```other/tensors,format=sparse```.
5. Write sparse tensor format converter. Sparse tensors are supposed to be transports and won't be processed by conventional tensor-* elements.
6. With all these done, mark version 2.0.0.

1, 2, 3: @kimjh12 (start after TVM and tf-lite sharing? can be done in July?)
4, 5: @anyj0527 (major part of code is already written? can be done in Mid-July?)

This is a major refactoring and consolidation with possibly huge impacts on code quality and correctness.
- Need a lot of test cases
- Need to keep backward compatibility with ML-API & Tizen Apps & TCs
- Need careful reviews (@jaeyun-jung @again4you )
- Block negotiating if the incompatible tensor format is fed to a tensor-* element.
- Let's complete this (release candidate) in July. Let me know if it requires more effort.

**Comment by jaeyun-jung** [comment]
First PR to determine default caps string with format (https://github.com/nnstreamer/nnstreamer/pull/3362)

**Comment by jaeyun-jung** [comment]
Added new PR to update caps template (https://github.com/nnstreamer/nnstreamer/pull/3381)
- caps template with new field 'format'
- caps for flexible tensor with 'framerate' field
