### ISSUE TITLE
tensor-converter caps-filter negotiation bug

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3352]
```
... ! tensor-converter ! other/tensors,num_tensors=1,... ! ...
```
In the above pipeline, tensor-converter's behavior should be determined by specifications of caps-filter with its property values (e.g., dims, types, ...) so that we can omit explicit properties for tensor-conveters.

Reported by @jaeyun-jung 

@jaeyun-jung you may reassign to the appropriate contributor.

**Comment by jaeyun-jung** [comment]
We checked peer caps when it is fixed. (If caps is not fixed, it is supposed not configured and return false, so cannot parse it.)
Some PRs (e.g. https://github.com/nnstreamer/nnstreamer/pull/3379 already merged) will fix this condition. Also we will update caps template with framerate and format fields. I also included some changes about this issue.
