### ISSUE TITLE
[CI] build java api

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/nnstreamer#3361]
After merging build script on api repo, we need to setup taos-ci and daily build to build Java API (.jar) on Ubuntu.

1. add script (pr-postbuild-build-ml-api-ubuntu-java.sh ?) in TAOS-CI
2. add deb package (ml-inference-jni-wrapper.deb ?)
3. enable daily build

See https://github.com/nnstreamer/api/pull/72
- add new script to build jar `java/build-nnstreamer-ubuntu.sh`
- android build script is moved from `java/android/build-nnstreamer-android-lib.sh` to `java/build-nnstreamer-android.sh`

**Comment by jaeyun-jung** [comment]
TAOS-CI
- add new script to check jar (https://github.com/nnstreamer/TAOS-CI/pull/727)
API
- generate deb pkg (https://github.com/nnstreamer/api/pull/74)
- remove nn framework feature in native (https://github.com/nnstreamer/api/pull/75)

Now we build java (.jar) in daily build.

After merging above PRs, close this issue.

**Comment by gichan-jang** [comment]
Daily build result release: [daily build](http://nnstreamer.mooo.com/nnstreamer/ci/daily-build/build_result/latest/java_ubuntu/)

**Comment by jaeyun-jung** [comment]
Daily build enabled
All related PRs are merged and taos-ci now checks ubuntu java build on api repository.
After preparing nn-runtime pkg, I will update script on api repo - adding nn-runtime dependency to build deb pkg.
