### ISSUE TITLE
Temporarily disabled features / test case

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#3377]
Below items should be checked before Tizen 6.5 M2 Release.

### MQTT: Feature disabled
* Reason: Some test cases are failed on the specific architecture
* Related patch: https://github.com/nnstreamer/nnstreamer/commit/a78ad73ddc2d7068f8818f1c025a21e085e6b675
* Owner: @wooksong 
* Status: Done

### TVM: Test cases only is running on x86_64
* Reason: Test model is not ready for other architectures.
* Related patch: https://github.com/nnstreamer/nnstreamer/commit/8711be9536162d95897a4ab80ae4d76e440f76e0
* Owner: @kimjh12 
* Status: In progress

**Comment by gichan-jang** [comment]
grpc is disabled in debian. (https://github.com/nnstreamer/nnstreamer/pull/3122)

**Comment by myungjoo** [comment]
If TVM sample models work in x64 only, enable test cases in x64. You can expand test case conditions accordingly in the future.

**Comment by again4you** [comment]
* TVM test supports `ARM`, `x86_64` and `aarch64` architecture.
* All bugs related `GstMQTT` are fixed.
