### ISSUE TITLE
Build TensorFlow Lite prebuilt libs with CMake or Bazel

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3399]
We've built [TFLite libs](https://github.com/nnstreamer/nnstreamer-android-resource/tree/master/external) (for android) with Makefile (ndkbuild). 
TensorFlow declared to deprecate it at the end of this July, we need to build those with CMake or Bazel

REF: https://github.com/tensorflow/tensorflow/commit/474264956ad829611e3f52531bc0458f3a769df7

**Comment by anyj0527** [comment]
In tensorflow/lite/CMakeLists.txt:

- Add CMake function bundle_static_library from https://cristianadam.eu/20190501/bundling-together-static-libraries-with-cmake 
- Add line `bundle_static_library(tensorflow-lite tensorflow-lite-bundled)`

This approach works on v2.6.0-rc1

**Comment by myungjoo** [comment]
You may prepare 2.5 or 2.6+ with a sandbox branch in tizen.org/tensorflow2 .
Then, you can switch it to tizen after 6.5 M2 release.

**Comment by anyj0527** [comment]
2.6.0: https://git.tizen.org/cgit/platform/upstream/tensorflow2/log/?h=sandbox/anyj0527/v2.6.0
2.7.0: https://git.tizen.org/cgit/platform/upstream/tensorflow2/log/?h=sandbox/anyj0527/v2.7.0
