### ISSUE TITLE
Flexible tensor should support static format

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#3405]
Flexible tensors don't support the static format. (only flexible or sparse).
If I just want to add a header to the static tensors, the format of the flexible tensor should be static.

As-is
- caps: other/tensors, format=flexible
- format in meta: flexible or sparse

To-be
- caps: other/tensors, format=flexible
- format in meta: static, flexible or sparse

**Comment by jaeyun-jung** [comment]
`.. media stream (static) ! tensor_converter ! other/tensors,format=flexible ! nnstreamer element ..`

tensor-converter should append header and its meta is static.

Now we have format info in each GstTensorInfo and if one of tensor is flexible, it is supposed flex-tensor caps. However, to support this, another format variable in GstTensorsConfig is required for caps negotiation.

I will check this after removing GstTensorConfig struct (#3389).

**Comment by jaeyun-jung** [comment]
Keep current implementation (format in tensor-info struct)
The case of mixed format : tensor_mux may receive buffers (static + flexible)

**Comment by jaeyun-jung** [comment]
#3418  move tensor format into tensors-config.
tensor format from caps, so it is unnecessary to set the format in tensor-info struct.

**Comment by myungjoo** [comment]
Is this issue still valid?

**Comment by jaeyun-jung** [comment]
After merging https://github.com/nnstreamer/nnstreamer/pull/3418 and https://github.com/nnstreamer/api/pull/76, I will close this.
