### ISSUE TITLE
[TIZEN-946] Release preparation for Tizen 6.5 M2 

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#3406]
## Release Items
 * Jira: https://code.sec.samsung.net/jira/browse/TIZEN-946

#### 1. Remote query (client / sever)
 * Owner: @gichan-jang 

#### 3. Compressed stream support
 * Owner: @anyj0527

#### 5. APIs for such usages
 * Description (JIRA): This may include heartbeats and persistent pipelines
 * Comment:
    * @wooksong: We have dropped this item (the existing ML APIs are enough to cover Edge-AI features).

#### 6. (Optional/Stretch) Pub/sub support and other transport service support
 * Owner: @wooksong
 * Description (JIRA): (If it is architecturally sound and BeyonD agrees) support smartthings natively or support zeroMQ natively
  * Comment:
    * @wooksong: We have supported pub/sub via MQTT. How about making this item mandatory?

#### 1. Auto Test (TCT / Script type)
  * TCTs for pub/sub have been added. If the release items are fixed, we need to investigate more TCTs to be implemented.
#### 2. Sample App Test
  * Need to discuss with @jaeyun-jung and @again4you 

#### 1. TCT for public APIs
  * Related to **Sample App Test** above. We would not export public APIs for Edge-AI but we can make TCTs using public ML APIs.
#### 2. Sample App Test
  * Need to discuss with @jaeyun-jung and @again4you

**Comment by wooksong** [comment]
@myungjoo We need to revise https://code.sec.samsung.net/jira/browse/TIZEN-946. PTAL.

**Comment by myungjoo** [comment]
3: done (gst-gz) by @anyj0527

**Comment by myungjoo** [comment]
> @myungjoo We need to revise https://code.sec.samsung.net/jira/browse/TIZEN-946. PTAL.

From Tizen-946:

1. Remote query (client / server): actively WIP

2. Data Serialization support ()

3. Compressed stream support: done

4. (Optional/Stretch) Remote query with robustness support
- This may include heartbeats and persistent pipelines

    --> If we support MQTT for finding server with capability, and let it "reconnect if fails", then, it's done.
    --> You may revise this as "Remote pub/sub streaming with robustness support"

5. APIs for such usages

    --> (If Edge-AI features can be supported by conventional API), we will not add APIs and ACR.
    --> However, we need to update 1. tutorial, 2. test cases (sample apps), 3. documentation

6. (Optional/Stretch) Pub/sub support and other transport service support

- (If it is architecturally sound and BeyonD agrees) support smartthings natively
- or support zeroMQ natively.

    --> Don't make it "mandatory". Regard this as a proudly completed "stretch" goal.

**Comment by myungjoo** [comment]
Released
