### ISSUE TITLE
[Query] Need a Command buffer(Header buffer?) 

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#3410]
This is sub-topic of https://github.com/nnstreamer/nnstreamer/issues/2802.

When we receive data using sockets, we don't know the number of memory in a buffer.
Flexible tensor contains only tensor info.
So before sending and receiving data, we have to send information using a command buffer (header buffers?).
A command buffer contains at least.. 
```
struct CommandBuf {
  guint num_mem;
  guint mem_size[16];
  ...
}
```

streams
```
command_buf | tensors | tensors | tensors | ... | buf info is changed | command_buf | tensors | tensors | ...
```

**Comment by gichan-jang** [comment]
As a result of the short meeting, we decided to send command buffers.
This is the buffer stream between the server and the client.
Command buffers are sent only once at the beginning and the end.

```
command_buf (START) | ... tensors { static, flexible } ... | command_buf (END)
```

Query state
```
enum query_state
{
  _QUERY_START = 0,
  _QUERY_END,
  _QUERY_ERROR,
  _QUERY_END,
} query_state;
```

Command buf
```
struct CommandBuf {
  query_state state;
  GstTensorsInfo info;
}
```
\* The name of the tensor is assumed to be null because it is only used in tensor_filter. tensor_filter is considered for use only by the server.

**Comment by kparichay** [comment]
As discussed offline, the command buffers can be sent during the negotiation phase if the connection between the client and server is established.

**Comment by gichan-jang** [comment]
the tensor query is implemented to use command buffers. Close this issue.

```
typedef enum
{
  _TENSOR_QUERY_CMD_REQUEST_INFO = 0,
  _TENSOR_QUERY_CMD_RESPOND_APPROVE = 1,
  _TENSOR_QUERY_CMD_RESPOND_DENY = 2,
  _TENSOR_QUERY_CMD_TRANSFER_START = 3,
  _TENSOR_QUERY_CMD_TRANSFER_DATA = 4,
  _TENSOR_QUERY_CMD_TRANSFER_END = 5,
  _TENSOR_QUERY_CMD_END
} TensorQueryCommand;

typedef struct
{
  TensorQueryCommand cmd;
  TensorQueryProtocol protocol;
  union
  {
    TensorQueryDataInfo data_info; /** _TENSOR_QUERY_CMD_TRANSFER_START */
    TensorQueryData data;          /** _TENSOR_QUERY_CMD_TRANSFER_DATA */
  };
} TensorQueryCommandData;
```
