### ISSUE TITLE
[Query] GstMeta for query info

### ISSUE THREAD

**Issue by gichan-jang** [nnstreamer/nnstreamer#3414]
This is sub-topic of #2802 .

Initially we tried to load query info on flexible tensors.
However, this requires additional memory copy.
It looks better to send information about clients using a GstMeta.

To do that,
 1. Send query information using GstMeta.
 2. Check if the elements copy GstMeta from in-buf to out-buf. or Modify if necessary.
 3. Inspect the pipeline to see if there are restricted? elements. (such as tensor_merge, tensor_mux or tensor_split ans so on)

QueryInfo (Not decided,, )
```
struct GstTensorQueryInfo {
  gchar *ip;
  gint port;
  gchar *topic; // needed later.
}
```

**Comment by myungjoo** [comment]
Do quick prototyping with TCP/IP and then please move on to MQTT+HLS(or other) hybrid protocol. Please try to make a fast prototyping cycle (design->implement->test->desian->...) as we need to validate the protocol and common data structure.

**Comment by gichan-jang** [comment]
Query meta information to distinguish clients has been changed from host to uuid.
Related PR: https://github.com/nnstreamer/nnstreamer/pull/3448
```
typedef struct
{
  GstMeta meta;

  gchar *client_id;
} GstMetaQuery;
```

**Comment by gichan-jang** [comment]
Support meta copy?

- [ ] tensor_converter
- [ ] tensor_decoder
- [ ] tensor_filter
- [ ] tensor_demux
- [ ] tensor_mux
- [ ] tensor_aggregator
- [ ] tensor_crop
- [ ] tensor_if
- [ ] tensor_merge
- [ ] tensor_rate
- [ ] tensor_repo
- [ ] tensor_sparse
- [ ] tensor_split
- [ ] tensor_transform

**Comment by myungjoo** [comment]
Questions:
1. How other non-nnstreamer (general gstreamer) elements handle GstMetaQuery? (tee, join, appsink, ...?)
2. Which src-pad is used for mux and merge?
3. Can we declare "client_id" as uint32 or uint64 and let the "common data structure" handle the detail?

**Comment by gichan-jang** [comment]
> Questions:
> 1. How other non-nnstreamer (general gstreamer) elements handle GstMetaQuery? (tee, join, appsink, ...?)
 -  If the element copy the meta, there is no problem with handling the GstMetaQuery.
 - I tested with tee, queue, videoconvert and videoscale, they handle meta info well.
> 2. Which src-pad is used for mux and merge?
 - collect pad is used for src-pad.
> 3. Can we declare "client_id" as uint32 or uint64 and let the "common data structure" handle the detail?
 - Ok, I will change client ID as uint32.

**Comment by myungjoo** [comment]
> > 2. Which src-pad is used for mux and merge?
> collect pad is used for src-pad.

``` appsrc name=input1 m.0 appsrc name=input2 m.1 tensor_merge name=m ! appsink name=output ```
If input1 and input2 have different GstMetaQuery.client_id, what's GstMetaQuery.client_id of output?

**Comment by gichan-jang** [comment]
> > > 1. Which src-pad is used for mux and merge?
> > >    collect pad is used for src-pad.
> 
> `appsrc name=input1 m.0 appsrc name=input2 m.1 tensor_merge name=m ! appsink name=output`
> If input1 and input2 have different GstMetaQuery.client_id, what's GstMetaQuery.client_id of output?

Currently, only the meta information of the input1 is copied. 
Need to discuss about how to handle buffers received from multiple clients.
For example, 
 - Refresh mode: copy the metadata of the largest number of clients.
 - Base pad: copy the metadata of the base pad.
 - Slowest: ??

**Comment by myungjoo** [comment]
The first release may use a single input (input1).
For later release (e.g., nnstreamer 2.1.1+), we need some additional policies mechanisms here (ask @jaeyun-jung and @again4you . I had discussions with them a while ago for this matter)

**Comment by myungjoo** [comment]
@gichan-jang Please close this if everything is done.

**Comment by myungjoo** [comment]
@gichan-jang PTAL.

**Comment by gichan-jang** [comment]
I will add additional policies.

MUX
 1) Refresh: latest buffers.
 2) Others:
    - pad is specified: Use the buffer from specified pad.
    - pad is not specified: Use first pad buffer.
 
MERGE
  - pad is specified: Use the buffer from specified pad.
  - pad is not specified: Use first pad buffer.

**Comment by gichan-jang** [comment]
https://github.com/nnstreamer/nnstreamer/pull/3574 is merged. Close this issue.
