### ISSUE TITLE
[EPIC][VoC] Rewrite example apps using tensor-decoder for post-processors

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3474]
Old example apps do not use tensor-decoder post-processors, but write hard-coded logic for post-processing.

Rewrite and update such old examples to use tensor-decoder for post-processing.

**Comment by gichan-jang** [comment]
Object detection and pose estimation examples have been modified to use tensor decoder.
The Tizen app is already using a decoder.

https://github.com/nnstreamer/nnstreamer-example/pull/278
https://github.com/nnstreamer/nnstreamer-example/pull/270

**Comment by myungjoo** [comment]
Great! If you have fixed all of such examples, please close this.

**Comment by gichan-jang** [comment]
Done. Close this issue.
