### ISSUE TITLE
would you give me some guide to support other device  AI hardware accelerator like(tensorrt rknn cann)

### ISSUE THREAD

**Issue by TUT-jiayou** [nnstreamer/nnstreamer#3486]
Hi,all

* If you can provide some documentation help, I think it can speed up our process
* thanks for your time

**Comment by myungjoo** [comment]
- TensorRT is already included. You just need to enable it via build options. (and install TensorRT package properly before building nnstreamer)
- If you want to write a "sub-plugin" for new AI hardware accelerator, other subplugins might be the best references: (tensorrt) https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc In this code, the class ```tensorrt_subplugin``` extending ```tensor_filter_subplugin``` is the one you need to look at. You are supposed to create a concrete class of ```tensor_filter_subplugin``` and register it with init function (```_init_filter_tensorrt``` and ```_fini_filter_tensorrt``` in that example).
- We do not have a proper documentation for tensor-filter subplugin (for AI HW accelerators and Nerual Network Frameworks). We thought that users normally won't write a tensor-filter subplugin and only "experienced" nnstreamer developers will try this. You have just proven it wrong :) Thanks for the input.

For next year developmental plan, we have the following agenda:
- User-friendliness
    - including better documentation (tensor-filter doc should be included as you've proven), better error messages, pipeline wysiwyg editor, ...
- Edge-AI (home IoT) capability.

**Comment by myungjoo** [comment]
Anyway, could you please let us know what is the target hardware?

**Comment by TUT-jiayou** [comment]
HI,

* I think this project is very useful for myself. I want to add the supporte for rockchip(rk3399 pro) , huawei( atlas 200dk) and Xilinx. I wonder if you have any plans to support these devices

 thanks for your time.

**Comment by myungjoo** [comment]
> HI,
> 
> * I think this project is very useful for myself. I want to add the supporte for rockchip(rk3399 pro) , huawei( atlas 200dk) and Xilinx. I wonder if you have any plans to support these devices
> 
> thanks for your time.

I have no plans for those devices. But I welcome contributions of supporting those devices.

**Comment by junnengzhao** [comment]
I am also want to integrate [openncc](www.openncc.com) to NNStreamer, could you show me more how to write a subplugin?

**Comment by myungjoo** [comment]
> I am also want to integrate [openncc](www.openncc.com) to NNStreamer, could you show me more how to write a subplugin?

as in  https://github.com/nnstreamer/nnstreamer/issues/3486#issuecomment-915163227 , a tensor-filter subplugin code would be the example for you: https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_filter/tensor_filter_tensorrt.cc and other files in the same directory.

Steps (if you've decided to write in C++)
1. Define a subplugin class inheriting ```tensor_filter_subplugin```.
   e.g., ```class yourhardware_subplugin final : public tensor_filter_subplugin ...```
2. Let it exist as a shared library, installed in filter subplugin directory (refer to meson.build in the directory above)
3. Define init/exit functions for the subpluigin class. For example:
```
void _init_filter_yourhardware (void) __attribute__((constructor));
void _fini_filter_yourhardware (void) __attribute__((destructor));
```
4. Let those init/exit function call the static init/exit functions of the subplugin.
e.g.,
```
/** @brief Initialize this object for tensor_filter subplugin runtime register */
void
_init_filter_yourhardware (void)
{
  yourhardware_subplugin::init_filter_yourhardware ();
}

/** @brief Destruct the subplugin */
void
_fini_filter_yourhardware (void)
{
  yourhardware_subplugin::fini_filter_yourhardware ();
}
```
5. The static init/exit functions of the class are supposed to use NNStreamer Filter Plugin APIs to register itself:
```
/**
 * @brief Register the yourhardware_subplugin object.
 */
void
yourhardware_subplugin::init_filter_yourhardware (void)
{
  registeredRepresentation
      = tensor_filter_subplugin::register_subplugin<yourhardware_subplugin> ();
}

/**
 * @brief Unregister the yourhardware_subplugin object.
 */
void
yourhardware_subplugin::fini_filter_yourhardware (void)
{
  assert (registeredRepresentation != nullptr);
  tensor_filter_subplugin::unregister_subplugin (registeredRepresentation);
}
```

**Comment by myungjoo** [comment]
with no further follow-ups, I assume this is resolved. Please reopen if there are things to be discussed further.
