### ISSUE TITLE
[Suggestion] Robustness support of MQTT-Hybrid 

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#3508]
To supports the Robustness of MQTT-Hybrid, we need to define the naming rule of the MQTT topic and its scenario.

## Basic Ideas
* MQTT Broker can maintain List of servers and their latest information such as status, algorithm, and so on.
  - Client can subscribe its updated information
  - Client can requests servers' information explicitly.

* Client can subscribe multiple topics of the same domain from various devices.
  - Use 'wildcards' of MQTT filter
    - \+ : single level wildcard that matches any name
    - \# : multi level wildcard used at the end of the topic

## Topic Rule
* Rule: **edge/[type]/[device_name]/[main_operation]/[option]**
  * edge: prefix (fixed)
  * type: 'inference' for server, client / 'sensor' for small sensor device 
  * device_name: Device Name such as 'galaxy_00' or 'bespoke_01'
  * main_operation: Main Operation such as 'object_detection', 'speed
  * option: optional topic for main operation (e.g. mobilev3)

* Examples
  * edge/inference/galaxy_00/object_detection/mobilev3 (for Server / Client)
  * edge/inference/tv_00/object_detection/yolo (for Server / Client)
  * edge/inference/bespoke_00/object_detection (for Server / Client)
  * edge/sensor/aircleaner_01/temperature (for Sensor)

### 1) Servers connect to Brokers
![robust_mqtt_00](https://user-images.githubusercontent.com/433435/135012310-4210fa46-9185-4017-845f-d51db8581f64.JPG)
  - edge/inference/galaxy_00/object_detection/mobilev3
  - edge/inference/TV_00/object_detection/yolo

### 2) Client connect to Broker
![robust_mqtt_01](https://user-images.githubusercontent.com/433435/135012612-f8e7dd73-844e-4679-8643-7161fbcabf4e.JPG)
  - Subscribe 'edge/inference/+/object_detection/#' topic
    - \+ : single level wildcard that matches any name
    - \# : multi level wildcard used at the end of the topic

### 3) Client gets server's Information
![robust_mqtt_02](https://user-images.githubusercontent.com/433435/135012747-3e66c5e4-6853-4ce1-a34a-91fb54b174c3.JPG)
* List of server nodes, and their algorithm, status or performance

### 4) Choose the suitable one
![robust_mqtt_03](https://user-images.githubusercontent.com/433435/135012910-0a2406b3-c2fb-4a83-b51e-54e2c7f70d4e.JPG)

### 5) New server is connected & get its info via callback mechanism
![robust_mqtt_04](https://user-images.githubusercontent.com/433435/135012950-8f123c4a-85c3-4d5e-b00e-a658811f6590.JPG)

### 6) Used server is unavailable
![robust_mqtt_05](https://user-images.githubusercontent.com/433435/135013072-7c73cc8a-2eb4-4712-a11c-05d8d4e0794c.JPG)

### 7) Choose the next one
![robust_mqtt_06](https://user-images.githubusercontent.com/433435/135013088-0f8f8db3-cb2d-4844-aa94-b7b4114f78b0.JPG)

**Comment by gichan-jang** [comment]
Close this issue via #3510
