### ISSUE TITLE
Can various media stream can be muxed as tensor?

### ISSUE THREAD

**Issue by joan-juyeon** [nnstreamer/nnstreamer#3523]
Hello all

Could you give ma an advice if there is a way to mux any kind of source(such as jpeg encoded video) with other/tensors?
tensor_converter helps us convert some limited media stream to tensor but i am not sure if it is the elements that can handle this.
i'm interesting on efficient way to deliver smaller but complete data to the other network end.

```
src:0 other/tensor             --┐
src:1 other/tensor             --┼-->tensor_mux -->...
src:2 image/jpeg ->*convert    --┘ 
```

thank you.

**Comment by myungjoo** [comment]
Yes, you can if you convert image/jpeg into other/tensor. 
This depends on the characteristics of the image/jpeg stream. Is it a stream or a static image?


Refer: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-jpegdec.html

**Comment by joan-juyeon** [comment]
I had tested it with static image using jpegenc and tensor_converter, but met error like below
```
gst-launch-1.0 -v filesrc location=/tmp/orange.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=100,height=100 ! videoconvert ! video/x-raw,format=I420 ! jpegenc ! tensor_converter ! filesink location=2.raw
WARNING: erroneous pipeline: could not link jpegenc0 to tensorconverter0
```

**Comment by myungjoo** [comment]
Why did you add ```jpegenc ! tensor_converter ```?

**Comment by joan-juyeon** [comment]
jpegenc is used for smaller data publish
and tensor_converter is used to tensor_mux with other tensors 
it is going to be an input tensors for an inference model.

```
src:0                        --┐
src:1                        --┼-->mux --> network sink
src:2(...->jpegenc ->tensor) --┘

                       ┌-- tensor 0                  --┐
network src -->demux --┼-- tensor 1                  --┼-->mux -->tensor_filter
                       └-- jpegdec...-> -->tensor 2  --┘
```

**Comment by myungjoo** [comment]
tensor_converter converts video/x-raw, audio/x-raw, text/x-raw (the raw formats) and binary octet.
It does not accept jpeg unless you write a jpeg tensor-converter subplugin (ref: https://github.com/nnstreamer/nnstreamer/tree/main/ext/nnstreamer/tensor_converter )

It appears that you are solving a wrong problem, but if you really need to mux two tensor streams and a jpeg stream into a tensors stream, convert jpg --> binary octct --> tensor.

There will be multiple interpretation for jpg-->tensor, so you need to define one. (someone will think the valid conversion of jpeg->tensor is a decoded (video/x-raw) tensor for a given jpeg and you think the opposite. and both appears valid at this point.)

**Comment by semun-lee** [comment]
Our purpose is transferring input data of a model to a remote device (edge) from a client. When a model requires multiple tensors as the input, I think we need to transfer multiple tensors synchronously. So, we considered tensor_mux to create other/tensors data to transfer via a proper protocol.

For video/image input, when we transfer a raw data, it consumes too high bandwidth, so we need to encode the input using jpeg or vp8 codecs.

This is the background of the problem.

1. What would be the best practice for transferring multiple input tensors for a model synchronously?
2. Could tensor_mux be used for this purpose? Then, how can we convert an arbitrary data to a valid other/tensor type using tensor_converter?
