### ISSUE TITLE
Converter subplugin request: application/octet to flex-tensor

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3527]
With variable size stream of application/octet, convert the stream to ```other/tensors,format=flexible,num_tensors=1``` with 1:1 (1 input frame == 1 output frame) and rank = 1.

This will satisfy #3523.

**Comment by jaeyun-jung** [comment]
Now converter uses the properties - type and dim to convert data format
1. flex-tensor to static tensor
2. octet to tensor

If input is octet stream without prop values, I think just setting a format 'flexible' and updating dimension with its size may solve this.

**Comment by jaeyun-jung** [comment]
PR #3547 handle single memory to multi tensors in tensor-demux

**Comment by jaeyun-jung** [comment]
GC added new PR (#3556) to convert tensor to octet stream w/decoder-subplugin.

**Comment by jaeyun-jung** [comment]
Now new decoder sub-plugin to convert tensor to octet-stream is added. Close this PR.
