### ISSUE TITLE
New element to serialize multiple tensors

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/nnstreamer#3540]
With flatbuf/protobuf, we can send/receive formatted tensors.
However, if user does not use these libraries on the device, we have no method to pack/unpack the formatted tensor.
(e.g. using gdppay/depay elements in pipeline description, gdpdepay cannot generates gst-buffer with multiple memory chunks.)

[suggestion]
new element to pack/unpack multi tensors as byte array.
- element name: tensor_serialize,deserialize / tensor_pack,unpack / ...
- define new mimetype (other/tensors,format=serialize) or handle output as application/octet-stream

```
.. ! tensor_mux ! tensor_serialize ! gdppay ! tcpsink
tcpsrc ! gdpdepay ! tensor_deserialize ! tensor_demux ! ..
```

We can also add new property later (compress=[none,gzip, ..] to reduce data size.

**Comment by gichan-jang** [comment]
How do buffers send information about each frame?
Attaching meta information like a flexible tensor?

**Comment by jaeyun-jung** [comment]
Define new struct and append header in gst-buffer
```
e.g, serialization info struct
tyepdef struct
{
  guint version;
  GstTensorsConfig config;
  gsize mem_size[16];
  compress_e compress; (default none)
  ...
} tensor_serialize_info_s;

GstBuffer *buffer = gst_buffer_new_allocate (sizeof (tensor_serialize_info_s));
// update serialize info
// append tensors (gst-buffer)
buffer = gst_buffer_append (buffer, buffer_tensors);
// push buffer into src-pad
gst_pad_push (src, buffer);
```

**Comment by myungjoo** [comment]
Suggestion (as told 1 hour ago):
keep the current tensors GSTCAP. Let tensor-* elements detect "serialized tensors" and separate such tensors transparently, which means multi-tensor-single-buf is now valid as well, starting with tensor-demux. Ultimately, all tensor-* elements will recognize multi-tensor-single-buf (with the exactly same GSTCAP with conventional multi-tensor-multi-buf) and turn them into multi-tensor-multi-buf automatically and internally.

**Comment by jaeyun-jung** [comment]
@myungjoo 
PR #3546 util function to separate single memory to multi tensors.

**Comment by jaeyun-jung** [comment]
Added util function to handle multi tensors in gst-buffer. We need update each nnstreamer element with this function now.
Close this issue.
