### ISSUE TITLE
Question: rebuilding nnstreamer from source w/ pytorch-1.10.0

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3591]
# Issue Description
Hi dev.
Now I'm trying to re-build nnstreamer from source with libtorch-1.10.0.
But I met errors while ninja -C build as below.

```
/home/workspace/nnstreamer/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc: In member function 'int TorchCore::invoke(const GstTensorMemory*, GstTensorMemory*)':
/home/workspace/nnstreamer/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc:486:27: error: 'struct c10::IValue' has no member named 'isGenericList'; did you mean 'isGenericDict'?
   } else if (output_value.isGenericList ()) {
                           ^~~~~~~~~~~~~
                           isGenericDict
/home/workspace/nnstreamer/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc:487:66: error: 'struct c10::IValue' has no member named 'toGenericListRef'; did you mean 'toGenericDict'?
     c10::ArrayRef<torch::jit::IValue> output_list = output_value.toGenericListRef ();
                                                                  ^~~~~~~~~~~~~~~~
                                                                  toGenericDict
cc1plus: all warnings being treated as errors
[199/210] Compiling C++ object 'tests/nnstreamer_filter_extensions_common/b8951fb@@unittest_tizen_pytorch@exe/gtest-all.cc.o'.
ninja: build stopped: subcommand failed.
```

and there have a lots of warnning about -Werror=redundant-decls & -Werror=unused-parameter too.
If you need information about those errors, I will add.

I think It occurs from my mistake because I'm not familiar with compile process.

Anyway I hope It is not a question that is not worth answering.

Expected Result
============
complete re-build nnstreamer from source w/ pytorch 1.10.0

How to Reproduce
===============
1. use Dockerfile as below

```
FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y software-properties-common
RUN apt-add-repository ppa:nnstreamer
RUN apt update

RUN apt install -y git vim wget

RUN apt install -y \
    meson \
    ninja-build \
    build-essential \
    pkg-config \
    cmake \
    libglib2.0-dev \
    libgstreamer1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-doc \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    gstreamer1.0-alsa \
    gstreamer1.0-gl \
    gstreamer1.0-gtk3 \
    gstreamer1.0-qt5 \
    gstreamer1.0-pulseaudio \
    libgstreamer-plugins-base1.0-dev \
    libgtest-dev

RUN mkdir /home/workspace
ENV GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
WORKDIR /home/workspace
```

2. make container with this image.
2. In container, wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.10.0%2Bcpu.zip
3. unzip at directory that you want, in my case I unzipped in /home/workspace
4. git clone nnstreamer source from github
5. make pkg-config file of pytorch as below into directory /usr/lib/pkgconfig

```
prefix=/home/workspace/libtorch
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
sharedlibdir=${prefix}/share

Name: pytorch
Description: pytorch static library
Version: 1.10.0
Libs: -L${libdir} -L${sharedlibdir} -lc10 -ltorch -ltorch_cpu
Cflags: -I${includedir}
```
6. Run meson build --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib --bindir=/usr/bin --includedir=/usr/include
7. Run ninja -C build

If there have any reference, tell me I will try more

regards.

**Comment by myungjoo** [comment]
Looks like PyTorch has renamed it: https://github.com/pytorch/pytorch/commit/7e3c438913c2ec1fe75a32b3c46591dc346d5fcc

You can add a commit w/ ```#ifdef``` and ```#endif```, which uses different names for different pytorch versions.

**Comment by myungjoo** [comment]
Actually, if PyTorch > 1.2.0, tensor_filter_pytorch.cc uses ```isList``` instead of ``isGenericList``` already.
Thus, if you have that error, it means that ```/ext/nnstreamer/tensor_filter/meson.build```'s LINE 287 is not working.

**Comment by myungjoo** [comment]
If is possible that meson thinks that ``` "1.10.0" < "1.2.0" ``` because it deals them as strings :)

**Comment by byungs2** [comment]
Your comment is right.
After I edit pytorch.pc version string as 1.9.0 or others that lower than 1.10.0, then struct naming different issue has been resolved.
But at this time I have warning of -Werror=redundant-decls redeclaration.
And I realized I've downloaded shared library of libtorch.

Even I changed to static type libtorch library, redundant warning still remain.
I will try more and then report it in this issue.

Thanks for your help

**Comment by myungjoo** [comment]
For version compare,
```
  if pytorch_support_deps[0].version().version_compare('>=1.2.0')
```
might work.

**Comment by byungs2** [comment]
My problem has been resolved all. I built nnstreamer w/ libtorch 1.10.0 completly.
When I install libtorch 1.10.0 at my personal project directory, there keep have redundant warning.
But after I install it at /usr directory, then all warning resolved.
I don't know exactly why, It might be some env_variable problem.

Thanks for all your help.

**Comment by myungjoo** [comment]
> When I install libtorch 1.10.0 at my personal project directory, there keep have redundant warning.

If you have installed libtorch at your personal directory, gcc might have **not** referred header files and shared libraries appropriately.
