### ISSUE TITLE
ML-API / ml_single_set_property (single, name, value);

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3598]
```ml_single_set_property``` requires ```value``` parameter to be non-NULL.

Don't we have cases where ```value``` is actually NULL? (e.g., set "custom = (NULL)")

PTAL: @jaeyun-jung  @again4you @gichan-jang @anyj0527

**Comment by gichan-jang** [comment]
How about add `ml_single_clear_property`?

**Comment by jaeyun-jung** [comment]
Yes, it would be necessary. Before changing a condition - validating param, we should update tizen-tct to prevent tc error.

**Comment by gichan-jang** [comment]
Ok, after changing the tizen-tct first, I will change the condition.

**Comment by gichan-jang** [comment]
https://github.com/nnstreamer/api/pull/117 is merged. Close this issue.
