### ISSUE TITLE
ml_single_open returns Streams Pipe Error

### ISSUE THREAD

**Issue by almirfilho77** [nnstreamer/nnstreamer#3603]
# Issue Description

I get Streams Pipe Error (error code -86) when I try to load the model [yamnet/classification/tflite](https://tfhub.dev/google/lite-model/yamnet/classification/tflite/1) using the following function:

`int status = ml_single_open(&single, TEST_MODEL_PATH, NULL, NULL, ML_NNFW_TYPE_TENSORFLOW_LITE, ML_NNFW_HW_ANY);`

When I use dlog I get the following messages:

I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
I/nnstreamer( 1031): Found tensorflow2-lite for tensorflow-lite.
E/nnstreamer( 1031): Failed to construct interpreter
E/nnstreamer( 1031): Failed to load model

Further Information
===============

When I use the same function to load [the yamnet/tflite model](https://tfhub.dev/google/lite-model/yamnet/tflite/1) or [the mobilenet_v1_1.0_224_quant model](https://github.com/nnstreamer/nnstreamer-example/tree/main/Tizen.native/SingleSample/res) it works fine.

* I'm working on Tizen 6.5
* Code is in C++ 
* nnstreamer 2.0 package
* tensorflow2-lite 2.3 package

EDIT:

I tried to use tensorflow APIs directly as follows:

```
std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(TEST_MODEL);

if (!model)
{
    _ERR("Failed to mmap model");
}

tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model.get(), resolver)(&interpreter);

if (!interpreter)
{
    _ERR("Failed to create interpreter");
}
```

With dlog I can see the message "Failed to create interpreter", also only for the problematic model.

**Comment by anyj0527** [comment]
@almirfilho77  The TFLite version may be the problem. The tool Netron says tflite runtime version for the problematic model is 2.6.0.

Could you try v2.6.0 https://git.tizen.org/cgit/platform/upstream/tensorflow2/log/?h=sandbox/anyj0527/v2.6.0
or
v2.7.0 https://git.tizen.org/cgit/platform/upstream/tensorflow2/log/?h=sandbox/anyj0527/v2.7.0
?

**Comment by almirfilho77** [comment]
@anyj0527 first of all thank you for your answer! 

Unfortunately I tried to build both versions with GBS but I get the a lot of the following warning:

```
[   26s] [  8%] Building CXX object _deps/ruy-build/CMakeFiles/ruy.dir/__/__/ruy/ruy/pack_avx.cc.o
[   26s] [  8%] Building CXX object _deps/abseil-cpp-build/absl/base/CMakeFiles/absl_base.dir/internal/thread_identity.cc.o
[   27s] cc1plus: warning: switch '-mcpu=cortex-a53' conflicts with '-march=armv7-a' switch
[   27s] cc1plus: warning: switch '-mcpu=cortex-a53' conflicts with '-march=armv7-a' switch
[   27s] cc1plus: all warnings being treated as errors
[   27s] _deps/flatbuffers-build/CMakeFiles/flatbuffers.dir/build.make:88: recipe for target '_deps/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o' failed
[   27s] gmake[2]: *** [_deps/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o] Error 1
```

I know it says "warning", but apparently the compiler is treating them as errors, so I tried to unset "-Werror" flag everywhere inside the repository, but I guess I am missing something (I'm not very familiar with building code specifics). Could you give me some advice on this?

PS.: sorry if I should had opened another issue or topic anywhere else, if that is the case please tell me so I can do it right.

Thank you!

**Comment by myungjoo** [comment]
What are you building and how are you building?

> cc1plus: warning: switch '-mcpu=cortex-a53' conflicts with '-march=armv7-a' switch

It appears that you are requesting two different and incompatible instruction sets. Technically "cortex a53" may execute "armv7-a" instructions. However, when you say "-mcpu=cortex-a53 -march=armv70a", compilers will understand that you want a arm32 binary that uses arm64 instructions.

**Comment by anyj0527** [comment]
@almirfilho77,
The following gbs build cmd would make valid rpm packages for arm64:
```
$ gbs build -A aarch64 (--clean --clean-repos)
```

Please check!

**Comment by almirfilho77** [comment]
@myungjoo ,

I'm building a test application on armv7l architecture board using GBS.
According to [this reference](https://developer.arm.com/ip-products/processors/cortex-a/cortex-a53) cortex-a53 processors should be fully compatible with 32-bits architectures, thus the warnings (not direct errors).

**Comment by almirfilho77** [comment]
@anyj0527 ,

Unfortunately, even if I could build it for 64-bits architecture it would not be useful to me, I'm sorry.

**Comment by myungjoo** [comment]
> @myungjoo ,
> 
> I'm building a test application on armv7l architecture board using GBS. According to [this reference](https://developer.arm.com/ip-products/processors/cortex-a/cortex-a53) cortex-a53 processors should be fully compatible with 32-bits architectures, thus the warnings (not direct errors). Maybe if I could disable -Werror flag it would finish the build, but I can't seem to find the correct point to do this.

cortex-a53 can run aarch32. but general arm32 systems are not compatible with cortex-a53's features. So you definitely shouldn't have -mcpu=cortex-a53 in your option.
check your gbs configuration and .spec file.

**Comment by almirfilho77** [comment]
@myungjoo @anyj0527 , first of all thank you very much for your support so far. I would like to share my progress on this matter with you: I was able to build TensorFlow 2.7 for Tizen by doing two things, basically:

- taking the "-mcpu=cortex-a53" flag out of the .conf file to solve the first issue (`[   27s] cc1plus: warning: switch '-mcpu=cortex-a53' conflicts with '-march=armv7-a' switch`)
- adding the "-fno-lto" to disable link time optimization and get rid of an error with the following signature: "this builtin is not supported for this target".

As a result, when I run the same piece of code that is implemented in "tensor_filter_tensorflow_lite.cc" to load my model it seems to work (at least I don't get the "Failed to construct interpreter" error):

```
std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(TEST_MODEL);

    if(!model){
        _ERR("Failed to mmap model");
        return;
    }

    tflite::ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);
    if (!interpreter)
    {
        _ERR("Failed to construct interpreter");
        return;
    }
```

But when I run "ml_single_open" I still get "Failed to construct interpreter" error.

PS.: I builded nnstreamer with TensorFlow 2.7.

**Comment by anyj0527** [comment]
@almirfilho77
Did you check the ml-api package `https://github.com/nnstreamer/api` is being built with nnstreamer with tf 2.7 ? I just check locally that the yamnet_classification.tflite model is opened well with the single api and passed a simple test:
```
  ml_single_h single;
  ml_tensors_info_h in_info, out_info;
  ml_tensors_data_h input, output;
  ml_tensor_dimension indim, outdim;
  int status;

  const gchar *root_path = g_getenv ("NNSTREAMER_SOURCE_ROOT_PATH");
  gchar *test_model;

  test_model = ".../yamnet_classification.tflite", NULL);
  ASSERT_TRUE (g_file_test (test_model, G_FILE_TEST_EXISTS));

  status = ml_single_open (&single, test_model, NULL, NULL,
      ML_NNFW_TYPE_TENSORFLOW_LITE, ML_NNFW_HW_ANY);
  EXPECT_EQ (status, ML_ERROR_NONE);

  status = ml_single_get_input_info (single, &in_info);
  ml_tensors_info_get_tensor_dimension (in_info, 0U, indim);
  EXPECT_EQ (indim[0], 15600);
  EXPECT_EQ (status, ML_ERROR_NONE);

  status = ml_single_get_output_info (single, &out_info);
  ml_tensors_info_get_tensor_dimension (out_info, 0U, outdim);
  EXPECT_EQ (outdim[0], 521);
  EXPECT_EQ (outdim[1], 1);
  EXPECT_EQ (status, ML_ERROR_NONE);

  input = output = NULL;

  /* generate dummy data */
  status = ml_tensors_data_create (in_info, &input);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_TRUE (input != NULL);

  status = ml_single_invoke (single, input, &output);
  EXPECT_EQ (status, ML_ERROR_NONE);
  EXPECT_TRUE (output != NULL);

  status = ml_single_close (single);
  EXPECT_EQ (status, ML_ERROR_NONE);
```

**Comment by almirfilho77** [comment]
@anyj0527 thank you for your input. I ran the TEST and this was the output:

```
[   35s] [ RUN      ] nnstreamer_capi_singleshot.invoke_Yamnet_01_n
[   35s] ** Message: 19:22:02.541: accl = cpu
[   35s] [       OK ] nnstreamer_capi_singleshot.invoke_Yamnet_01_n (299 ms)
```

It seems like the model works fine, but I don't get how this is valid for my case once it did not run on my target, but on my PC. Could you please bring me some light into this? Is there a way that I can run this test on my target?

**Comment by anyj0527** [comment]
@almirfilho77 
Unfortunately, no armv7l target board is available now or soon for me. But at least I verified the yamnet_classification model is well invoked with dummy data on tizen-aarch64 target board:
```
$ gst-launch-1.0 \
videotestsrc ! videoscale ! videoconvert ! video/x-raw,width=1,height=15600,format=GRAY8 ! \
tensor_converter ! other/tensors,num_tensors=1,dimensions=1:1:15600:1,types=uint8,format=static ! \
tensor_transform mode=transpose option=2:0:1:3 ! \
other/tensors,num_tensors=1,dimensions=15600:1:1:1,types=uint8,format=static ! \
tensor_transform mode=typecast option=float32 ! \
other/tensors,num_tensors=1,dimensions=15600:1:1:1,types=float32,format=static ! \
tensor_filter framework=tensorflow2-lite model=./yamnet_classification.tflite latency=1 ! \
tensor_sink
```

The tf2 tizen package install binary `tflite_benchmark_model` which examine input tflite model. So you may try other build options for tensorflow in your target.

```
$ /usr/bin/tflite_benchmark_model --graph=./yamnet_classification.tflite
STARTING!
Log parameter values verbosely: [0]
Graph: [./yamnet_classification.tflite]
Loaded model ./yamnet_classification.tflite
The input model file size (MB): 4.12681
Initialized session in 3.842ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=34 first=47905 curr=13686 min=13619 max=47905 avg=14727.6 std=5775

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=73 first=13767 curr=13701 min=13617 max=13853 avg=13710.5 std=58

Inference timings in us: Init: 3842, First inference: 47905, Warmup (avg): 14727.6, Inference (avg): 13710.5
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=4.00781 overall=8.69141
```

**Comment by myungjoo** [comment]
Closing this as there's no recent follow-ups. Reopen if you want to continue discussing.
