### ISSUE TITLE
[Docs/build] nnfw-dev dependency issue

### ISSUE THREAD

**Issue by dongju-chae** [nnstreamer/nnstreamer#3612]
NNStreamer debian build requires `nnfw-dev` provided by https://launchpad.net/~one-runtime/+archive/ubuntu/ppa.
https://github.com/nnstreamer/nnstreamer/blob/7d83700b2424181d5183271d230516c84d878700/debian/control#L18

It means nnstreamer ppa (https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa) does not fully support nnstreamer debian packaging. If it's intended (please check this: @jaeyun-jung), the pbuilder/debuild document is outdated and should be updated. 
- https://github.com/nnstreamer/nnstreamer/blob/main/Documentation/getting-started-ubuntu-debuild.md

CC: @niley7464

**Comment by jaeyun-jung** [comment]
Yes, recently I requested to add ppa (nnfw package) to ONE team, and building nnstreamer on ubuntu now requires ONE pkg.

**Comment by gichan-jang** [comment]
Close this issue with #3638
