### ISSUE TITLE
[Question] PyTorch tensor_filter causes internal data stream error.

### ISSUE THREAD

**Issue by wheodid2** [nnstreamer/nnstreamer#3613]
# Issue Description
Hi maintainers and committers.
I'm trying to apply my PyTorch model to nnstreamer.
Since the version of PyTorch I used to make the TorchScript of my model was 1.8.2, so I built nnstreamer with a new version of libtorch with meson build.
However, when I tried to run nnstreamer using the created TorchScript, the following error occurs.

```
$ gst-launch-1.0 v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! tensor_converter ! tensor_filter framework=pytorch model=my_model.pt input=1:480:640:3 inputtype=uint8 output=1:480:640:3 outputtype=uint8 ! tensor_decoder mode=direct_video ! videoconvert ! autovideosink

** Message: 11:12:27.924: gpu = 0, accl = cpu
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:cam_src: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:cam_src:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.000789128
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

And here is the forward part of my model.
```
@torch.jit.script_method
def helper(self, val):
    with torch.no_grad():
        # NHWC (RGB) tensor to NCHW tensor
        float_input = val.float() / 255
        float_input = float_input * 2 - 1
        val = float_input.transpose_(2, 3).transpose_(1, 2)
        out = self.net(val)
        out = out.clip(-1, 1) * 0.5 + 0.5
        out = (out * 255).byte()
        out = out.transpose_(1, 2).transpose_(2, 3)
    return out
```
As I know, since gstreamer processes data in NHWC format, my TorchScript should internally convert data into NCHW format and processes it.
After the processing, it also converts the output data back to NHWC format.
(I found that we can change dimensions by using `tensor_transform mode=dimchg option=0:2`, but I didn't know this information when I created the TorchScript.)
So, I wrote above command like this, tensor_filter framework=pytorch model=my_model.pt input=1:480:640:3 inputtype=uint8 output=1:480:640:3 outputtype=uint8
(My model takes a 640x480 RGB image as input and also outputs a 640x480 RGB image as output.)

Also, I check that if I delete the tensor_filter part, the nnstreamer works well.
```
$ gst-launch-1.0 v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! tensor_converter ! tensor_decoder mode=direct_video ! videoconvert ! autovideosink
```

As I am a newbie to gstreamer and nnstreamer (and even meson build), I am not sure how to solve this problem.
In addition, I wonder if it is right to use the PyTorch model for tensor_filter like above.
Any comments or suggestions or debugging approach would be appreciated.

Expected Result
============
Run my PyTorch model with nnstreamer.

How to Reproduce
===============
I couldn't find a similar PyTorch model. If information is not enough with the issue description alone, I will find a way to reproduce it.

Further Information
===============
Environment: Ubuntu 18.04
GStreamer Core Library version 1.14.5
LibTorch 1.8.2

**Comment by anyj0527** [comment]
@wheodid2 I'm not sure, but check the output value, It seems your forward return float values but the pipeline assumes uint8

**Comment by myungjoo** [comment]
> # Issue Description
> Hi maintainers and committers. I'm trying to apply my PyTorch model to nnstreamer. Since the version of PyTorch I used to make the TorchScript of my model was 1.8.2, so I built nnstreamer with a new version of libtorch with meson build. However, when I tried to run nnstreamer using the created TorchScript, the following error occurs.
> 
> ```
> $ gst-launch-1.0 v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! tensor_converter ! tensor_filter framework=pytorch model=my_model.pt input=1:480:640:3 inputtype=uint8 output=1:480:640:3 outputtype=uint8 ! tensor_decoder mode=direct_video ! videoconvert ! autovideosink
> 
> ** Message: 11:12:27.924: gpu = 0, accl = cpu
> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:cam_src: Internal data stream error.
> Additional debug info:
> gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:cam_src:
> streaming stopped, reason not-negotiated (-4)
> Execution ended after 0:00:00.000789128
> Setting pipeline to PAUSED ...
> Setting pipeline to READY ...
> Setting pipeline to NULL ...
> Freeing pipeline ...
> ```
> 
> And here is the forward part of my model.
> 
> ```
> @torch.jit.script_method
> def helper(self, val):
>     with torch.no_grad():
>         # NHWC (RGB) tensor to NCHW tensor
>         float_input = val.float() / 255
>         float_input = float_input * 2 - 1
>         val = float_input.transpose_(2, 3).transpose_(1, 2)
>         out = self.net(val)
>         out = out.clip(-1, 1) * 0.5 + 0.5
>         out = (out * 255).byte()
>         out = out.transpose_(1, 2).transpose_(2, 3)
>     return out
> ```
> 
> As I know, since gstreamer processes data in NHWC format, my TorchScript should internally convert data into NCHW format and processes it. After the processing, it also converts the output data back to NHWC format. (I found that we can change dimensions by using `tensor_transform mode=dimchg option=0:2`, but I didn't know this information when I created the TorchScript.) So, I wrote above command like this, tensor_filter framework=pytorch model=my_model.pt input=1:480:640:3 inputtype=uint8 output=1:480:640:3 outputtype=uint8 (My model takes a 640x480 RGB image as input and also outputs a 640x480 RGB image as output.)
> 
> Also, I check that if I delete the tensor_filter part, the nnstreamer works well.
> 
> ```
> $ gst-launch-1.0 v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! tensor_converter ! tensor_decoder mode=direct_video ! videoconvert ! autovideosink
> ```
> 
> As I am a newbie to gstreamer and nnstreamer (and even meson build), I am not sure how to solve this problem. In addition, I wonder if it is right to use the PyTorch model for tensor_filter like above. Any comments or suggestions or debugging approach would be appreciated.
> 
> # Expected Result
> Run my PyTorch model with nnstreamer.
> 
> # How to Reproduce
> I couldn't find a similar PyTorch model. If information is not enough with the issue description alone, I will find a way to reproduce it.
> 
> # Further Information
> Environment: Ubuntu 18.04 GStreamer Core Library version 1.14.5 LibTorch 1.8.2

You need to provide the error message (error/warning that is related), not just error code.

Anyway, tensor_converter will give you "3:640:480/uint8" while your tensor_filter requests "1:480:640:3/uint8".
You need to transform 3:640:480:1 (3:640:480 == 3:640:480:1 = C_array[1][480][640][3])  to 1:480:640:3/uint8 or 480:640:3/uint8 if your model really requires 480:640:3 (== C_array [3][640][480]). Anyway, check if your model require 1:640:480:3, not 1:480:640:3.

**Comment by myungjoo** [comment]
@wheodid2 Anyway, if there are enough number of graduate students interested in NNStreamer and have questions and discussion points related with NNStreamer, you may open up a short informal workshop (qna sessions + free discussions without presentations)  and invite NNStreamer maintainers. (you may invite students from different universities and advisors, too.)

**Comment by wheodid2** [comment]
@anyj0527 Thanks for your rapid comment! I solved the problem. Thanks again.

@myungjoo Thanks for your kind and detailed comment. It helps me a lot.

Actually, I'm not in graduate school now, but I've moved to a company.
However, I heard about nnstreamer when I was in the lab, so let me see if there are any interested students in the lab.
By the way, there is a lot of interest in nnstreamer in my company team, so is it okay to hold a short informal workshop together with the company team and graduate school in the future?
(My company team consists of about 10 people.)

**Comment by myungjoo** [comment]
> Actually, I'm not in graduate school now, but I've moved to a company. However, I heard about nnstreamer when I was in the lab, so let me see if there are any interested students in the lab. By the way, there is a lot of interest in nnstreamer in my company team, so is it okay to hold a short informal workshop together with the company team and graduate school in the future? (My company team consists of about 10 people.)

Yes, as long as you can share your related info/code openly (as other open source contributors do), it's perfectly fine.

**Comment by wheodid2** [comment]
Great! First of all, I will do a survey for people who are interested in both the company and the lab.

My company has a year-end performance appraisal, so I think this year will be difficult to hold a workshop.
So, I will contact you again early next year.
I would be very happy if I could learn more about NNStreamer from the maintainer!
I will get back to you once I have more information on it. Thanks again.

**Comment by myungjoo** [comment]
@byungs2 @junarwohn you may join, too, if this really happens :)

(I can arrange a meeting room at https://map.naver.com/v5/entry/place/34304030?c=14139699.4068176,4504334.8488228,15,0,0,0,dh )
