### ISSUE TITLE
[Korean] NNStreamer Conference 2022 (NC22-Seoul), Feb 16, 2022

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3614]
최근 국내에서 NNStreamer를 사용해 보시는 기업 및 대학 연구실들이 여럿 등장하였고, 사용 중 궁금한 점도 많으시며 적절한 사용법이나 문제 해결방법, Pipeline Architecture로 사고하는 방법에 대한 상호 교류가 있으면 좋겠다는 생각이 듭니다.

#3613 에서 언급된 바와 같이, Offline + Online Hybrid로라도 모여서 작은 Informal Workshop 를 개최할까 합니다.

주제는
- NNStreamer를 사용한 어플리케이션 / 서비스 소개. (말씀하시고 싶으신 분들이 자유롭게 짧게 소개해 주시면 되겠습니다.)
- NNStreamer 사용과 관련한 QnA 및 자유토론

정도로 생각하며, 별도로 자료준비를 하여 Formal Presentation을 하기보다는
첫 공개행사인 만큼 자유토론과 질의응답 위주로 짧게 진행되는 것을 생각하고 있습니다.

장소는 https://map.naver.com/v5/entry/place/34304030?c=14139699.4068176,4504334.8488228,15,0,0,0,dh
에서 작은 회의실 하나 사용하려 하며, 참여 희망자 분들이 어느정도 Critical Mass를 넘어서면 시간도 정해보도록 하겠습니다.
(외부 참석자 6명 이상? 외부 참석 단체 4가지 이상?)

본 회의에서의 내용은 모두 상호 공개되는 것을 전제로 하여 Open Source Contribution의 일환으로 간주 부탁드립니다.

기존 NNStreamer Committer 들 중에서는 Maintainer 및 주요 Contributor 몇 분 참석하도록 할 계획입니다.

주변 연구실이나 단체들 중에 nnstreamer에 관심있으시거나 사용하시는 분들 계시면 공유도 부탁드리겠습니다.

---
- [ ] NC22-Seoul 날짜/시간 :  2월16일 / 오후 3시 - 6시
- [ ] NC22-Seoul Agenda
    - Introduction (~10분)
    - Introduction: NNTrainer (~15분)
    - 각자 만드시는 pipeline 이나 nnstreamer app에 대한 소개 (5~10분 이내) x 5~6팀
    - NNStreamer Roadmap (2022-2024 features) & User Feedback (~30분)
    - 자유 토론 및 상담. (++)
- [ ] NC22-Seoul 참석/발표자
    - HU: @junarwohn ___ (미참)
    - KAIST: INA ( @jaykim305  + 2 )
    - FAINDERS.AI: @byungs2, ___
    - Klleon.io: @wheodid2 @TunaLee @baek449
    - NNStreamer: @myungjoo + ...
    - NNTrainer: @jijoongmoon + ...
- [ ] ~~Offline or On-Offline Hybrid.~~ ==> ZOOM Online
    - ~~Offline: 삼성전자 서울R&D캠퍼스 D/E동 1층 대형 회의실~~ ==> No offline meeting due to COVID19 CRISIS.
    - Online: ZOOM  929 5616 2813   (대기실 입장 후 github ID 말씀해 주세요)

**Comment by junarwohn** [comment]
이메일이 예전 계정으로 설정하는 바람에 지금 확인했네요.
개최하신다면 참여 희망합니다.

**Comment by wheodid2** [comment]
안녕하세요. 저는 클레온(https://klleon.io/)을 다니고 있는 조대양 이라고 합니다.
저희 회사 딥러닝 기술팀에서 저 포함 3명 참가 희망합니다.
@TunaLee @baek449

**Comment by myungjoo** [comment]
코로나 거리두기가 어찌될지 불확실 하나, 1월 중에 준비가 곤란할것 같아 2월 16일 수요일로 일단 날짜를 정해두겠습니다.

시간은 참석하시는 분들이 오후시간에 참석 가능하면 오후 3시~6시 정도로 하고, 정시 퇴근 후 참석만 가능하시다면
오후 6:30 ~ 9시 정도 어떨까 합니다.

**Comment by jaykim305** [comment]
안녕하세요. 워크샵 개최하신다면 KAIST INA 연구실에서 저 포함 3명 참가 희망합니다.

**Comment by myungjoo** [comment]
> 안녕하세요. 워크샵 개최하신다면 KAIST INA 연구실에서 저 포함 3명 참가 희망합니다.

넵!

**Comment by myungjoo** [comment]
NOTE: 참석자 전원 COVID-19 백신접종 완료자 이셔야 합니다.

**Comment by myungjoo** [comment]
삼성전사 서울R&D캠퍼스 E동 E107호 + Online Hybrid 진행

**Comment by junarwohn** [comment]
안녕하세요, 사정이 생겨 부득이하게 2월 16일 행사에 불참하게 되었습니다. 죄송합니다.
또한 NNStreamer라는 좋은 오픈소스를 관리해주심에 감사드리며 다음에 또 기회가 닿는다면 꼭 뵙고 싶네요.
감사합니다. 한양대학교 @junarwohn

**Comment by myungjoo** [comment]
행사는 그대로 진행합니다.
Zoom 혹은 Google Meet으로 진행하는 URL도 이 페이지에 띄울것이오니
Online으로 참석하셔도 됩니다. (공개행사이므로 아무나 들어오셔도 됩니다.)

KAIST: INA  @jaykim305
FAINDERS.AI  @byungs2
Klleon.io: @wheodid2 
Samsung: @myungjoo , @jijoongmoon 

이렇게 각 단체에서 NNStreamer 를 이용한 App 혹은 Pipeline 혹은 제안 사안에 대해 10분이내로 간단히 발표도 해주시면 좋겠습니다. PPT 나 웹 페이지 하나 준비하셔도 되고, 그냥 Live로 바로 말씀만 하셔도 됩니다.

아직 시간 여유는 있으니 이야기 발표 Slot 더 추가하셔도 됩니다.
Free Discussion때는 실제 만들고 계신 Pipeline의 성능이나 기능 문제에 관한 토론도 환영합니다.

  - NNStreamer introduction (15:00 - 15:10)
  - NNStreamer side-project introduction, "NNTrainer" (15:10 - 15:30)
  - Lightening Talk of NNStreamer applications (KAIST-INA, FAINDERS.AI, Klleon.IO, Samsung) (15:30 - 16:10)
  - NNStreamer Roadmap (16:30 - 17:00)
  - Free Discussions (17:00 ~ )

**Comment by myungjoo** [comment]
ZOOM으로 진행되며, 대면으로 상담하실분은 방문하셔도 좋습니다.
ZOOM은 2/16일 오후 2:45부터 회의실이 열리며, 대기실로 입장 후 Github ID 확인후 참가시켜 드릴 예정입니다.
회의 ID는 929 5616 2813 / NNStreamer Conference 2022 Seoul 입니다.

Conference 후원해주신 Linux Foundation에 감사드립니다 ^^

**Comment by myungjoo** [comment]
Offline 참여 하실 분은 미리 알려주세요

**Comment by myungjoo** [comment]
삼성리서치 COVID-19 대책으로 인하여 Offline 모임은 강제 취소되었습니다.
ZOOM으로만 진행됩니다.

**Comment by myungjoo** [comment]
https://docs.google.com/presentation/d/1Xhk1rI9tBiFnvrYmBhWVkAD5hu7WNKCElXHMPomU7P0/edit?usp=sharing

**Comment by myungjoo** [comment]
mqtt, query-client/server 등이 언급된 논문 링크입니다: https://arxiv.org/abs/2201.06026

**Comment by myungjoo** [comment]
https://wiki.lfaidata.foundation/ 에 곧 영상 올라옵니다.

**Comment by myungjoo** [comment]
# NC22-Seoul Report

WIP
