### ISSUE TITLE
(Edited) Question::purpose of validateOutputTensor

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3618]
# Issue Description

@kparichay 

안녕하세요
#3594 이슈에서 질문했었던 Tuple 타입 처리에 관해서 개인적으로 수정해서 사용해보려 하고있는데요,
우선 최근 나오는 딥러닝 모델들의 아웃풋을 보니 Tuple ( tensor_list(tensor, tensor ...), tensor )와 같이 여러 차원으로 이뤄진 형태의 아웃풋을 주는 경우가 종종 있는 것을 확인했습니다

때문에 현재 코드로는 list 형태로 주는 tensor output을 제외하면 처리할 수 없는 상태라고 생각해서 아래와 같이 텐서 트리를 순회하면서 텐서를 만날 때마다 하나씩 TorchCore::processIValue 에 넣어주는 함수를 만들어보고 있었는데요
```
// need to fix return type
void
TorchCore::serialize (torch::jit::IValue *output_value, GstTensorMemory *output, int *idx)
{
  if ((*output_value).isTensor ()) {
    if (processIValue (*output_value, &output[(*idx)])) {
      ml_loge ("Output tensor is wrong");
    }
    (*idx)++;
  } else if ((*output_value).isTuple ()) {
    c10::intrusive_ptr<c10::ivalue::Tuple> output_ref_tuple = (*output_value).toTuple();
    std::vector<torch::jit::IValue> output_vector = (*output_ref_tuple).elements();
    for (auto &ivalue_element : output_vector) {
      TorchCore::serialize (&ivalue_element, output, idx);
    }
#ifdef PYTORCH_VER_ATLEAST_1_2_0
  } else if ((*output_value).isList ()) {
    c10::ArrayRef<torch::jit::IValue> output_ref_list = (*output_value).toListRef ();
    std::vector<torch::jit::IValue> output_list (output_ref_list.begin (), output_ref_list.end ());
#else
  } else if ((*output_value).isGenericList ()) {
    c10::ArrayRef<torch::jit::IValue> output_list = (*output_value).toGenericListRef ();
#endif
    for (auto &ivalue_element : output_list) {
      TorchCore::serialize (&ivalue_element, output, idx);
    }
  } else {
    ml_loge ("Output has no tensor");
  }
}
```

해당 함수는 제가 의도한대로 잘 동작하는 것을 확인했으나, TorchCore::processIValue에서 사용하는 TorchCore::validateOutputTensor 함수에서 에러가 생겨 확인해보니, 아래 코드에서 processIValue에 입력된 텐서의 shape이 output tensor의 개수와 같아야 하는 부분이 잘 이해가 되질 않습니다

```
int
TorchCore::validateOutputTensor (const at::Tensor output)
{
  auto tensor_shape = output.sizes ();

  if (tensor_shape[0] != 0 && outputTensorMeta.num_tensors != tensor_shape[0]) {
    ml_loge ("Invalid output meta: different size");
    return -1;
  }
...
```
아래의 코드는 TorchCore::invoke 함수의 원본 일부분인데요
```
...
    g_assert (outputTensorMeta.num_tensors == output_list.size ());
    int idx = 0;
    for (auto &ivalue_element : output_list) {
      if (processIValue (ivalue_element, &output[idx++])) {
        ml_loge ("Output Tensor Information is not valid");
        return -2;
      }
    }
  } else {
    ml_loge ("Output is not a tensor.");
    return -3;
  }
...
```
이 부분에서 torch::jit::IValue 가 list인 경우를 보면, list에서 텐서를 하나씩 processIValue에 넣어주고 있는 것 같은데 이런식이면 대부분의 경우 outputTensorMeta.num_tensors가 tensor_shape[0]와 달라지는 것 아닌가 하는 생각이 들어서 혹시 torch::jit::IValue 리스트의 원소는 전체 리스트 크기에 대한 정보를 가지고 있나 해서 확인해보니 그것도 아닌 것 같더라구요

더 찾아보면 이유를 알게 될 수도 있겠지만 여쭤보는 게 더 빠를 것 같아 이슈를 남기게 됐습니다

요약하자면 TorchCore::validateOutputTensor 함수에서 output tensor 개수와 TorchCore::processIValue 함수에 입력된 tensor의 shape의 첫번째 값을 비교하는 이유가 궁금합니다

**Comment by byungs2** [comment]
# 추가질문 (Edited)
NNS_TENSOR_RANK_LIMIT보면 4로 되어있는데 최대 rank 4까지만 지원하도록 만들어진 이유가 궁금합니다

**Comment by myungjoo** [comment]
git blame으로 해당 코드 작성자 분 

> # 추가질문 (Edited)
> NNS_TENSOR_RANK_LIMIT보면 4로 되어있는데 최대 rank 4까지만 지원하도록 만들어진 이유가 궁금합니다

구현 상 편의를 위해 4를 한계로 두었습니다.

nnstreamer는 hidden feature를 다루지 않고 각 network의 output/input만 다루고, stream inference 상황에서는 언제나 Batch는 1이기 때문에 해당 dimension을 생략할 수 있어 4 면 충분하다 보았습니다. 아직까지 실제 적용사례에서 rank는 3을 넘지 않았습니다.

**Comment by byungs2** [comment]
해당 이슈도 좀 더 확인해보고 영어로 질문드리겠습니다.
