### ISSUE TITLE
Questions on file "tensor_filter_pytorch.cc"

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3620]
# Issue Description
@kparichay 
Hi dev
While I fix tensor_filter_pytorch.cc as my usage, I found some things suspected as bug in this file.
Below lines has those things.

```
int
TorchCore::invoke (const GstTensorMemory *input, GstTensorMemory *output)
{
#if (DBG)
  gint64 start_time = g_get_real_time ();
#endif

  std::vector<torch::jit::IValue> input_feeds;
  torch::jit::IValue output_value;
  torch::Dtype type;
  at::Tensor tensor;

  for (uint i = 0; i < inputTensorMeta.num_tensors; ++i) {
    std::vector<int64_t> input_shape;
    input_shape.assign (&inputTensorMeta.info[i].dimension[0],
        &inputTensorMeta.info[i].dimension[0] + NNS_TENSOR_RANK_LIMIT);

    if (!getTensorTypeToTorch (inputTensorMeta.info[i].type, &type)) {
      ml_loge ("This data type is not valid: %d", inputTensorMeta.info[i].type);
      return -1;
    }
    at::TensorOptions options = torch::TensorOptions ().dtype (type);

    std::reverse (input_shape.begin (), input_shape.end ());
    tensor = torch::from_blob (input[i].data, input_shape, options);
   
    ###########################################
    ##### THIS LINE IS SUSPECTED AS BUG 1 #####
    ###########################################
    if (use_gpu) {
      tensor.to (at::kCUDA);
    }

    input_feeds.emplace_back (tensor);
  }
...
  if (output_value.isTensor ()) {
    g_assert (outputTensorMeta.num_tensors == 1);
    if (processIValue (output_value, &output[0])) {
      ml_loge ("Output Tensor Information is not valid");
      return -2;
    }
#ifdef PYTORCH_VER_ATLEAST_1_2_0
  } else if (output_value.isList ()) {
    c10::ArrayRef<torch::jit::IValue> output_ref_list = output_value.toListRef ();
    std::vector<torch::jit::IValue> output_list (
        output_ref_list.begin (), output_ref_list.end ());
#else
  } else if (output_value.isGenericList ()) {
    c10::ArrayRef<torch::jit::IValue> output_list = output_value.toGenericListRef ();
#endif
    std::cout << "Find tensor list IValue" << std::endl;
    g_assert (outputTensorMeta.num_tensors == output_list.size ());
    int idx = 0;
    for (auto &ivalue_element : output_list) {

    ###########################################
    ##### THIS LINE IS SUSPECTED AS BUG 2 #####
    ###########################################
      if (processIValue (ivalue_element, &output[idx++])) {
        ml_loge ("Output Tensor Information is not valid");
        return -2;
      }
    }
  } else {
    ml_loge ("Output is not a tensor.");
    return -3;
  }
...
```
```
...
int
TorchCore::processIValue (torch::jit::IValue value, GstTensorMemory *output)
{
  g_assert (value.isTensor ());
  at::Tensor output_tensor = value.toTensor ();

  /** bring from gpu to cpu */
    ###########################################
    ##### THIS LINE IS SUSPECTED AS BUG 3 #####
    ###########################################
  if (use_gpu) {
    output_tensor.to (at::kCPU);
  }
  /** make the memory contiguous for direct access */
  output_tensor = output_tensor.contiguous ();

  /* validate output tensor once */
  if (!configured && validateOutputTensor (output_tensor)) {
    ml_loge ("Output Tensor Information is not valid");
    return -1;
  }

  /** @todo avoid this memcpy */
  std::memcpy (output->data, output_tensor.data_ptr (), output_tensor.nbytes ());
  return 0;
}
...
```
```
...
int
TorchCore::validateOutputTensor (const at::Tensor output)
{
  auto tensor_shape = output.sizes ();
    ###########################################
    ##### THIS LINE IS SUSPECTED AS BUG 4 #####
    ###########################################
  if (tensor_shape[0] != 0 && outputTensorMeta.num_tensors != tensor_shape[0]) {
    std::cout << "Number of tensor :: " << outputTensorMeta.num_tensors << std::endl;
    std::cout << "Tensor shpae :: " << tensor_shape << std::endl;
    ml_loge ("Invalid output meta: different size");
    return -1;
  }
  
  if (tensor_shape[0] == 0) {
    tensor_type otype = getTensorTypeFromTorch (output.scalar_type ());
    if (outputTensorMeta.info[0].type != otype) {
      ml_loge ("Invalid output meta: different type");
      return -2;
    }
    goto done;
  }

    ###########################################
    ##### THIS LINE IS SUSPECTED AS BUG 5 #####
    ###########################################
  for (uint i = 0; i < outputTensorMeta.num_tensors; ++i) {
    tensor_type otype;
    gsize num_gst_tensor, num_torch_tensor;
    at::Tensor sliced_output = output.slice (0);
    c10::IntArrayRef sliced_output_sizes;

    otype = getTensorTypeFromTorch (sliced_output.scalar_type ());
    num_gst_tensor = gst_tensor_get_element_count (outputTensorMeta.info[i].dimension);

    num_torch_tensor = 1;
    sliced_output_sizes = sliced_output.sizes ();
    for (int j = 0; j < sliced_output.ndimension (); j++) {
      num_torch_tensor *= sliced_output_sizes[j];
    }

    if (outputTensorMeta.info[i].type != otype) {
      ml_loge ("Invalid output meta: different type");
      return -2;
    }

    if (num_gst_tensor != num_torch_tensor) {
      ml_loge ("Invalid output meta: different element size");
      return -3;
    }
  }

done:
  configured = true;
  return 0;
}
...
```
### Bug 1,3
In class structure in libtorch, at::Tensor::to function has return that type as "at::Tensor". But for now, Codes in tensor_filter_pytorch.cc have been write like It has no return type.
This bug make segmentation error on std::memcpy in TorchCore::processIValue & device mismatching error on model->forward when user use gpu mode 
So I think, It should be fixed like as tensor = tensor.to (at::Device something);

### Bug 2,4,5
In function TorchCore::invoke, If model output is tensor list type, then It will iterate that list and put each element in function TorchCore::processIValue.
And then, TorchCore::processIValue put each tensor IValue into TorchCore::validateOutputTensor.
As last, TorchCore::validateOutputTensor will process check validation with that single tensor.
But, as you can see, in TorchCore::validateOutputTensor, check tensor validation with first value of shape of tensor and total number of tensors.
This mean, I think, in almost cases there has failure with error message as "Invalid output meta: different size"

So I have checked this with my personal model that output shape is List(tensor, tensor).
And as my expectation, there has errors.

```
Find tensor list IValue
Number of tensor :: 2
Tensor shpae :: [1, 10]

** (tester:109): CRITICAL **: 05:09:32.443: Invalid output meta: different size

** (tester:109): CRITICAL **: 05:09:32.443: Output Tensor Information is not valid

** (tester:109): CRITICAL **: 05:09:32.443: Output Tensor Information is not valid

** (tester:109): CRITICAL **: 05:09:32.443: Tensor-filter invoke failed (error code = -2).

0:00:00.187165868   109 0x55c8376e0400 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<videotestsrc0> error: Internal data stream error.
0:00:00.187176411   109 0x55c8376e0400 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<videotestsrc0> error: streaming stopped, reason error (-5)

```
So I want to know if my suspicions are true or not.

Additionally, for now tensor_filter_torch cannot handle output shape as Tuple & multiple dimension type. (eg. Tuple(tensor, list(tensor, tensor ...))
So I suggest to fix code like as below.
```
...
// need to fix return type
void
TorchCore::serialize (torch::jit::IValue *output_value, GstTensorMemory *output, int *idx)
{
  if ((*output_value).isTensor ()) {
    if (processIValue (*output_value, &output[(*idx)])) {
      ml_loge ("Output Tensor Information is not valid");
    }
    (*idx)++;
  } else if ((*output_value).isTuple ()) {
    c10::intrusive_ptr<c10::ivalue::Tuple> output_ref_tuple = (*output_value).toTuple();
    std::vector<torch::jit::IValue> output_vector = (*output_ref_tuple).elements();
    for (auto &ivalue_element : output_vector) {
      TorchCore::serialize (&ivalue_element, output, idx);
    }
#ifdef PYTORCH_VER_ATLEAST_1_2_0
  } else if ((*output_value).isList ()) {
    c10::ArrayRef<torch::jit::IValue> output_ref_list = (*output_value).toListRef ();
    std::vector<torch::jit::IValue> output_list (output_ref_list.begin (), output_ref_list.end ());
#else
  } else if ((*output_value).isGenericList ()) {
    c10::ArrayRef<torch::jit::IValue> output_list = (*output_value).toGenericListRef ();
#endif
    for (auto &ivalue_element : output_list) {
      TorchCore::serialize (&ivalue_element, output, idx);
    }
  } else {
    ml_loge ("Output has no tensor");
  }
}
...
```
```
int
TorchCore::invoke (const GstTensorMemory *input, GstTensorMemory *output)
{
#if (DBG)
  gint64 start_time = g_get_real_time ();
#endif

  std::vector<torch::jit::IValue> input_feeds;
  torch::jit::IValue output_value;
  torch::Dtype type;
  at::Tensor tensor;
  int result = 0;

  for (uint i = 0; i < inputTensorMeta.num_tensors; ++i) {
    std::vector<int64_t> input_shape;
    input_shape.assign (&inputTensorMeta.info[i].dimension[0],
        &inputTensorMeta.info[i].dimension[0] + NNS_TENSOR_RANK_LIMIT);

    if (!getTensorTypeToTorch (inputTensorMeta.info[i].type, &type)) {
      ml_loge ("This data type is not valid: %d", inputTensorMeta.info[i].type);
      return -1;
    }
    at::TensorOptions options = torch::TensorOptions ().dtype (type);

    std::reverse (input_shape.begin (), input_shape.end ());
    tensor = torch::from_blob (input[i].data, input_shape, options);

    if (use_gpu) {
      tensor = tensor.to (at::kCUDA);
    }
    input_feeds.emplace_back (tensor);
  }

  /**
   * As the input information has not been verified, the first run for the model
   * is encapsulated in a try-catch block
   */
  if (first_run) {
    try {
      output_value = model->forward (input_feeds);
      first_run = false;
    } catch (const std::runtime_error &re) {
      ml_loge ("Runtime error while running the model: %s", re.what ());
      return -4;
    } catch (const std::exception &ex) {
      ml_loge ("Exception while running the model : %s", ex.what ());
      return -4;
    } catch (...) {
      ml_loge ("Unknown exception while running the model");
      return -4;
    }
  } else {
    output_value = model->forward (input_feeds);
  }

  int idx = 0;
  TorchCore::serialize (&output_value, output, &idx);

#if (DBG)
  gint64 stop_time = g_get_real_time ();
  g_message ("Invoke() is finished: %" G_GINT64_FORMAT, (stop_time - start_time));
#endif

  return 0;
}
```

**Comment by DaeyangCho** [comment]
I also solved bug 1, 3 by the way you suggested.
This part needs to be fixed as suggested.

**Comment by byungs2** [comment]
How do you think about bug 2,4,5?
I think for now, tensor_filter_pytorch.cc can handle only single tensor output.

**Comment by anyj0527** [comment]
I opened a PR for supporting `Tuple` output #3622 . You may review it, Thanks!

**Comment by byungs2** [comment]
I've read your PR carefully.
Thanks to you first.

If you have enough time, I would expect more PR about Bug 1, 3 and Supporting multiple dimension type of output (eg. Tuple(tensor, List(tensor, tensor...)).

For now I fixed and I'm using it myself as recursive way as my suggetion in this issue.
It works now but I don't know It is efficient or not.
Now many of neural network has multiple dimension type of output.
I hope nnstreamer to support those models soon.

Thanks again

**Comment by anyj0527** [comment]
You're right. Other types other than Tuple(tensor, tensor, ..., tensor) should be supported for both input and output.
And feel free to share your implementation by PR(s).

**Comment by myungjoo** [comment]
> For now I fixed and I'm using it myself as recursive way as my suggetion in this issue. It works now but I don't know It is efficient or not. 

Because whether it's tuple or list, its representation in memory should look like arrays; thus, if you do it with tail-recursion, it should be efficient enough. Even if it's not tail-recursion, as long as the number of tensors in the list/tuple is only around 10, it shouldn't matter too much.


If efficiency really matters, the model should be redesigned to use flat structure (just use an array of tensors with different dimensions: [ tensor1, tensor2, ... ]). Otherwise, you are already creating excessive overhead inside the model I/O, making it useless to optimize I/O out of the model.

**Comment by myungjoo** [comment]
(@kparichay is on vacation and will return 2 wks later)

**Comment by byungs2** [comment]
Then after more fixing and after I read rules of PR in this project, I'm gonna try to open PR about output type of pytorch model.
Thanks to reply.

**Comment by kparichay** [comment]
@byungs2 Thanks for your detailed comment. I apologize for the late reply.
All the reported bugs are right. It seems that the GPU code as well as some other cases were not well tested.
@anyj0527 thanks for fixing bugs 2,4,5, and supporting tuple type for the output.
#3651 provides a quick fix for bugs 1 and 3.

Another PR will soon be added to support other complex types with the outputs of the PyTorch filter.
Note: as @myungjoo said, it's best to redesign the model to return the serialized output than doing it at runtime with each output.

**Comment by byungs2** [comment]
@kparichay 
Thanks for your reply.
I will wait update with glad.
And as you said, I think redesigning is good to use.
But I'm not sure whether I can use pre-trained model with redesigned model because I don't know well about deep learning things.
After check that, I will follow that advice.
Thank you.

**Comment by kparichay** [comment]
> But I'm not sure whether I can use pre-trained model with redesigned model because I don't know well about deep learning things.
After check that, I will follow that advice.

The pre-trained model can be modified to perform operations/allocate memory for the operations in a way so that the output is serialized, or additional operations can be introduced in the model (like concat, vstack, etc) to serialize the output. These modifications do not change the output of the model but adjust the layout of the output. 
This results in serializing the output on the same accelerator where the model is running, giving good performance and keeping the overall pipeline simplified.

**Comment by byungs2** [comment]
I will close this issue cause all problem has been resolved.
