### ISSUE TITLE
App should run `g_main_loop_run (loop)` when using tensor_query_*

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3630]
Currently tensor_query's socket communication feature is implemented using `g_socket_listener_accept_socket_async`.
And it needs a `GMainLoop` is running (https://github.com/GNOME/glib/blob/main/gio/gsocketlistener.c#L872), or it won't work.

Until the working on decoupling the network related code from glib dependency is done,
application should take care of the `g_main_loop_run`.
An example:
https://github.com/nnstreamer/nnstreamer-example/blob/main/native/example_query_object_detection/example_query_object_detection.c#L102

**Comment by myungjoo** [comment]
@gichan-jang w/ nnstreamer-edge, do we still have this issue?

**Comment by gichan-jang** [comment]
Yes, `nnstreamer-edge` still uses `g_socket_listner`, we need to run g_main_loop.
I think we need a proper guide document on how to use it. I will upload it.

**Comment by myungjoo** [comment]
@jaeyun-jung / @gichan-jang  I think this is already resolved at nnstreamer-edge side (for RTOS builds). Please close this if it's resolved.

**Comment by gichan-jang** [comment]
Close via https://github.com/nnstreamer/nnstreamer-edge/pull/82
