### ISSUE TITLE
Information about NNStreamer new releases and features

### ISSUE THREAD

**Issue by jvuillaumier** [nnstreamer/nnstreamer#3641]
Hello,

I have been looking for NNStreamer new releases and roadmap information, being interested in high level features and approximate releases timeframe.

Browsing through wikis I found pages:
https://github.com/nnstreamer/nnstreamer/wiki/Development-Plans
https://github.com/nnstreamer/nnstreamer/wiki/Release-Notes
https://wiki.lfaidata.foundation/display/NNSTREAM/Development+Roadmap

But those do no seem relevant or up to date for incoming releases and developments.

Would such information (releases date and content) be available in a wiki page or in a different forum?

Thank you

**Comment by myungjoo** [comment]
Uh.. yes.. those are not maintained for months and we are preparing yearly (w/ 3yrs plan) project plans these days, which I expect to be published next month. Anyway, for a sneak peek, refer to https://arxiv.org/abs/2201.06026

**Comment by jvuillaumier** [comment]
Thank you @myungjoo for 2022 topics early preview and very interesting article.
