### ISSUE TITLE
[decoder] custom decoder creates wrong caps

### ISSUE THREAD

**Issue by LieberwirthF** [nnstreamer/nnstreamer#3647]
Hi,
I'm trying to create a custom tensor_decode which decodes the resulting tensors from tensor_filter
I've registered the decoder like so:

` if(0 != nnstreamer_decoder_custom_register("tdec_custom", tensor_decoder_bounding_boxes_cb, NULL)){ `
`        g_print("Failed to registser custom tensor_decoder\n");`
`    }`
`    g_object_set(t_pipe.t_decoder,  "mode", "custom-code",`
`                                    "option1", "tdec_custom",`
`									NULL);    `

Problem is as I'm trying to link the decoder to a compositor it fails due to wrong src caps coming from the decoder:
Snippet from `GST_DEBUG=5`:
`0:00:01.517235205  5116 0xaaaaf9ef6400 DEBUG               GST_CAPS gstpad.c:2282:gst_pad_link_check_compatible_unlocked:<tensordec0:src> src caps application/octet-stream`
`0:00:01.517280581  5116 0xaaaaf9ef6400 DEBUG               GST_CAPS gstpad.c:2284:gst_pad_link_check_compatible_unlocked:<imxcompositor_g2d0:sink_0> sink caps video/x-raw, width=(int)[ 64, 2147483647 ], height=(int)[ 64, 2147483647 ], framerate=(fraction)[ 0/1, 2147483647/1 ], format=(string){ RGB16, RGBx, RGBA, BGRA, BGRx, BGR16, ARGB, ABGR, xRGB, xBGR, I420, NV12, UYVY, YUY2, YVYU, YV12, NV16, NV21 }`

Is there a way to change the decoder caps to `video/x-raw`?

Here is the full log:
[log.txt](https://github.com/nnstreamer/nnstreamer/files/7906500/log.txt)

Here is a minimal example:
[ssd_minimum.zip](https://github.com/nnstreamer/nnstreamer/files/7906525/ssd_minimum.zip)

Coding this example I've followed this implementaion:
https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c

**Comment by gichan-jang** [comment]
Hello, @LieberwirthF.
As can be seen in your log, the source cap of the custom tensor decoder is `application/octet-stream`.
```
0:00:01.241222810 [34m 5145[00m 0xaaab0a6e3400 [37mDEBUG  [00m [00m      tensor_decoder 
tensordec.c:803:gst_tensordec_transform_caps:<tensordec0>[00m Direction[2] transformed other/tensors, format=
(string)static, framerate=(fraction)[ 0/1, 2147483647/1 ], num_tensors=(int)4, dimensions=
(string)"4:20:1:1\,20:1:1:1\,20:1:1:1\,1:1:1:1", types=(string)"float32\,float32\,float32\,float32" into application/octet-stream
```

How about using a capssetter to change the application/octet-stream to video caps?
Here is a simple example.

```
 gst-launch-1.0 videotestsrc ! video/x-raw,format=RGB,width=640,height=480,framerate=5/1 ! \
    tensor_converter ! tensor_decoder mode=octet_stream ! application/octet-stream ! capssetter caps="video/x-raw,format=RGB,width=640,height=480,framerate=5/1" replace=true join=false ! videoconvert ! ximagesink
```

**Comment by LieberwirthF** [comment]
That worked out perfectly. Many Thanks!
-> closing
