### ISSUE TITLE
Questions for function gst_tensor_transform_transform_caps when using funnel element.

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3666]
# Issue Description
Hi

First, below is my test pipeline.
```
        const char *string = "funnel name=f ! \
                videoscale ! videoconvert ! video/x-raw,format=RGB,width=640,height=640 ! \
                tensor_converter ! \
                tensor_transform mode=1 option=float32 silent=0 ! \
                tensor_transform mode=dimchg option=0:2 ! \
                tensor_filter framework=pytorch \
                model=./dummy_model_maker/yolov5s.torchscript.pt \
                accelerator=true:gpu \
                input=640:640:3:1 \
                inputname=image_tensor \
                inputtype=float32 output=25200:85,3:80:80:85,3:40:40:85,3:20:20:85 \
                outputname=num_detections,detection_classes,detection_scores,detection_boxes \
                outputtype=float32,float32,float32,float32 ! tensor_sink name=tensor_sink \
                rtspsrc location=rtsp://Account:PW@IP:Port/profile0 latency=0 \
                protocols=tcp ! application/x-rtp,media-type=video ! rtph265depay ! avdec_h265 ! f.sink_0 \
                rtspsrc location=rtsp://Account:PW@IP:Port/profile0 latency=0 \
                protocols=tcp ! application/x-rtp,media-type=video ! rtph265depay ! avdec_h265 ! f.sink_1";
```
While I'm using this pipeline, I keep have continuos error message like below with each every video stream packets.
`(tester:2672): GLib-CRITICAL **: 08:45:54.025: g_string_insert_len: assertion 'len == 0 || val != NULL' failed`

After trace callstack, I realized It happens at the element tensor_transform when the element funnel src pad make pakcet that have different stream_id with the other packet right before.

```
static GstCaps *
gst_tensor_transform_transform_caps (GstBaseTransform * trans,
    GstPadDirection direction, GstCaps * caps, GstCaps * filtercap)
{
  GstTensorTransform *filter;
  GstCaps *result = NULL;
  GstStructure *structure;
  guint i, j;

  filter = GST_TENSOR_TRANSFORM_CAST (trans);

  silent_debug (filter, "Calling TransformCaps, direction = %d\n", direction);
  ...
    if (gst_tensors_config_is_flexible (&in_config)) {
      /* output caps is also flexible */
      out_config.format = _NNS_TENSOR_FORMAT_FLEXIBLE;
    } else { 
      for (j = 0; j < in_config.info.num_tensors; j++) {
        gst_tensor_transform_convert_dimension (filter, direction,
            j, &in_config.info.info[j], &out_config.info.info[j]);
      }
    }
  ...
    if (gst_structure_has_name (structure, NNS_MIMETYPE_TENSOR)) {
      gst_caps_append (result, gst_tensor_caps_from_config (&out_config));
    } else {
      gst_caps_append (result, gst_tensors_caps_from_config (&out_config));
    }
  ...
```
when the GstPadDirection is 1 (SRC), the function gst_tensor_transform_convert_dimension convert in_config.info.info[i].type from float32 (Enum 7) to _NNS_END (Enum 10).
After that, the function gst_caps_append makes error message because there is no type string but only null.

```
static gboolean
gst_tensor_transform_convert_dimension (GstTensorTransform * filter,
    GstPadDirection direction, guint idx, const GstTensorInfo * in_info,
    GstTensorInfo * out_info)
{
...
    case GTT_TYPECAST:
      /** For both directions, dimension does not change */
      if (direction == GST_PAD_SINK) {
        /** src = SINKPAD / dest = SRCPAD */
        out_info->type = filter->data_typecast.to;
      } else {
        /* cannot get the incoming data type on sink pad */
        out_info->type = _NNS_END;
      }
      break;
...
```
So I checked the function gst_tensor_transform_convert_dimension, and I found there is no way to get type when direction isn't 2(GST_PAD_SINK).

So my Questions are 
1. What is the direction of Pad? I feel still confused even after read GST documents. which element is the owner of direction among caller and called?

2. Is it intended behavior of gst_tensor_transform_convert_dimension?

3. meaning of "cannot get the incoming data type on sink pad" ?

4. If every thing is correct and only my usage of pipeline isn't proper, then can you give some advice?

thanks for reading.
I hope it's worth answering my question.

Expected Result
============
No error message while running pipeline.

How to Reproduce
===============
use funnel element with rtsp cameras and tensor_transform type cast mode.

**Comment by anyj0527** [comment]
I think the codes that you pointed are intended in here: #2505
to avoid nego failure in appsrc -> tensor_transform direct connection.

As a result, the error message is coming from this line, https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/tensor_common.c#L717
but after negotiation phase, pipeline should work properly.

I'll handle the "false" logs (... `g_string_insert_len: assertion 'len == 0 || val != NULL' failed` ...).

**Comment by byungs2** [comment]
Thanks for your reply.
Your comment is right.

I don't know well about what is the caps negotiation exactly, but anyway I think funnel keep trying caps negotiation when stream id is changed.
So pipeline work fine but 'false' log keep comming out.

Your comments gave much clues.
Thanks again.
I will try more.

**Comment by byungs2** [comment]
My problem is resolved
Thanks
