### ISSUE TITLE
Is there a way to share memory between models in pipeline? (without using tensor_decoder)

### ISSUE THREAD

**Issue by TunaLee** [nnstreamer/nnstreamer#3668]
Hello.
I'm trying to stream video using several neural net models on NNStreamer.

Is it possible to share data(python class object) on memory without using a tensor decoder between models?

For example, there are two models that need to be processed sequentially in one pipeline, and the output of the first model needs to be used input in the second model.

I got know about 'tensor_sink'. Can python class share memory in the pipeline?

**Comment by gichan-jang** [comment]
If the output of the first model is used directly as the input of the second model, two tensor filters can be used continuously.
Is there a problem when you use it like this?

**Comment by TunaLee** [comment]
Actually, I'm a Newbie ... Sorry for asking easy question.

I think found a way. thanks for your answer.

I will try to change the Python data structure to tensor that fit the nnstreamer pipeline.
