### ISSUE TITLE
Refactor header names.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3672]
The initial principles for header naming are obsolete and the header names are very confusing.

Refactor, Rename, and Clean up header files!

**Comment by myungjoo** [comment]
Plan (WIP)

Path rules

/gst/nnstreamer/include/*.h   headers to be exported
/gst/nnstreamer/*.h  headers to be used internally by /gst/nnstreamer/*, /ext/nnstreamer/*
/gst/nnstreamer/${module}/*.h don't be used out of /gst/nnstreamer/*
/ext/nnstreamer/*..*/*.h never exported. never referred by /gst/*

Naming rules for exported headers

**Comment by jaeyun-jung** [comment]
suggestion: library name and dependency about single
nnstreamer single library -> nnstreamer base (utils + configuration) + filter_single

**Comment by myungjoo** [comment]
minor issues in this topic:
- nnsconf_* functions in nnstreamer_internal.h (move to nnstreamer_conf.h?)
-
