### ISSUE TITLE
TensorFlow Lite filter - link issue depending on delegates supported by TFlite lib

### ISSUE THREAD

**Issue by jvuillaumier** [nnstreamer/nnstreamer#3674]
Hello all,

# Issue Description
A change has been merged recently into main branch changing the configuration options for NNStreamer TFLite filter:
https://github.com/nnstreamer/nnstreamer/commit/2a86a9c9147a8b59693af9dbee4b96876fb035f9
Before this change, delegates support of GPU, NNAPI and XNNPACK was configurable via meson option.
It is no longer the case and from now on, support of this 3 delegates is expected by NNStreamer filter to be always available.

This is not an issue at build time because headers for every delegate are exported by the lib so can be #include-d by filter.
However it is an issue at  link time, because delegates support in TFLite lib is defined at library configuration time by its cmake:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/CMakeLists.txt#L64
It still stands true on main branch of tensorflow upstream project: it can not be expected that all delegates are built in the lib.
When one delegate is not compiled in TFLite lib, NNStreamer TFLite filter can not link, because it references symbols missing in TFLite lib.  

We have the issue using a TFLite 2.6.0 library without GPU delegate compiled in - error output below.
But similar issue would presumably show up with any missing delegate and with any TFLite version.

Error at link reported during subplugin (.so) build:
tensor_filter_tensorflow_lite.cc.o: in function `TFLiteInterpreter::loadModel(int, tflite_delegate_e)::{lambda(TfLiteDelegate*)#2}::_FUN(TfLiteDelegate*)':
tensor_filter_tensorflow_lite.cc:475: undefined reference to `TfLiteGpuDelegateV2Delete'
tensor_filter_tensor_filter_tensorflow_lite.cc.o: in function `TFLiteInterpreter::loadModel(int, tflite_delegate_e)':
tensor_filter_tensorflow_lite.cc:458: undefined reference to `TfLiteGpuDelegateOptionsV2Default'
tensor_filter_tensorflow_lite.cc:472: undefined reference to `TfLiteGpuDelegateV2Create'
collect2: error: ld returned 1 exit status
 

Expected Result
============
NNStreamer tflite filter should be able to link with multiple flavours of TFLite library, even when all delegates (XNNPACK, GPU, NNAPI) are not built-in.
Note: same NNStreamer change has added a TODO to remove the meson option for external delegate. Doing so would presumably lead to the same issue.

Can the previous meson options be reenabled, as well as conditional build in the NNStreamer tflite filter of the delegate-specific block
option('tflite2-gpu-delegate-support', type: 'boolean', value: 'false')
option('tflite2-nnapi-delegate-support', type: 'boolean', value: 'false')
option('tflite2-xnnpack-delegate-support', type: 'boolean', value: 'false')

How to Reproduce
===============
Build NNStreamer TFLite filter on a file system hosting a TFLite library without GPU delegate.

Thank you for your support.

**Comment by anyj0527** [comment]
@jvuillaumier
In #3559, we removed those build options because the platforms that we support - Tizen, Ubuntu, Android - now provides tflite v2.7.0 which built with those delegates including GPU delegate (but not with external delegate).
And your point seems also valid. Some community users may want to custom tflite lib. AFAIK, the GPU delegate in tflite takes quite a binary size.

@myungjoo @jaeyun-jung How about your opinion? Should these meson options
```
option('tflite2-gpu-delegate-support', type: 'boolean', value: 'false')
option('tflite2-nnapi-delegate-support', type: 'boolean', value: 'false')
option('tflite2-xnnpack-delegate-support', type: 'boolean', value: 'false')
```
be re-enabled?

**Comment by jaeyun-jung** [comment]
YJ: I agree reenabling these options (no way to detect supported delegates in tflite library?)

**Comment by myungjoo** [comment]
Or.. maybe.. as we are now making them turned on by default, you may do:
```
option('tflite2-gpu-delegate-support', type: 'boolean', value: 'true')
option('tflite2-nnapi-delegate-support', type: 'boolean', value: 'true')
option('tflite2-xnnpack-delegate-support', type: 'boolean', value: 'true')
```


Moreoever, nnstreamer-tflite2 meson script should check related symbols or headers so that it can disable corresponding delegate.

Then.. it'd be
```
option('tflite2-gpu-delegate-support', type: 'feature', value: 'auto')
option('tflite2-nnapi-delegate-support', type: 'feature', value: 'auto')
option('tflite2-xnnpack-delegate-support', type: 'feature', value: 'auto')
```
and in meson.build scripts, logically, it should be
```
if (X-delegate == auto && X-delegate symbol-or-header available == TRUE) ||
    (X-delegate == enabled && X-delegate symbol-or-header available == TRUE)
  enable
if (X-delegate == auto && X-delegate symbol-or-header available == FALSE)  ||
    (X-delegate == disabled)
  disable
if (X-delegate == enabled && X-delegate symbol-or-header available == FALSE)
  error!
```

**Comment by jvuillaumier** [comment]
Just to comment:
Our use case is that all delegate headers files are exported, but symbols for disabled delegates are not compiled in the TFLite lib (link error). For that, a simple logic where unavalaible delegates can be selectively disabled at config time via meson option would be sufficient.

I do not know about meson symbol verification capability, but in case of feature 'auto' option implementation, support enablement logic with symbols+headers would probably have to be:
- enabled if both headers and symbols are available
- disabled if either headers or symbols are not available.

Thanks

**Comment by anyj0527** [comment]
@jvuillaumier 
Please check & review PR #3682. It checks linking each delegate symbols with tflite lib in meson configuration time.

**Comment by jvuillaumier** [comment]
@anyj0527 
I have tested PR #3682. I confirm it fixes the issue reported in this ticket.
Thank you for your support
