### ISSUE TITLE
[gbs] python converter test stucks

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3684]
With latest tizen/base/latest/ and tizen/unified/latest, the test is stucked after python_converter unittest.

With tizen/unified/tizen-unified_20220228.1/ and tizen/base/tizen-base_20220228.1/,
it does not stucked.

May the version of python3 be the reason?
tizen/base/tizen-base_20220228.1/repos/standard/packages/x86_64/**python3-3.9.1-10.28**.x86_64.rpm
vs.
tizen/base/latest/repos/standard/packages/x86_64/**python3-3.9.10-11.3**.x86_64.rpm

REF: #3683

**Comment by myungjoo** [comment]
Is this addressed by #3685 ?

**Comment by gichan-jang** [comment]
> Is this addressed by #3685 ?

No, #3685  is not directly related with this issue.

**Comment by myungjoo** [comment]
#3872 is trying to resolve this...
