### ISSUE TITLE
[converter] assert fails with different sized input frames without any message

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#3687]
I am using `tensor_converter` element to convert decoded png frames to tensor format and store them into binary files. Below is the used pipeline:
```
gst-launch-1.0 multifilesrc location="frame%01d.png" ! pngdec ! tensor_converter ! filesink location="frame.bin"
```

The pipeline works well when the input frames are of the same size. However, with input frames of different sizes, the pipeline fails with an assert failure - 
```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
**
ERROR:/home/kparichay/FastDrive/Working/nnsuite/nnstreamer_pk.git/gst/nnstreamer/tensor_converter/tensor_converter.c:905:gst_tensor_converter_chain: assertion failed: (offset % 4)
Bail out! ERROR:/home/kparichay/FastDrive/Working/nnsuite/nnstreamer_pk.git/gst/nnstreamer/tensor_converter/tensor_converter.c:905:gst_tensor_converter_chain: assertion failed: (offset % 4)
Aborted (core dumped)
```

It would be great to have a better error message in this case.

Note: ideally storing data into binary files can be done without tensor_converter, but was just playing with it.

**Comment by myungjoo** [comment]
You will need to ensure using flexible tensors (```other/tensors,format=flexible```).

**Comment by myungjoo** [comment]
After recent changes in error messages, I'm pretty sure that we will get more detailed error messages.

However, with recent versions, this pipeline does not incur any errors (automatically uses flexible tensors...)
