### ISSUE TITLE
If `tensorflow1-lite` and `tensorflow2-lite` both are used in a pipeline, It gets error

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3709]
```
... ! tensor_converter ! tee name=t \
t. ! queue ! tensor_filter framework=tensorflow1-lite model=...tflite ! tensor_sink \
t. ! queue ! tensor_filter framework=tensorflow2-lite model=...tflite ! tensor_sink
```
If both subplugins are installed, this pipeline got error. The later called subplugin was not initialized.

**Comment by myungjoo** [comment]
Maybe... it's the issue of duplicated symbols between dlopen-ed libraries.

**Comment by jaeyun-jung** [comment]
Suggestion

1. Update subplugin searcher
- add hashtable for dl-opened handles(gmodule) instead ptr-array (key:path value:handle)
- when calling _search_subplugin(), look up handle from hashtable. If not exists, call dl-open and add handle into hashtable. (key : path)
- In fini_subplugin(), destroy hashtable.

2. Macro to define sub-plugin name (discussion later)
- declare macro to define sub-plugin name to avoid duplicated constructor/destructor.
e.g. NNS_SUBPLUGIN_CONSTRUCTOR(type,name) >> init_type_name(void)
