### ISSUE TITLE
[tensor_transform mode=arithmetic] Operate with different values for each channel

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3711]
For some neural networks models, especially for image input models,
it requires different normalizing values for each channel.

```
... ! \
video/x-raw,format=RGB,width=W,height=H ! tensor_converter ! \
other/tensors,num_tensors=1,dimensions=3:W:H:1,types=uint8 ! \
tensor_transform mode=dimchg option=0:2 ! \
other/tensors,num_tensors=1,dimensions=W:H:3:1,types=uint8 ! \
tensor_split name=split tensorseg=W:H:1:1,W:H:1:1,W:H:1:1 \
split.src_0 ! queue ! tensor_transform mode=arithmetic option=typecast:float32,add:0.1234,div:0.2323 ! merge.sink_0 \
split.src_1 ! queue ! tensor_transform mode=arithmetic option=typecast:float32,add:-0.4312,div:0.2111 ! merge.sink_1 \
split.src_2 ! queue ! tensor_transform mode=arithmetic option=typecast:float32,add:0.466,div:0.188 ! merge.sink_2 \
tensor_merge name=merge mode=linear option=2 ! \
other/tensors,num_tensors=1,dimensions=W:H:3:1,types=float32,framerate=0/1,format=static ! \
tensor_transform mode=transpose option=2:0:1:3 ! \
other/tensors,num_tensors=1,dimensions=3:W:H:1,types=float32,framerate=0/1,format=static ! \
... 
```

Using `tensor_transform mode=dimchg`, `tensor_transform mode=transpose`, `tensor_split` and `tensor_merge`  can achieve this... but,
adding this feature with `tensor_transform mode=arithmetic` could be better.

**Comment by myungjoo** [comment]
Interesting!

Decision point:
1. option/mode syntax: how "target ranges/dimensions" are specified
2. are you going to handle "multiple targets" in a single tensor_transform? (less memcpy / more complex syntax) or are you going to let it be handled in a sequence of tensor-transform's (more memcpy / simple syntax) ?
