### ISSUE TITLE
I am not able to test NNStreamer::tensor_query for echo and object detection

### ISSUE THREAD

**Issue by areberoto** [nnstreamer/nnstreamer#3724]
Hello,

I'm trying to run the object detection test and echo test provided by [tensor_query](https://github.com/nnstreamer/nnstreamer/tree/main/gst/nnstreamer/tensor_query) but client side stops at:

 `Setting pipeline to PAUSED ... Pipeline is PREROLLING ...`

I'm running the test without changes on the same host machine, is there anything I should change on the command-line pipeline? I also tried with two different machines but failed.

I would appreciate some help here, thanks!

**Comment by myungjoo** [comment]
Could you please write a minimized pipeline (or a pair of pipelines) description that recreates the same error?

**Comment by areberoto** [comment]
Hello, sorry I did not reply, I was on vacation.

I did try custom pipelines but the thing is that I am not able to run the tests provided on the official documentation, which are the following:

`gst-launch-1.0 \
    tensor_query_serversrc ! video/x-raw,width=640,height=480,format=RGB,framerate=0/1 ! \
        videoconvert ! videoscale ! video/x-raw,width=300,height=300,format=RGB ! tensor_converter ! \
        tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
        tensor_filter framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! \
        tensor_decoder mode=bounding_boxes option1=mobilenet-ssd option2=tflite_model/coco_labels_list.txt option3=tflite_model/box_priors.txt option4=640:480 option5=300:300 ! \
        videoconvert ! tensor_query_serversink`

`gst-launch-1.0 \
    compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink \
        videotestsrc ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 ! tee name=t \
            t. ! queue ! tensor_query_client ! videoconvert ! mix.sink_0 \
            t. ! queue ! mix.sink_1`

The only element I changed on the client side was the `v4l2src`. I replaced it with `videotestsrc` because I'm testing on VM, so I do not have an available camera to use. VM is on the cloud.

Running the test I get the following output on the client side:

`** (gst-launch-1.0:1399905): CRITICAL **: 07:54:21.261: Failed to connect to host

** (gst-launch-1.0:1399905): CRITICAL **: 07:54:21.261: Failed to create new socket

** (gst-launch-1.0:1399905): CRITICAL **: 07:54:21.261: Failed to connect server source 

** (gst-launch-1.0:1399905): CRITICAL **: 07:54:21.261: _client_retry_connection: assertion 'self->operation' failed`

Any suggestion on what can be wrong? Thanks

**Comment by areberoto** [comment]
Okay, then it should be a problem regarding my VM network configuration, probably there is something blocking TCP connection on localhost :/ I'll check with IT team, thanks for confirming that this is working well and sorry for bothering.
