### ISSUE TITLE
Question on tensor_transform aarch64 ORC acceleration support

### ISSUE THREAD

**Issue by jvuillaumier** [nnstreamer/nnstreamer#3736]
Hello,

Some operations of [tensor_transform.c](https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/tensor_transform/tensor_transform.c), namely typecast and arithmetic ops, have the option to use SIMD acceleration through ORC library via primitives from [tensor_transform.orc](https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/tensor_transform/transform-orc.orc).

On [ORC upstream project](https://gitlab.freedesktop.org/gstreamer/orc), aarch64 support is recorded to be broken for some time now: https://gitlab.freedesktop.org/gstreamer/orc/-/issues/33

ORC aarch64 support implementation was in the backlog from NNStreamer project some time ago (https://github.com/nnstreamer/nnstreamer/issues/1666). But this ticket is now closed.

Have the plans for tensor_transform aarch64 Neon acceleration been abandoned, or are there still plans for implementing such acceleration through ORC or other libraries?

Thank you

**Comment by myungjoo** [comment]
With the news of aarch64 adoption in ORC upstream, we have dismissed this issue, assuming that the upstream ORC resolves the issue completely. Thus, we do not have any plans for it.

Anyway, as we have products to be released with 64bit systems enabled, I expect that we might be using ORC with a commit that is tested to be working with aarch64 if ORC upstream doesn't fix it soon.

**Comment by jvuillaumier** [comment]
Thank you @myungjoo  for the feedback
