### ISSUE TITLE
[Tizen/ACR] missed error reporting infra.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3746]
Register error reporting API infra for 7.0 M2 ACR.

**Comment by jaeyun-jung** [comment]
https://github.com/nnstreamer/api/pull/98
const char * ml_error (void);
const char * ml_strerror (int errnum);

**Comment by jaeyun-jung** [comment]
+ new ACR item (ml-option) with ml-error.
https://github.com/nnstreamer/api/pull/164

**Comment by jaeyun-jung** [comment]
ACR required : NNFW type
https://github.com/nnstreamer/api/pull/173

**Comment by jaeyun-jung** [comment]
ACR is started today.
