### ISSUE TITLE
How about making the github discussions?

### ISSUE THREAD

**Issue by designe** [nnstreamer/nnstreamer#3755]
If the nnstreamer project opens `discussions` tab on the repository, 
I think more active communication between users and developers will be possible.
Actually, `issue` tab is designed for developer's view. and `discussions` tab is focused on the user's point of view. 

https://docs.github.com/en/discussions

Discussions tab can use like the stackoverflow and github issue and so on.

### examples
- https://github.com/euphony-io/euphony/discussions
- https://github.com/vercel/next.js/discussions

I hope this becomes the open source for more people to use.

**Comment by myungjoo** [comment]
Thank you for the suggestion. As I'm an old school, using github for too long, I didn't know that such a feature exists! It's created.
