### ISSUE TITLE
[ACR] New NNFW_TYPE for MXNET should be added?

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3767]
REF: https://github.com/nnstreamer/api/pull/171

**Comment by jaeyun-jung** [comment]
tvm also needs to be added (ML_NNFW_TYPE_TVM)

**Comment by jaeyun-jung** [comment]
I added new PR (https://github.com/nnstreamer/api/pull/173) for NNFW type.
Please check previous github issue for next ACR (https://github.com/nnstreamer/nnstreamer/issues/3746).
