### ISSUE TITLE
Add Yocto build check in Daily Build

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3783]
TBU

**Comment by myungjoo** [comment]
github action?

**Comment by anyj0527** [comment]
> github action?

Clean Yocto build requires tens of GBs and 3+ hours, making itself unsuitable to Github-hosted action. To use github action we may look for [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

**Comment by myungjoo** [comment]
> > github action?
> 
> Clean Yocto build requires tens of GBs and 3+ hours, making itself unsuitable to Github-hosted action. To use github action we may look for [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

Yes... In that case, TAOS-CI looks better.
