### ISSUE TITLE
Increase NNS_TENSOR_RANK_LIMIT, the rank of tensor

### ISSUE THREAD

**Issue by anyj0527** [nnstreamer/nnstreamer#3800]
NNS_TENSOR_RANK_LIMIT is currently 4. We may increase it.
Ops like conv3d requires 5-D tensors. And widely used yolov5 pytorch model has 5-D output.

REF:
ONE has rank limit 6.
TFLite seems does not have limit, but its delegates have (xnnpack: 6, gpu: 4, ...)

---
[Added by @myungjoo]

- Development Target: 2022-4Q
- Release Target: 2023-1Q (with Tizen 7.5M1 ACR & GBM Pre-release)
- Priority: Medium
- Functional Requirements
    - RANK_LIMIT = 8 or 16
    - Support all nnstreamer elements
- Non-Functional Requirements
    - Backward compatibility (all previous nnstreamer pipelines should be kept working)
    - Performance & resource-efficiency shouldn't drop
    - Minimize code changes
    - (Recommended) no more hardcoded RANK_LIMIT logic (c.f., tensor\_transform)
- CAUTION
    - tensor\_transform may require a lot of changes
    - be careful with flexible/sparse tensors <-- --> static tensors
    - tensor\_aggregator may require a bit of changes
- You will need to add a lot of test cases to ensure backward compatibility and RANK>4 behaviors.

**Comment by myungjoo** [comment]
If you are going to increase it, let's try 8. :)

We may let each tensor\_* element declare its supported RANK.
Most elements will be trivial for this change; however, ```tensor_transform``` may suffer from a lot of changes and you'll need to delay its changes for RANK>4.

Anyway, as long as we now have models with RANK>4, we need to start this (w/ priority after nnstreamer-edge(+RT) and ml-service-api/Phase2&3).

CC: @jaeyun-jung @again4you @gichan-jang @niley7464

**Comment by jaeyun-jung** [comment]
Let's discuss below items with rank change,
1. dynamic shape (3:?:?:1)
2. scalar (model rank is 0)

**Comment by myungjoo** [comment]
![image](https://user-images.githubusercontent.com/1109011/173759573-42caed30-9232-4df1-8c1b-4b7902c15632.png)

**Comment by myungjoo** [comment]
I think it's done along with test cases, right? @niley7464 
Please close this if you have enough test cases registered. (if you have #negativecases > #positivacase > N > 0 and code-line-coverage > 80%, major-function-coverage == 100% , it's enough.)

**Comment by niley7464** [comment]
> I think it's done along with test cases, right? @niley7464 Please close this if you have enough test cases registered. (if you have #negativecases > #positivacase > N > 0 and code-line-coverage > 80%, major-function-coverage == 100% , it's enough.)
> 
> Anyway, if you need more test cases, you just need to do it by mid-october

There is a problem with nnstreamer_repo when increasing the rank.
I will fix it after NPU driver issue.
Also, pytorch yolov5 model has a version problem so it will take some time to make test cases.

**Comment by myungjoo** [comment]
Fine. Thanks!

**Comment by myungjoo** [comment]
Any follow-up commits of this issue (test cases & sample pipelines, dimension description backward-compatibility) should be applied to "for-next" until we have 7.0 M2 released.

**Comment by myungjoo** [comment]
@niley7464 has implemented most parts.

Now, remaining tasks are:
- fix test cases
- add test cases (of using RANK > 4)
- add test cases (checking backward compatibility along with #3937)
