### ISSUE TITLE
Simple Question) Batch size of nnstreamer

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3815]
# Issue Description

안녕하세요
nnstreamer의 tensor filter를 사용하여 pipeline을 구성하던 중, 
서로 다른 pipeline에 각각 tensor filter를 사용했을 때
개인적인 예상으로는 모델을 여러개 올린 셈이니 GPU 메모리가 거의 tensor filter 개수 배에 가깝게 늘어날 것이라 생각했는데
마치 뭔가 공유하고 있는 것 처럼 아주 약간의 메모리만 상승하는 것을 확인했습니다
(tensor filter 한개 사용 시 3315MiB, 두 개 사용시 4225MiB로 약 900MB만 증가)

1. 때문에 혹시 tensor filter를 여러개 사용하면 각 tensor filter가 모델의 파라미터를 공유하여 
마치 batch size를 늘린 것과 정확히 같은 효과를 가져오게 되는 건지 궁금합니다

2. 만약 아니라면, 혹시 모델의 무언가를 공유하는 구조때문에 성능상 문제가 있을 수 있는 건지 궁금합니다

3. 마지막으로 이건 NNStreamer와 관계없이, 이런 부분에 대해 여쭤볼 곳이 없어서 여쭤보는 문제인데 yolov5가 약 50fps까지
커버 할 수 있는 것을 확인하고, yolov5를 넣은 tensor filter를 여러개 사용하려고 하고 있는데, 총 FPS가 일정 수준부터는 늘어나질 않는 문제를 확인했습니다. GPU util은 75%정도에서 머물고 있고,  CPU사용량은 남고 각 스레드별로도 70%가량 사용중이며
network rx tx는 내부망 bandwidth에선 거뜬하고 pcie rx tx도 병목이 아닌걸 확인했는데 
어떤 이유에선 지 tensor_filter를 더 만들고 INPUT을 더 많이 넣어줘도 어디서 병목이 걸리는 것인지 일정한 FPS에 수렴하는 것 같습니다
혹시 이 부분이 모델간 무언가를 공유하는 문제로 발생하고 있을 가능성이 있을까요?
아니라면 어디가 또 병목이 될 수 있을까요?

너무 관계없는 질문도 드리는 것 같아 죄송합니다
읽어주셔서 감사합니다

Expected Result
============
tensor filter 수에 비례하는 GPU 메모리 사용량

How to Reproduce
===============
1. 한 프로세스 내에서 별개의 복수 파이프라인을 구성
2. 각 파이프라인에 tensor filter 포함
3. 스트리밍 시작 후 GPU 메모리 사용량 nvidia-smi로 체크

Further Information
===============
1. GPU 종류 : 3070ti, 3090

**Comment by myungjoo** [comment]
메모리 사용량 기준은 어떤것을 사용하시나요? RSS? PSS? VSS? VSS-peak? USS? .. Metric에 따라 측정치가 매우 크게 다르게 나올 수 있습니다. 예를 들어 Shared library의 code page가 상당히 큰 경우 위 값들은 서로 크게 다를 수 있고, 별도의 Process에서 Pipeline이 여럿 생겨날때 이들끼리 Share된 영역이 많이 나타날 수도 있습니다.

일반론적으로 말씀드려서, 사용되는 메모리 중 대부분이 Library code page인 경우 말씀하신 상황이 쉽게 나타납니다. 같은 모델화일을 두 Pipeline이 공유하는 경우 그 화일이 메모리에 Mapping된 영역이 공유되어 이러한 상황이 나타날 수도 있습니다. 사용된 메모리 중 어떤 부분이 Tensor값들을 다루고 있는 Heap인지를 파악해 보셔야 할 것입니다.

Shared library의 code 영역 공유라던가 file의 memory mapped영역 공유는 Linux가 성능 최적화를 위해 제공하는 기능입니다.

병목은 Thread 간 (CPU-GPU 간 포함) Synchronization (critical section)에 의해도 나타날 수 있고, memory & bus bandwidth에 의해 나타날 수도 있고, 폰 노이만 아키텍쳐의 최대 문제이기도 합니다. ^^
이부분은 제대로된 Profiler/Tracer 동원해서 동작 상황을 검사해 보셔야 합니다. (ARM이라면 DS-5 쓰시면 보통 잘 나옵니다.)

**Comment by myungjoo** [comment]
그리고 data stream에서는 batch size는 그다지 의미 없습니다.
Inference 위주이다 보니 batch size = 1 라고 가정되기는 합니다만,
Training을 하는 측에서 aggregate해서 마음대로 batch size를 가져가거나
tensor-aggregate로 직전에 batch 만들어 써도 됩니다.

물론 stream 내 단일 frame이 batch size > 1 을 가지도록 사용해도 문제는 없습니다.
counter intuitive하고 성능적인 이점도 없을 것 같을 뿐이고요.

**Comment by byungs2** [comment]
감사합니다 
메모리 메트릭같은건 알지도 생각도 못하고 있었고, 리눅스에서 말씀하신 최적화 기능을 제공하는줄도, 말씀하신 profiler, tracer에 관한 것들도 몰랐어서 좀 더 조사하는데 많은 도움이 되었습니다

다만 제가 이해를 잘 못한 부분을 좀 더 질문 드리고싶은게

1. 여러개의 파이프라인이 model file memory mapped 영역이 공유하면서 여러 input을 병렬적으로 처리하는 것과 배치 사이즈가 늘어나는 것과의 차이를 정확히 모르겠습니다
2. 만약 제가 생각한 것과 다르게 배치 사이즈가 늘어나는 것과 스레드가 늘어나는 것이 다르다면, thread sync 과정에서 병목이 발생할때 배치사이즈를 늘리는 것으로 병목을 해소할 수는 없을까요?

이상한 질문을 자꾸 드려 죄송합니다..

**Comment by myungjoo** [comment]
Batch size 늘리는 건 Training 할때 Training dataset을 묶는 것이고 학습효과 + 유사영역을 읽도록 해서 메모리 읽는 속도 (Cache 효과 증대 + Sequential read를 확대해서 SDRAM 특성 이용) 하는 것이지, 메모리 사용량 줄이기 위해 쓰는건 아닙니다. batch size 늘리면 일반적으로  peak memory는 늘어나겠지요. Inference때에는 Batch 늘린다고 성능적 이점이 있도록 framework를 만들지는 않았을것 같습니다. Real-time processing에서 그렇게 하면 latency 만 늘리기 딱 좋고요. Batch 이야기가 왜 나오는지 아직 잘 이해는 되지 않습니다.... 배치사이즈가 늘어나는 것과 Thread 늘려 쓰는게 어떤점이 유사한건지 잘 이해가 안됩니다. Inference때 배치 늘리면 자동으로 그만큼 Thread 늘려서 동시에 Inference 돌려주나요???

배치사이즈가 제가 생각한 그것이 아닌 다른 개념을 가져오셨을것 같기도 하고요.. Thread 동기화 문제는 그렇게 단순히 파라메터 조절로 어찌해볼 수 있는 문제는 아닙니다. 누가 어디서 뭐하면서 기다리는지 분석 가능해야 합니다. 혹시 이 THread들이 직접 만드신 Thread인가요? 아니면 사용하는 Framework내에서 알아서 만들어 쓸 것으로 "추측"되는 추상적인 것들인가요?

**Comment by byungs2** [comment]
답변 감사합니다
우선 말씀하신대로 제가 오해하고있는 상태로 배치 사이즈를 틀린 개념으로 말씀드린거 같아요
제가 제일 이해를 못하고 있는 부분이 아래와 같은데

640*640*3 짜리 input을 받는 모델이 있을 때
배치 사이즈를 N으로 늘리면 640*640*3*N input이 들어올텐데 이걸 640*640*3짜리 input을 받는 모델이 한번에 돌려줄 수 있나요?

망상하기로는 640*640*3 짜리 모델을 여러개 메모리에 넣어놓고 병렬적으로 Input들을 연산하거나, 모델 하나만 올려두고 여러 인풋 간에 모델을 공유해서 병렬적으로 연산하거나, 아님 그냥 직렬적으로 모델 하나를 여러번 돌려주거나 한다고 생각했었습니다.. 
근데 주변 동료분들께 여쭤보니, 배치사이즈를 늘리면 모델은 하나만 올려두고 인풋 여러개에 동시에 연산을 수행하도록 하는거라고 하시길래(이 부분도 이제 보니 제가 듣고 이상하게 오해한것 일 가능성이 커보이는데) 혼자 스레딩같은거구나.. 했던것 같습니다..

말씀하신 스레드는 사용하는 프레임워크인 gstreamer에서 알아서 만들어 쓸 것으로 추측되는 추상적인 것인데, 현재 사용중인 yolov5s에 최대 50fps까지만 속도가 나오고, gpu util은 낮은 상태에서 gpu를 최대한 쓰기 위해 파이프라인을 여러개 만들어서 모델을 여러개 올려 input을 더 많이 넣어주고 있는 상황인데요
이 상황에서 각gpu util, cpu 등 위 코멘트들에서 언급드렸던 부분들이 다 사용되지 않고 있음에도 성능이 마치 제한이 걸린 것처럼 일정한 (약 120fps) fps에서 모델 개수나 input fps등을 변경해봐도 넘지를 못하고 있습니다
때문에 이 부분이 파이프라인마다 알아서 만들어 쓸것으로 추측되는 추상적인 스레드간의 간섭으로 벌어질 수 있을거같았고, 혹시 그렇다면 파이프라인을 늘려서 input수를 늘리기보다 배치 사이즈를 늘려서 input수를 늘리면 뭔가 해소되는 부분이 있을 수 있지 않을까 했었습니다

일단 말씀해주신 것들을 참고해 제가 겪는 문제가 진짜 무엇인지부터 확인해보고 다시 질문드리겠습니다
바쁘신 와중 이상한 질문에도 대답해주셔서 감사합니다

**Comment by byungs2** [comment]
좀 더 정리가 된 후 다시 질문드리겠습니다 감사합니다
