### ISSUE TITLE
How do I set up the build to use the pytorch gpu supported by NNstreamer?

### ISSUE THREAD

**Issue by mars3219** [nnstreamer/nnstreamer#3868]
How do I set up the build to use the pytorch gpu supported by nnstreamer?

1) Download libtorch1.8.2-cuda11.1 compression file
2) Configuration and installation following installation information in nnstreamer git (except pytorch cpu installation)
3) In the pkgconfig folder, pytorch.Create pc
4) meson build
5) ninja -C build
6) Setting environmental variables in the docker file of git
7) make torchscript

I proceeded as above, but there is an error that cannot load the pytorch framework. I think the construction process is wrong while building, but it's hard to find the cause because I'm a beginner. I ask for your help me.

For your information, the contents of the pc file are as follows.

prefix=/usr/local/lib/libtorch
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

cudaroot=/usr/local/cuda-11.1/
cudalibdir=${cudaroot}/targets/x86_64-linux/lib
cudalibstubs=${cudalibdir}/stubs

Name: pytorch
Description: pytorch static library 1.8.2+cu111
Version: 1.8.2
Requires: nvrtc-11.1 nvToolsExt-11.1 cudart-11.1 cufft-11.1 curand-11.1 cublas-11.1
Libs: -L${libdir} -lc10 -lc10_cuda -ltorch -ltorch_cpu -ltorch_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -lgomp -lcudart -lnvToolsExt -L${cudalibstubs} -lcuda -L{cudalibdir} -lcudnn
Cflags: -I${includedir}

**Comment by mars3219** [comment]
Upload additional content.
I'm newbie for meson and ninja.
I understood that I need to rebuild to use the pytorch gpu version.
Could you tell me what settings I should set for Mason.build and meson_option?

**Comment by myungjoo** [comment]
Add the following options to meson:
```-Dpytorch-support=enabled -Denable-pytorch-use-gpu=true```

Because you are not using packaging system, you'll need to be careful with how you install built files, too; e.g., installation paths.
You can checkup the installation status with ```gst-inspect``` (whether nnstreamer itself is installed properly or not) and ```confchk``` (nnstreamer's utility that verifies installation status of its subplugins).

**Comment by mars3219** [comment]
Thank you your comments.

I builded the environment by referring to the dockerfile of nnstreamer git.
The libtorch1.8.2-cuda11.1 zip file was extracted to /usr/local/lib/libtorch inside the container that was created.
There are bin, lib, and include directories in the /usr/local/lib/libtorch.

Dockerfile is as follows.
# ARG UBUNTU_VER=18.04
# If the value assigned to MIN_RUN_ENV is non-zero length,
# only nnstreamer, nnstreamer-core, and nnstreamer-configuration packages are installed
# in the container.
ARG MIN_RUN_ENV=""
# FROM ubuntu:${UBUNTU_VER} AS dev-base
ARG PYTORCH="1.8.0"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel AS dev-base

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
ENV FORCE_CUDA="1"

ARG DEBCONF_NOWARNINGS="yes"
ARG DEBCONF_TERSE="yes"
ARG LANG="C.UTF-8"
ARG BUILDDIR=build
ARG LIBTORCH=/usr/local/lib/libtorch

ENV DEBIAN_FRONTEND noninteractive

RUN set -x && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC && \
    echo "debconf debconf/frontend select ${DEBIAN_FRONTEND}" | debconf-set-selections && \
    echo 'APT::Install-Recommends "false";' | tee /etc/apt/apt.conf.d/99install-recommends && \
    echo 'APT::Get::Assume-Yes "true";' | tee /etc/apt/apt.conf.d/99assume-yes && \
    sed -Ei 's|^(DPkg::Pre-Install-Pkgs .*)|#\1|g' /etc/apt/apt.conf.d/70debconf && \
    apt-get update && \
    apt-get install software-properties-common && \
    add-apt-repository ppa:nnstreamer/ppa -u && \
    add-apt-repository ppa:one-runtime/ppa -u && \
    apt-get install git \
        equivs \
        devscripts

SHELL ["/bin/bash", "-c"]
WORKDIR /home
RUN git clone https://github.com/mars3219/nnstreamer.git
WORKDIR /home/nnstreamer

RUN mk-build-deps debian/control
RUN apt-get -f install ./nnstreamer-build-deps*.deb && \
    rm -f ./nnstreamer-build-deps*.deb && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY ./libtorch-cxx11-abi-shared-with-deps-1.8.2+cu111.zip /usr/local/lib/
RUN unzip /usr/local/lib/libtorch-cxx11-abi-shared-with-deps-1.8.2+cu111.zip -d /usr/local/lib/ && \
    rm -rf /usr/local/lib/libtorch-cxx11-abi-shared-with-deps-1.8.2+cu111.zip
    # mv /usr/lib/pkgconfig/pytorch.pc /usr/lib/pkgconfig/pytorch.pc.backup

COPY ./pytorch.pc /usr/lib/pkgconfig

WORKDIR /home/nnstreamer

RUN meson ${BUILDDIR} --prefix=/ --sysconfdir=/etc --libdir=/usr/lib --bindir=/usr/bin --includedir=/usr/include && \
    ninja -C ${BUILDDIR}

ENV GST_PLUGIN_PATH=/home/nnstreamer/${BUILDDIR}/gst/nnstreamer \
    NNSTREAMER_CONF=/home/nnstreamer/${BUILDDIR}/nnstreamer.ini \
    NNSTREAMER_FILTERS=/home/nnstreamer/${BUILDDIR}/ext/nnstreamer/tensor_filter \
    NNSTREAMER_DECODERS=/home/nnstreamer/${BUILDDIR}/ext/nnstreamer/tensor_decoder \
    NNSTREAMER_CONVERTERS=/home/nnstreamer/${BUILDDIR}/ext/nnstreamer/tensor_converter \
    NNS_BUILDDIR=${BUILDDIR} \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/local/libtorch/lib \
    C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include:/usr/local/libtorch/include \
    CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include:/usr/local/libtorch/include \
    PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig


Modify items below.
Modified option('pytorch-support', type: 'feature', value: 'enabled'), option('enable-pytorch-use-gpu', type: 'boolean', value: true) at meson_option.txt
Deleted phytorch framework from debian/control.

The contents of the .pc file are as above.

When I build meson, there is an error that the pytorch framework cannot be loaded.
I don't know whether the dir path of the framework is a problem or a problem of setting environmental variables.

After running container, there are no libtorch related so-files in the container's /usr/lib path.
Is it related to setting environment variables or setting meson build dir?
Thank you for your comment in advance.

**Comment by anyj0527** [comment]
Check my step to test pytorch-1.10.1 with nnstreamer:
1. Download "libtorch-cxx11-abi-shared-with-deps-1.10.1+cpu" from pytorch.org and unzip it at some path. Let's say the path is PYTORCH_PREBUILT_PATH
2. Make a pc file "pytorch.pc" and fill it with:
    ```
    prefix=PYTORCH_PREBUILT_PATH/libtorch
    exec_prefix=${prefix}
    includedir=${prefix}/include
    libdir=${exec_prefix}/lib
    sharedlibdir=${prefix}/share
    
    Name: pytorch
    Description: pytorch static library
    Version: 1.10.1
    Libs: -L${libdir} -L${sharedlibdir} -lc10 -ltorch -ltorch_cpu
    Cflags: -I${includedir}
    ```
3. Build NNStreamer and Install it. You may fix unused variable warning-errors.
4. export LD_LIBRARY_PATH=PYTORCH_PREBUILT_PATH/libtorch/lib:$LD_LIBRARY_PATH
5. Test pytorch filter. What I did was `bash runTest.sh` in nnstreamer/test/nnstreamer_filter_pytorch

Disclaimer: I don't have proper cuda resources so the test was executed in pytorch-cpu version

**Comment by myungjoo** [comment]
With no further follow-ups, I assume that the issue is resolved. Reopen this if you are still struggling with the issue.
