### ISSUE TITLE
Request for Clarification (doxygen comments) on NNStreamer-Edge Interface

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3882]
1. More detailed explanations for APIs (as doxygen entries)
2. For stream-pub, stream-sub, query-server, query-client usage cases, provide example usages (pseudo code) on the top as comments.

**Comment by gichan-jang** [comment]
Closed via https://github.com/nnstreamer/nnstreamer-edge/pull/64
