### ISSUE TITLE
How to write custom tensor filter with different size of output tensor from frame to frame

### ISSUE THREAD

**Issue by bruecks** [nnstreamer/nnstreamer#3926]
I would like to write a custom tensor filter that accepts a static tensor and returns a flexible tensor. The dimensions of the flexible tensor are different from frame to frame and only known after invoking the filter on the frame under consideration. Is this possible with the flexible tensor? If yes how do I implement it?

**Comment by bruecks** [comment]
If I look into the function gst_tensor_filter_transform of the file tensor_filter.c, I see that the output buffer can be allocated in invoke, but still a value is assigned to the size of the tensor in line 675 and other info about the tensor in line 679, which should not be known yet.
out_tensors[i].size = gst_tensor_filter_get_tensor_size (self, i, FALSE);

Furthermore, I do not understand the use case of the function getModelInfo. In a case of a flexible tensor, I think ops == SET_INPUT_INFO must write to GstTensorsInfo &in_info and GstTensorsInfo &out_info. But where is this info used considering that the tensor gets allocated in invoke and invoke does not have access to the TensorsInfo.

**Comment by myungjoo** [comment]
I thought flexible tensors with tensor_filter would resolve this. However, as @jaeyun-jung has confirmed, it's not yet implemented and tensor_filter assumes dimensions to be constant as long as GSTCAP is fixed.

Although it appears that your requirements can be met with a workaround consisting of tensor_filter and tensor_decoder as @jaeyun-jung has mentioned in the mailing list, we are going to resolve this with more elegant solution with #3931 .

**Comment by gichan-jang** [comment]
Close with this PR: https://github.com/nnstreamer/nnstreamer/pull/4073
