### ISSUE TITLE
Tensor_filter w/ dynamic flexible streams, changing input/output dimensions.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3931]
With a model that can handle varying input dimensions (and output dimensions), this features needs to run test cases that look like:

```
videotestsrc 640x480 ! tensor_converter ! other/tensors,format=flexible ! join name=j ! tensor_filter some filter ! other/tensors,format=flexible ! filesink testfile
      videotestsrc 320x240 ! tensor_converter ! other/tensors,format=flexible ! j.
      videotestsrc 200x200 ! tensor_converter ! other/tensors,format=flexible ! j.
    # see if the output is consistent with what we've intended.
```

We need to make sure that such usages of flexible tensors work.

**Comment by myungjoo** [comment]
@jaeyun-jung @gichan-jang : This is done, right?

**Comment by gichan-jang** [comment]
Right. It's finished. For each nnfw sub-plugin, the dynamic invoke function should be implemented whenever necessary.
