### ISSUE TITLE
Dimension Declaration and Compatibility.

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3937]
It is supposed that

```N:M``` == ```N:M:1``` == ```N:M:1:1```

However, we no longer have proper test cases for such and it appears that it is no longer supported. This is a serious regression.

Todo:
1. Allow to declare without trailing ```:1``` and keep the compatibility in GSTCAP and dimensions properties.
2. Make enough test cases for different elements.

@niley7464 As you've been looking at the issue of RANK>4, this is highly related with the code you are already looking at and modifying. Please take a look at this issue along with RANK>4 issue.

**Comment by niley7464** [comment]
I will check it along with RANK issue :)
