### ISSUE TITLE
Simple question) Join element code

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#3938]
# Issue Description
Hi 
thanks for your elements.
Recently I tried to make element that has similar purpose of join element in nnstreamer.
Because It is my first time of making gst element, so I'm trying to reference join element.
While doing that I read code line as below and just wonder purpose of this line (gstjoin.c line 418)

I'm not sure but perhaps prev_active_sinkpad != active_sinkpad && selpad->events_pending would be more correct?
```
  /* if we have a pending events, push them now */
  if (G_UNLIKELY (prev_active_sinkpad != active_sinkpad
          || selpad->events_pending)) {
    gst_pad_sticky_events_foreach (GST_PAD_CAST (selpad), forward_sticky_events,
        sel);
    selpad->events_pending = FALSE;
  }
 ```

**Comment by myungjoo** [comment]
PTAL: @gichan-jang (the author of gstjoin)

**Comment by gichan-jang** [comment]
@byungs2, Thanks for posting the issue.
I think the current conditions are right.
`prev_active_sinkpad != active_sinkpad` 
 ->To process the pending event when the pad is changed
`selpad->events_pending`
 -> The active pad is not changed, but if there is a pending event, process it.

If there is anything unclear, please ask again.
And `gstjoin` is a modified gstinputselector. If necessary, refer to the code as well.

I have a question, what is the purpose of the element you are making?

**Comment by byungs2** [comment]
My pipeline should handle M:N relation between data source and tensor_filter.
In my pipeline there has problem of source and sink scheduling.
For example, If I attach 6 rtsp source to 3 tensor filter, then there have two type of peak.
First one is CPU peak for decoding rtspsrc at the same time.
And second one is GPU peak for invoke model at the same time.
Becuase of those two kind of peak, My pipeline needs more resource to inference multiple sources.
So now I'm trying to make an element that perform like threadpool things for M:N source & sink pad.
It is not only purpose of solving problem, also purpose to improve my skills with GObject and Gstreamer.

**Comment by myungjoo** [comment]
If you have multiple sources and, possibly, multiple destinations, you may need to track the data origin for each frame, too.

To implement such capability, refer to tensor_query_serversink/src for tracking such data in each frame; it accepts data from multiple clients and sends back the results to the corresponding clients.

**Comment by byungs2** [comment]
Thanks for your advice.
I'm gonna read those elements code too.
