### ISSUE TITLE
PyTorch support for macOS build

### ISSUE THREAD

**Issue by notsimon** [nnstreamer/nnstreamer#3953]
I am trying to build nnstreamer from source with support for torchscript models on macOS Monterey. libtorch has been installed from homebrew and pytorch from pip3. Meson doesn't seem to detect the dependencies and therefore disables pytorch support.

[The documentation](https://nnstreamer.github.io/getting-started-macos.html) for building from source on macOS uses `-Dpytorch-support=disabled` (as well as for all the other deep learning frameworks), so I suppose this is not supported at the moment?

I'm willing to do a PR if you can provide some guidance as to where I should look to fix this 🙂

**Comment by notsimon** [comment]
I found in [another issue](https://github.com/nnstreamer/nnstreamer/issues/3868#issuecomment-1207668795) that it is recommended to make a pkg-config file for pytorch. This is actually not required as `dependency()` can use cmake to find the packages.

https://github.com/nnstreamer/nnstreamer/blob/b55d44cdb8faa080f9067b99486a6026143412f2/meson.build#L354-L357

In the file above adding `Torch` as alternative target did the job, not sure if that's an issue elsewhere. 

```meson
  'pytorch-support': {
    'target': 'pytorch',
    'target_alt': 'Torch',
    'project_args': { 'ENABLE_PYTORCH': 1 }
  },
```

Note that I also had to configure with `-Dwerror=false -Denable-tizen=false -Denable-test=false` to get the project to build.

Sadly, I am now stuck further away. I am using a `yolov5s.torchscript` exported from [ultralytics/yolov5](https://github.com/ultralytics/yolov5) with the following pipeline:

```
gst-launch-1.0 \
    videotestsrc \
    ! video/x-raw,width=640,height=640,format=RGB,framerate=30/1 \
    ! tensor_converter \
    ! tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 \
    ! tensor_filter framework=pytorch model=yolov5s.torchscript \
    ! fakesink
```

which gives me the error:

```
** Message: 19:46:36.688: gpu = 0, accl = cpu
**
ERROR:.../nnstreamer/gst/nnstreamer/tensor_filter/tensor_filter_common.c:2354:gst_tensor_filter_load_tensor_info: assertion failed: (in_info.num_tensors > 0)
Bail out!
ERROR:.../nnstreamer/gst/nnstreamer/tensor_filter/tensor_filter_common.c:2354:gst_tensor_filter_load_tensor_info: assertion failed: (in_info.num_tensors > 0)
.../nnstreamer/run_ssd.sh: line 17: 10251 Abort trap: 6
```

**Comment by myungjoo** [comment]
> In the file above adding Torch as alternative target did the job, not sure if that's an issue elsewhere.

If that did work, please submit a PR. That's a good news. :)

> Note that I also had to configure with -Dwerror=false -Denable-tizen=false -Denable-test=false to get the project to build.

- ```-Denable-tizen``` is false by default. So, this is find.
- If ```-Denable-test``` is required to be false in MacOS, it means we will need to fix something someday.
- If ```-Dwerror=false``` is required, it also means that we will need to fix something soon.

For now, it's ok, but worth a few PRs to fix the two points.


> Sadly, I am now stuck further away. I am using a yolov5s.torchscript exported from [ultralytics/yolov5](https://github.com/ultralytics/yolov5) with the following pipeline:

The error message implies that we cannot get input/output dimension information from this yolov5s.torchscript . Can you give a URL to get the very file you are using? One possibility is that this torchscript file is not ready for deployment or not compatible with PyTorch API of ```std::make_shared<torch::jit::script::Module> (torch::jit::load (model_path))```.

**Comment by anyj0527** [comment]
You may check following pipeline and the result, which is done in my local env (build with libtorchv1.10.1 and use model yolov5s.torch.script.pt exported by yolov5 project guide):

```bash
$ gst-launch-1.0 videotestsrc ! videoscale ! videoconvert ! video/x-raw,width=640,height=640,format=RGB ! \
tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:640:640:1 ! \
tensor_transform mode=transpose option=2:1:0:3 ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=640:640:3:1 ! \
tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
tensor_filter framework=pytorch model=./yolov5s.torchscript.pt input=640:640:3:1 inputname=image inputtype=float32 output=1:25200:85.3:80:80:85.3:40:40:85.3:20:20:85 outputname=a,b,c,d outputtype=float32.float32.float32.float32 latency=1 ! \
other/tensors,num_tensors=4,format=static ! tensor_sink
** Message: 13:42:22.084: gpu = 0, accl = cpu
** INFO: 13:42:22.192: Filter pytorch with model file ./yolov5s.torchscript.pt is opened. It took 107854 us
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
** (gst-launch-1.0:27416): DEBUG: 13:42:22.197: Failed to validate tensors info. the number of tensors: 0. the number of tensors should be greater than 0.
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
** INFO: 13:42:25.356: [./yolov5s.torchscript.pt] Invoke took 2916.346 ms
** INFO: 13:42:25.473: [./yolov5s.torchscript.pt] Invoke took 105.507 ms
** INFO: 13:42:25.582: [./yolov5s.torchscript.pt] Invoke took 98.263 ms
** INFO: 13:42:25.686: [./yolov5s.torchscript.pt] Invoke took 94.251 ms
** INFO: 13:42:25.789: [./yolov5s.torchscript.pt] Invoke took 92.931 ms
** INFO: 13:42:25.894: [./yolov5s.torchscript.pt] Invoke took 95.443 ms
** INFO: 13:42:26.000: [./yolov5s.torchscript.pt] Invoke took 94.926 ms
** INFO: 13:42:26.105: [./yolov5s.torchscript.pt] Invoke took 95.727 ms
** INFO: 13:42:26.213: [./yolov5s.torchscript.pt] Invoke took 97.658 ms
** INFO: 13:42:26.317: [./yolov5s.torchscript.pt] Invoke took 94.239 ms
** INFO: 13:42:26.425: [./yolov5s.torchscript.pt] Invoke took 97.644 ms
** INFO: 13:42:26.530: [./yolov5s.torchscript.pt] Invoke took 95.008 ms
** INFO: 13:42:26.635: [./yolov5s.torchscript.pt] Invoke took 94.531 ms
** INFO: 13:42:26.738: [./yolov5s.torchscript.pt] Invoke took 93.216 ms
** INFO: 13:42:26.844: [./yolov5s.torchscript.pt] Invoke took 96.153 ms
** INFO: 13:42:26.949: [./yolov5s.torchscript.pt] Invoke took 94.333 ms
** INFO: 13:42:27.054: [./yolov5s.torchscript.pt] Invoke took 94.882 ms
** INFO: 13:42:27.156: [./yolov5s.torchscript.pt] Invoke took 92.059 ms
** INFO: 13:42:27.259: [./yolov5s.torchscript.pt] Invoke took 92.954 ms
** INFO: 13:42:27.363: [./yolov5s.torchscript.pt] Invoke took 94.733 ms
** INFO: 13:42:27.470: [./yolov5s.torchscript.pt] Invoke took 95.829 ms
** INFO: 13:42:27.575: [./yolov5s.torchscript.pt] Invoke took 94.806 ms
** INFO: 13:42:27.679: [./yolov5s.torchscript.pt] Invoke took 93.415 ms
** INFO: 13:42:27.783: [./yolov5s.torchscript.pt] Invoke took 94.105 ms
** INFO: 13:42:27.888: [./yolov5s.torchscript.pt] Invoke took 94.747 ms
** INFO: 13:42:27.992: [./yolov5s.torchscript.pt] Invoke took 94.563 ms
** INFO: 13:42:28.096: [./yolov5s.torchscript.pt] Invoke took 93.791 ms
** INFO: 13:42:28.201: [./yolov5s.torchscript.pt] Invoke took 94.667 ms
** INFO: 13:42:28.305: [./yolov5s.torchscript.pt] Invoke took 94.311 ms
** INFO: 13:42:28.409: [./yolov5s.torchscript.pt] Invoke took 93.757 ms
** INFO: 13:42:28.513: [./yolov5s.torchscript.pt] Invoke took 94.058 ms
** INFO: 13:42:28.617: [./yolov5s.torchscript.pt] Invoke took 94.381 ms
** INFO: 13:42:28.722: [./yolov5s.torchscript.pt] Invoke took 94.762 ms
** INFO: 13:42:28.828: [./yolov5s.torchscript.pt] Invoke took 95.826 ms
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:06.496377810
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
** INFO: 13:42:28.933: [./yolov5s.torchscript.pt] Invoke took 95.185 ms
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by notsimon** [comment]
@myungjoo I'll make a PR and update the documentation accordingly.
@anyj0527 Indeed that works with my model 👏

Thanks to you both for your quick answers!
