### ISSUE TITLE
How about object tracking?

### ISSUE THREAD

**Issue by fengxueem** [nnstreamer/nnstreamer#3956]
Congrats on this well-designed AI streaming framework. BIG Thumbs UP!
Here is a problem. How does this classic CV algorithm, object tracking, fit into NNStreamer? Since, object tracking is mandatory in many scenarios like, ADAS, Surveillance Camera, etc.
DLStreamer2.0 and DeepStream6.1.1 have their own tracker gst element, gvatrack and Gst-nvtrack. I would like to see NNStreamer's solution.

**Comment by myungjoo** [comment]
NNStreamer design is orthogonal to tensor semantics.

Whether it is object tracking, semantic segmentation, automatic language translation, object classification, lane detection for autonomous vehicles, lane changes, recommendation systems, or so on should NEVER matter as long as the writers understand their neural network models.

So, in short answer, yes, you can apply object tracking.

**Comment by fengxueem** [comment]
Thanks for this super-quick reply.

**Comment by gichan-jang** [comment]
> we need to make sure a person should always be tracked from its first appearence, but only be age-predicted once, 

To to that, How about using input and output selector?
```
... Tensor-Filter(person tracking)->Tensor-Decoder(mode=tracks)-> output selector ----------------------------------------------------------------------->input selector ->Tensor-Sin
                                                                                  |->Tensor-Filter(age-prediction)->Tensor-Decoder(mode=image_labeling)-|
```

**Comment by fengxueem** [comment]
> > we need to make sure a person should always be tracked from its first appearence, but only be age-predicted once,
> 
> To to that, How about using input and output selector?
> 
> ```
> ... Tensor-Filter(person tracking)->Tensor-Decoder(mode=tracks)-> output selector ----------------------------------------------------------------------->input selector ->Tensor-Sin
>                                                                                   |->Tensor-Filter(age-prediction)->Tensor-Decoder(mode=image_labeling)-|
> ```

Could you share more thoughts about input and output selector? I am not quite following up. Thanks.

**Comment by myungjoo** [comment]
tensor_if might be useful if you want to run age-prediction conditionally.

**Comment by gichan-jang** [comment]
> > > we need to make sure a person should always be tracked from its first appearence, but only be age-predicted once,
> > 
> > 
> > To to that, How about using input and output selector?
> > ```
> > ... Tensor-Filter(person tracking)->Tensor-Decoder(mode=tracks)-> output selector ----------------------------------------------------------------------->input selector ->Tensor-Sin
> >                                                                                   |->Tensor-Filter(age-prediction)->Tensor-Decoder(mode=image_labeling)-|
> > ```
> 
> Could you share more thoughts about input and output selector? I am not quite following up. Thanks.

You can set the stream path according to the condition from the app level.
For output-selector, you can set the active-pad.
Or as myungjoo mentioned, you can use tensor_if custom condition.

**Comment by fengxueem** [comment]
Thx @myungjoo and @gichan-jang.
Based on gichan's proposal, at least 2 kinds of Gst element will get involved, one for output-selector and the other for input-selector.(I am curious that are there any exsiting elements satisfying the conditional output/input-selector requirement.)After building a working pipeline, developer should use NNStreamer create a app to dynamically set element property during pipeline runtime.
Based on Dr. Ham's proposal, the Tensor-if could be the preferred approach.
This discussion is so far focused on one case:

> a concrete scenario, person detection, tracking, age-prediction and on-screen-display

About the more general question: What is a proper way for NNStreamer pipeline to support various features/needs coming from application-level/client? Based on the previous discussion and my poor development experience, I am assuming there are 2 ways: 
1. put client's-problem-solving-codes in custome .so, set .so to NNStreamer element and build a static NNStreamer pipeline, start the pipeline using **gst-launch-1.0** once for all.
2. (A)write an app using NNStreamer SDK, (B)put client's-problem-solving-codes somewhere in the same app, (C)try to glue (A) and (B) together elegantly.

Looking forward to any thoughts and ideas.

**Comment by gichan-jang** [comment]
> About the more general question: What is a proper way for NNStreamer pipeline to support various features/needs coming from application-level/client? Based on the previous discussion and my poor development experience, I am assuming there are 2 ways:
 > 1. put client's-problem-solving-codes in custome .so, set .so to NNStreamer element and build a static NNStreamer pipeline, start the pipeline using gst-launch-1.0 once for all.
 > 2. (A)write an app using NNStreamer SDK, (B)put client's-problem-solving-codes somewhere in the same app, (C)try to glue (A) and (B) together elegantly.

If you want to process tensors as custom, you can use the custom or custom-easy mode of tensor_filter.
You can load .so using tensor filter custom.
 * Refer here for custom filter:
    - https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/include/tensor_filter_custom.h
    - https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_example/custom_example_passthrough/nnstreamer_customfilter_example_passthrough.c
    -  https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_custom/runTest.sh

And if you want to process it as code in the app, use custom-easy.
 * Refer here to how to use custom filter: 
     - https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/include/tensor_filter_custom_easy.h
     - https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_custom/runTest.sh

To use input-selector or output-selector, you should write an app.
gst-launch-1.0 is a debugging tool for checking the operation of a pipeline simply.
You would be better write the app using gst_parse_launch for production.
 - Simple NNStreamer app: https://github.com/nnstreamer/nnstreamer-example/tree/main/native/example_object_detection_tensorflow_lite

**Comment by fengxueem** [comment]
Closing this Issue. However, any further ideas are more than welcome to share.
