### ISSUE TITLE
[CI/Clang] How about adding a new GitHub Actions workflow that checks clang-build?

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer#3979]
**Is your feature request related to a problem? Please describe.**
Related to #3978 

**Describe the solution you'd like**
As the other checks with GCC do, it would be helpful if CI checks the clang-build.

**Describe alternatives you've considered**
At the current moment, rejecting PRs by the proposed workflow looks a little bit improper.
Instead, just checking might be OK.

**Comment by myungjoo** [comment]
Yes. It's perfectly fine to add a clang-build test.

You may add one more workflow. Or... you may add "clean && clang-build" step to https://github.com/nnstreamer/nnstreamer/blob/main/.github/workflows/ubuntu_clean_meson_build.yml ,

**Comment by wooksong** [comment]
If no one minds, I will take this issue.
