### ISSUE TITLE
nnstreamer pipeline with yolov5 - fully integer quantized model

### ISSUE THREAD

**Issue by costaz9** [nnstreamer/nnstreamer#3999]
Hi, I have succesfully converted yolov5 model in TensorFlow Lite. However, the suggested pipeline in the previous issues for yolov5 (https://github.com/nnstreamer/nnstreamer/pull/3628#issue-1092286401) seems to work only for some quantization type. In particular the full integer quantization model seems to not work, but also float fallback.

I attach the gst-launch pipeline that works well with the simple tflite model and the dinamyc range quantized model. Do you have any suggestions to modify the pipeline for full integer quantization, or there are other related issues?.

```
gst-launch-1.0 \
v4l2src device=/dev/video0 \
! videoscale ! videoconvert ! video/x-raw,width=416,height=416,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t \
  t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:416:416:1 ! \
    tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! queue leaky=2 max-size-buffers=2 ! \
    tensor_filter framework=tensorflow2-lite model=$YOLOV5_MODEL_PATH ! \
    other/tensors,num_tensors=1,types=float32,format=static,dimensions=85:10647:1:1 ! \
    tensor_decoder mode=bounding_boxes option1=yolov5 option2=$YOLOV5_LABEL_PATH option4=416:416 option5=416:416 ! \
    video/x-raw,width=416,height=416,format=RGBA ! mix.sink_0 \
  t. ! queue ! mix.sink_1 \
compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! fpsdisplaysink video-sink=ximagesink text-overlay=false sync=false -v 2>&1
```
Thanks for your time.

**Comment by anyj0527** [comment]
@costaz9 Please consider this pipeline:
```
gst-launch-1.0 filesrc location=bus.jpg ! jpegdec ! videoscale ! videoconvert ! \
video/x-raw,width=810,height=1080,format=RGB,framerate=0/1 ! tee name=t   \
  t. ! queue ! videoscale ! video/x-raw,width=416,height=416,format=RGB ! tensor_converter ! \
    other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:416:416:1 ! \
    queue ! tensor_filter framework=tensorflow2-lite model=yolov5s-416-int8.tflite  ! \
    other/tensors,format=static,num_tensors=1,dimensions=85:10647:1:1,types=uint8 ! \
    tensor_transform mode=arithmetic option=typecast:float32,add:-3.0,mul:0.004723627585 ! \
    queue ! tensor_decoder mode=bounding_boxes option1=yolov5 option2=./coco.txt option4=810:1080 option5=416:416 ! \
    video/x-raw,width=810,height=1080,format=RGBA ! mix.sink_0  \
  t. ! queue ! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! \
    videoconvert ! pngenc ! filesink location=bus_boxes_tflite_int8.png
```

The used input image is from the reference bus image from yolov5 project.
And the  model `yolov5s-416-int8.tflite` is made from command:
`python export.py --weights yolov5s.pt --imgsz=416 --include tflite --int8`

Note that this int8 quantized model requires uint8 input type and dequantizing the output values.
The dequantization information`tensor_transform mode=arithmetic option=typecast:float32,add:-3.0,mul:0.004723627585` is from the model iself.

**Comment by myungjoo** [comment]
Without further follow-ups or dicsussion, I'm closing questions and discussions.
