### ISSUE TITLE
question about tensor_filter caps negotiation & tensor_converter query caps function with reconfigure situation

### ISSUE THREAD

**Issue by byungs2** [nnstreamer/nnstreamer#4064]
Hi

Casue I'm still not familiar with gstreamer caps negotiation processes, I have questions about reconfigure situations..

my test pipeline is as below

```
join name=j \
rtspsrc ! decodebin ! videorate drop-only=1 ! videoconvert ! videoscale ! video/x-raw,format=RGB,framerate=15/1 ! j.sink_0 \
rtspsrc ! decodebin ! videorate drop-only=1 ! videoconvert ! videoscale ! video/x-raw,format=RGB,framerate=15/1 ! j.sink_1 \
... 
rtspsrc ! decodebin ! videorate drop-only=1 ! videoconvert ! videoscale ! video/x-raw,format=RGB,framerate=15/1 ! j.sink_%u \
j. !  \
tensor_converter ! \
tensor_transform mode=1 option=float32 ! \
tensor_transform mode=dimchg option=0:2 ! \
queue ! \
tensor_filter framework=pytorch anymodel ! \
tensor_sink
```

when I changed capsfilter framerate from 15/1 to 1/1 all on pipeline fly, then there has some problems with tensor_converter & tensor_filter

1. tensor_converter get query caps from upstream element, and then call gst_tensor_converter_query_caps. 
but It seems that when calling gst_caps_intersect_full in the tensor converter, it always returns an empty caps if a part of the caps has changed because it retrieves the current caps of the already-negotiated pad. Therefore, it appears that caps reconfiguration is not being performed.

If first problem is resolved, then tensor_filter has problem.

2. when its priv->configured is TRUE, tensor_filter doesn't allow different in_config, out_config. 
but after negotiated, I don't know how to change priv->configured from TRUE to FALSE again..

So my question is how to change framerate correctly in this pipeline situation.. 
thanks for reading

**Comment by myungjoo** [comment]
I'd recommend to add ```rate``` property to videorate and try not to control framerate with gstcap.

Ideally, with FIVE streams with 1/1 Hz joined, the output of join should be 5/1 Hz, but join does not touch framerate, which may cause problems if you rely on framerate information while using join.

And please make sure that all the joined streams have the SAME gstcap, including the size and colorspace.

You may use ```tensor_debug``` to printout gstcaps in pipeline. (not sure if it works, it's untested experimental code :)  )

**Comment by byungs2** [comment]
I understood what you said
Thanks for reply..

**Comment by myungjoo** [comment]
Anyway, if you want to have JOIN understand framework properties, you can add such features by commiting a few code lines to join.c :)

**Comment by byungs2** [comment]
Thanks for encourage me😭
