### ISSUE TITLE
Is there a gst-launch-1.0 command for tensor_filter mediapipe?

### ISSUE THREAD

**Issue by Ar4enal** [nnstreamer/nnstreamer#4067]
I want to use [selfie_segmentation](https://google.github.io/mediapipe/solutions/selfie_segmentation) in nnstreamer.

**Comment by myungjoo** [comment]
You may call mediapipe pipeline with tensor_filter::mediapipe (/ext/nnstreeamer/tensor_filter/tensor_filter_mediapipe.cc). But that's just an experimental feature that is not for actual production. It is always more efficient to run without meidapipe pipelines.

Just download the model file (.tflite file) and run it within an nnstreamer/gstreamer pipeline as @anyj0527 has suggested. If you need visualization, you may need to write a corresponding tensor_decoder subplugin. If you don't need visualization (as most productions), it'd be a straightforward gstreamer pipeline.

**Comment by anyj0527** [comment]
@myungjoo @Ar4enal 
Just downloading the model file and running pipeline is not possible for the second model file in the link. It has custom op in itself. Check https://github.com/anyj0527/nnstreamer_pipeline_zoo/tree/main/selfie_segmentation to resolve the issue.

**Comment by Ar4enal** [comment]
> @myungjoo @Ar4enal Just downloading the model file and running pipeline is not possible for the second model file in the link. It has custom op in itself. Check https://github.com/anyj0527/nnstreamer_pipeline_zoo/tree/main/selfie_segmentation to resolve the issue.

Thank you so much for replying.

I have downloaded this model and run it. It can run successfully. 

Howerver, I do not know the output format of this selfie_segmentation_256_256.tflite. I want to change the background into green and show no color on the person. How to use the tensor_decoder instead of `tensor_decoder mode=direct_video` ?

I use `tensor_decoder mode=image_segment option1=tflite-deeplab` and GSTREAMER shows the error: `invalid input data format detected`

**Comment by myungjoo** [comment]
Being able to use direct_video means that the tensor format is already in ```video/x-raw```. You can use general gstreamer media filters after it's converted to video w/ direct_video for color conversion, before feeding to compositor.
