### ISSUE TITLE
Unable to locate package nnstreamer-example (Ubuntu 22.04)

### ISSUE THREAD

**Issue by pedrobagatin** [nnstreamer/nnstreamer#4088]
```
sudo apt-get install nnstreamer-example
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nnstreamer-example
```

After adding ppa repository:
`sudo add-apt-repository ppa:nnstreamer-example/ppa`

**Comment by myungjoo** [comment]
Uh.. yes.. nnstreamer-example at Ubuntu didn't enable 22.04 release: https://code.launchpad.net/~nnstreamer/+recipe/nnstreamer-example

I've just added Jammy a few seconds ago and it will become available soon.

**Comment by myungjoo** [comment]
https://github.com/nnstreamer/nnstreamer-example/pull/300 will enable Ubuntu 22.04 ppa for nnstreamer-example

**Comment by myungjoo** [comment]
Nnstreamer-example for Ubuntu 22.04 appears in the PPA repository: https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+packages
