### ISSUE TITLE
Yolov5 Model w/ Custom Dataset

### ISSUE THREAD

**Issue by learytomlin** [nnstreamer/nnstreamer#4105]
I've trained a yolov5 model with custom COCO dataset to perform object detection on a single class (i.e., people). I've confirmed the model is working as expected before and after converting the model (e.g., mymodel.pb to my model.tflite). I've constructed a pipeline similar to the one below using a updated COCO labels file that only includes one class. This pipeline is very similar to the one shared in issue #3995, and like that issue I believe the problem I've encountered is due to the yolov5 decoder expecting a single output tensor, with dimension 85:X:1:1. However, my model provides a single output tensor, with dimension 6:X:1:1, as I am only using one class. What are my options? I assume writing my own version of the yolov5_boundingboxes decoder is an option or is there some option in the pipeline (e.g., other/tensors,num_tensors=1,types=float32,format=static,dimensions=6:X:1:1) that I can use? I spent some time looking at this so any help would be greatly appreciated.  

`gst-launch-1.0 v4l2src device=/dev/video1 ! video/x-raw,width=640,height=480,framerate=30/1 ! tee name=t t. ! queue max-size-buffers=2 leaky=2 ! imxvideoconvert_g2d ! video/x-raw,width=416,height=416,format=RGBA ! videoconvert ! video/x-raw,format=RGB ! tensor_converter ! tensor_filter framework=tensorflow-lite model=mymodel.tflite custom=Delegate:External,ExtDelegateLib:libvx_delegate.so ! tensor_decoder mode=bounding_boxes option1=yolov5 option2=my_coco_labels.txt option4=640:480 option5=416:416 ! mix. t. ! queue max-size-buffers=2 ! imxcompositor_g2d name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink`

Please let me know if you would like a copy of my model to reproduce the issue.

**Comment by myungjoo** [comment]
If the issue is having 6:X:1:1 instead of 85:X:1:1 and that 6 are subset of 85, I think you can simply do zero-padding to the rest (79 entries of 85).

You may do so with the model itself.
Or, you may write a custom filter in C/Pytho/Lua (or custom-easy as a C-function) that do the padding.

We may implement a zero-padding operator in tensor-transform in the future.
@anyj0527 how do you think about this idea? as the next OJT item for Suyeon?

**Comment by myungjoo** [comment]
If you want to add a custom-filter to change dimensions, please refer to:

- Add a Python script in a pipeline to process tensors: https://github.com/nnstreamer/nnstreamer/tree/main/tests/nnstreamer_filter_python3
- Add a LUA script in a pipeline to process tensors: https://github.com/nnstreamer/nnstreamer/tree/main/tests/nnstreamer_filter_lua

Look at the runTest.sh files for how to run Python/Lua scripts in a pipeline, Look at the refered (in runTest.sh) script file to see how to write Python/Lua scripts for a pipeline.

**Comment by myungjoo** [comment]
https://github.com/nnstreamer/nnstreamer/blob/main/tests/test_models/models/scaler.lua This script for tensor-filter::custom appears to be most similar to your need. I think you can easily modify that script for your needs if it can be solved by padding.

**Comment by anyj0527** [comment]
@learytomlin
In this case, padding or extra processing is not needed. If your `mymodel.tflite` has output dimension as `6:10647:1:1`, and your `my_coco_labels.txt` has just one line with "person", then the pipeline should work fine. The 85 or 6 is determined by the number of lines in the label file.

The 10647 is determined by input image's shape (416 x 416). Check https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c#L1135-L1138
