### ISSUE TITLE
tensor-decoder / ssd-mobilenet biased towards first classes

### ISSUE THREAD

**Issue by gaetanbahl** [nnstreamer/nnstreamer#4137]
I believe I found an issue in the box decoding of ssd mobilenet (without post processing).

The function iterates over class scores and breaks at the first class above the selected detection threshold (sigmoid_threshold).

However, multiple classes could theoretically have a score above this threshold. In particular, subsequent classes could have a higher score than the first one above the threshold (for example: threshold of 0.5, score for bus 0.6, score for truck 0.7, the chosen class would be bus since it appears first in the list).

https://github.com/nnstreamer/nnstreamer/blob/e7439ca2e78fdc877a86963683dcd2a54ee6d906/ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c#L1399

Can you confirm that this is indeed a bug? Then I can submit a fix.

Thanks!

**Comment by anyj0527** [comment]
@gaetanbahl
Thanks for reporting this issue! It really seems as a bug.
It would be grateful if you submit the fix for this.

**Comment by myungjoo** [comment]
Uh.. it was intentionally set 1.
With 0, it behaves inappropriately by showing hundreds of boxes.

**Comment by gaetanbahl** [comment]
> Uh.. it was intentionally set 1.
> With 0, it behaves inappropriately by showing hundreds of boxes.

Are you talking about c=1 ? This is not the issue here. The problem is that the loop breaks as soon as it encounters a positive score. Please read the first message and reopen the issue. Thanks.

**Comment by myungjoo** [comment]
Uh.. then do you have a fix?

**Comment by gaetanbahl** [comment]
> Uh.. then do you have a fix?...
> 
> or #4177 might be the fix? :)

Indeed, #4177 should fix this issue. Thanks for implementing it!
