### ISSUE TITLE
How to combine multiple Tensors and use a model (batch_size > 1) inference

### ISSUE THREAD

**Issue by yancaoweidaode** [nnstreamer/nnstreamer#4156]
I wrote a plugin for a new device and nnstreamer is using it correctly to load models and perform inference, now I try to load another model(batch_size=4) for inference but see this error ```gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.479: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.479: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.481: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.481: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.481: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.481: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.481: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.481: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.492: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.492: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.492: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.512: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.512: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.512: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.525: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.525: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.525: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.551: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.551: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.551: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.615: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.615: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.615: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.672: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.672: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.672: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.683: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.683: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.683: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.720: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.720: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.720: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.764: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.764: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.764: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.834: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.834: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.834: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.842: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.843: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.843: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.870: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.870: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.870: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.929: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.929: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.929: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:42942): GStreamer-CRITICAL **: 11:10:56.979: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:42942): CRITICAL **: 11:10:56.979: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed```. How should I solve it?

**Comment by yancaoweidaode** [comment]
the pipeline is `gst-launch-1.0 rtspsrc location=path/to/rtsp ! queue ! rtph264depay ! h264parse ! avdec_h264  ! videoconvert ! videoscale ! video/x-raw,height=1080,width=1920,format=BGR ! tensor_converter ! tensor_transform mode=typecast option=uint8 ! tensor_aggregator frames-in=1 frames-out=4 frames-flush=4 frames-dim=3 ! tensor_transform mode=dimchg option=0:1 ! tensor_filter framework=ourdevice model='path/to/model' inputlayout=NCHW outputlayout=NCHW input=4:3:1920:1080 output=4:3:1920:1080 outputtype=uint8 inputtype=uint8 ! fakesink`

**Comment by anyj0527** [comment]
If your model takes input layout of `uint8[4,1080,1920,3] (NHWC)` (which is equivalent to `3:1920:1080:4` for gstreamer dimension notation), refer to this working pipeline:
```
gst-launch-1.0 videotestsrc ! videoconvert ! videoscale ! \
video/x-raw,height=1080,width=1920,format=BGR ! \ # 3:1920:1080:1 ([1,1080,1920,3])
tensor_converter ! tensor_transform mode=typecast option=uint8 ! \
tensor_aggregator frames-in=1 frames-out=4 frames-flush=4 frames-dim=3 ! \ # 3:1920:1080:4 ([4,1080,1920,1]) 
tensor_sink
```

If your model input layout is `uint8[4,3,1080,1920] (NCHW)` (which is same as `1920:1080:3:4` in gstreamer pipeline), refer to this working pipeline:
```
gst-launch-1.0 videotestsrc ! videoconvert ! videoscale ! \
video/x-raw,height=1080,width=1920,format=BGR ! \ # 3:1920:1080:1 ([1, 1080, 1920, 3])
tensor_converter ! tensor_transform mode=typecast option=uint8 ! \
tensor_aggregator frames-in=1 frames-out=4 frames-flush=4 frames-dim=3 ! \ # 3:1920:1080:4 ([4,1080,1920,1]) 
tensor_transform mode=transpose option=1:2:0:3 ! \ # 1920:1080:3:4 ([4,3,1080,1920])
! tensor_sink
```

**Comment by yancaoweidaode** [comment]
There is no shape conflict between tensor_transform and tensor_filter, because the pipeline does not throw a not equal error and still outputs
' gst-launching-1.0:42942): CRITICAL **: 11:10:56.479: gst_pad_set_caps: assertion 'caps! = NULL && gst_caps_is_fixed (caps)' failed
(gst-launching-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_mini_object_unref: assertion 'mini_object! = NULL' failed
(gst-launching-1.0:42942): GStreamer-CRITICAL **: 11:10:56.479: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed
** (gst-launching-1.0:42942): CRITICAL **: 11:10:56.479: gst_pad_set_caps: assertion 'caps! = NULL && gst_caps_is_fixed (caps)' faile', 
how can I fix this error

**Comment by anyj0527** [comment]
In your pipeline, tensor_filter takes input dimension of `4:3:1920:1080`, but the former tensor_transform emits dimension of `1920:3:1080:4`. Please check my previous comment.
It is sad that sometimes logs are not enough for resolving issues...

**Comment by myungjoo** [comment]
Without further discussions, I'll close questions/discussions.
@anyj0527 Anyway, you can add a better log for such issues.
