### ISSUE TITLE
Shared V4L2 Camera Sources for Multiple NNStreamer Pipelines

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#4158]
We need a mechanism to create multiple pipelines sharing the same video live source.

It's ideal to have a single pipeline with multiple NNs; however, there's a client who wants to have multiple instances of pipelines from different user processes to handle the same camera source.

**Comment by gichan-jang** [comment]
I think we can use gst-interpipe for this issue.
https://github.com/RidgeRun/gst-interpipe

**Comment by myungjoo** [comment]
When the clients request "shared camera sources", @again4you @jaeyun-jung @gichan-jang let them use shmsink/shmsrc.

Example:
```
PROCESS1$ gst-launch-1.0 v4l2src ! videoscale ! videoconvert ! videorate ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 ! shmsink socket-path=/tmp/x112 sync=true wait-for-connection=false shm-size=1000000

PROCESS2$ gst-launch-1.0 shmsrc socket-path=/tmp/x112 ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 !  videoconvert  ! ximagesink

PROCESS3$ gst-launch-1.0 shmsrc socket-path=/tmp/x112 ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 !  videoconvert  ! ximagesink
```

What I wanted for the clients was something like ```v4l2shmsrc``` that hides "PROCESS1" from "PROCESS2/3", but it appears that there is no such a thing.
