### ISSUE TITLE
How can I customize GstTensorInfo variable "char *name" in tensor_converter

### ISSUE THREAD

**Issue by yancaoweidaode** [nnstreamer/nnstreamer#4162]
![WARNING](https://media.giphy.com/media/Zsx8ZwmX3ajny/giphy.gif)

Please only create issues/feature requests for the project here.

For support contact our project maintainer(s), they meet online in a 'Issues' list.
There you can ask questions if you have trouble understanding something, seek advice and mingle with other project members.
For further information see 'Wiki' page.

**Comment by myungjoo** [comment]
In gstreamer pipeline description, you may configure it with ```inputname``` and ```outputname``` properties: ```name_of_tensor0,name_of_tensor1,...```.

In C code, you may configure it with NNStreamer API, ```gst_tensors_info_parse_names_string``` from "nnstreamer_plugin_api_util.h" with the same syntax. You can see a usage at nnstreamer/tensor_filter/tensor_filter_common.c

**Comment by yancaoweidaode** [comment]
> In gstreamer pipeline description, you may configure it with `inputname` and `outputname` properties: `name_of_tensor0,name_of_tensor1,...`.
> 
> In C code, you may configure it with NNStreamer API, `gst_tensors_info_parse_names_string` from "nnstreamer_plugin_api_util.h" with the same syntax. You can see a usage at nnstreamer/tensor_filter/tensor_filter_common.c

ok,thanks
