### ISSUE TITLE
Inference Results

### ISSUE THREAD

**Issue by poornimakr28** [nnstreamer/nnstreamer#4174]
Hi,
I want the inference results data in a text or a Json file. Can that be dumped into a file in the same pipeline?

gst-launch-1.0 \
    v4l2src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
    t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=300,height=300,format=RGB ! tensor_converter ! \
            tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
            tensor_filter framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! \
            tensor_decoder mode=bounding_boxes option1=mobilenet-ssd option2=tflite_model/coco_labels_list.txt \
                option3=tflite_model/box_priors.txt option4=640:480 option5=300:300 ! \
            compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink \
    t. ! queue leaky=2 max-size-buffers=10 ! mix.

Thanks
Poornima

**Comment by myungjoo** [comment]
Use [filesink](https://gstreamer.freedesktop.org/documentation/coreelements/filesink.html?gi-language=c) elements to write a file from a stream.

Write a tensor-decoder subplugin that writes a text from a given tensor value according to your own syntax.

Then, you have all you need.
