### ISSUE TITLE
struct for tensors information (ML API and NNStreamer)

### ISSUE THREAD

**Issue by jaeyun-jung** [nnstreamer/nnstreamer#4175]
Currently ML API internally defines ml-tensors-information struct.
We can use gst-tensors-info instead for reducing code complexity.

```
typedef struct {
  unsigned int num_tensors; /**< The number of tensors. */
  ml_tensor_info_s info[ML_TENSOR_SIZE_LIMIT_STATIC];  /**< The list of tensor info. */
  ml_tensor_info_s *extra; /**< The list of extra tensor info. */
  GMutex lock; /**< Lock for thread safety */
  int nolock; /**< Set non-zero to avoid using m (giving up thread safety) */
  bool is_extended; /**< True if tensors are extended */
} ml_tensors_info_s;
```

Suggestion: use gst-tensors-info
```
typedef struct {
  GMutex lock; /**< Lock for thread safety */
  int nolock; /**< Set non-zero to avoid using m (giving up thread safety) */
  GstTensorsInfo info;
} ml_tensors_info_s;
```

**Comment by myungjoo** [comment]
I like this idea, too.
Anyway, I would recommend to define an alias (typedef) so that the "Gst" is not shown in API. I do not want users to misunderstand that there is a direct GStreamer dependency from ML API.

So.. let's add ```typedef nnstreamer_tensors_info GstTensorsInfo``` and use ```nnstreamer_tensors_info``` in ML API.

**Comment by jaeyun-jung** [comment]
Related PRs to update gst-info in ML API
https://github.com/nnstreamer/api/pull/416
https://github.com/nnstreamer/api/pull/417

I will replace the prefix 'Gst-' after merging all related PRs.

**Comment by jaeyun-jung** [comment]
https://github.com/nnstreamer/nnstreamer/pull/4338 to remove unnecessary lines from api repo.
Now all PRs for this issue is done, closing this issue.
