### ISSUE TITLE
Tensor_decoder sub-plugin

### ISSUE THREAD

**Issue by poornimakr28** [nnstreamer/nnstreamer#4179]
I want to write the inference results to a file from the pipeline.

As I see there are reference to writing a sub-plugin for tensor_filter
https://github.com/nnstreamer/nnstreamer/blob/d05854f673a89769a6478006adf63f98a636dd34/Documentation/writing-subplugin-tensor-filter.md

I don't see any reference for tensor_decoder.
Could you please share any reference to build and install a tensor_decoder sub-plugin.

**Comment by myungjoo** [comment]
You may use the files at https://github.com/nnstreamer/nnstreamer/tree/main/ext/nnstreamer/tensor_decoder as references for now.

Anyway, if you want to write the tensor streams to file, you don't need tensor_decoder. You can directly write files from tensor streams with [gstreamer/filesink](https://gstreamer.freedesktop.org/documentation/coreelements/filesink.html), [multifilesink](https://gstreamer.freedesktop.org/documentation/multifile/multifilesink.html?gi-language=c), and other gstreamer's basic elements. You need decoders only if you need conventional media (video/audio/...) streams from tensors requiring some interpretations of the given tensor values and their semantics.

If you need to do some arithmetics on tensors before writing it, I'd recommend to use tensor_transform or tensor_filter with custom-easy/custom.

**Comment by myungjoo** [comment]
Without further followups, questions, or discussions, I'm closing this.
