### ISSUE TITLE
could not link tensorfilter0 to tensordecoder0 error

### ISSUE THREAD

**Issue by pedrobagatin** [nnstreamer/nnstreamer#4190]
```
gst-launch-1.0 \
uridecodebin uri=url.mp4 ! \
videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! videorate ! video/x-raw,framerate=9/1 !   \
tee name=t   t. ! queue ! tensor_converter !     tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! \
queue leaky=2 max-size-buffers=2 !     tensor_filter framework=tensorflow2-lite model=./model.tflite !    \
other/tensors,num_tensors=1,types=float32,format=static,dimensions=6:6300:1:1 !     \
tensor_decoder mode=bounding_boxes option1=yolov5 option2=./coco.txt option4=320:320 option5=320:320 !     \
video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0   t. ! \
queue ! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink
```

The error I am getting seems to be related to:

`WARNING: erroneous pipeline: could not link tensorfilter0 to tensordecoder0, tensorfilter0 can't handle caps other/tensors, num_tensors=(int)1, types=(string)float32, format=(string)static, dimensions=(string)6:6300:1:1`

Can it be the reason of pipeline not running?  Was there any changes recently that could cause it to stop working?
Model is 1x6300x6 when checking in netron.app

**Comment by pedrobagatin** [comment]
Testing the example code of: https://github.com/nnstreamer/nnstreamer/pull/3628#issue-1092286401

`gst-launch-1.0 v4l2src ! videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t   t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 !     tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! queue leaky=2 max-size-buffers=2 !     tensor_filter framework=tensorflow2-lite model=./yolov5s-fp16-320.tflite !     other/tensors,num_tensors=1,types=float32,format=static,dimensions=85:6300:1:1 !     tensor_decoder mode=bounding_boxes option1=yolov5 option2=./coco_labels_list.txt option4=320:320 option5=320:320 !     video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0   t. ! queue ! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink`

Error:
```
** Message: 09:54:21.010: accl = cpu

** (gst-launch-1.0:2863): CRITICAL **: 09:54:21.014: bb_getOutCaps: assertion 'dim[0] == (data->labeldata.total_labels + YOLOV5_DETECTION_NUM_INFO)' failed

** (gst-launch-1.0:2863): CRITICAL **: 09:54:21.015: bb_getOutCaps: assertion 'dim[0] == (data->labeldata.total_labels + YOLOV5_DETECTION_NUM_INFO)' failed
WARNING: erroneous pipeline: could not link tensorfilter0 to tensordecoder0, tensorfilter0 can't handle caps other/tensors, num_tensors=(int)1, types=(string)float32, format=(string)static, dimensions=(string)85:6300:1:1
```

**Comment by anyj0527** [comment]
[A recent commit](https://github.com/nnstreamer/nnstreamer/commit/ba46d6f22884bfa3e126e6c3a7be39ec60f09846) makes same tensor dimensions should be equal in terms of tensor rank.
Use `85:6300:1` other than `85:6300:1:1` cause yolov5s-fp16.tflite has `float32[1,6300,85]` output. Or you can remove the `other/tensors,.... 85:6300:1` from the pipeline.

And apply https://github.com/nnstreamer/nnstreamer/pull/4191, or the decoder would complain about the dim.

**Comment by pedrobagatin** [comment]
@anyj0527 Thanks, how can I know if installed nnstreamer was already updated to the main branch with the changes (https://github.com/nnstreamer/nnstreamer/pull/4191)?

`pedrobb7@VM:~/Desktop/nnstreamer$ apt list -a nnstreamer
Listing... Done
nnstreamer/focal,now 2.3.0.0-0~202308220252~ubuntu20.04.1 amd64 [installed]
`

Date seems to be right, but how about 2.3.0.0-0 ? Where can I check this version on the commit?

**Comment by pedrobagatin** [comment]
I am still getting error:

Either if I specify other/tensor filter or not logs are the same:

`pedrobb7@VM:~/Desktop/nnstreamer$ gst-launch-1.0 v4l2src ! videoscale ! videoconvert ! video/x-raw,width=320,height=320,format=RGB,framerate=30/1,pixel-aspect-ratio=1/1 ! tee name=t   t. ! queue ! tensor_converter ! other/tensors,num_tensors=1,types=uint8,format=static,dimensions=3:320:320:1 !     tensor_transform mode=arithmetic option=typecast:float32,add:0.0,div:255.0 ! queue leaky=2 max-size-buffers=2 !     tensor_filter framework=tensorflow2-lite model=./yolov5s-fp16-320.tflite !     other/tensors,num_tensors=1,types=float32,format=static,dimensions=85:6300:1 !     tensor_decoder mode=bounding_boxes option1=yolov5 option2=./coco.txt option4=320:320 option5=320:320 !     video/x-raw,width=320,height=320,format=RGBA ! mix.sink_0   t. ! queue ! mix.sink_1 compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink
** Message: 18:46:33.396: accl = cpu

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.401: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.402: bb_getOutCaps: assertion 'dim[i] == 1' failed
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.557: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.565: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.566: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.566: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.568: bb_getOutCaps: assertion 'dim[i] == 1' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_caps_intersect_full: assertion 'GST_IS_CAPS (caps2)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_mini_object_make_writable: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_caps_is_subset: assertion 'superset != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.573: gst_caps_is_fixed: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.574: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.574: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.578: bb_getOutCaps: assertion 'dim[i] == 1' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.578: gst_caps_intersect_full: assertion 'GST_IS_CAPS (caps2)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.578: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.579: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.579: gst_mini_object_make_writable: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.579: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.579: gst_caps_is_subset: assertion 'superset != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.579: gst_caps_is_fixed: assertion 'GST_IS_CAPS (caps)' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.873: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.874: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:33.889: bb_getOutCaps: assertion 'dim[i] == 1' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.889: gst_caps_intersect_full: assertion 'GST_IS_CAPS (caps2)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.889: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.889: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.889: gst_mini_object_make_writable: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.890: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.890: gst_caps_is_subset: assertion 'superset != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:33.890: gst_caps_is_fixed: assertion 'GST_IS_CAPS (caps)' failed
Redistribute latency...

** (gst-launch-1.0:37457): CRITICAL **: 18:46:35.639: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:35.640: bb_getOutCaps: assertion 'dim[i] == 1' failed

** (gst-launch-1.0:37457): CRITICAL **: 18:46:35.643: bb_getOutCaps: assertion 'dim[i] == 1' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.643: gst_caps_intersect_full: assertion 'GST_IS_CAPS (caps2)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.643: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.644: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.644: gst_mini_object_make_writable: assertion 'mini_object != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.644: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.644: gst_caps_is_subset: assertion 'superset != NULL' failed

(gst-launch-1.0:37457): GStreamer-CRITICAL **: 18:46:35.644: gst_caps_is_fixed: assertion 'GST_IS_CAPS (caps)' failed
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:02.239323089
Setting pipeline to NULL ...
Freeing pipeline ...
`

Camera capture is displayed for a while and closed suddenly.
