### ISSUE TITLE
WARNING: erroneous pipeline: no element "tensor_converter"

### ISSUE THREAD

**Issue by amrithkrish** [nnstreamer/nnstreamer#4198]
Hi,

I installed nnstreamer in Ubuntu 18 machine via the PPA repo using the following commands :

$ sudo apt-add-repository ppa:nnstreamer
$ sudo apt install nnstreamer

I tried running the object detection example pipeline from the '/usr/lib/nnstreamer/bin' path. 
This is the pipeline I used : 

gst-launch-1.0 \
    v4l2src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=30/1 ! tee name=t \
    t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! video/x-raw,width=300,height=300,format=RGB ! tensor_converter ! \
            tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! \
            tensor_filter framework=tensorflow-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! \
            tensor_decoder mode=bounding_boxes option1=mobilenet-ssd option2=tflite_model/coco_labels_list.txt option3=tflite_model/box_priors.txt option4=640:480 option5=300:300 ! \
            compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink \
    t. ! queue leaky=2 max-size-buffers=10 ! mix.

But execution of the above pipeline is resulting in the error  - WARNING: erroneous pipeline: no element "tensor_converter"

Why is the nnstreamer element cannot be found? 
Please let me know whether I am missing something here and to how fix it.

Attaching the output from the 'apt-cache search nnstreamer' command as well : 

nnstreamer-example - Examples of nnstreamer
ml-inference-single-api - Machine Learning Inference Single API
nnsreamer-cpp-dev - NNStreamer CPP Filter Subplugin Development Support
nnstreamer - NNStreamer plugins for Gstreamer
nnstreamer-api - NNStreamer API
nnstreamer-api-common-dev - NNStreamer API common
nnstreamer-api-dev - Development package for NNStreamer API
nnstreamer-caffe2 - NNStreamer Caffe2 Support
nnstreamer-configuration - NNStreamer plugins for Gstreamer
nnstreamer-core - NNStreamer plugins for Gstreamer
nnstreamer-cpp - NNStreamer CPP Filter Subplugin Support
nnstreamer-cpp-dev - NNStreamer CPP Filter Subplugin Development Support
nnstreamer-dev - NNStreamer development package
nnstreamer-dev-internal - Development package to access internal functions of NNStreamer.
nnstreamer-edge - nnstreamer-edge library
nnstreamer-edge-dev - development package for nnstreamer-edge
nnstreamer-edgetpu - NNStreamer Edge TPU support
nnstreamer-flatbuf - NNStreamer Flatbuf converter/decoder support
nnstreamer-grpc - NNStreamer gRPC tensor source/sink support
nnstreamer-grpc-flatbuf - NNStreamer gRPC IDL support for flatbuf
nnstreamer-grpc-protobuf - NNStreamer gRPC IDL support for protobuf
nnstreamer-misc - NNStreamer extra package
nnstreamer-nnfw - NNStreamer NNFW (ONE) support
nnstreamer-nntrainer - NNStreamer tensor filter for nntrainer
nnstreamer-nntrainer-dev - Development package for nntrainer tensor filter
nnstreamer-openvino - NNStreamer OpenVino support
nnstreamer-protobuf - NNStreamer Protobuf converter/decoder support
nnstreamer-python2 - NNStreamer Python Custom Filter Support (2.7)
nnstreamer-python3 - NNStreamer Python Custom Filter Support (3.x)
nnstreamer-pytorch - NNStreamer Pytorch Support
nnstreamer-single - NNStreamer Single-shot
nnstreamer-single-dev - NNStreamer single-shot development package
nnstreamer-single-dev-internal - Development package to access internal functions of NNStreamer single-shot.
nnstreamer-tensorflow - NNStreamer TensorFlow 1.x Support
nnstreamer-tensorflow-lite - NNStreamer TensorFlow Lite 1.x Support
nnstreamer-tensorflow2-lite - NNStreamer TensorFlow Lite 2.x Support
nnstreamer-test-dev - Development package to provide testable environment of a subplugin (tensor_filter/custom).
nnstreamer-tvm - NNStreamer TVM support
nnstreamer-util - NNStreamer utility

Thanks,
Amritha

**Comment by anyj0527** [comment]
`gst-inspect-1.0 tensor_converter` or `nnstreamer-check` should give the path of libnnstreamer.so plugin. By default it should be at `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/`. Check the installed path.
Or you can set env var `GST_PLUGIN_PATH` to include path where the plugin resides.

**Comment by amrithkrish** [comment]
Hi,

I tried running both the commands you had shared and the result is as follows : 

gst-inspect-1.0 tensor_converter
No such element or plugin 'tensor_converter'

nnstreamer-check
nnstreamer-check: command not found

But, I was able to find the libnnstreamer.so in the /usr/lib/x86_64-linux-gnu/gstreamer-1.0/    path.
What should I do next?

Thanks,
Amritha

**Comment by anyj0527** [comment]
You may check web for the reason why gstreamer does not load plugins.
How about this article? https://stackoverflow.com/questions/35261461/why-compiled-and-installed-gstreamer-plugin-from-boilerplate-code-is-not-found-b

**Comment by gichan-jang** [comment]
NNStreamer Ubuntu 18.04 package is not distributed in ppa.
We will fix this issue later.
If you want to use nnstreamer before fixing this, How about building nnstreamer by yourself?
https://nnstreamer.github.io/getting-started-meson-build.html
(Install except `tvm-runtime-dev`)

**Comment by wooksong** [comment]
@amrithkrish Please attach the result from ```dpkg -l | grep nnstreamer```.
