### ISSUE TITLE
How to build nnstreamer for Buildroot based Linux?

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [nnstreamer/nnstreamer#4226]
Hello,

This is not a bug report but rather a support request.
I need to build `nnstreamer` for `i.MX.8M Plus ARM-Cortex-A53` board using `Buildroot` image. Since there is no `nnstreamer` package in Buildroot I am trying to cross-compile it for the board. Can anyone please let me know how to cross-compile `nnstreamer` using `meson` build system? Is there any documentataion for this?

My setup is WSL2 with docker and I am using a cross-build configuration file:

```
[binaries]
c = '/opt/sdk/bin/aarch64-linux-gcc'
cpp = '/opt/sdk/bin/aarch64-linux-g++'
ar = '/opt/sdk/bin/aarch64-linux-ar'
strip = '/opt/sdk/bin/aarch64-linux-strip'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'

[properties]
sys_root = '/opt/sdk/aarch64-buildroot-linux-gnu/sysroot'
pkg_config_libdir = '/opt/sdk/usr/lib/pkgconfig'
include_directories = '/opt/sdk/usr/include'
```

invoking meson build with
`meson setup --cross-file cross_file.txt build`

But this gives below error:

```
The Meson build system
Version: 0.61.4
Source dir: /home/nnstreamer
Build dir: /home/nnstreamer/build
Build type: cross build
Project name: nnstreamer
Project version: 2.3.0
C compiler for the host machine: /opt/sdk/bin/aarch64-linux-gcc (gcc 10.3.0 "aarch64-linux-gcc.br_real (Buildroot 2022.02.1-03792-ga987eb4732) 10.3.0")
C linker for the host machine: /opt/sdk/bin/aarch64-linux-gcc ld.bfd 2.36.1
C++ compiler for the host machine: /opt/sdk/bin/aarch64-linux-g++ (gcc 10.3.0 "aarch64-linux-g++.br_real (Buildroot 2022.02.1-03792-ga987eb4732) 10.3.0")
C++ linker for the host machine: /opt/sdk/bin/aarch64-linux-g++ ld.bfd 2.36.1
C compiler for the build machine: ccache cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the build machine: cc ld.bfd 2.34
C++ compiler for the build machine: ccache c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C++ linker for the build machine: c++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: armv7
Target machine cpu family: arm
Target machine cpu: armv7
Compiler for C supports arguments -Wmissing-braces: YES
Compiler for C++ supports arguments -Wmissing-braces: YES
Compiler for C supports arguments -Wmaybe-uninitialized: YES
Compiler for C++ supports arguments -Wmaybe-uninitialized: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C++ supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -Wformat: YES
Compiler for C++ supports arguments -Wformat: YES
Compiler for C supports arguments -Wformat-nonliteral: YES
Compiler for C++ supports arguments -Wformat-nonliteral: YES
Compiler for C supports arguments -Wformat-security: YES
Compiler for C++ supports arguments -Wformat-security: YES
Compiler for C supports arguments -Winit-self: YES
Compiler for C++ supports arguments -Winit-self: YES
Compiler for C supports arguments -Waddress: YES
Compiler for C++ supports arguments -Waddress: YES
Compiler for C supports arguments -Wno-multichar: YES
Compiler for C++ supports arguments -Wno-multichar: YES
Compiler for C supports arguments -Wvla: YES
Compiler for C++ supports arguments -Wvla: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C++ supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wmissing-declarations: YES
Compiler for C supports arguments -Wmissing-include-dirs: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wnested-externs: YES
Compiler for C supports arguments -Waggregate-return: YES
Compiler for C supports arguments -Wold-style-definition: YES
Compiler for C supports arguments -Wdeclaration-after-statement: YES
Found Pkg-config: NO
Found CMake: NO
Run-time dependency glib-2.0 found: NO

meson.build:134:0: ERROR: Pkg-config binary for machine 1 not found. Giving up.
```

But `pkg-config`, `glib2.0` is available in the SDK (`/opt/sdk/`)

Thanks in advance

**Comment by anyj0527** [comment]
May check other meson-based project works with the "cross_file.txt"  in BuildRoot?

I never use BuildRoot, but [the manual](https://buildroot.org/downloads/manual/manual.html#_infrastructure_for_meson_based_packages) says it uses internal `cross-compile.conf` for building meson-based project. May try it?

**Comment by Sourabh-ALTEN** [comment]
Hello @anyj0527 thanks for the update. I tried the buildroot meson package and it installed the nnstreamer tools to the target image. In my application I need to use `tensor_converter` but in the Buildroot image I see only `tensor_converter_custom.h` installed to `/usr/include/nnstreamer/`. Is this expected?
Also, can you please let me know all run-time dependencies? Do I need to have `tensorflow` or other packages available in Buildroot?

**Comment by myungjoo** [comment]
You can configure such dependencies at build time; please refer to meson_options.txt for such.
Depending how you configure the build, you will need run-time dependencies for your selected subplugins. If you have build nnstreamer-tensorflow as shared, not static, then you will need tensorflow at run-time.

**Comment by Sourabh-ALTEN** [comment]
Hello @myungjoo thanks for the info.

> If cross-compiling gets too complicated, you can build it on qemu-chroot or on iMX board directly, too. I, personally, build it on qemu-chroot.

Can you please give some info about building it on qemu-chroot? I am working on WSL2 with docker container and I need to build it for aarch64

**Comment by myungjoo** [comment]
https://www.google.com/search?q=qemu+on+chroot+directory
Not sure how it works in WSL2, though.

You should be able to build things inside i.MX devices as well.

**Comment by Sourabh-ALTEN** [comment]
> You should be able to build things inside i.MX devices as well.

Buildroot doesn't include any compilers in the image. So, building on the target (i.MX) is not an option for me.

**Comment by Sourabh-ALTEN** [comment]
Hello @myungjoo I made some progress and now I have issues with `flatbuffers` version. 
I have `flatbuffers` version 23.5.26 [https://github.com/buildroot/buildroot/blob/master/package/flatbuffers/flatbuffers.mk](url)
But `meson.build` is complaining about invalid version. `Required flatbuffers version [2.0.7] Found 23.5.26`

Why can't we use version `23.5.26`? How to make this work with this version?

**Comment by Sourabh-ALTEN** [comment]
Hi @myungjoo , do you have any updates on above issue?

Thanks in advance

**Comment by myungjoo** [comment]
> Hello @myungjoo I made some progress and now I have issues with `flatbuffers` version. I have `flatbuffers` version 23.5.26 [https://github.com/buildroot/buildroot/blob/master/package/flatbuffers/flatbuffers.mk](url) But `meson.build` is complaining about invalid version. `meson.build:156:2: ERROR: Invalid version of dependency, need 'flatbuffers' ['2.0.7'] found '23.5.26'.`
> 
> `Dependency flatbuffers found: NO found 23.5.26 but need: '2.0.7'`
> 
> Why can't we use version `23.5.26`? How to make this work with this version?

That means you have installed flatbuffers 23.5.25 while you have installed flatbuffer-compiler 2.0.7.
Use the same versions for flatbuffers and flatbuffers-compiler.

In this case, you can remove flatbuffers 23.5.26 and install flatbuffers 2.0.7
or
you can remove flatc (flatbuffers-compiler) 2.0.7 and install flatc 23.5.26.

**Comment by myungjoo** [comment]
#4274 will give more info on the error you've experienced.
