### ISSUE TITLE
Running tensorflow lite model

### ISSUE THREAD

**Issue by leechanwoong** [nnstreamer/nnstreamer#4290]
I have built nnstreamer and nnstreamer-example with meson following the [guide](https://github.com/nnstreamer/nnstreamer/wiki/usage-examples-screenshots#build-examples-ubuntu-1604) on my ubuntu 22.04 machine.
and I ran tflite examples in "~/nnstreamer/bin".

My goal is running multiple human [pose estimation tflite model that is used by mediapipe](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker). 
And it has two steps 1.Detect 2.Landmark. I have two .tflite files for both.

Now I see I need some options for tensor_decoder, tensor_transform, tensor_filter.
But with just nnstreamer docs, It seems hard to use other tflite models.

could you help me?

[mediapipe_pose_estimation_tflite.zip](https://github.com/nnstreamer/nnstreamer/files/13040126/mediapipe_pose_estimation_tflite.zip)

**Comment by myungjoo** [comment]
Be more specific. Don't throw the whole code of models you want to use.
Make and share **minimal** code that reproduces your problem on a general clean machine.

If what you want is really "use other tflite models", apply ```tensor_filter framework=tensorflow2-lite model=YOURFILE``` in your GStreamer pipeline and configure the input/output stream capabilities according to YOURFILE.

**Comment by myungjoo** [comment]
And.. try to search already published example; however, the input/output requirements may differ per every model.

When I search pose estimation in nnstreamer org:
https://github.com/nnstreamer/nnstreamer-example/pull/213
https://github.com/nnstreamer/nnstreamer-example/pull/105

When I search nnstreamer pose estimatino in github:
https://github.com/nxp-imx/nxp-nnstreamer-examples/tree/main/pose

**Comment by myungjoo** [comment]
Or.. [google pose estimation nnstreamer](https://www.google.com/search?q=nnstreamer+pose+estimation)

**Comment by myungjoo** [comment]
without further follow-up, closing this question.
