### ISSUE TITLE
Problem running tutorial 4 (query)

### ISSUE THREAD

**Issue by pedrobagatin** [nnstreamer/nnstreamer#4325]
https://github.com/nnstreamer/nnstreamer/blob/main/Documentation/tutorials/tutorial4_query.md#run-pipeline-object-detection

Was able to run the tutorial using the webcam, but when chaning video src to urideocodebin or videotestsrc it stopped working.

Tried chaning async to false but it didn't work out, any idea or tips to run successfully this tutorial with different video src?

**Comment by gichan-jang** [comment]
Try with `is-live=true` property of `videotestsrc`
```
$ gst-launch-1.0 \
    compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink \
        videotestsrc is-live=true ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 ! tee name=t \
            t. ! queue ! tensor_query_client ! videoconvert ! mix.sink_0 \
            t. ! queue ! mix.sink_1
```

**Comment by pedrobagatin** [comment]
> Try with `is-live=true` property of `videotestsrc`
> 
> ```
> $ gst-launch-1.0 \
>     compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink \
>         videotestsrc is-live=true ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 ! tee name=t \
>             t. ! queue ! tensor_query_client ! videoconvert ! mix.sink_0 \
>             t. ! queue ! mix.sink_1
> ```

Thanks! it worked well.

**Comment by gichan-jang** [comment]
Please test with `videorate` element.
```
gst-launch-1.0 uridecodebin uri=https://gstreamer.freedesktop.org/data/media/sintel_trailer-480p.webm ! videoconvert ! videoscale ! videorate ! video/x-raw,width=640,height=480,format=RGB,framerate=10/1 ! tensor_query_client ! videoconvert ! ximagesink
```

There was timing difference between the framerate of the original video (uridecodebin) and the interference result arrived from query server, so I removed compositor.
