### ISSUE TITLE
How to measure the time taken for inference in a nnstreamer pipeline?

### ISSUE THREAD

**Issue by amrithkrish** [nnstreamer/nnstreamer#4339]
Hi team,

I wanted to know whether is there any way to obtain the inference time ran using nnstreamer pipeline.

I have a pipeline that uses Yolov5 model for object detection and is working from the imx8MP board. But I wanted to check the time it takes for performing this inference.

Is there any way for getting this?

Thanks in advance!

**Comment by myungjoo** [comment]
Yes. You may use nnshark to visualize it.
or, you may enable ```latency``` and "latency_reporting" property of tensor_filter and fetch"info" log from gstreamer.
