### ISSUE TITLE
[Ubuntu]: Not able to use pytorch & tensorflow as framework in tensor_filter

### ISSUE THREAD

**Issue by IvanFilipov** [nnstreamer/nnstreamer#4357]
Hello, nnstreamer team!

I have a few questions related to the frameworks, which can be passed to _tensor_filter_. 

My current setup is as following:
- Ubuntu 22.04 (but also same questions opened for 20.04)
- nnstreamer installed via PPA 
- additional sub-plugins also installed (see the picture below for details)

So, those are my questions:

### Q1:  Is _tensorflow_ supported?
From the list of the supported features - [here ](https://github.com/nnstreamer/nnstreamer/blob/main/Documentation/features-per-distro.md), looks like it shall be. But while trying to install the sub-plugin, I am getting:

```
sudo apt-get install nnstreamer-tensorflow
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nnstreamer-tensorflow : Depends: tensorflow but it is not installable or
                                  tensorflow-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Respectively, when a pipeline is run with gst-launch:
`** (gst-launch-1.0:1011307): WARNING **: 16:02:12.355: Cannot identify the given neural network framework, tensorflow`

Will _tensorflow_ be supported via PPA in the feature? Or it will be available only on a custom build of nnstreamer directly from the source?

### Q2: _pytorch_ library is missing?

Unlike the situation in Q1, _pytorch_ sub-plugin is installed without issue. What I have currently as packages related to nnstreamer:

![nnstreamer1](https://github.com/nnstreamer/nnstreamer/assets/15016284/de128fa0-fa55-4716-94fd-3d56690376cc)

The libraries are:
![nnstreamer2](https://github.com/nnstreamer/nnstreamer/assets/15016284/a75545d2-2e0c-4a53-812b-204e7e4cc1d8)

The _pytorch_ one is missing. Probably that's why I get an error when running a pipeline with `tensor_filter framework=pytorch`:

`** (gst-launch-1.0:1020814): WARNING **: 16:55:37.516: Cannot identify the given neural network framework, pytorch`

Can you give a little more information about the _pytorch_ support, what possibly could have gone wrong?

### Q3: Upto which version is _OpenVino_ supported?

I have used the latest tools from OpenVino and when I tried to pass the model to nnstreamer's pipeline, I got:

`failed with version [cannot parse future versions: 11]`
Which is the latest supported one?

### Q4: Support for _Onnx_ format models?

I have seen that there is already some effort done in getting onnx models run by nnstreamer pipelines, which is great. 
What is the current state of the support and is it planned when it will be fully integrated?  

As additional information, this is the output of `nnstreamer-check`:
```
NNStreamer version: 2.4.1
           loaded : TRUE
           path   : /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libnnstreamer.so

NNStreamer configuration:
============================================================
Configuration Loaded: TRUE
Configuration file path: /etc/nnstreamer.ini
    Candidates: envvar(NNSTREAMER_CONF): (null)
                build-config: /etc/nnstreamer.ini
                hard-coded: /etc/nnstreamer.ini
[Common]
  Enable envvar: TRUE
  Enable sym-linked subplugins: TRUE
[Filter]
  Filter paths from .ini: /usr/lib/nnstreamer/filters/
             from envvar: (null)
         from hard-coded: /usr/lib/nnstreamer/filters/

============================================================

** (nnstreamer-check:1023271): CRITICAL **: 17:09:23.360: Cannot open tensorflow2-lite-custom(/usr/lib/nnstreamer/filters/libnnstreamer_filter_tensorflow2-lite-custom.so) with error libtensorflow2-lite-custom.so: cannot open shared object file: No such file or directory.

NNStreamer registered sub-plugins:
============================================================

[Filter]
  cpp
    - No custom property found
  openvino
    - No custom property found

[Decoder]
  tensor_region
    - No custom property found
  direct_video
    - option1: The output video format. If this is unspecified, it is 'GRAY8' (dim[0]/channel == 1), 'RGB' (dim[0]/channel == 3), or 'BGRx' (dim[0]/channel == 4). Available options are: { GRAY8, RGB, BGR, RGBx, BGRx, xRGB, xBGR, RGBA, BGRA, ARGB, ABGR, GRAY16_BE, GRAY16_LE }
  image_segment
    - option1: Mode of image segmentation. { tflite-deeplab (input: #labels x width x height (float32, label probability). e.g., deeplabv3_257_mv_gpu.tflite), snpe-deeplab (input: width x height x 1 (float32, label index) e.g., deeplabv3_mnv2_pascal_train_aug.dlc), snpe-depth (input: 1 x width x height (float32, grayscale) e.g., .dlc snpe models producing grayscale images) }
    - option2: Maximum number of labels. 20 is applied if not specified.
  octet_stream
    - No custom property found
  bounding_boxes
    - option1: Decoder mode of bounding box: [mobilenet-ssd|mobilenet-ssd-postprocess|ov-person-detection|ov-face-detection|tflite-ssd|tf-ssd|yolov5|mp-palm-detection|yolov8]
    - option2: Location of the label file. This is independent from option1.
    - option3: Sub-option values that depend on option1;
        for yolov5 and yolov8 mode:
                The option3 requires up to 3 numbers, which tell
                - whether the output values are scaled or not
                   0: not scaled (default), 1: scaled (e.g., 0.0 ~ 1.0)
                - the threshold of confidence (optional, default set to 0.25)
                - the threshold of IOU (optional, default set to 0.45)
                An example of option3 is option3 = 0: 0.65:0.6 
        for mobilenet-ssd mode:
                The option3 definition scheme is, in order, as follows
                - box priors location file (mandatory)
                - detection threshold (optional, default set to 0.5)box priors location file (mandatory)
                - Y box scale (optional, default set to 10.0)
                - X box scale (optional, default set to 10.0)
                - H box scale (optional, default set to 5.0)
                - W box scale (optional, default set to 5.0)
                The default parameters value could be set in the following ways:
                 option3=box-priors.txt:0.5:10.0:10.0:5.0:5.0:0.5
                 option3=box-priors.txt
                 option3=box-priors.txt::::::
                It's possible to set only few values, using the default values for those not specified through the command line.
                You could specify respectively the detection and IOU thresholds to 0.65 and 0.6 with the option3 parameter as follow:
                 option3=box-priors.txt:0.65:::::0.6
        for mobilenet-ssd-postprocess mode:
                The option3 is required to have 5 integer numbers, which tell the tensor-dec how to interpret the given tensor inputs.
                The first 4 numbers separated by colon, ':', designate which are location:class:score:number of the tensors.
                The last number separated by comma, ',' from the first 4 numbers designate the threshold in percent.
                In other words, "option3=%i:%i:%i:%i,%i"
        for mp-palm-detection mode:
                The option3 is required to have five float numbers, as follows;
                - box score threshold (mandatory)
                - number of layers for anchor generation (optional, default set to 4)
                - minimum scale factor for anchor generation (optional, default set to 1.0)
                - maximum scale factor for anchor generation (optional, default set to 1.0)
                - X offset (optional, default set to 0.5)
                - Y offset (optional, default set to 0.5)
                - strides for each layer for anchor generation (optional, default set to 8:16:16:16)
                The default parameter value could be set in the following ways:
                 option3=0.5
                 option3=0.5:4:0.2:0.8
                 option3=0.5:4:1.0:1.0:0.5:0.5:8:16:16:16
    - option4: Video Output Dimension (WIDTH:HEIGHT). This is independent from option1.
    - option5: Input Dimension (WIDTH:HEIGHT). This is independent from option1.
    - option6: Whether to track result bounding boxes or not
                 0 (default, do not track)
                 1 (track result bounding boxes, with naive centroid based algorithm)
    - option7: Whether to log the result bounding boxes or not
                 0 (default, do not log)
                 1 (log result bounding boxes)  This is independent from option1
    - option8: Box Style (NYI)
  image_labeling
    - option1: The path to the label file
  pose_estimation
    - No custom property found

[Conterver]

[Trainer]

============================================================
```

Thank you in advance for your answers and suggestions!
Keep up the good work,
Ivan Filipov

**Comment by myungjoo** [comment]
Thank you for reporting. Starting with Q2, pytorch:

https://github.com/nnstreamer/nnstreamer/blob/e1e494bec3673c2b9b9923203b5c1d745e08c184/debian/control.ubuntu.ppa#L11-L13

is the source of this bug. Because we do not have pytorch >= 3.10, PPA will skip installing pytorch when building nnstreamer. Then, nnstreamer won't build nnstreamer-pytorch in PPA build, which, in turn, creates an "empty" nnstreamer-pytorch package, which is yet another bug of packaging file (it should fail to build, not create a package file, or create a filled package file.)

I'll fix these two bugs soon (control.ubuntu.ppa for the former bug and meson build for the later bug)


For Q3, @wooksong do you have some info on this?

For Q4, @yeonykim2 has added onnx-runtime subplugin a few days ago. It does not have a PPA release; she's working on Tizen release for now. After Tizen release is done, I expect PPA release will be prepared. Anyway, you can build nnstreamer-onnx based on PPA packages, too (nnstreamer-core and other packages from PPA and nnstreamer-onnx built in your PC)

For Q1, Yes, we suppor tensorflow. we just don't support it in PPA. Packaging (full) tensorflow is a PITA and often creates a bottleneck for the whole CI system. (building full tensorflow often consumes the whole PPA quota, blocking nnstreamer PPA builds.) Anyway, if there is a tensorflow PPA package with dev packaging (headers and pkg-config), we can rely on it for PPA nnstreamer-tensorflow2 releases. Do you have any pointers for such PPA packages?

**Comment by wooksong** [comment]
@IvanFilipov NNS supports 2019R3 of the old versions of OpenVino, and I would update the filter and its dependencies to the latest one.

**Comment by IvanFilipov** [comment]
@myungjoo, @wooksong - thank you for the swift response!

For Q2/3/4 - sounds great, I will keep an eye on the feature updates!

For Q1 - tensorflow topic, I understand, but currently, I am not familiar with such dev packages.

@myungjoo - as per your question about my usage of nnstreamer -
Me and my team are developing Linux-based edge devices, which are monitoring the environment around them and
notifying when an event of interest is detected. It requires near real-time data handling of video/audio inputs combined with 
ML algos - and that's why we believe nnstream can be the "backbone" of our application.

Still having a lot of experiments to be done with the algorithms, it is much easier for us to make evalutions, when we can easily change the framework - that's why I came up with the questions in the first time :)

Thank you once again! 
All the best,
Ivan F.

**Comment by myungjoo** [comment]
nnstreamer-pytorch in PPA is working:
```
nnstreamer-pytorch_2.4.1.0-0~202401030705~ubuntu20.04.1_amd64.deb
-----------------------------------------------------------------

 new Debian package, version 2.0.
 size 26560 bytes: control archive=688 bytes.
     495 bytes,    13 lines      control              
     257 bytes,     3 lines      md5sums              
 Package: nnstreamer-pytorch
 Source: nnstreamer
 Version: 2.4.1.0-0~202401030705~ubuntu20.04.1
 Architecture: amd64
 Maintainer: MyungJoo Ham <myungjoo.ham@samsung.com>
 Installed-Size: 92
 Depends: nnstreamer-single, pytorch, libc6 (>= 2.14), libgcc-s1 (>= 3.0), libglib2.0-0 (>= 2.43.2), libstdc++6 (>= 9)
 Section: libs
 Priority: optional
 Multi-Arch: same
 Homepage: https://github.com/nnstreamer/nnstreamer
 Description: NNStreamer Pytorch Support
  This package allows nnstreamer to support pytorch.

drwxr-xr-x root/root         0 2024-01-03 08:16 ./
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/lib/
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/lib/nnstreamer/
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/lib/nnstreamer/filters/
-rw-r--r-- root/root     80944 2024-01-03 08:16 ./usr/lib/nnstreamer/filters/libnnstreamer_filter_pytorch.so
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/share/
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/share/doc/
drwxr-xr-x root/root         0 2024-01-03 08:16 ./usr/share/doc/nnstreamer-pytorch/
-rw-r--r-- root/root      1218 2024-01-03 08:16 ./usr/share/doc/nnstreamer-pytorch/changelog.Debian.gz
-rw-r--r-- root/root        64 2024-01-03 08:16 ./usr/share/doc/nnstreamer-pytorch/copyright
```
