### ISSUE TITLE
Tensor decoder bug

### ISSUE THREAD

**Issue by KozAAAAA** [nnstreamer/nnstreamer#4409]
# Issue Description
I'm unable to use tensor_decoder in protobuf, flatbuf and flexbuf modes. Examples provided on the doc site do not work. 

Expected Result
============
Being able to convert tensor at least to protobuf.

How to Reproduce
===============
Run any of the following:
```
gst-launch-1.0 videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! tensor_converter ! tensor_decoder mode=flatbuf ! fakesink

gst-launch-1.0 videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! tensor_converter ! tensor_decoder mode=protobuf ! fakesink

gst-launch-1.0 videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! tensor_converter ! tensor_decoder mode=flexbuf ! fakesink

```

Further Information
===============
The error I get every time:
`
WARNING: erroneous pipeline: could not link tensorconverter0 to tensordecoder0
`

**Comment by anyj0527** [comment]
If you build/install your nnstreamer with flatbuf/protobuf, may check your nnstreamer.ini has correct entry for decoder subplugins
```ini
...
[decoder]
decoders=/your/path/to/libnnstreamer_decoder_*so/directory
...
```

**Comment by myungjoo** [comment]
Or, check the installation status with "nnstreamer-check" utility. If you don't see protobuf, flatbuf, and flexbuf in the list of ```[Decoder]```, it means you have not installed flatbuf/protobuf decoder subplugins or nnstreamer.ini is not configured properly.

If you are using nnstreamer PPA, install ```nnstreamer-protobuf``` and ```nnstreamer-flatbuf```.

If you are building your own binaries, enable ```flatbuf-support``` and ```protobuf-support```.

**Comment by myungjoo** [comment]
Without any further follow-ups, I'll assume that this issue is resolved.
