### ISSUE TITLE
Upgrade to tensorrt 10?

### ISSUE THREAD

**Issue by bveldhoen** [nnstreamer/nnstreamer#4477]
Hello,

I'm running into an issue w.r.t. the tensor_filter using tensorrt. I'm trying to build it, but need to revert back to ubuntu 20.04 when using the nvidia container nvcr.io/nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04. However, I would like to use a more recent version of this container (for instance, nvcr.io/nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04).

From the meson.build file, line 276, I assume that cuda 11.0 is the most recent version supported.

1) Are there any plans to upgrade the version of tensorrt?

2) Is there an example showing the usage of tensorrt in the tensor_filter?
(I couldn't find an example in nnstreamer-examples repository.)

Thank you in advance!

**Comment by myungjoo** [comment]
Could you please build and test with recent versions of CUDA?
I think it will probably work with recent CUDA, but I just don't have test reports from such.

Then, after testing it, you can add supported versions to the list of ```cuda_vers``` and upstream it.

**Comment by bveldhoen** [comment]
Hi @myungjoo, Thanks for you reply!

My issue isn't so much with the version of cuda, but more with the version of tensorrt. I couldn't find the UffParser anymore, it might have been deprecated. Next to that, I'd really want nnstreamer to work with our existing tensorrt 10 .engine model files, which we are currently using in a different solution.

I went ahead and made some changes in order to compile against tensorrt 10. Please find this branch:
https://github.com/bveldhoen/nnstreamer/tree/feature/upgrade_tensorrt_to_10

It is still heavy Work-In-Progress with much to be improved.

I'm currently trying (and failing) to test a pipeline with the appropriate elements and configuration, with a model with the following characteristics (output generated with polygraphy) :

```
[I] ==== TensorRT Engine ====
    Name: Unnamed Network 0 | Explicit Batch Engine
    
    ---- 1 Engine Input(s) ----
    {images [dtype=float32, shape=(1, 3, 640, 640)]}
    
    ---- 1 Engine Output(s) ----
    {output0 [dtype=float32, shape=(1, 25200, 10)]}
```

If you have suggestions for how to test a pipeline with such a model, please let me know!

**Comment by myungjoo** [comment]
```
v4l2src ! videoconvert ! videoscale ! videorate !
video/x-raw width=640,height=640,format=RGB !
tensor_converter !
tensor_transform mode=transpose option=1:2:0:3 !         ### This changes 3:640:640 (1, 640, 640, 3) --> 640:640:3 (1, 3, 640, 640)
tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 !  ### Assuming that your model wants -1.0 ~ 1.0 float32. This differs per model, please check the specification of your test model.
tensor_filter ${YOUR OPTIONS FOR TENSORRT} !
filesink location=${OUTPUT_FILE}

```

Then, you can verify with the stored ```${OUTPUT_FILE}```.
If you want to create a test case for automated testing, you may create an input file and replace ```v4l2src``` with ```filesrc```.

**Comment by bveldhoen** [comment]
Hi @myungjoo, Sorry for this long post/question, I hope it's clear. If you have any questions, please let me know!

With the most recent commit(s) on the working branch it's possible to execute the model (with 'garbage' bounding box output):
https://github.com/nnstreamer/nnstreamer/compare/main...bveldhoen:nnstreamer:feature/upgrade_tensorrt_to_10

I'm using the following gstreamer incantation:
```
gst-launch-1.0 \
    v4l2src name=cam_src ! videoconvert ! videoscale ! \
    video/x-raw,width=720,height=720,format=RGB,framerate=30/1 ! tee name=t \
    t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! \
        video/x-raw,width=640,height=640,format=RGB ! tensor_converter input-type=uint8 ! \
        tensor_transform mode=transpose option=1:2:0:3 ! \
        tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! \
        tensor_filter framework=tensorrt model=/mnt/projects/nnstreamer-example/models/yolov8s_gpu_1_3_640_640.engine input=1:3:640:640 inputtype=float32 output=1:84:8400 outputtype=float32 ! \
        tensor_transform mode=transpose option=1:2:0:3 ! \
        tensor_decoder mode=bounding_boxes option1=yolov8 option2=/mnt/projects/nnstreamer-example/bash_script/example_yolo/coco.txt option3=1:0.1:0.1 option4=720:720 option5=640:640 ! \
        compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! ximagesink \
    t. ! queue leaky=2 max-size-buffers=10 ! mix.
```

I changed the tensorrt model, so that it is a more standard model. The current model I'm using is the yolov8s pytorch model, exported to tensorrt:
https://github.com/ultralytics/ultralytics
with the following properties (note that the output dimensions are different compared to stated in an earlier comment) :
```
Input "images" with shape(1, 3, 640, 640) DataType.FLOAT # NCHW
Output "output0" with shape(1, 84, 8400) DataType.FLOAT
```

As I mentioned, the produced bounding boxes are nonsense, all over the image with 'random' object types. However, since they are 'valid' bounding boxes (with matching coordinates), I suspect that the frame which is handed over to tensorrt is incorrect (dimensions are reversed), and inference is performed on a garbled image (as tensorrt 'sees' it).

If I change `input=1:3:640:640` to `input=640:640:3:1`, I get the following error message(s):

```
** INFO: 17:34:22.269: Filter tensorrt with model file /mnt/projects/nnstreamer-example/models/yolov8s_gpu_1_3_640_640.engine is opened. It took 80511 us
** (gst-launch-1.0:8860): DEBUG: 17:34:22.269: Tensor info is not equal. Given tensor dimensions 1:3:640:640 vs 640:640:3:1

** (gst-launch-1.0:8860): CRITICAL **: 17:34:22.269: The input tensor is not compatible with the configuration of the model or tensor-filter property. The two tensor meta (GstTensorsInfo) are not compatible:  0 : float32 [1:3:640:640] | float32 [640:640:3:1] Not equal
```

The links below (to the pytorch tensor_filter implementation and example) seem to be relevant:
https://github.com/nnstreamer/nnstreamer/blob/859a300b96107b56ca4b9c002751f149d68f52ca/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc#L527
https://github.com/nnstreamer/nnstreamer-example/blob/99c07f7c9fb2430d042eb5ea28b24c293d171018/bash_script/example_yolo/gst-launch-object-detection-yolov8-torchscript.sh#L11

In this example, `transpose option=1:2:0:3` and `input=320:320:3:1` are used. I don't understand why this would work (assuming the example is still correct), given the error message above, which is generated with the same configuration.

I think that specifying `input=640:640:3:1` (and `output=1:84:8400`) would be correct in my example, but I don't know how to get around the error messages. If you have any pointers, that would be highly appreciated!

**Comment by bveldhoen** [comment]
Hi @myungjoo,

I managed to get it to work, after shooting myself in the foot a couple of times :). See the branch above.

Using the ultralytics yolov5su model from here:
https://github.com/ultralytics/ultralytics

Command line to test it:
```
gst-launch-1.0 \
  v4l2src name=cam_src ! videoconvert ! videoscale ! \
    video/x-raw,width=1000,height=1000,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tee name=t \
  t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! \
    video/x-raw,width=640,height=640,format=RGB ! tensor_converter ! \
    tensor_transform mode=transpose option=1:2:0:3 ! \
    tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! \
    tensor_filter framework=tensorrt model=/mnt/projects/nnstreamer-example/models/yolov5su_gpu_1_3_640_640.engine latency=1 ! \
    other/tensors,num_tensors=1,types=float32,dimensions=8400:84:1,format=static ! \
    tensor_transform mode=transpose option=1:0:2:3 ! \
    tensor_decoder mode=bounding_boxes option1=yolov8 option2=/mnt/projects/nnstreamer-example/bash_script/example_yolo/coco.txt option3=1 option4=1000:1000 option5=640:640 ! \
    video/x-raw,width=1000,height=1000,format=RGBA ! mix.sink_0 \
  t. ! queue leaky=2 max-size-buffers=10 ! mix.sink_1 \
  compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink sync=false
```
What I still don't understand completely is the fact that I need to use
```
tensor_decoder mode=bounding_boxes option1=yolov8
```
while it is a yolov5 model.

Anyway, I'll round things up by adding a test case with file input.

**Comment by bveldhoen** [comment]
I've added a basic runTest.sh to be able to invoke the tensorrt tensor_filter, but the test doesn't do any validation. Do you have a suggestion/pointer on how this test can be improved?

Also, I've encountered a rather strange issue when testing the example in nnstreamer-example. When I tested with a 640x640 model, the output video looked correct, with correct bounding boxes.However, when testing with a 320x320 model, the bounding boxes didn't show, **however** the object types **were** printed on the top of the screen:

![image](https://github.com/nnstreamer/nnstreamer/assets/1177238/ed79368c-e78b-4b91-97d1-b687c2ae7388)

This is from a recording of me holding up a cup, therefore the string "cupson" ("person" overwritten with "cup").

Considering that the filter and decoding steps seem to work (because of the successful decoding of the object types, and I assume also the bounding boxes), I think this may be related to the way the video is displayed. Do you have any ideas?

**Comment by myungjoo** [comment]
> Hi @myungjoo,
> 
> I managed to get it to work, after shooting myself in the foot a couple of times :). See the branch above.
> 
> Using the ultralytics yolov5su model from here: https://github.com/ultralytics/ultralytics
> 
> Command line to test it:
> 
> ```
> gst-launch-1.0 \
>   v4l2src name=cam_src ! videoconvert ! videoscale ! \
>     video/x-raw,width=1000,height=1000,format=RGB,pixel-aspect-ratio=1/1,framerate=30/1 ! tee name=t \
>   t. ! queue leaky=2 max-size-buffers=2 ! videoscale ! \
>     video/x-raw,width=640,height=640,format=RGB ! tensor_converter ! \
>     tensor_transform mode=transpose option=1:2:0:3 ! \
>     tensor_transform mode=arithmetic option=typecast:float32,div:255.0 ! \
>     tensor_filter framework=tensorrt model=/mnt/projects/nnstreamer-example/models/yolov5su_gpu_1_3_640_640.engine latency=1 ! \
>     other/tensors,num_tensors=1,types=float32,dimensions=8400:84:1,format=static ! \
>     tensor_transform mode=transpose option=1:0:2:3 ! \
>     tensor_decoder mode=bounding_boxes option1=yolov8 option2=/mnt/projects/nnstreamer-example/bash_script/example_yolo/coco.txt option3=1 option4=1000:1000 option5=640:640 ! \
>     video/x-raw,width=1000,height=1000,format=RGBA ! mix.sink_0 \
>   t. ! queue leaky=2 max-size-buffers=10 ! mix.sink_1 \
>   compositor name=mix sink_0::zorder=2 sink_1::zorder=1 ! videoconvert ! autovideosink sync=false
> ```
> 
> What I still don't understand completely is the fact that I need to use
> 
> ```
> tensor_decoder mode=bounding_boxes option1=yolov8
> ```
> 
> while it is a yolov5 model.

Maybe... it is because the two have the same output tensor formats and none of tensor_decoder's bounding-boxes contributors have never cared to look at yolov5.

**Comment by myungjoo** [comment]
> I've added a basic runTest.sh to be able to invoke the tensorrt tensor_filter, but the test doesn't do any validation. Do you have a suggestion/pointer on how this test can be improved?

As in https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_lua/runTest.sh ?

You can run a small object classification model with a small png/jpg files (e.g., apple, banana, pen, ...) and check the detected class; then you can ensure that tensorrt has run the given model properly. It is recommended to use really tiny models for such tests. (MNIST is perfect, too.)

For negative test cases, you may put an invalid model file, unavailable file paths, or invalid input streams.


> 
> Also, I've encountered a rather strange issue when testing the example in nnstreamer-example. When I tested with a 640x640 model, the output video looked correct, with correct bounding boxes.However, when testing with a 320x320 model, the bounding boxes didn't show, **however** the object types **were** printed on the top of the screen:
> 
> ![image](https://private-user-images.githubusercontent.com/1177238/338671083-ed79368c-e78b-4b91-97d1-b687c2ae7388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTc2MDgsIm5iZiI6MTcxODE1NzMwOCwicGF0aCI6Ii8xMTc3MjM4LzMzODY3MTA4My1lZDc5MzY4Yy1lNzhiLTRiOTEtOTdkMS1iNjg3YzJhZTczODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDE1NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRjNzg5ZDFiMjgxYzVmNTZiNTRmMGQ2NWFjNjU5OTVlZmNkYjAyMGVkZjhmM2RkZDkzMjM2OTdiZTY1OGIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e3XpKjGoaGUiUEomqIU1GG-dBMPXHgtsIpekSH-8mUk)
> 
> This is from a recording of me holding up a cup, therefore the string "cupson" ("person" overwritten with "cup").
> 
> Considering that the filter and decoding steps seem to work (because of the successful decoding of the object types, and I assume also the bounding boxes), I think this may be related to the way the video is displayed. Do you have any ideas?

I guess that it is caused by the text stream format of GStreamer. GStreamer's standard text streams do NOT append ```'\0'``` at the end of a string in a text stream. You need to process accordingly when you convert strings between C/C++ and GStreamer text stream.

**Comment by bveldhoen** [comment]
> > I've added a basic runTest.sh to be able to invoke the tensorrt tensor_filter, but the test doesn't do any validation. Do you have a suggestion/pointer on how this test can be improved?
> 
> As in https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_lua/runTest.sh ?

Pls. see runTest.sh in the PR below:
https://github.com/nnstreamer/nnstreamer/pull/4482/files#diff-6c39b882d0d1ad2d81487d1aed2d7875a2a4e5c8eb8e8678e7725b9ec5a1e879
It uses the yolov5 nano model of around 10 MB, which is of similar size to other test model files (in tests/test_models/models). I also made this model file part of the commit:
https://github.com/nnstreamer/nnstreamer/pull/4482/files#diff-046f353916309673df1ba6ce199214d4bbe8b1a0996de06c7a448835ec43d12c

> 
> You can run a small object classification model with a small png/jpg files (e.g., apple, banana, pen, ...) and check the detected class; then you can ensure that tensorrt has run the given model properly. It is recommended to use really tiny models for such tests. (MNIST is perfect, too.)

For some reason, the mnist onnx file couldn't be converted to a tensorrt engine. I can look into it further, but I could also try to use the yolov5nu.onnx file. What do you prefer?

> 
> For negative test cases, you may put an invalid model file, unavailable file paths, or invalid input streams.
> 
> > Also, I've encountered a rather strange issue when testing the example in nnstreamer-example. When I tested with a 640x640 model, the output video looked correct, with correct bounding boxes.However, when testing with a 320x320 model, the bounding boxes didn't show, **however** the object types **were** printed on the top of the screen:
> > ![image](https://private-user-images.githubusercontent.com/1177238/338671083-ed79368c-e78b-4b91-97d1-b687c2ae7388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTc2MDgsIm5iZiI6MTcxODE1NzMwOCwicGF0aCI6Ii8xMTc3MjM4LzMzODY3MTA4My1lZDc5MzY4Yy1lNzhiLTRiOTEtOTdkMS1iNjg3YzJhZTczODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDE1NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRjNzg5ZDFiMjgxYzVmNTZiNTRmMGQ2NWFjNjU5OTVlZmNkYjAyMGVkZjhmM2RkZDkzMjM2OTdiZTY1OGIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e3XpKjGoaGUiUEomqIU1GG-dBMPXHgtsIpekSH-8mUk)

With the 320x320 model only, there is an additional problem in the display that the bounding boxes aren't drawn at all.
Note that this seems to be a text (and bounding box) drawing problem, not a string termination problem.

> > This is from a recording of me holding up a cup, therefore the string "cupson" ("person" overwritten with "cup").
> > Considering that the filter and decoding steps seem to work (because of the successful decoding of the object types, and I assume also the bounding boxes), I think this may be related to the way the video is displayed. Do you have any ideas?
> 
> I guess that it is caused by the text stream format of GStreamer. GStreamer's standard text streams do NOT append `'\0'` at the end of a string in a text stream. You need to process accordingly when you convert strings between C/C++ and GStreamer text stream.

The example uses the (unchanged) nnstreamers elements, such as tensor_decoder mode=bounding_boxes and ximagesink, in order to interpret and draw the model output. I would assume that the tensor_decoder performs the proper string conversions?
Please see this example:
https://github.com/nnstreamer/nnstreamer-example/pull/338/files#diff-2b84c14651d9a96e8767854fe61758668592c0703b16259e9195e591abdd7ca5

**Comment by bveldhoen** [comment]
I think this issue can be closed because https://github.com/nnstreamer/nnstreamer/pull/4489 has been merged.
