### ISSUE TITLE
Is there a repo to storage pervious version of package such as nnstreamer_pytorch?

### ISSUE THREAD

**Issue by liuhao-97** [nnstreamer/nnstreamer#4480]
I notice that nnstreamer pytorch only support pytorch2 in the following link. Is there a repo to support pytorch version 1, such as 1.10? Thanks!
[http://ppa.launchpad.net/nnstreamer/ppa/ubuntu/pool/main/n/nnstreamer/](http://ppa.launchpad.net/nnstreamer/ppa/ubuntu/pool/main/n/nnstreamer/)

**Comment by myungjoo** [comment]
You may build nnstreamer-pytorch (```/ext/nnstreamer/tensor_filter/tensor_filter_pytorch.cc```) with Pytorch 1.x in your machine. Then, extract and install the libnnstreamer_pytorch.so, or, build and install the whole nnstreamer with pytorch 1.x in your machine.
