### ISSUE TITLE
Support for Raspberry Pi AI Kit?

### ISSUE THREAD

**Issue by bveldhoen** [nnstreamer/nnstreamer#4483]
**Add support for Raspberry Pi AI Kit / Hailo-8?**
See here:
https://news.itsfoss.com/raspberry-pi-ai-kit/

It uses the Hailo 8 Edge AI processor:
https://hailo.ai/products/ai-accelerators/hailo-8l-m-2-ai-acceleration-module-for-ai-light-applications/?ref=news.itsfoss.com#hailo8lm2-overview

I assume this isn't supported yet (Pls. correct me if I'm wrong!).
Are there any plans to add support for this?

**Comment by myungjoo** [comment]
If this requires a new user library or runtime (Hailo RT?) to run, yes, you need a new tensor_filter subplugin for Hailo.

I do not have a plan to support this.

Anyone who's interested in this may implement (by adding a tensor_filter_subplugin C++ subclass) and upstream.

**Comment by bveldhoen** [comment]
There is a repository with a number of gstreamer components here:
https://github.com/hailo-ai/tappas

Do you see a good way to integrate with these elements?

**Comment by myungjoo** [comment]
If they are GStreamer elements, they can be integrated at run-time via GStreamer as long as they are compiled for the same architecture and OS. You just need to install all components in one system.

Are there any issues against uring them in a single system?

**Comment by bveldhoen** [comment]
Thank you! I might give it a try later. Closing for now.
