### ISSUE TITLE
Add support for numcpp?

### ISSUE THREAD

**Issue by bveldhoen** [nnstreamer/nnstreamer#4484]
**Add support for numcpp? **
See here:
https://github.com/dpilger26/NumCpp

Investigate possibilities to create an element with a dedicated interface to enable invocation of numcpp functionality, with perhaps built-in conversions to/from numcpp NdArray.

Not sure how much it would add over a custom c++ element, but perhaps worth a look?

**Comment by myungjoo** [comment]
You can use custom-filter for such code:
Custom Interface: https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/include/tensor_filter_custom.h
Custom-easy Interface: https://github.com/nnstreamer/nnstreamer/blob/main/gst/nnstreamer/include/tensor_filter_custom_easy.h
Usage Examples (from unit tests): https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_custom/unittest_filter_custom.cc

**Comment by bveldhoen** [comment]
OK, makes sense.
