### ISSUE TITLE
Reporting some typos 

### ISSUE THREAD

**Issue by aychun** [nnstreamer/nnstreamer#4527]
Hello, I noticed a few typos in the repository and figured I might share them here. Please let me know if this is not the right channel for such purposes. 

1. `nnstreamer/gst/nnstreamer/elements/gsttensor_decoder.c` [line 869](https://github.com/nnstreamer/nnstreamer/blob/da7da92b90ac2ba7bdd39d4193d519739a5dfdd8/gst/nnstreamer/elements/gsttensor_decoder.c#L869C45-L869C54) 
_if the direction is GST_PAD_SRC. Thus, gstreamer **_sholdn't_** fixate_ 

2. `tools/profiling/README.md` [line 28](https://github.com/nnstreamer/nnstreamer/blob/da7da92b90ac2ba7bdd39d4193d519739a5dfdd8/tools/profiling/README.md?plain=1#L28)
_$ git checkout -v 0.2.3 0.2.3_

3. `tools/profiling/README.md` [line 41](https://github.com/nnstreamer/nnstreamer/blob/da7da92b90ac2ba7bdd39d4193d519739a5dfdd8/tools/profiling/README.md?plain=1#L41)
_$ ./auto**d**gen.sh_

Again, I will move this post to somewhere else if needed. Thank you!

**Comment by niley7464** [comment]
Thank you for reporting the typos :)
#4528 fixes it
