### ISSUE TITLE
Is there a way to control the order of sending/receiving tensors?

### ISSUE THREAD

**Issue by liuhao-97** [nnstreamer/nnstreamer#4569]
Hi team,

May I ask, is there a way to control the order of sending/receiving tensors packets? (I think some prior knowledge is required if I want to do it on the receiver side?)

I am building a prototype of split computing for DNNs. The sender executes several DNN layers and sends the intermediate feature map tensors to the receiver via UDP, and the receiver executes the other DNN layers.

The receiver executes the following code. (tensor_aggregator is used because the tensor will be split into two UDP packets if the tensor data size exceeds the max data size UDP packet can support.)
```
gst-launch-1.0 udpsrc port=6000 ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=2:10:10:1, types=uint8 ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_aggregator frames-in=1 frames-out=2 frames-flush=2 frames-dim=2 ! other/tensors,num_tensors=1,dimensions=10:10:4:1,types=uint8  ! tensor_filter ! ...
```

The sender may execute like this. But the sending order of the first 10:10:2:1 tensor and the second 10:10:2:1 tensor are not fixed. Or maybe I should not use tensor_split to do that? 
```
gst-launch-1.0 filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, width=10, height=10,format=RGBA ! tensor_converter ! tensor_transform mode=transpose option=1:2:0:3 ! tensor_split name=split tensorseg=10:10:2:1,10:10:2:1 \
split.src_0 ! queue ! udpsink host=10.68.186.155 port=6000
split.src_1 ! queue ! udpsink host=10.68.186.155 port=6000
```

May I ask do you have any suggestions about that? Thanks!

**Comment by myungjoo** [comment]
1. As you can see in https://forum.veye.cc/topic/157/cs-mipi-imx307-camera-gstreamer-udp-streaming-error , I recommend to use gdppay and gdpdepay over UDP. Manually cutting and stitching up UDP packets to circumsbent packet size limit is highly unreliable. Use the layered architecture of network protocols.


2. For split-computing, if you have splited the model into two and exported them to popular frameworks, you don't need any custom layer. E.g., split a large tensorflow-lite model into two smaller tensorflow-lite models, where the second model accepts the first model's output as its input. Then, you can keep using tensorflow-lite subplugin.
    - I believe https://www.sciencedirect.com/science/article/pii/S2665917422000435 has the same approach.

**Comment by myungjoo** [comment]
So in your code,
```
gst-launch-1.0 udpsrc port=6000 ! gdpdepay ! other/tensors,format=static,framerate=0/1,num_tensors=1,dimensions=.... ! tensor_filter ! ...
```
and 
```
gst-launch-1.0 filesrc location=rgb.jpg ! jpegdec ! videoconvert ! videoscale ! video/x-raw, width=10, height=10,format=RGBA ! tensor_converter ! gdppay ! udpsink host=10.68.186.155 port=6000
```
should be sufficient.


Besides, don't forget that, unlike TCP, UDP does NOT guarantee the packet sequence. The order of incoming UDP packets is not guaranteed to be the same as the order of UDP packet transmission.
