### ISSUE TITLE
Question about tensor_filter execution latency

### ISSUE THREAD

**Issue by liuhao-97** [nnstreamer/nnstreamer#4604]
Hi team,
I compare the execution latency of pytorch model tensor_filter in nnstreamer and the exeuction latency of the model (including moving data from CPU to GPU) in C++. But it seems like the element tensor_filter is much slower than the C++ version.  For example, for the model I test (one convolutional layer with input 3*32*32 and output 32*32*64),  C++ version takes 0.0016 second and tensor_filter takes 0.0045 second.  

For nnstreamer I test  with a timestamp subplugin [timestampc](https://github.com/liuhao-97/myfilter/tree/main/subplugin_c/timestampc). 

`... ! timestampc position=1 ! other/tensors,format=static,num_tensors=1,dimensions={self.input_height}:{self.input_width}:{self.input_channel}:1,types=float32,framerate=0/1 !  tensor_filter framework=pytorch model={self.model_path}/layer{self.divpos}_inch{self.input_channel}_outch{self.output_channel}_inputhw{int(self.input_height)}_outputhw{int(self.output_height)}.torchscript.pt input={self.input_height}:{self.input_width}:{self.input_channel}:1 inputtype=float32 inputname=input output={self.output_height}:{self.output_width}:{self.output_channel}:1 outputtype=float32 accelerator=true:gpu ! timestampc position=2 ! ...`

The chain function of the timestampc is as this

```
static GstFlowReturn
gst_timestampc_chain(GstPad *pad, GstObject *parent, GstBuffer *buf)
{
  GstTimestampc *filter;
  gsize position;
  struct timespec receive_timestamp;

  filter = GST_TIMESTAMPC(parent);
  position = filter->position;

  clock_gettime(CLOCK_REALTIME, &receive_timestamp);
  g_print("position: %zu, timestamp: %ld, ns:%ld\n", position, receive_timestamp.tv_sec, receive_timestamp.tv_nsec);

  return gst_pad_push(filter->srcpad, buf);
}
```

For C++ I test the same model with the following code.
```
void profiling_exec_latency(int batch, const std::vector<LayerConfig> &all_layer_config_opt, const std::string &csv_path, const std::string &model_name, const std::string &dataset_name)
{
    // Check if CUDA is available
    if (!torch::cuda::is_available())
    {
        std::cerr << "CUDA is not available! Exiting..." << std::endl;
    }
    std::cout << "CUDA is available! Using GPU." << std::endl;

    for (const auto &layer_config : all_layer_config_opt)
    {
        std::string model_path = "../model_segment/" + model_name + "_" + dataset_name + "/layer" + std::to_string(layer_config.layer_idx) + "_inch" + std::to_string(layer_config.inputchannel) + "_outch" + std::to_string(layer_config.outputchannel) + "_inputhw" + std::to_string(layer_config.inputHW) + "_outputhw" + std::to_string(layer_config.outputHW) + ".torchscript.pt";

        // Load the model
        torch::jit::script::Module module;
        try
        {
            module = torch::jit::load(model_path);
        }
        catch (const c10::Error &e)
        {
            std::cerr << "Error loading the model:\n"
                      << e.what() << std::endl;
            continue;
        }
        module.to(torch::kCUDA);
        module.eval();

        // Prepare input tensor
        torch::Tensor input_tensor = torch::randn({batch, layer_config.inputchannel, layer_config.inputHW, layer_config.inputHW}).to(torch::kCUDA);

        // Warm up
        for (int warmup = 0; warmup < 10; ++warmup)
        {
            auto output = module.forward({input_tensor}).toTensor();
        }

        std::vector<double> exec_latency_list;
        for (int i = 0; i < 100; ++i)
        {
            input_tensor = torch::randn({batch, layer_config.inputchannel, layer_config.inputHW, layer_config.inputHW});

            auto start = std::chrono::high_resolution_clock::now();
            input_tensor = input_tensor.to(torch::kCUDA);
            auto output = module.forward({input_tensor}).toTensor();

            torch::cuda::synchronize();
            output = output.to(torch::kCPU);

            auto end = std::chrono::high_resolution_clock::now();
            std::chrono::duration<double> exec_latency = end - start;
            exec_latency_list.push_back(exec_latency.count());
        }

        // Write results to CSV
        std::ofstream csvfile(csv_path, std::ios::app);
        if (!csvfile.is_open())
        {
            std::cerr << "Failed to open CSV file for writing: " << csv_path << std::endl;
            continue;
        }
        for (size_t i = 0; i < exec_latency_list.size(); ++i)
        {
            csvfile << layer_config.layer_idx << "," << layer_config.inputHW << "," << layer_config.inputchannel << "," << layer_config.outputHW << "," << layer_config.outputchannel << "," << batch << "," << exec_latency_list[i] << "\n";
        }
        csvfile.close();
    }
}
```
Is there any suggestion about this? Thanks!

**Comment by gichan-jang** [comment]
Hello, @liuhao-97 
We have latency prop of tensor_filter.
Please try with `latency` prop.
```
... ! tensor_filter latency=1 ... ! ...
```
To enable the log,
```
export G_MESSAGES_DEBUG=all
```

**Comment by liuhao-97** [comment]
Thanks! 

May I ask, the latency it shows is the whole tensor_filter (including data pre-preparation such as  /* 1.1 Prepare tensors to invoke. */  /* 2. Prepare output tensors. */ and etc.) or just the line for DNN inference` GST_TF_FW_INVOKE_COMPAT (priv, ret, invoke_tensors, out_tensors);`?

**Comment by liuhao-97** [comment]
> Thanks!
> 
> May I ask, the latency it shows is the whole tensor_filter (including data pre-preparation such as /* 1.1 Prepare tensors to invoke. _/ /_ 2. Prepare output tensors. */ and etc.) or just the line for DNN inference` GST_TF_FW_INVOKE_COMPAT (priv, ret, invoke_tensors, out_tensors);`?

Seems like it is for `GST_TF_FW_INVOKE_COMPAT (priv, ret, invoke_tensors, out_tensors);` Thanks!
