### ISSUE TITLE
[Tensorflow] `armhf` Build failure on launchpad.net

### ISSUE THREAD

**Issue by again4you** [nnstreamer/nnstreamer#684]
After applying some hotfixes to `sandbox/sangjung/launchpad_bugfix` branch in platform/upstream/tensorflow, Current status is as below.

Completed
-----------
* PPA: https://launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+packages
* amd64 Xenial (16.04)
* amd64 Bionic (18.04)
* aarch64 Xenial (16.04)
* aarch64 Bionic (18.04)

Failed
--------
* armhf Xenial (16.04): [buildlog](https://launchpadlibrarian.net/394430284/buildlog_ubuntu-xenial-armhf.tensorflow_1.9.0-0~201810220136~ubuntu16.04.1_BUILDING.txt.gz)
* armhf Bionic (18.04): [buildlog](https://launchpadlibrarian.net/394430462/buildlog_ubuntu-bionic-armhf.tensorflow_1.9.0-0~201810220136~ubuntu18.04.1_BUILDING.txt.gz)

Compile option for `armhf`
-------------
* CFLSGS: -Wno-sign-compare -Wno-unused-but-set-variable -Wno-format-security -Wno-format -fPIC --std=c++11 -DARM_NON_MOBILE -mfpu=neon-vfpv4 -std=gnu11 --ftree-vectorize -fomit-frame-pointer
* CPPFLAGS: -Wno-sign-compare -Wno-unused-but-set-variable -Wno-format-security -Wno-format -fPIC --std=c++11 -DARM_NON_MOBILE -mfpu=neon-vfpv4 -std=gnu11 -ftree-vectorize -fomit-frame-pointer

Detailed failure reasons
--------
* Too long link time

```bash
[ 99%] Building CXX object CMakeFiles/pywrap_tensorflow_internal.dir/pywrap_tensorflow_internal.cc.o
c++: warning: /<<PKGBUILDDIR>>/tensorflow/tf_version_script.lds: linker input file unused because linking not done
[ 99%] Linking CXX shared library libpywrap_tensorflow_internal.so
make[3]: *** Deleting file 'libpywrap_tensorflow_internal.so'
debian/rules:46: recipe for target 'build' failed
make: *** [build] Terminated
E: Caught signal ‘Terminated’: terminating immediately
CMakeFiles/pywrap_tensorflow_internal.dir/build.make:2833: recipe for target 'libpywrap_tensorflow_internal.so' failed
make[3]: *** [libpywrap_tensorflow_internal.so] Terminated
CMakeFiles/Makefile2:127: recipe for target 'CMakeFiles/pywrap_tensorflow_internal.dir/all' failed
make[2]: *** [CMakeFiles/pywrap_tensorflow_internal.dir/all] Terminated
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Terminated
Build killed with signal TERM after 150 minutes of inactivity
```

* undefined reference to `void tensorflow::ConcatCPU`
  * Related issue: Add `ARM_NON_MOBILE` or `RASPBERRY_PI` in CPP/CFLAGS [(Link)](https://github.com/tensorflow/tensorflow/issues/17790#issuecomment-392185433)
```bash
[ 99%] Linking CXX executable summarize_graph
CMakeFiles/tf_core_kernels.dir/<<PKGBUILDDIR>>/tensorflow/core/kernels/list_kernels.cc.o: In function `tensorflow::TensorListStack<Eigen::ThreadPoolDevice, tensorflow::bfloat16>::Compute(tensorflow::OpKernelContext*)':
list_kernels.cc:(.text._ZN10tensorflow15TensorListStackIN5Eigen16ThreadPoolDeviceENS_8bfloat16EE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow15TensorListStackIN5Eigen16ThreadPoolDeviceENS_8bfloat16EE7ComputeEPNS_15OpKernelContextE]+0x500): undefined reference to `void tensorflow::ConcatCPU<tensorflow::bfloat16>(tensorflow::DeviceBase*, std::vector<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> >, std::allocator<std::unique_ptr<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix, std::default_delete<tensorflow::TTypes<tensorflow::bfloat16, 2, int>::ConstMatrix> > > > const&, tensorflow::TTypes<tensorflow::bfloat16, 2, int>::Matrix*)'
collect2: error: ld returned 1 exit status
```

**Comment by leemgs** [comment]
> Related issue: Add ARM_NON_MOBILE or RASPBERRY_PI in CPP/CFLAGS (Link)

It's reasonable to me at least. In my case, I have used `--copt=-DRASPBERRY_PI ` option in order to build  the Tensorflow source code directly using bazel on my own Raspberry Pi3 board at home. At that time, the build time  (From my experience, the estimated time was +16 hours.) is problem to me. 

* https://github.com/samjabrahams/tensorflow-on-raspberry-pi
* https://www.tensorflow.org/install/  (Google has supported Ubuntu and Rasbian officially Since 4 Aug 2018.)

**Comment by leemgs** [comment]
> * Too long link time
> make[1]: *** [all] Terminated
>  Build killed with signal TERM after 150 minutes of inactivity

@again4you , I suggest that you try to use  a **-Wl,--no-keep-memory**  option to avoid a memory issue while linking object files. From my experience, if the launchpad server requires a few memory space, this option will be helpful to fix this issue. 
 
* --no-keep-memory (https://sourceware.org/binutils/docs/ld/Options.html)
ld normally optimizes for speed over memory usage by caching the symbol tables of input files in memory. This option tells ld to instead optimize for memory usage, by rereading the symbol tables as necessary. This may be required if ld runs out of memory space while linking a large executable.

**Comment by flyhorseli** [comment]
build still failed for "undefined reference to void tensorflow::ConcatCPU".
Why it is closed? or what is the solution?

**Comment by myungjoo** [comment]
> 
> 
> build still failed for "undefined reference to void tensorflow::ConcatCPU".
> Why it is closed? or what is the solution?

@flyhorseli We are abandoning tensorflow build for armv7 and x86_32. We will disable tensorflow-filter in nnstreamer for armv7 and x86_32 as well. However, we will keep support tensorflow-lite for these 32bit systems.
