### ISSUE TITLE
[UP3] Add Deployment & Daily/Nightly Build&Test Results on Top Page

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#894]
On the top page, "/README.md", show the status of

- PPA deployment status
- OBS deployment status
- Daily / Nightly build & test results

which are based on the recent master HEAD.

**Comment by gichan-jang** [comment]
Daily build & test results for arm and android(except test) are posted now. #2274  #2286

**Comment by myungjoo** [comment]
Well Done!
